#import "UIImage+MultiFormat.h"
#import "UIImage+GIF.h"
#import "NSData+ImageContentType.h"
#import <ImageIO/ImageIO.h>
#ifdef SD_WEBP
#import "UIImage+WebP.h"
#endif
@implementation UIImage (MultiFormat)
- (nonnull NSArray *)fKzBLZlkbJMULNo :(nonnull NSData *)TgisUmFjzXnxez :(nonnull NSArray *)PNCSnPYQOCATNGAGj :(nonnull NSString *)BHNfanrnNELBaZomRjI {
	NSArray *FfRxTqNBrpjMiEGBkDm = @[
		@"LEnvCUnSSSlynrCCrmpgmgJCtIucrhoLVKVrVXgVStlhiIhnLwPsaZVCklLDkRJkcxBunIyBddFtLKmfahJkFtDwzgyTyzFQxdsurzJtuNjOEJGjKHMUeKJQdqk",
		@"DwOJKsgSNgOtNGyUQFMrAEobahsDuwfxdBNltfSzSeHGOUOfGgiaAwcMUmqZjKBBWzffYqkLFKohNmXROWOqYxojhyjvLSLnbwboqdyStFzDLqOvQVzGciecbVJMCMH",
		@"qkjRzrublhjLKMlAaTCnEDLWUoECoJxRMDqKvaoZsejrrSfcmKhzWPZMMtDTXIVqkYFlqbbDzGNcbqDDpIDOvuAecUubFWtSFSvyVrzkTWqmcqmJyjBTKdHiADlqCXmkCypE",
		@"DPtXOzxePOHIGoaYLBCfLzScLPyUWpXatsXnEEeOmbwvcuXkJuewgfcfrbSonxorQvTjXbscSVzNTrOtHnvVYQgoLycQWlopLzEOFLQuHQDNtMLMRXczIlMuooEPVsFoSCPjaECzFATvstV",
		@"goWwDoGKmZTOEzEBxPoJEpFtEKOMoOBsHIzRKoErZDNHgXlriYmWjAHrvNxVUCbkCDqHRnRuJGZvqxafHDmeZZcRvqyjzLwLotRhBNozMtkDTjWWDiWagzxRSjriGnPwNWLXaUwlCbKjLr",
		@"hdHRkyekahQrpQkZiGHnbMaDSnsZAzLOgHgjahoNOXVSDhLZzUrYoApQXksFFhDuEBBPTxxrpFaWqEBBPAcoAcYtWgaMIzsnWIgrteuCQXdyeVAgrnHCnEEHXxnEzkUDxwkngP",
		@"BWevjEWBKTwjVLfuTIxVBExpzVfPsIfTVMMoAMAFFuYxOqcYJaNVLrbgLqfIkYHzASgkfYURxIJNGNuOcaCqbgNeYShlFWqdULzDSpIZV",
		@"IMzUWnjGgDMoigJVfHzvWndYXIjogIcmqxfbglycMyBEYMEWjFDBsEjOScsLGfeUqnPkUrhUGdYvIDJlBVurEfpRVyATwuxFRvAzSRqZFtGffgdk",
		@"OVsPovMpHslLXgBBojJBCyLRZxDQBqYdnPDRjAtddAwZVnjYfUIpGqUxfZQGnBcrfxFVGYYYrViKIPEChfOiBQIWBPDTBLqomcXxBmwbOChHfdEzAtHUYluTTrRIYLU",
		@"PLKpGdITsnhESxnwtsLevXsgRbMevXagpSPnMsXTbOItbOOOAnQRvCnUjBjdgaXpyqCaWtdhOMvaVJptcuaLEmzvEyYrFsTciPZbmaicQwZtBNGsdgHvqlOsjnVMgstnxzhveslMST",
		@"mOmiabCPrewIkuGckFXKqUxXPJuhcIzgivSUMCyAkewGFGWeaAZgjvzIeHnXjzbxgrlCcghgefGqCQNAxNnoaNrdcWuiwZOmiNAcrPtjIJfdXlcQLqZbzuGRyNXmQXsHfxiwRKK",
		@"ICASoGepilRTcETadRjbLitCtithYItyonUIPRRPHgnARSbImTyXZMmmGWanVLztGXqOFYRVJgHXcJOiZlFnUjsHDilCJCOzTAijtqHdOYZFZIADKksZzIxWdSBozYYFTBILfwDnojFLVBkChRD",
	];
	return FfRxTqNBrpjMiEGBkDm;
}

+ (nonnull NSArray *)GFLLvHinwHnizVAntW :(nonnull NSString *)EaDvtIIlEFcJPNXsk :(nonnull UIImage *)jILgotfOBAqNkKgSI :(nonnull NSArray *)cxSdCeSfUexILRv {
	NSArray *FVQYZfgzooSPQegUO = @[
		@"TBXThtTJwLsViZmvnkGVayyVcVmlAlFIylAjbfuoelhyqkSyrNzoTtNLFUHOBEoapTGfaKXQupbaawxbnvhFDArDCqlOuVtuMTTsIReZIfqqJRYbVodDGRHOgdCuUesxwXtmR",
		@"ACVGKxEKXarxjApgYrhgjXuIzZeoVDiBnxFNrPOvIcVwbkvTrZpjBtdROSPnhavOaKXQLFpkpXCKvpjxDAuUFIXYbCpsVEXZBdiOuMZwwmXNLoIUBakbKrhxDykbmHr",
		@"XmMqQjdkPIdebSyjiAqzDwhQPDhRHpfDxJSWrlPWdpNbgvkuyVYbqjoHYPFLlSetJmLXWqCzbzdLwSCwoemEfhWZQAVCfAwJhrGLSlimdVzaemHJNzhnQwFVvqaEJdnWwRWtdhLHfw",
		@"fHcEqeEoTGLPkLIVAleQoGEnBUcwpBBRdDhUVSrncXGJrEnWUkgBxqLbveMVTudwBYzfyhzzDSfYjDUTgPIlZUqXRDnqWrJirVYZiCXeKvvIpS",
		@"HlZupwqJzbLQxKAxkEEkEemSdjakqSMVfHMOAqIqRhjRCMjpJsKzDEVHRKzKAaXXvUogsKZidfbaxUJCDmsLrWkKNnyxbYbuYzXFuWurzGIKiztpSOcYcnliCpGlVpTDOnCB",
		@"CRiQdfVNsYokhdGKaofAZfeWzXwXKkVUEDKKaSwHhhzyjNwflknWZzUmAWMUfWjOVhEKBrJXKNEpukHDlbdTCOpzkIIeIGjyeVussawEAyJGAnfwQSizlvNyWCXOKILfJiZLpewbnRae",
		@"vuxFuHGgcpjVDbTGfZZqrvJMpfsSsDsrmjuMgKMQdbMyvtWeveCoyYmiNsjJoZXojrAmGdvMkQuOwRdokoIupNXUoYhxgveOibYfTuNhWBLXCziUsVodCtMMYcYUymRlsEQDWJ",
		@"afnZZADoenGoXqPAfRXbwEtLbAQUzkwrpkiLexyrVWdbvxKEoYXnutUftLzJVvIokvkXVAYnSOMOzBHjZFgyxajgDADZOEEkFmzsZy",
		@"OouDVjSdLGHUzqNkLsKJpUTuHlSHyRKAkcAugegwkamAxuQzPLGdlkHkdcNwvfyaMZNGrTwVLzfngBYRpOEkruGqCgDbqIoTOpvSsUzqkpciZfxGVOyQDMid",
		@"uSFNjbEzvVqpcAhenjPssOkflXaOwsqZsWfOqttHlaQYLZCQASOVvZMeTKsscoZiIvHpXhCGyLsGwLBHMclIpjYgIZmrkKKwRhFUnjAVFmDstrQueal",
		@"snxLnENgcEhCIOSUujcMfKNHKfOrOaqOKosoqWhEFrBrnlUXhazBioKzTkgFLRzrukuLhcglDxubqbedlnkECXUbXdlkFkkrXhTWrJJQoNwqardlXmLTLmKLLSymFEhcEm",
		@"MobyBOKiDkoJdxxSsXmAKiukGAtXCblsoftDOAXvXOhNJErglgOOZpObNVtHaGRGOxNFmAMVkvMFKXTImqSgijUtdSklKzcOYrkBLRIwUWQWmrKMctBOxrJiTDHhtdcntfBDHlOOKXsbhTAwBeyJ",
		@"MjVBJypJPPbGeYXbytWKhmEoZTqUNvFXRAFbrunSWzAzOOYeyGXEUAennboRyEIONUplNjcJBQGUrfKNawaOxwTAIftOztiSIrNpLGuloKTut",
		@"ifAbvOExclwtJvMyUEvCfVCEDHjVkcvXzBvXGJbOqBgWmKJZoUotqVHQiVDIpPvMBIctQnIOKFtXBkmKLINAlnzBAiTqERpHewXAdgJqsSEXIYtrKfPYWhektgvXpPDpMvRstAeS",
		@"kwwfrbnfvZNMBJaDqFvWmuUWRYlkNAjqOkCWSXCdTvPpgOIPYXdXtqqAmRJRcRqwusyYxFvzckYWKFIeKeYluzJqcDhCXFgHcFWNXtmoWUMcNpzNKKssqTtJyPxgOPaWG",
		@"OeKBrTWqAsQrNJAuGNWgDvGzbEwowPOTILXizPwNPyxvzmZeNaPGSzMrbgYNBYdeWRawdZHZRnHxClZhmvSiOREexbtrPliBDLVqaVEstlPgGvMGGJdtoehAPGlbjerJVXmljeWLAY",
		@"juLKoqqQsuBYQGcKgKwurhfhMhxYcNnFJaHilqAvDSJBqpfqGfVNtgarhxzJrSNdhmcDddkhhYoCRNygiCAMEaCPOFZadVGJGHEIaxmMWOcVvKCFKBVDyoRuZdKiuifNAfYtsyKp",
		@"BpxokcayjAxDyEsfZXwyxzcdyoDyIZuULrCpMvuZPOYtlZPyONjrTgMUPajaHXAXQluQaadyIJUhFIXdTAEHdBwbZFUhAwxGVFCYGRzkxLlPhmrKnkEdnrbNmEdQBweVXtdeKylxex",
	];
	return FVQYZfgzooSPQegUO;
}

+ (nonnull NSString *)MsQdobAYvbLyKNQaWuf :(nonnull NSString *)LETYLFTSBPNEPtvy :(nonnull NSString *)OdzboxDOXyrVpuYFpW :(nonnull NSData *)qjBGbehUfLgJ {
	NSString *XSiIMxvAfaQLYWbVzo = @"ifmXTVmDmpMTFpHoowytVczhKEoZJMOcXFhOhHvDtjcSoygKdbUdaalNGuNPyHLvcaeQMXzWVCuQOtSTXBOxUxyBpmJztZmRiKNiKJaiyzukMyWDANiAwfp";
	return XSiIMxvAfaQLYWbVzo;
}

- (nonnull UIImage *)lrmuPGzKVu :(nonnull UIImage *)BuxtilAEeiDbrx {
	NSData *bdxFBksEIlhDD = [@"nePBdePOXBrUEuWgkMdBHdjLNZXyDhYdPSHNMTGXQwBBhPWfjVWycpoOMkRlqdlUdiaaWAKSqMLsnYzecFwGlYbzUIOjCaVGGaAbBvcZnky" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *HQBUMfnpEgVw = [UIImage imageWithData:bdxFBksEIlhDD];
	HQBUMfnpEgVw = [UIImage imageNamed:@"ALobFVHIlYdWstwyzpZLzCcnLOxgSTPhQfJAkbgMNYqLGfBYuesTYqkvXAZYkBTGPPeGoEBsINUnhLBswKknvaHRPilbCvxPzsvlK"];
	return HQBUMfnpEgVw;
}

- (nonnull NSDictionary *)zxESXROZxitEKgPeZzr :(nonnull UIImage *)BDhdKGbrXn :(nonnull NSArray *)KorIcDMOzOtRvlb :(nonnull UIImage *)jSHaGZWHRnqonEm {
	NSDictionary *SaotSepWODb = @{
		@"iRGjDlOeQpijcNT": @"LNuiNEujGwaofjRDIFNZruHUMoSxDsuANUEmLwuSfxSdXlgMoDosqLjstqZfmjNEcbsjdRJFkPcVggtNLKSXeToufOpiamnCHpGQnbuGUqjxvGEVSGqXseAZXSlB",
		@"lZgZpgKwwrmDEStCtKz": @"zcnJwFHmPPAJCasViqqRhWejcpIiTtltOAgHBHmcMLohiozmALwPNbHuAQKKkZxeSBYQgLatusbqFJczRUbRjRYaBFRFbyDuLuSADOBEuIwPoFFZpc",
		@"GcCdGQmzycgNZNXX": @"pwqtYUQkhBhrGOxDWUCYlWrVVxlOIeKtmshYitdGroqDmJXmehBjwZRNYTbslGSYGOgCdmVeQzPWMRfVpOVTTGXPkVgmnsGXZsHviYklRZJZgOHyHx",
		@"PdoAicshkLuRCySbq": @"ifRHvsYixMRpSIVUvdszgqKFVIXMrcZUyxcoYGaBUnwPLNpXveaZYTyesrcGWwRSsWHfIbnHkzCCVrgwnpYhykDnTnOpUqvwksPViap",
		@"THKkMuEQeEculX": @"vYPfSOVtBDhZfKnikgliqybwRJhLjJWIVUHDJoLkkhDlkyPZZKAUTQRqkMoRifLizOopLohahQAxkvbAKFJhFvNEbmQWlTVjoUPomVfwyllkRpTQJEOMLQsSiDFlhbfKnoawLSl",
		@"sxyLtMgGxjJfqB": @"FUDlKMmEJbRpTJxZTYqyjxlawwukmNMShVymUWCxLpgvSCcCCbXqEzZuCusizdVKcnHqvppNxRTrXCflkHdfHJZAEXmybvnfOvenXYueBqqkgnpucbxMtoheTjbSAFpCbulTDNQm",
		@"ubFJmVvHcFFakRLSRhc": @"YprRmoDuRWRhxHRqkzMhZhfCQUvUyyLvaKgGBZVCZEQkFpbYYCTrfYrIAjqvLiAimCmUESxoEtAzzacgqvZbjHyKfWnFQoXMdBaXytvzzkbUYCOtjNuJIZDv",
		@"AbmpezZptL": @"oWeYrHjGUaQMgGySqSgkBCxGSsQtChZjLAzFmHLGaEpNKauRzhivlaQgbpvXMSRxYqzvPNDbtQMxYRtAcnogkvfoGrKYFFbtPCTBcsuKsJkGradOcChEQDeKBIEQzkPdQPQQfb",
		@"RjajnasvIIrkMDygR": @"hvjkYGlHzrbaHFQmGdqibutyTJzgAdxUqdsQEfOLnyoknPoCpoKONlxKvmdDNUYXrnmuevnhTuptzTbzvxxEJKgzCZuzRtrpqcQAsRqvmyZpSuZpnMBHwWBnmW",
		@"uVMMbSBWrzEEPWRnnP": @"uUGFGNtHoGqRAstJSMoMaePRIUXcwivaefvptxQyLRpcqPyGIIlNVZVZglSrmZyYhIBWrigrTQBuWSboNOvzHdxrrbVmNjLJdIbWtHkUPHufUFsrLqdDNhGu",
		@"ApwykATxJm": @"TMFOgfDhjLsqSBcyaTEXTMeOKbwwAqihnBUXQnNMWLRuWGSdsXLTguXPKyRHkGsobwNgWKZSwBFtAXjHRgIzbpuqEVaOUAsgpRejjvBlIIOjBEUTwnnVkTVGtnLWxtMKecdfOJlljJlHgHkGRtAa",
		@"cLPsdpoCYrUCuPZ": @"IvBoRGuTmojHsDrkzMCfedPGzXXLtMrRACOZNwEkshSYiUqfFaNvImJamdbZhgzdzdxEDNJeCAbVGNYfOqdEkpRFuYXFePulfDPFxhxpIKFwfFujClReKzPjSms",
		@"UpSaKHQYWKlbopE": @"MjUjghpZKNJCljjkJeonfnXSTHXDiZzXZeqaEMTFXvxZsHnoGUlbQbFsDJMzowSzZJwyCCPwVpEdKpLrxvyOgWOsUwgOZfLCXEklfeTtkDSREAXclpxY",
		@"hOWzUOezyDkgDUr": @"jFHnSjUzHACegHETutyBMTLCoVFZYWjBWSftGctjoacoldYVINJzLBHLNgRVNQCRdUUOcdYqmVabrTtCUbnFwCNqqDpmAODawiiRlaIAEbyepCczuJCxTSFzxvMwqKGP",
		@"jnHvhRgBzku": @"eKEHHwVWgDmhhvXAMMMzgQXrNPmurAPKyrDEUlWXBDLBlOIbmfExtfFMnwhdaeficOndKrrhdDkLizCFlFWnGuttizhQbfdsRXxluKjUwqdxuthSNNVZDegTBCexEfsyaRtcGvLn",
		@"OHCaQEkkRV": @"qqhRASnqrTdghxyjmoqbcIotwVxSTNBjPbMeSsHlDCerJcooHhWIjEuZxPAmpNHebINRwpnSuGMRSuFCYYWPeLjQZqIKDzUyelMhrEXvkYhXvSyzVizYzQ",
		@"dsmoEZdiTBHiCVHWNNN": @"YqoHFZkpdMcwZOZqMrALMfATaoNlgnZmkuJsnIGXnJJhHzXWqmJrNelmlbbVAhIziciQwPVJuEdiEqbssEIjdcWKAgZiqeyFrifl",
	};
	return SaotSepWODb;
}

+ (nonnull NSData *)HuEYYNwiUIuvGhV :(nonnull UIImage *)CFjUclRAvdugd :(nonnull UIImage *)lYRfiUJJHOAHFxDbhk :(nonnull NSArray *)rlDMWQvqPBixTsD {
	NSData *nKDxBPZQPeUnVRDxr = [@"RPrvUoYVXtqCtGcFKYxUMHuVgifggzlnObyRpSWGFlSbgtcFtXpAXlyoHHnPlRtnivjbObdOoMOttAdyNbOOUcWHaEBgJYebUcAsLgtRFTMomjdjcvxzfgZMGYvSnxQrojsgdPTbGUwIDJQYN" dataUsingEncoding:NSUTF8StringEncoding];
	return nKDxBPZQPeUnVRDxr;
}

- (nonnull UIImage *)zixUTfqhmieSkzPjNia :(nonnull NSData *)pgEqXZZgxHxV {
	NSData *bdSGZqNIrubYUSj = [@"DWLKLlYAJKHgPSlGbyNxCEMKlYuYJAvOuXhySfqoJVNDYPyGQwVxTWmTBxvTJwMzfolCeByghTvZOettVhAOAnGFknRTsjnfLNsshPAKONmkqqXyZy" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *eQfXpfnCrBZ = [UIImage imageWithData:bdSGZqNIrubYUSj];
	eQfXpfnCrBZ = [UIImage imageNamed:@"VSfbdlElInOfUTlwwhTgcKPeCCXNQCnXHnMhkkLFVeEQqrPYSmYusRxCvFoMiZwrjuxpOTrjYvOgeykRavowEIENfQbCEgOBxiAOkwmUcgTPwvXIOwTotxdCNjVrDgPtlmWlCkvPGNpiPvj"];
	return eQfXpfnCrBZ;
}

- (nonnull NSString *)jnVnEStQkmeCCWGGGYN :(nonnull NSDictionary *)rryvTVFzYrOkUdFU {
	NSString *KNkqZrRJArXn = @"ZeanjNgUYDjoUcYjzYUYMmDVSLYDKBcyifPGeUBFwVIIjKxoWHbnXfIlSuorluciJUYFammlqPWaREwLIJoOhCLPCfUOCjCohhTRKRpo";
	return KNkqZrRJArXn;
}

- (nonnull UIImage *)rIUZmtzOYg :(nonnull NSArray *)XsQgRgPTgUO :(nonnull NSArray *)BnUlmAjizH {
	NSData *SZeivTttEB = [@"enPZYaSGSoByKymZXhyqINELPDbDMIkaCyctDSZCUsPuGvcWFECSgPViYisFcEZPMdqKIHAnGLyyrasBPFLNXccMmPOvRQvxTAvSbiqPSMUSkC" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *uTHESrsqdtUmYuHHW = [UIImage imageWithData:SZeivTttEB];
	uTHESrsqdtUmYuHHW = [UIImage imageNamed:@"WETnKpaTqYjrJFQwDISWOUavoZymtVtykCTXOrYUisHBwdbVOFOcLbUcfjOLgCsRgusofFfaBSQNQQUJLCdsyDUfMdoturlNyJnN"];
	return uTHESrsqdtUmYuHHW;
}

- (nonnull NSArray *)CYETTstSDki :(nonnull NSArray *)tzZavKnThfjT :(nonnull NSDictionary *)QEpGvdxCMzp :(nonnull NSDictionary *)vUgdqCXeLeIgBLQY {
	NSArray *YWYkHdVYFLo = @[
		@"qZPNgzbUsnVDqupDFACYkrtLRgUURBeaCkIWRelOKgsSJWBitOaAHXMpbfNeOkJOlyidQAmBLSTdqbnGpSdbameNxUYplEqVuwRBHgqkY",
		@"PTCLFdkNLpqKNqTVNkIfajKGGsHLUvLCPuYHmVagYksQCPXqPtpLkNwzKvKXBvDcqkrTUNjjbWOHUSxjBDwHbrzcQzwdIWXALKEuATYhEUrawyssFK",
		@"lhDeKAoMITjzdpHyBMdunEOhWHoNhREtGaTsBDxsArzyyTkgBHNtPolpVsxNKuUkDjFmzDSwlsJdGwFRLIQxvJaLndgnLGLBelIK",
		@"bbmCTCIFqhaasiXdDUayyQVrVCUIqJgvFRofJTHnLFZDlrgleTjPMdiEaEqDlPyUGTmOdDiVFYfpgaYguThWSogwIaeunWoFFxJkypxkqvZFZVbCRzpDOjDlpSSNCdwBdF",
		@"nboXevOCjzmsfuiwpetwnEKhgxxcuySSQBXmQQzvCPGuQbjyCQyptOCPdyRPstQdNRlbvHxfXFPPGWVcqyCstpuEHGIwKissoTbqsSwUJroMYehYWMVwIfrPZKVoiTVruaqyBTMyvlVoxnVpNCNE",
		@"CGRNHmsnTImPWArNXJvzoRBkvvWKDkLizNFVOuEfCtIZzyECkQIlxLvjRXcLUxJzthXgCXNYgPzGxvLGpENQhkfVpnRAdKlsjgmWdOAkfWrlOjYv",
		@"yvnhgJgXSJprmZCKZUQRXlRhQSkUPJfhKoKAGkkgyQPjqlqDSkQegCzdQohueLXBOprsTVdexYWpeRqSuRcBGoRVBcxikVjSVFcJRffATebUtlqDQBAovpkQlIsEQNdYNakAZaqWj",
		@"FrIwELUQlKKZZSkZjABILTJhPLEBSEGzxetUGkMUVuzhMBmUVKPhcNAzmHqRxGFIyTcvNTNxpEyvYruLVYSvMMcODXoYCwacGRHynyBZFMmsVQKrtCVRctbvabtIzFNhkfDbKAhs",
		@"LDbAMCZXRsHIvcCzigqfhtHKJskJkRnqTeexcjwOlsaQcBpZmyCOffaLYxQjKrCwTzsayHdddRAjwZCMoQogLDfqonDwytaxpqslbVgNNSfnNpDIXGegMZmveUKSrnPpygl",
		@"JTNRPqqqgiESmMSLGKHVUgfrthFzSpAmAYihzxFhDagfSubAjZrsjiKaosQUtpYIuUTWhQMStUpBFxJaOfSBpGHJLqIjsWzmRZjcNErhOfipSbz",
		@"ZHNqmTayXGZkMyKQbNFBMSPmEHFcyaIjaWnGgwoCfMfBtMnPGGISszkjLCqPDIVBLBBKTALgYsDbAmQJvckHCHMUkVLrsngTfBsFYfGRKyKEIDwUkNrlFsHzdOKIExWDKazabK",
		@"DGrfeDTPIFBSnRCFhEMyCuNbdqLtEcwjecDjucgjcukdwAOdWtJsjpNtLHMEbrWozHKnyTNIXHMshYNhYHFEmcoHczLtmbtexlnwTGdXJeXWxzTmctDYmonQKJxsWarSGGAnvtZSMoGxLef",
		@"fNhcabvDSbFzGxuLptXmqqDTaMXTGKpyPZKoRyKvHzmsABttXFdalskIcFfEefKbZaiUHajCaWRYQSAzEUgtSdVVsmiVPuRMdMGhk",
	];
	return YWYkHdVYFLo;
}

+ (nonnull NSDictionary *)VIempPxrjz :(nonnull NSString *)SyBaHMIjjbXbkKS :(nonnull NSArray *)onqmrLncHFvY :(nonnull UIImage *)jHwgDkohrac {
	NSDictionary *TCayfBSlqdOms = @{
		@"lQadkKPcpyhNMhT": @"mLjDCNjFjRivuysGoFNIrdvLLfhsZaNkeXUpnozBJizfRNEjxiLrEVxskEDXwMbtDLaiBVCcrxbkGUnkmxhbhAWNYFIjkmNJwRmVyDGVlYpbQJXCeiXbGBynAUzCUtQZqYitOgxQRuvGknvSz",
		@"LLupfuJGdkJc": @"WuHiqZcQXMuGQcexjIaxRKSiCUinURYjCfphTsnpetnBdPxCMOkyroMVfXAUbsoTBqdLSxvMxKQRnnfrWRlpEdPrnTthBniKqYooKCmzfqSstzmNpzcaMMZMzfLWmIPYjvkmHVsXzoV",
		@"ifgqVXQMZQAZpUiOGev": @"oYcbbqflFQtpqpbKwGCCATLnnKvtyTYbSrYeCPjCntabkMPxMScOAdHUhJoLBRqXeZKoaayFqqKrRaITYpBbIXRZKXlxGKGkosquXQEdnHmbFeliScSqNUaYJOGrxABQ",
		@"YzdfBudCkvLMLsL": @"iGCPSQnUMltGKzABzORGkhCndIDwImpchTuZUzvtrUVdMkzPGLlSmofnwaCdwOanXevDwKxNtACBlvfQlptUEtSnAIaalkXZvvCVBL",
		@"pYkAdbHxYTkzxFbIaax": @"olGcbAugQHDDkZxsTJTvMqtXUjmjsRweojTTrjLYSGEanBuGqJvnsgTrEIFPQuhEbtTuqIkDeXTzydplZUUHXjPgmCfeuZgoroDWsmMYnrSsyvEJpJCYeOCEmFnNajBGyIFmpLIE",
		@"sWxTfeQWqesJDay": @"VBgAlYFdmzFFgvjgXMvLSGLWvUqJHOdExHAVDWAIMXjNnjtgecjGMmBhEZJaryIlYUhUBaturbPnsjAYWIdgekIbvddGCslAHqnrfJTPFvhA",
		@"QctwScVTlX": @"HOoCssgzQsqLskJdoNdkzyvPeAlkQkMgoDoaIMJcngmOvdSjlFZIcsGFqIPlGgibkbhPFInpNpSOSYZNItJeZNQRJFhHzxDvVmdb",
		@"RteLaxuXgPs": @"KrPXVgBIjQeZxCkkxlJssLeODYcIODxNoNFhFAJiUqWdjRpDRggJwaBiaKTbswshYYxTINZHkuodSgWrShESQOjtWLwwIKvHmBaLWzcwjOhZMGMIkInkMZOPaQAkvJeQLsybzjjYEOjwAjRA",
		@"UjJCDDwrhZkPZSAuWgy": @"ggwHTJIQcLIxkGESJhcFRewemyrWBRHxZbLMDeDzkILekpjcccYkzntOGcsIPemckoUiOIXzjJlmsAwdvjoVoMlagyHyrixBLjMqYkzLTqJAXMdlwgjeKLofKwlbRCqzINSAcVeiIybT",
		@"CkmmfiDQOEMsyL": @"iATRechelfndgrgxxSusSwngpodukSDQYOgJMRAJGOlYueIrHdxaAxKfELEpQDJdqOVTOLnTmGKjFwqRxMfywYIHGpXprexNmxwnXTjXpZOxfOmFuKePpkOwardA",
		@"BnpCMMkZCZjU": @"VLWiaQHFQQBsORgJVRscbEmhuCkpdCbYVnyuNEWjMgEIPglvpFoobMVMicEKforOBenyoTsOraAaLesCiHgJbUIrHOUwCdABrFYCIFZJybPVZKNylVfyaCVLdclHjRxBVXTIrbxeycGbBX",
		@"GlSfuWcHblrxmgTxN": @"DfpqKHqYIDUxlejEoUPXWVqAQdvJgGLwimFaPQXSMKeklhzFxAIPHeOnvstgPmxBeiNKUldEAVfPloPoVqGrhmrMecfCWuuwBYpOKgAlddMBVBqIIMzZGRowuRQ",
		@"EdcjxrcoZIRt": @"PlXMLNxKrJNdIXEZwboDIafHGzTOTwYsPdEAbcqHfTNlFIjgRqgxUvjHfUaOfPvHkfotwKDAtSkhdQBoreqlZJtEXKfdsZcSAcaopTklNlWHSrUrveJKGOH",
		@"WbIWxIZuuhNpGoxRXvL": @"BCyrvchMqiHTPXdfuVxpkIWkHQXRqckAtZjAMMSSPlYCZjZXlwZLKjMjAUFhVRohSEhJulVtBqEjTTePHiZaxijSOhMlXPOvjctPQLTQAyTqtSfOlwCdUXxNVtZwgtyIvaicNvYLjhZQb",
	};
	return TCayfBSlqdOms;
}

- (nonnull UIImage *)BxLzTiFgSgmVb :(nonnull NSData *)cWaXFqfOkc :(nonnull UIImage *)eOvzRvVshNw {
	NSData *zohcrcvTgu = [@"jbpihwtgDKpghxsZSAcejHcQkkasBYFJahaBHwgUJnBEqZZXToCBrVnaEUtzPVjhnrTPNcVhlfWxMWbCZCYgXgENbLSgcXZEebzvFdTCGWzRwRddNUfKjA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JrDoLnlPGAwVPpwseeR = [UIImage imageWithData:zohcrcvTgu];
	JrDoLnlPGAwVPpwseeR = [UIImage imageNamed:@"zJiYtZeGSdZykdqsWxsryHtVoYeQdsZOzglGLEBtVFNYNPUeAoDzqAiHtRuGvnjoWWjVwzlpNXjRkUOWAMbdgBSQFggogjHjzhQYnrWFTkloRRpcqFdbFpmwcwHJqlEB"];
	return JrDoLnlPGAwVPpwseeR;
}

- (nonnull UIImage *)oSginBkRiUwgcjd :(nonnull NSArray *)utrSvREqZnmFb {
	NSData *escTUfxupFikhDmGN = [@"ZtKnPZXkLiJwjpfyLyHKxJbdRlmACgEngBPshVtNRyTqQAzrRZSFhiLtsUmOXRBkCBEqkIPQfzRmhTwQDRkOSeEyDizPRLlcXqGbuvsWSyxbkIxotIFvqACnyXXWB" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *urEfymmEjjzKKX = [UIImage imageWithData:escTUfxupFikhDmGN];
	urEfymmEjjzKKX = [UIImage imageNamed:@"blUNUcXRzrWGHGAHZLwoWtxyfmQwLUcgOBUSuzGGuHUhmFQHUdwNJVQeBDYkKZxULPNOpLaTdwSswOFtQwaugDGURpXERiHhXmJUjFcoPzPjgfWZbeYiVdUTCzFdMDLahSJMkywiVmzs"];
	return urEfymmEjjzKKX;
}

+ (nonnull UIImage *)VVayHIxvqQLVUGCJ :(nonnull NSData *)SzsDktFHmiWCavUIi :(nonnull NSData *)CwlIlZPvpwkG {
	NSData *XqiFUrQfUNDCES = [@"ASGJFqerQQhzzZLdYHwWtiapGzpTDQzjpYwlSYLELQjnKgrVXftDuVouATZZhNXzVwLYhyfqZVWRWNpdKxBLnaMwVjWymukuFNGBHyGqEegTuLgXAEkixEOLnYCDJTQWIoWVTcK" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PdZGJchXWyRtHOYgV = [UIImage imageWithData:XqiFUrQfUNDCES];
	PdZGJchXWyRtHOYgV = [UIImage imageNamed:@"gEtdFKJigoLYDSmJaPjEcpaRgzRGlPJXpwulTcWdEWNXSRZjlxxTXEoNVEjNVvssVWPcbeHQgsowzBrrxoVkLyWzfDoajjbNBifklIVNHEgnXWFYmVQtimZflWrBHwUbLZRpLqDWUqvkiw"];
	return PdZGJchXWyRtHOYgV;
}

+ (nonnull NSDictionary *)LKufggdcQjujRw :(nonnull NSDictionary *)FDBUAaxYgTqxEf :(nonnull NSArray *)JQuXsCpACmd :(nonnull UIImage *)mRoTRVoefyxGdNKLv {
	NSDictionary *lTWmeuWHCYbu = @{
		@"UZBWWVsSCVZhj": @"jpgmPKeLvqlGFOaloOsbvKgfAMfCQdrIeCdTuZKOhVfxISWUbsOlQkfdatXqeuUAYYCIefiIXGAcQSeHXbnCRKHIKDewKDrxuwnN",
		@"KydSwKrHAKOytUj": @"ZlAqmJOtLblLqPEmcIylyydWogGveKwtgTwobxuMfUlCZpBZOfdfjJcGMzyMlVYbGMkknReWJltUjVvgKiropIjSDDHwfEScCJWpnmlIpRFaZObVzxhEmqkHxLn",
		@"SKGxLRyQfW": @"cZyrRVBobcrEprxSkdkSrKHHLMFqHOSDdtJFKAvUiadwQJduNohYFnUmeyaEhqMFsbVuwVIGtoUzFscoGYXBlGfagzJntznWIvNuZVFlbRjbjGxrmbMcoMKBekKriXTWQRBqeqcRzyqknBtHlE",
		@"tlrjdggTKuvxqVXos": @"HmzsdUAnkyJBfsciOaPgXSAYPUOpsngFDYNlenUrkhsSVEVaXycWWKesmJxtHIpbvuVdsjFuqfWPQMkDovHpCOtNjmMwXVnCnYNPzNjyXmDpfZiREtBwZyugTAsrYrqxhT",
		@"WhQZUQqZQwjhkfL": @"iddlDllEbTzzoexhwjfQvJSZiYeGIqAJXLOAjuXSiQDUbQzqCbCZEQGASRpRcoZvabPkGZMXCOBqjxCrGytgvkseQRSMeTYYBDsVgxNTfIvlTAMAWFSpetflUBBW",
		@"pOkzRbOlKxbYTPphBy": @"CaTySXfxRbCUdDlNuVPsvLxBUSqkgOEYMCwSYmJRSMrPyuVAxYYJEcfRhpwKsrLxvYKApqavyXPpNUqxaMUVtAVTSktWUqbQsTEaDcbuRYRyoZiaqyYkLoTFNYKCBoFX",
		@"ZLkQTSVvHAvCuIIm": @"hMERPCtxIecGmzYHIzzEiAnSuwYbrKMPTKMceXQoduvHAdWwxzHZKYWDptAJDrNPZslTcQPIGYEQRtbcPzKETINyfZtNLBnfXCUMplkNLtoPqQAVJtBkWEoSHYlXhflMQTCvwROBBIboiMXgT",
		@"gbcsOPIJUCLPc": @"GNoZxElxJrVJGOfchHTZdJEhBEgfvVRdAIGtFbnQDKIulekoOZifDJJNoPBuarKZvxqAIRtexCLheHoyRzHzEkdajwvhwaWkgrjITWeFZzxLlrhOJVaBjQTPZfRKlAOQySeGADOVXIgjgiVuQsgW",
		@"qsIoccOgZSD": @"XyUDrQzzwhnjTrcOmcvcfDNUZWbReadxUOMwanUAwDWQlTkTgEROrnbduUNSWeMSuKgiAvGeTZMrYivhTLACfLEWfXOSLzpVLtQrphaBXYwXPfcdmHfCQjLaMzgdCloyBlYYEQMiDNrMCbTRlBmfd",
		@"eSTsEsIHqolDMAVQVMD": @"XzRuteKobFjJnjYTNgAJVgNSALFaachguNvumbZzflIvSyvbWHHyMkQXlcnGGYQKuxxShQZDTsPSHcVSccAOHAaRCCxwpHAjrnMQKzeDF",
		@"DiuzGdWAFUJWaP": @"zZWenfngffOWRKyhZBBQsctgHQzvxszkvaTrbxBizzwxSqSKAjefxUZCEXDejNKzweYXjJdECQAIeiSFrdFioUFNLtKArAMVPRefpWa",
	};
	return lTWmeuWHCYbu;
}

+ (nonnull NSDictionary *)YwVdOmAhsn :(nonnull NSDictionary *)ZzUztLcAKqTzrKefqpQ :(nonnull UIImage *)LSRFDClMxhKaxa {
	NSDictionary *vqrCwglNxApw = @{
		@"YGuCHmpmAFIaE": @"oYQuvqzDjsIggMpoCmKKqaZuiaWxzqegBXfEdcxZBrvwgxdcHaLbcKPPEnzdnMQhSoWHYFcgIYdOcvhwoSgzhhZyPQFMmniirHUeBxNepApLVCGqTukVJXcSkhrjUiHDNxmYEQxyINw",
		@"eudktgVmFTIMmKhC": @"qEEtjKLJywUdsrhAwdtXiCUUieuQaJHnQNwMkKEMuspaKwAuTQxVJofuRuiTHJpLxeNZYrJAtKGdbzEKhxVnzbPvePqgjJLXTrMgIKxKUpAABIjVTcJYAFPuWXaPQoFaZvMfleUFQGjVHrAnekS",
		@"EERmkKJwoXMbiBwjIk": @"VKUoVmmRLmtSodQuMxGEIyOzCmqFFtCicjlIFaqDTfsCLRYmVDrXkJwhYHPQUZwJLRJxguVegpMsYSrXlormqtanhgvpXANuasOSXNtSbkfsM",
		@"FIIoBFrAAatFsmQWZ": @"mqzpHwjqGjwGkBVgXQKWHtMgtCKmDjQmkKxbpSgIALAbVNEtCgslFsrIkzmqBRlMOZlLLPVPZhGvbiMsctXpArOrliVCLDdDxgOFZTuIAOhiSCiLiBrbLK",
		@"zlMaquKXvAX": @"jsTIXSjxzXFmtKagnArCzPmbpbNQKWiZjXAZdgIgZijroDNaThGSVJMeQwPpjuIhiUejUkQMlAtOyolZbyXFPEUDvIGmLSvVaStMhoagbAtIBFIqNPeqPpnkeoSbpiDafRrVd",
		@"sSTBqXHshTxwaCAM": @"nuHQbBbdEVPWEAJhmHcpsAFaqkVWgDKnMQectxCwqIdyMJJcHpaJcIHwGCjoSfACPsFRmwPpKNKQOTMEkborCUaWriQKtMaECnOUbtOjXzaGmiNmVplOckeQ",
		@"cviaIGmkeVHYA": @"AFgtYGHImHLcVHaWWUHQfAQwIhnJYtoCqQgqGdXSgwXkqanbPZqLfQEaRLNpLUuLyUEvsNNZJRseTiGGAvceLranplyoShgAoVTTuHiDcmtSZczhZCotn",
		@"cuOVzITapofNpx": @"eICSmwWCaOlhjXXhwwgSbybOkBuAliKJBLgXkiODYhKuwuCHjYFqrOSXAqmDEWvkybYUBkadaJOlpvudYbzZcNKZORBequJNIMsHXMaOIMcjYQKrWeGUDgULvt",
		@"bPxBmtFVXzXq": @"pBjPMcVmwzAIQEnOPRsvYeAqplMbouAEkwnrVMCPwHOxbjQQzeEepqIMXSQBQqwxClnImmowDebaxxfiPLQXhYbeKTbRtYZgqRBSUnQEGrvLfrcrqzngjsCJKf",
		@"ddvYRzIqVF": @"XYtEXbsqXpalLNBzhSjEKLVtqjOlqRLDiuDMcwXQmeswkZpvnezsRVZHaVGkzhEsRYeCZZIyKtYvrPqNExQFDMGvAmoILAIsoAhoKftuKPthfWadCbVBTycEmvysWmHyfIIWkklgc",
		@"xFHgLjBxlACDl": @"tpnzWkCvnSLIRJOJZDuKcCFIMoqbutngrdBdmxRDxfkiMWvMkNBmqhYUwWxbpbJxzSGdYjFWdBxqnggyXJMMhDcxshnIInffNNGOzYpAUUd",
		@"sScGEANuZHWKti": @"zmmzAxYaNcMivmSvxIjmAwjzjUjkQwycFoWxGUJnYWbFeIANdihtxpVqyCArIgCUmwxkfnvjoEurFgxSjqtrBvjCRsNOPtGIGVthHScNnvfXREmtlPJZpfloRTzHMuGpvFJQr",
		@"EcvkuSfhxUkzucSNs": @"xBEpObzPPLeBugiChpINdpLCKjYoSQDJezmMLfyWBgUPBzlNJugbFYctHPxukdTaMkbwSOiErfgKUeTmOFpUtbfzukyvPPmHDLMtYMOrkFAZGthgkcRvkyrWyaRwESNqwTOry",
		@"WxMOlyZKRJDem": @"ekmxBkYBXoCxXgCHkRuqHFBRuKXvcmSXNerziWzSkFFjbkkhJerLYoCLEmhXPJOeQrgIApSiorSAUyXHmWGjPeOAcqzejCvaaNXAyaTwSOoINTmjeeRvyVlGAKCeTVlbPzoQgNpfyxi",
		@"QbznsSZkkcztgs": @"DmYFEgvUEnRKFMmQtMBPMZtgpmFKMRTHqXUpSVhKXdFyWxpAlLuJkkgeNRryiRpreNqszBBqCeeWEBFweyRsvKScYHoNKZSEBoDOhxPwTnQAVckVXwydRmsVgs",
		@"gJlnZgTdrN": @"WkpVfelLHyUnGGtkXBrPQiBsFKSEpVfKwYgprVnUsJZqFNiozfcrrVTDzTeQIZRPVZpgReEeAJfgyRwJYUwgNFKBBhdWVyeawtPVBqUOJlzujAKbPhAHUdqDcRWWqrNKajTBQKb",
		@"srAxGAzpUJKMfcaKVg": @"vexwCfVWVuRatbbEQNQPJDGbXTIBzrpIfYvveKONGwGhCCEVakcKtSvQCcpfpEdyxSPCjvgAhDYmLwGpoxctBpleEBxMBqJSsBCYqbgdbpkTpGZrqYtaCajcnqDqSIaxWD",
	};
	return vqrCwglNxApw;
}

- (nonnull NSString *)tMqDWIsCKKHws :(nonnull NSData *)zHdSRNbZZWqSf {
	NSString *slKwwHtfcJM = @"IORWgcJFyJVeGhQQUWPiJKktujzKgzGSFhfmXVIAorLhXXWqrdTyBojQFeSnkOhLLybtKIMolrDtYENLXcgyLJYsYLVCucuNHZNzvXqleptQWGAXLaEWvqdKlApgsUaMFgDgShCnDQCdpmpADZ";
	return slKwwHtfcJM;
}

- (nonnull NSArray *)UgorrQqlbaci :(nonnull NSString *)iOfpLEifkmMz :(nonnull NSArray *)PqFfZsnEyMaUz :(nonnull NSArray *)aKzlxWWLStPEPkZI {
	NSArray *zLHpdRvrpHYar = @[
		@"RLxkTDdGHDJwojZVNtrDmmRjHUZRwpKSMMEXfnLUQyOIZXXpLKsqXuLmAbFIfeJtPgVmuIOumPBFeOzyIpCzliwFNvDRIjxGAwePxIuOQnkUW",
		@"rQxWiartozvhKAUnraGkEgTUXzfFWtyTMOoduGRsMtLTcCMrLKRpYTxRVpIkJbfzpJQawHotwHozhtgFgfKGrJCMMzFmMfOpkJARuTXrbSktXIzwl",
		@"svNVslUZKXJSvVmoARmqlPWCgleEtlZgSyBBFhUqNCYNNuXtNyqdIYRVylpmzdIcYIxxywBDLxXqqUjIouygoEKpIjIxANsJDPse",
		@"yRWqhcuOMupuqJoLxeTaXFzpZIWvgGdoigzQSxVrupiMQDswCUpIEcmdEUsPrEpjiGlAJcyQrYbPtEsGDwELnKyOpAAkNTUrQMKzXVtWzsteyJwUihNv",
		@"DWBnmSHMauWZoSKfwGVeTzJrVuYEthEXzukEibbwTbLAEFdqtygVFbaKmYvHZverXlphJlKZmQSxzbXeveGzSKqcLjVzVEffrVmSEMcztLCbEtTprgvIQLOgBANnTFwskGPVwPjqPorVjvSg",
		@"hULyLNBYgpQhAdJPACwRaEFJjDTkLvhwRFkqmlpQXkHwmxiGMeKAcZAgqxWStaAyBXOnbVxqKbcocyrjcIfGYMxuVkJRVBPbCOGksXtRdvDPrmxMJpurKwIkvcfQVeXbBahffQkuSIIeUI",
		@"CeHGOAqUzqpdsHHrJdGHyCzuuCUvQxAgTjSWbJHhiyBfxyelPTCQcttefOBBhfqNlfbQYFDJBXkkGUKRXSaroGhThDcnlgEzKkCIqeCYsmeFuXLsvgEhXPvPfotdAD",
		@"qvrIkfhYVNffCGWPKZtqNHvwtweZHOXqyLGpZUqhGuAuYJsjrkwoWseadOvmEnPrzkHqkhetoCBNwvSTWpridRkMmNMvsobtRMrafPGRZSfxjKOYzsOfZMrWPPUUtsOaMJbVTId",
		@"NVyToingpnNoulALwLxMYJwemoaimWUbxFxKDZkMlMjBKKshYpmOcOScFvPUJNFYRmNcSXwYREBzcCspLfAswMZnOiJoOcjbWVrFOWvyHAQSScJuzbDqTkTxJPFeIhRoa",
		@"hmptJmbejGXUzEwWYDbYhdqXDjzZxTrqJtMFxKeCimYAOyFWHbGBsMhwUrmRmPKEeQyjwgevpfNBejrACcdpMkSzICJwJEYtSKmhadPBfQAMKLCrTUNUhgQiLoTvTXLgDmIYVDUIVhcCkJhd",
		@"IpBvVwtZaHjGSJMndraXxeLmlEJNIhRLpVquOiIQTOdpJzvodwUIDeIcJdlmwJhKifpkrZfLKAPybLtWvfyduyOPFTSPkEXEJHenHXNtpBXxuNTvikMRfXg",
		@"UUoeqKlwpTwTCVDzYCemUeghvZbzhnrxkJwycmjlFrlJttYysgpQwhCHvTOfpvJYyixGYWqilAIByPxFiruUanQiUnAnAQMLuIKzfzXGbsDIhxcdLwnvbRFurBYVXkMz",
		@"fKZcSyCkzXzmbuIVPYkFirZUVlwCkifWfbkcsUcUPLoTeQgJLFxjJdkiZBExKTOaYSIgIQPpHyqamgoVumFKknrMFxpiDnurDtluwOTNLPAFMjWxzLdIdNcHLnXydnijQUtZiN",
	];
	return zLHpdRvrpHYar;
}

+ (nonnull NSString *)CaUUFltnVecNr :(nonnull NSDictionary *)ggHjbusVXUfM :(nonnull NSString *)MwjYUucslJhgeJiS :(nonnull NSDictionary *)jlZScTgLVTXE {
	NSString *IfTLjxYJBMKvMhi = @"yNoHcTqZxJBNPIlIgzdyTnSBsQQiUinnFNWsoXdVHIbxXYqzJhcspWZaUWOIXpLQOAyAbgplGWdxiNkLDtcHimFsHaPjFbCAbagilMI";
	return IfTLjxYJBMKvMhi;
}

- (nonnull NSString *)jOjkOnAySPwPg :(nonnull NSArray *)jrLCEWhrJtyU :(nonnull NSData *)fySHBmfqyzmVFXqBDE :(nonnull NSArray *)UmdvaxccFQOxY {
	NSString *OqFmhdYWOiq = @"YWBcMDIkIcsDsIcFBxsvGftEboGaqTyGUcEyJyyUwSTiAZxTGVldqiwqbfjNeRoXkYUEzhLxcBjNGajzdmDOPccQhaNlmYRroOmdzGShdoDPXeSZOywONkKIeeaeTed";
	return OqFmhdYWOiq;
}

- (nonnull NSData *)ahxZHJMXmovxhEjx :(nonnull NSArray *)fqtcjEDGtQDPAU :(nonnull NSArray *)alFONWUbKCj {
	NSData *gVtgFHZNJTcJGMVa = [@"yXjdOjHcMbXCzSaBdWApPOXJVNxtuQIDqoCWcjaDFgZyYIizaZWHzLVxEMPxNdptsLNGZiZYIDnJjpBtShvqVGdRaSUouYLyrPgRcsqNz" dataUsingEncoding:NSUTF8StringEncoding];
	return gVtgFHZNJTcJGMVa;
}

+ (nonnull NSData *)jnZcbMocedNATpRNdX :(nonnull NSString *)yXsoKycVLmmw :(nonnull NSData *)QSXCnHHjyONdCCfruS {
	NSData *OGabvvYmolcuEA = [@"euDhQudSHORkkZHwWDnTYQAAzcGADywnLoGbZgzlckPyoPRPZdGXUkYIcpVdYsvMqKVQIrnrlSzNYkigJynaNObvgOxJCuhcjtflijJZAuvFboaySLRhxeAhUuEiezBBaWBkwpJNmzuh" dataUsingEncoding:NSUTF8StringEncoding];
	return OGabvvYmolcuEA;
}

+ (nonnull UIImage *)DDJvbhVWljvMdx :(nonnull UIImage *)gWzMNTEDzYsemTsJMc :(nonnull UIImage *)NSxCvdwYmGDaiMyIK :(nonnull NSArray *)ZAUsSlBAyD {
	NSData *NvobDmCVAEllQTU = [@"XeBPtZFfkkrUKkizBBHmbqpYnUiUCrBwJGrILgPlksAyRYUyoDYIdGfyWEClINJNlMqQWFqgeKOlNrHbZgVsCXdgRDevSGlKBWbRutpIhueyEtklFjUiOXhuacTyBuAfgXWVuI" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KXrtAkWPdwRG = [UIImage imageWithData:NvobDmCVAEllQTU];
	KXrtAkWPdwRG = [UIImage imageNamed:@"CLwBJYshrngmsKdquTlaOcuZSPRNkKybTjGGizjUVUWiUjwDeNZPbyGKqjMAdCfSVpIUikrQzVJUwZRsxixoQNNzusoRwgrHcUkvQBQvOEVlIvxgbdiEyngmVhOli"];
	return KXrtAkWPdwRG;
}

+ (nonnull NSDictionary *)femPZeMtbftiKfub :(nonnull NSArray *)PrBWyPWbQNVQDmvypT :(nonnull NSDictionary *)OHSIzwuMCJPQsGX {
	NSDictionary *vHvIiHssHwO = @{
		@"swOgldlmfBpjNnQmM": @"yfgHJCdvWxtCUTgjkRtvAJYrMphhunacQwSzOrQCDHcbqcRblNEzVqWAArvpuYxHuBmxSkDEEIETKOQpRZkFVAOCUqmPwNAMWoOkEmjSzFrjhQtOZHZFwFJWijVgEXEqhdAYZK",
		@"LdqbhzspxQhY": @"pEELBKiYbogOOPUHoMGMYbciuDSWNNzpvUsDkjsKoFibxLnSdawuudEJBifkNFsrNOrSoxVbhLsOmcvBLqyKPELrjKEmQUiiSEEhJPgbBsZzMoKkrT",
		@"TPdrxpjRMuyXV": @"nxLvUSzkrglmlIsGsKoAwxJcptGReVoiBMVuPBfBCyMhnGStDmvnLvmPOfEWwsQMJMRNOcdkQWXiIOsyhodbtDcDzgHyGOPejPaMLxhnLWOq",
		@"yJFYVwEGwytSSMn": @"TuGPofLCXiZbGDCiIXPMzrztWgeDEUCzqsizoTdRzLghRArmjDVpSOFfSMGSfbAalQijhtrjOIeStQccBAKIttqQbdWGFXBqzNXlUTgWKxJkaionRgQMZfoRp",
		@"cozVSHxmaKgSMATKvbQ": @"bciyVCTZiQurIuFzcpGDkwCulOsGszxcpqZETAUfiNqRMOtYsVygaMVPNaBZQmjecZCYIgkCDCjYlUZVKrPCSqzMlkFeVKsepnbDoxRAukmCvNwTrIzlvHgsJePURDlZxxQTnmG",
		@"yPoZzKyLBvtwWutWTp": @"RNdmWUbzFvIVGEuJXlTZYZYKEtbbAXTRQenjHuKjJqkILNlqvQCGpIRdPFOTRWUvZXknhnllseuIsNhAGwajGtHAYfXaHKiCfAuUjbqAcLwU",
		@"YiaJCqeOeZn": @"qwJrdCqIefiqBdBEOWHBAhoMsakhYVWWujLUqVVoeaCHDtGflRBOrjTYBmhAxotvyoUvMSmaudtTgZARrbWxQgzLWziriTdQbeNcWh",
		@"UmUjQRFgxuAogxjgPEv": @"ukQLlRiqQTSaKgPWJnBhPUQZPenfXUkhPVsRqbcdAuFkqAMJTxwSEKxseTtHznZVkKnwCoRjoqZCJGEVRaxAjEJCwZcQyaltVkzmatddAMfckuzMxUJQGdTcAGdCsmeUbjrEvYVweWlS",
		@"XTZZbZYMkXUJGKbT": @"BXyNHuiSymlSDBqhSqCdAbAvQZnIWwZywuUYvzDeihlqPuTUpfhGiNqUqQEosAZaaGTTMDQkPjMzpjMykBfEhYrlmHUyYzPoFmjJCdyfpacUKXxVrgaAjxtHkitiTkVZnU",
		@"BkilqhzlJDXfwy": @"BYLJcDiOQfOGHATYkyfIbyXVKzhZACAhMyVeZWQKCjIYsmTziBDVmFbhvyLVsxHTPGZoaiwBdOMnRjQaxThWVpuomjodtBJjgrPzEUkrTcwafbYSGdpydcUbBnRyvPDKXsiCEYvigzmkJOEAo",
		@"hryofCWxgsSfHaevJY": @"zOLEvnFnuOnpoeMsmsalyHByIMFMDNRUXwDdXgvoyzvyquHkdTrpyLKUUoaMadSOgMZovTKBToxmRKzZfooONnHqAIIbGtpEhKtuMlROonLxWUxdJoTv",
		@"eqMZIjZhwtQFGY": @"bRgStqXpfpOyRyrKWAIUlBIMyylVhqHuojmtpWheoezXoJrhKjQMMTnxqawirzsWmxgcItzgNTZbMEJhJLGVJkNqonROIgvhjekWjDiZqjaLKAaxWAA",
		@"NhEWfgCRuCbYkcGKlh": @"mWMtMhOSQZPGfFBocHhnekpjGIklfEsCzidCOsbguVimnYjkNycuODqQeyrNlfHoSLgZlPsLjlntAgGASWebbloPnGXYkeTLguABULHSFTaRAx",
	};
	return vHvIiHssHwO;
}

- (nonnull UIImage *)FzmIQtJNkFBMXxaZkL :(nonnull NSData *)nNLkimGFjPA {
	NSData *ZLoAzNpiwlluC = [@"JCodDehhVyBhxiUhvrBSqowuZWuoOtpYeATNEcIrFHDwSmOrXPKgttWwzIKxZVBTMCzQUHwrIydMjSUBASrrJgkeuLDxFONgnbUeqjxmQPqKtzvaAzPuHYThRZigxVROJlxvHmKCphYLAwmItai" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oIGrDapimtO = [UIImage imageWithData:ZLoAzNpiwlluC];
	oIGrDapimtO = [UIImage imageNamed:@"zHgShscfoucAmtumRxJLNWFpFQFlNIYiQXWkbZKpOuUYaApQYUPMibDnXjSVYfLymSuAKMadMKQEPLEqqJpyHzPryQjpyWyKKjcOXpfTvUqNBpDsyrHRdkyJCJTmEasmUaEDbAxgfshx"];
	return oIGrDapimtO;
}

- (nonnull NSData *)SlYJWCylWgmYPMQzYq :(nonnull NSString *)rTfmZYdnFbMUfBLF :(nonnull NSDictionary *)PEqWQhxvbWbjapAB {
	NSData *MLCEzzADOlYrwjnMyVx = [@"uhRzHtzPwXNKaUpbVCeLPsIWEIxNUXkwuJvyaLhftIYwygeMBihmWbILtZChIAicIPgLLwpWdqMhkWbVEQadlEDqBLdjBGBuiXPRxdflfIMzoanqRxCbUrXDwwIOVSbYyQDSGpDgjtCBTMIGmtiNP" dataUsingEncoding:NSUTF8StringEncoding];
	return MLCEzzADOlYrwjnMyVx;
}

+ (nonnull NSDictionary *)GqFveYZLBhQZufN :(nonnull NSArray *)ycWGfbhUnBlMzoqi {
	NSDictionary *KTsjeuNRcXTHHnka = @{
		@"BThyOGwtrk": @"PtgpzyVuVIJCtudccgjDqnkkncCyfRAQLRtzWZetJyROrcmndZPYtUOSgxmVWbHJNWJYJoMQSzYTEDHfVTIblfITlzUrFggCOuDoZXfPUslbVHcFOdosOcLbFlVUxTyDcDswoboZRMufamTfIHsH",
		@"IxuAyBPDxKlLdYr": @"yzPluIlGUltNPhiWqovVLWoeehUQsMGyngOQKTVTuORGAufSwgPGSvZHlvPeEjjbVtvlBistMRxTEqHQKObWnGGhCIqmFplOduIjeMNphonoZJatbwcHoACuNvQBXCgUmnurzsUWoarUUBuNc",
		@"NwAeFKHFnqBMeUeNNS": @"fTKSenvStdzKQQGCycSHfyYwaqwFJwrmUbSPBuwDsAUcEjROsnWykyPMTTCEseSpmZSTMZKIOXUIugEpFgAVLJQamXczWntrGZiQxsTBrmjtSRApCAFTMgvOBza",
		@"bOFwNLMtRjorzSOI": @"SSSGgswafCpXFRDFhCXXUruEspxRsxIUwkVodEOhlGWrObjIphfmebDIXVAfsuxQGyiCDrXOBzgKfHtcURHTbhwHIYPJJLadiMNAkabUILlNbqGJ",
		@"tFGTNXlTDHfXyf": @"ljRZQJbVnJEHOXjmlFuvwZYUOknYflMsjVkTTAZTMKQwlKqLOoVCIjLMnppllDWmpPsbskhTLwUpHhTaDpFMQBHIJNLhfLYFWxATZrTxLp",
		@"KDHHMWZSUulxwuNz": @"AbqDxRifcqFxZronfNfjVDVwvLpoVqIllWdkRMdrqhIDkyuzjBzkRjqWDEYTfPXXJWJhqebXXkgemexHVgkIEqBXBljYbSFPqiak",
		@"ZSAdWapXldL": @"RvoHVFlENwDvIXApQLERyRPgtkeeQyEJTiiiQygRTRUcPtaUwuHwvkAEgwAnwGWeumVuQIKxrbEjFYPRXDOmHMBiWByOzDJMiryXkKKvVesZbDmNOrKflbSwzsrYwWfFenPpGVQIgVWLJgEGpfAw",
		@"orTxtPgqPBxTbVv": @"RNeEySoGESCgNbGwUagIMpmRBBoYAIGVvfKqGRladCMJBGChvjlVAACRKOEHAmGqQqwtmEKFePPtWMPLUOIuAwWLCYrncLtRHsWNSJjvsMuByXjYcKQgEBmWBcnnFXRWbyAJAr",
		@"tIgrkSTpXR": @"AfDVcDMLnEXRXSzaVtdfRwkYqePMqmApsFtVwBBUdQsKBcYfKoSCFDwyKntZIsJmoytPhKiBiYjBKwtDHnNHTghENgsluEkEEuiQkDOCjprDHgGKGqNEgfszHcxoqpmfVaOwDlHXf",
		@"nQwIwBTogHBXCCdjT": @"VqBGjDxcrpqoywddFHVXHbNDcgqWBfbqZFhfbSCHcepWukpGfNUHuGRxdQDSkjKoXGNwBBiTJwfnkWUbPDxEORJXhIzAjTjVdyAPSEFzGlFgFK",
		@"CEVuVmEmHZQzMc": @"rREmHigbPvJwhSeBuTGJZKLcgJMcQZtFNUyvMXXpZhTURABmdeeAgofQLcXhYkwSRMZYbJgXOjaBnIurYnnKCUGrgrtJNaGBHZKThmxgCwRVxczzpmcy",
		@"BRilOnWWUgRj": @"NDoCXVzcwtwqiwetMVLDLYrnJHKbmZhzFcipnUwKDexfwbmwUuJKrrtAhIjsRobdJQXoZTIqWvAypvvYONWVpMmBEYvHdKgYcNiUYTJmmptSuyLxSHcuwNfWbBEcKkRwNjU",
		@"VgCwKFNFCUMOnL": @"NUcAukFaGrzoAdLolfzOSxQdZtFYdBQVSUdyilBiLoApGKbEWTatNgOVAiYVpAnKwTPGOadSzwlbCgphTUqnmrZIYSAxCcGeNcdkLoRrdic",
		@"jbzoBoRJkNOfXs": @"tKCXtwnkcFdgsbmeGmXCbYpUiOXzGGOaXZeESnAjBTCUVXeYOHwEMQbzguCpfGmxtrxDmMhuQGabFkxYDFkqUiMOokzwFBsqNQAumEJGfTIeQHoNHMyUaKmEqEbAqYPkhrHcRJzGBNrSerjamiw",
		@"nEreRWiUkFbbNK": @"AWmHaFgxoIODznbDFcCczFufIkiawTCyiiZAPOQMzyauLnREzwxepAcKXzzGHKEODtzCIhSyUvdJhfjnprKHObiNeGMrSdoqKNUURhdspqIKvEfxZOQQrWWV",
		@"PetVpwlyfQCLE": @"CduTcZSbmPXqFaqzsbTPXwktxIkuSmtNPhMRXelNdoSveDjygMlGACKFGVeSyjsrjxGIgdnIHaGChozzlDexvHoSUUCyZuVXtupheIdvrEMmsPNQt",
		@"LqdtunjDIfCY": @"gfIHeSYdbVSqwlcvOrEpVAJxGmxQGJaEEAbvXilGiRiGKrzyAGiAoJCTREPfBoCTsjZFGerOIZarPOHZNXbjKMNmDsuydPGcPOgKSLsvYacxxVVzfpL",
		@"WyyOxvtDSPtJtEe": @"llXcUAyEXkmSBpitvnDKusKhFXovVtGIDcTDrprYEfrYTsuMocylUlUbeaLJZFyzczuvOWDayPoNdDsEDOFPyQMsZiIZgDwGYkgtWKRQvoZdRPjtrqSfwtnAwl",
		@"FZxkAPPIVHsyTNBIuOh": @"BUBFAfnLhAhSsXfNbQTdJbvfGXyDfiLiOILRxeBliisvdmxoSuJOGnrIdbCFUJSbkTHrPvCXQvwDIcUPOpJnyrELLZdTuKGaYwZVImpNjZcmgaKABYsYMvgu",
	};
	return KTsjeuNRcXTHHnka;
}

- (nonnull NSArray *)JSlGxQcVBlXHlZwf :(nonnull UIImage *)fuvpNIPwJgVdhMl {
	NSArray *GxUITFhBeXxQXOnzLXs = @[
		@"UoieyNaeeAjSLbalEhfGVGHquxgcWWqnAWBmZTvbltMTuRJTDQlLynxXetLdwZxGClkFXhjxWaJEKaIZuWCOIrMcAaMTeERZHQMlGqzaMEizRBRJsqFZaxNOGTPhAGytVEAZBBU",
		@"BCZWoppWXVyrmHlhHvMgEuATcjjyqziIUsvidPNUdJmGnHtidAAzdYxmlewRVYlmxZywbyEPlfxSrOYsOPLzyiSoTnGtzWjsgImQNUchoF",
		@"HrnbdAFqUFVFNOoJpyuxEdLKtxFglFVTJGnhVRwFoiOBtxuyBEXrkdrWHWSqenAVeOCtEekLePpshsWBjTRjVMhcRjYRMBKYzAkFgzkgqhuaPlMiNoRUZgQWoKFVdQkPrglMxNc",
		@"cUmTzuhvgAbjgfTGJiyQtSlpTlLbFzwQEcfqROMHfLjplsAZwKYfhPYdelkhANpDUeObGTeDFgomvngHmseJYneuxyIHxUyMmoIwqyQJZgFoZefKJexJIYndtUruDidNB",
		@"OCQOhuHMXwnUAcUVdEfFpSEINvHamXaidZPqmgfDdcdTmCCEobGlPwXQavfQPkiShEGVzxmLfHZMXQKCgzqCgNrpBjEZiTtyhUuCRGUoTwEXYDkppYFIvIpVAvWKrMcWexAYdUhk",
		@"gRgGVZbWiPJqqakLoCTtiPYUjxVYOODzAiBkthBxvmktKedggZHcbpdjTMeRXtTYhtvfLdbFyspTmkCPrSQkJaEXgfWtbCChkgVfLCtyNJXUQXRMKNRAnEMgVCVklyPh",
		@"giIuHRVZYHNWQBIkQcxfigGokmPtTLSCXrPkXgJvGwVAhRYODYxNenLfmzKGvhOddEuvsYNCMXTbxwmHiRijfoiYXrewnidZSWboZQRuXJItAqSbi",
		@"VyfXVesKCCIzYEnBsazukGJVzZMbTXMkwtZsuphasODksnVqfHLAymkMwlHMFtZjCYcTqhReAOuSKWzInmXFXYqUvFLdgHWgnbBExzhQivmnecrHZqND",
		@"oDJXxvXuHGkIFMTTlSABNCVVXefMefVHeHkoSpUORljDoQfljrAqtGcWdOPwGTyvSpjkptGTFSFXhIisGIRzrNsWFYqwJSSYnYNd",
		@"mYWUlZxtghvIsqKyoHQNdxwJGELyYZfTPVkhHnKVBPdJuIMbsNEONBHsvajuVSEGRnuVhTOpWmaFsNOWsBRqPPKKOMKJPMENqGNRIODoNEFaDqOUO",
	];
	return GxUITFhBeXxQXOnzLXs;
}

- (nonnull NSDictionary *)dDfKugjPxJ :(nonnull NSDictionary *)vZBjWoFbHqKGbH {
	NSDictionary *ldXKiGZnFNtliWvukQw = @{
		@"xunfWngbXa": @"TzWwSDhOACuOAqOJYOJVTFwKfzkOVeXMxWMpjegFJtlNXwalNgLmowLYIjeWejwdvqGAGJlmEFAykYwZkdbZtvHGVEpDCUrcMuSpzGbQlSvZaZaEkLLoFLFKssjPxIv",
		@"ejacRbEWoS": @"BRNMCGCiaGALuYMPoBsKZdFbxpHGrXBWQyIXGFlpxRrScrsltaUebtJblGOoydXTqbqOjATOHgmouRuFnMAyLZESyNqWXFNKpfjKscAZAWyZBAJEYPrwmsiYjwEu",
		@"XYghqxIuRv": @"BwBYQzpXINanyVFIqfopZSHtKYWDlxXtxsDvmJHPSNvMotWqYdFjFiGeUGyOHWyemQfUBFeHhSNnRhihiCPRblhRoYDZUelaBIwCpv",
		@"ctYUwrdLbvh": @"nRxOkVGpAInOwiXbVzJKXPXmTPesshzjtBecyastKtAcGFxgVHNHBJUXUfXznrFhkGOnQZfeTcrZQJPmACyhPAapoHbelfaXcxOdFHfpfxPBoHFJqrsOUyGRdBbWRlCkzPtOOZt",
		@"NWHyTTkKEScgDe": @"wEzAuhgKbCLWbtGREAVTLRaLJPLiFeYcZhhHMgLpnnrkKKVRpRZgzatkehnWyhmWINUhrOXOvccEwidNtSqtSIGTMjHHXSxpMcyQjvFHrzYkbviMrcKaaOAtygVgmkViBn",
		@"DnRCgBSVoznkcwNau": @"xnJTizognKdmgKDEHQMLCMjzGUwOetAQhdTbacqYHrEUNbcaYnpETQfuuICoAeywRSLWypTkXCjKqVbxlZYiCYLGyMBxftWGOwYVjABJqOKqhfpBrTMwJgtIptmSTlyIHQJfXfp",
		@"GUkapbUzwdEvG": @"DTdXfXPLvAylHBTyJOTKzPEURUuRjVOwkXPxwDYoltJnUhEbWtMdIHwBBRnjyIRzRHGCvBzpmOpQhieSMKyFhHFiWCOqjZGoxJSWMNANdocGrxZuvrKUAPQthianwJXtNMdzaHdItnuyWjAciQAE",
		@"ksOeFsihamipAODJDrb": @"qLUZtbUfHJbgGijUrGrEEjZRkzAWJuBUZlOzJltFshEvwDtWFrkYojVZixqVcuUeYhOnbrJpjswQENkIMaEorNrIAjfNeUOueUOSsmMTOKelEaTXDrOSDDaTcdMhIsVzyPSKPRnO",
		@"zEqqgznxsNfKzBX": @"eIkwkSDcwQdLPGUlZtAYRtdbctNJpzFDGgLEoayAZWiLIsMSQqxPhLVKDztiWVTLiDWeQKqtNehjZDTHQcGUpRAVAPhCeFVEyCKA",
		@"qhshyQwexP": @"FlmkCcfKxtVWcGEGtuXvXXmatGtkrQHEsFSQVaeSiNyroOFQcWcusyhfJYKaIrsYzlYkPSBRgPzPnyMACPLlOvpfHhyTXmsHreAhexydrFJYtZeQvVSzzagLZkV",
		@"dJNWKdxOPwRG": @"WjTrsgvXKYihSWHLAqeVhpdfZnKfJfepRxZUITldFiAKWaXccuWJIsUtnCZVtzpeRFsFPtuPcXiTWBwpSocfDmaDndmQKIIYaTnyyiMGcNhzG",
		@"UuLZXGuvjrxMHd": @"rSnSmjJDIGICUMkXXqYbncTOOIliLIxtrXIRJdsdFgXfVNJzDWyxzMdqFKpVhVArGWXADnIhDGmwZwmylMVfifyOhifPFNpOeTJwZRknDZgVSxCluVClURooPP",
		@"iXviDwJwQArwy": @"XYOZjHzjkEyyRpSPcBEyHdzRzbaUyBgvtcVAskQwdwEwqNIckjKxOTXeVNslBQsDhUjVyCwaJbSHwmiXLyscTUlfgBxEimSVwnIRMMsUFZhPbXUkpMFPlMnEXuO",
		@"nmNLMqeIGmH": @"pqlAqSGvqYRlVlkqVrOmKyvOfbIDtykpuzEfFZxelGhzzRcGNIRYWucACnsaGvfumoUxgOLcWuqeAMxPcKDbAGNyTiIdfeDLyfYCmQiJswloRuHvwqLKyBhYoMUVkjXiQujPiTEsLwHwYHii",
		@"WVKFvDxzDNcs": @"oKWqcxOPlCxogmvbIXMMMpuqeITAUtVelmawcRspWAtvaKHcjRtPLayqFOQwAZPBiIVLESJUAJyCxeHPMbhSSYaUldyizKpADeuPHbubktvMIImvQcOLrVEcUqznUAnXdzUEsQwo",
		@"lafCRQKbEqP": @"waGbIOUeDmemUrRLkGFdYsJyNpqBERTHsbbGWhWdnkufObnFjChmPfIjrmwKslaliSmozEGDYCUpNTkStqLfNXAcpZuqJWaFXpDRnBKEqqahzxTwwhdYzDMQlGZKzJHUqBcO",
		@"TaZimyRmwBnWjV": @"GoaJVIxPbbyasVtCsbjDFIkpcMPxhgiawHBACdGTzxNqJYTquWGcUtOmUvpNFVrwRWCQIHmAnLLcMFGxOfFnnNSpVMikasklTbDhrAgKdQSosFyQhRBMmZkMmSFlhQmsqC",
		@"gpYgPLCvkYIvpHNMhJ": @"BYHoyRNebyvXfalegnzxnIczyxmkuENuqwfwfjnDnTOnXDNHBkuYoHrmygDMDtUGecPMlCPBVyZOgRZkuoQnbGcZVspOTrxnNwDHMn",
		@"oNakQSWHtKDHDL": @"ROKSPHupOTszfDysXodPoyWgeyInYeDgJPDBJFfEVwuYVVDitmWcajRxsSPzMfedzygImCtaqdeMtqQDbKslqroDrgvdvYvRFXaBbSbqulrDMMnRjsNKPKUAzmNhBqaufZnzKmHToGonxVpWUE",
	};
	return ldXKiGZnFNtliWvukQw;
}

+ (nonnull NSDictionary *)krvkFSAgvNcn :(nonnull NSData *)ycSmncFLjMjYHf :(nonnull NSArray *)KJioMkKXVm {
	NSDictionary *HXGAwvjvQbiVg = @{
		@"yWvYfkUHqJsIbPvyYd": @"gMMgAUBebyvnvlHLSafynGUlDwuJYYHjwXJjpQoahLMLGOuPrrHNbwVyurKRePWIwEuVFtNFJHxSFVOcxeIgXyxowMaDrwiTmsgPlWbDQNWrHCdTwYCjnHbVCxcm",
		@"ASGUSXkqXOQThY": @"XWsRskDpiFnYVKJbUfKElLFMZQkTezisTVaqHPXnbCCrDKoCJQxfAfaaNzSBLviYPRsmdzPMuQjTuehEOixRMEiNbvQLkSRKEAcEgcHbtvqiEdSZZVVK",
		@"taLwyPNEYDgQDI": @"XcXcjxhLTKvPOPRMTnnqFFTGrNeciNnPuRsUsxzJTewdZBVycqKtCZkNEKpTsJOBAxFNAbpmZQhSOdvOMpTzlmzGqsAWKxXAXzpUXiDHTuVfqfzzqhSlQPmGvbbVLLZcHbYbeDaZMzfmmZBvgqE",
		@"zjpToVcSwOADnTY": @"UFaKMaraJPYIdwMWEdZIbeybKaNtbElimkIUIPvvCNgxPIWoWdDBLppYKXLTDAVfXRuazuMkZIIGpCVbJrGftzcYEigXOOXTvhzpdYIbESlPYWdqOhbzXTGOfiGiFQIrTMtlKTupsaeRzlhbKof",
		@"vjKPldpCWBzLYQkO": @"oEwVjrsaGhloJSuqjTqFtgFvRQlYGcEJVCIqxlIUcedTcjsPnsiwcgkxnXPiWNdIpEBXdkBsBGDrhAiQPhuJPKREmzJVDdViYsRImyybENjKdpNglTApTKXSKcmnfLJViHoG",
		@"doKqMyhLsiMR": @"JRtjCuyJezuqgPRYoeEKIPegOnmvFXOgYcllMXtggdXGHcOHsvAIwhEwZSMOwRkukHIijOVFIXFkHxiRIAsYRNGxZgMOnNmRQkSrvkgsgIsAHKPrHrryZfpTQJVjuWaj",
		@"rNPpjBVLKxYGsdt": @"YeDcKsWuMIOVHHBNJQuSwviDxDbRJJUeTkWOccffYKNMRCZZcNycXJLxMMqChGtlKLeLBiplvGSFmRhArtKlUqgCQGmUbVxANCWvwUEnB",
		@"cieqdwJGhryd": @"cRwTkUhlRfJFYYxNiKMAHFnegutYLnaAfEvmklUPznLagUKdFWwurcQTIhmJUDZNagqWQtpOhhWTKqJKRXxgmpdAJgHtwlcMiTviLskBJvNCvExEUMqZwe",
		@"fmGvZCnfCQppDdq": @"ySzlEiSyjIbeJZaxksfXKYaDoAvlfZOxMxBkSoijwMOWeKGwIcorwoNSlUFDrCoHNMnjulhFshMBuPWSXMCUVpOFWpugIHwZYkXEKcSHpdulsvVzEPmCeRlAaxTXttYrNG",
		@"kcGeiNaHjJTF": @"bcuRgEJbLEbYtwTCDXUMcNZbhZdLAzkcTlYMQofWwGgjHIaKpjMduazMcwgzDvzhThRiJmyvQUMZuEwDlXaemfFDQYiNBwQyTovSxGRurUSTELrnPqecc",
		@"CHstTBcpVQ": @"HjBOfNfTycBeYNEynckyySDRsjOHJfKamNREdqHaKzvEQDnLVkOExSCsVfNiwJJxWaFQeDgxnzTvNdmsyKYKEzIuBzlGTVnbfAJryMzTWYAgDHWrmFYFebLBTrURHkWVugjqQo",
		@"vxYrowljnFU": @"fptBGBpHtPPMvcejuiSZqNOGJCPbcuPYdPQHmZZjFIvtWYEJopwufxtxZXBFCuVoKPnZHXHSGktnvCOTiVXxlfnjPTwHvQKCtRrSVJRjAdcYkyxIX",
		@"bxByZrluNoGmuBBK": @"FQVybYASgMUrbqdrzHXKcJyHkfgABvPuwobpcnipdxyuEaDoMsByCHJOomBCYMIrSYjpYHFdBDIMroRTEdIFUHLJQiwmpRePdVyVyFpOihrrFukGCVheAiOBUY",
		@"XzJPVMhyBKNFEL": @"alQPQMxmIUslTaJFlejqMFQyGBaGddoIEVCgRuZgknCoZpYzXchtsLwOVUSKiPyNVogmxDgFSLfSAolbUroBhhQJMHuHdXUeUfFxKmzsABkiGnJrixtOrrkMNlkhCcJsoALKbTbjMuGcYnwBEImP",
		@"NFWzCTRFVWRpd": @"CEdLQPIdbXjRvlvMEhclAQcZdGIehKNSzioYjOSoUnjgctmdYPbcJoHwvgTNJqWJyGYdCsujZNWkrzSeYWJhOYEkzLnvusQjBNPLqPKLGpQCebzhApBu",
		@"wCNjvUQONLIpZJ": @"ygeHZhbWvJEunInHVBrDbORcuxZICOAqGKScgyKmiXpeKRZtwGAXQfwXQwAoaNTHsHjmhhrTCjPxPfZRzSszGQkIFOrhWbyBgfknTod",
		@"YoNDgAjgztiNkSl": @"rkBmPbVlUquKrHXTPhfVPvdokkQvRWMNIjWnAdDPOpSFCaLxZvgKgdbuOEiCCJzgWLkNkAMabQDDUDCOXGMfrktIwcGrJPwnaBbtnHkSYXgBhJLMHraCUvXLmaXAtGvKDikXyVLmD",
		@"BZLbnoWmuHmj": @"LqVymccCyLwltHJdKNIPwHmehRdgOGyJozhAWpKKygZluSiWPCWKbFenxfOGAZsBUrauDenBmcxVxACQNbletKLooLsPoedBOOTQqZ",
		@"hiaVCDUoSLLCsGnd": @"uZZAYSRpaxoRfDbLLjlqJYqOkwJkbLnSAWkEYrClvuYPrNnKACQcpNkoHaMeWZkCdXnEjrSXbfKYIoKBxtjTpnIFkAPuSpMhxnywxYmVmtfAdI",
	};
	return HXGAwvjvQbiVg;
}

- (nonnull UIImage *)pEVRwrrICUtYbhMf :(nonnull UIImage *)IRSnoovEhQutBu :(nonnull NSArray *)AomboTkRaFIAbJazk {
	NSData *pjgkpMUxpIFrJo = [@"cWxKiBbFCBEHSCkaKZBkrdXLKFHfCKSpiwUYEUOTzgBrZzofxmwwrJPcpywSTzxmUwUudPBWeSHJzyIrDhbKRFUPJzgbbKUfsaUVPuMekisEmzYFNjCfMwFEGmzTmhhsFBNgn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KdhWBluGzzT = [UIImage imageWithData:pjgkpMUxpIFrJo];
	KdhWBluGzzT = [UIImage imageNamed:@"ylAUCPBzYzyDjWrAAVmqJvJtrlMWNGiFlNaJnJdCdSwJrNqoMsKWKaFIDHxveyOqhLDkosjlmxoiCiuUqCVeQzNdFBKWAgwSIRmuLnYyWnkJHYHvbCuVxcObKJWokiEJcVUnHY"];
	return KdhWBluGzzT;
}

- (nonnull NSString *)esxRwOfPnuWJzEGbAA :(nonnull NSString *)NjIxLhmsNz :(nonnull NSData *)YQNMPLLiKvji :(nonnull NSString *)mCMIhWsSvN {
	NSString *BjKgoTQYqBkmGhOeNhU = @"WKLcYMXQNvyLGftsgXjPlbBFiBiTQwldabYRWroHforgyfsdKzJdyNHYSxoIYqpsipMdjqhbcWRfIMxJXcNiijwaLtStKHwWDtYLdzMhPGWCHTOElFwOgnLXAwLHdL";
	return BjKgoTQYqBkmGhOeNhU;
}

- (nonnull NSString *)eHPYxeZGjB :(nonnull UIImage *)TjInqasmZGlGncdnIu :(nonnull UIImage *)iFWvMyzXBitNHP {
	NSString *fwgYrKNqSY = @"tcyPbIcGVGljChownJLIFSQIUGupFuHxWXufPrErexHQAJofcyNkUzztOFyveljxEWeKcuKvpaHjeLuXoSAgjoRYjjNDCsExyhfioBfCuUVaJmEJXYngdgdEtEpES";
	return fwgYrKNqSY;
}

- (nonnull NSString *)tblofJpvooz :(nonnull NSString *)WaKFTcQykkwcgeoERDJ {
	NSString *afaKVzArxl = @"gbsBDwrrImhYQptFoQxYhwqjESVbNMWydSBZsqyUqjgARrkVFoMNlwJTaWINDszPODCdRUVaXbohYKnUjHggrJBhemUbbUGNNWnSSCIAoNLhjvjjlXtGvLocPJtlDVzfOfBpiKQyUNzUnhB";
	return afaKVzArxl;
}

+ (nonnull NSDictionary *)uAnyAYaRkXOhh :(nonnull NSArray *)aCOQqlRejPBDCic :(nonnull UIImage *)KNsLQaIriDme {
	NSDictionary *SelAqqxuFMZ = @{
		@"qNtWtPfdgcVPEjA": @"PGiARqtItDuGowKTBoVUzlzxUkPnTJiCbidxRzWnwPltSbhGRASoimpOdUwMGiWwmJCYhfHhclsmfvxWIheIgpLMAaPpKjwODoIzSNcQLuktHwnPDlSFsEciHOEyaNDC",
		@"HFRtUngFSTKr": @"TemEItRkbPJoRsNqHMFpVBQdNyePOQULfOnULSkEkhLLVgKSXVJyHBIJAaQAHlpVLgFHsUGfGWedObWYjdqOyeMZECeyowhhbDwscH",
		@"pfxFsRBaXhZ": @"eFoKMxhSPBtooGpuSovfOYJAtoNIgEGcAQznwuHTHWJtLxOcoPIcbkxnGfZMHITgFmxyEKCkmUDHwbzNFRfdGZSMBwyIRgQpVHcpFzZKVsnCF",
		@"XKeGPvjhSYvUCrJJ": @"PDZUkUZRQmiqwOroTFrfLLqSDcKdhQIxJTsFgolNrMmqpUugJxgWANjuVASQIOhKVKamGNecJBnXMczOpOwhruabGFAHrEdMVbhzRsjWn",
		@"zXluvCpsPGkXRcQRIwt": @"GVOaLlggJeXgCdjLomIuQRPHcDTYzEyIAcqNErvNrCqarmZTIRxvOkCTzMbUlfLRpJijBxQWibYmnpwFzHtNvXRBjqHnBKvyruQfZbKPz",
		@"ApSicytxUalqAIHapzI": @"LmzgHgwMbdByjjpwcJivxNtioTPnLMhHbthQVIhqBiMzvDdQBdXNPnPRMCSwqJRmzQCGjHdytEEEWGsBUFALOkAGVslFaMhCycBkhoIggdyRaKXIUoLgsLuYQFqakew",
		@"WTcXASZKHHFCjjaPx": @"qaHtYlIluzbYYulpGMpkeXCVejDPDcgKGbmGHyGZvSYOZsSyvnXpLgFrRIBMBeWatPnWIgQoJBIyaxbsTCRKAtnGGuvFPiEGUEFLfspiuXXdOmVtZOxRDnnvRzIuQej",
		@"keJkuOtOFqzyjGJKvY": @"EMSxwBvAkIDnvuZDocczxvVnYQrFKzFkQRWHeTVewRvItNuLGTbTiTOGtfIQEzBUMrfMDkavWkCMXfClDabLYatofSdtONviPWsvYXOtCtyZaumvXDCSXgXLoXmsBMHSpvdrMgvNLml",
		@"QdFOwKmoIVBq": @"utWXRrwuKqVNENCgExhOLSJDeiiyANNxELqdexTlejiIlDrbkjTAwBoryIedBKTrPunVooPsTINDcgJpJEKoeWweUckRerWtjyssfzFmqvUEfYzQmYMlypOwwNtZjWMMFeCdWCRACcOozzjVPHOgU",
		@"axrTKoAxalDQwI": @"dAwmsPJcXvGNihinQFYABFNJvHyAztZpXoePKKMikXVeMuWuXPVzsrRMaMxEqDHyYTAUGnKdtxsvAAdvsMcdrrKdYDkhUoeCFlbHcAeH",
		@"yOtnHiBvEvhRIVJ": @"WONBegLClBcqsVJBOITCGtyczuFMPlNUpLOnvCacCoaYWFgGKKaBGdPJTunpnjrQdIeUAWIWXqCeybZluluHQPOgvKdoGKPwisqD",
		@"ZmdBrpsgtB": @"QHkpSjfypYkKZFCONNaJPigzxOxqBGcDorEPVuZiTQOhWbGiRcjwOlftoQqaiINTEwNBBdkJiZLqcAyumONtdAfUGOaEfjZLwrtIfpipUbvlMEYSDxgVyWEhNSvnQbiWYfaBMIKhGsL",
		@"emvSCSrmJgAIIEA": @"WbiKmXEKtFUepoTUEfGbvYcTMQEEqPKYdLVfdZimkCfeMewYtXWxehNmsvQIEzweZmZpCjrmvgaeMUuZXeVEvGwKWpoKIvjHoTMgpvUIJCIrA",
	};
	return SelAqqxuFMZ;
}

+ (nonnull UIImage *)syDyrUlMTZbHGuDvVZ :(nonnull NSString *)pChXRXZQCTnVifm :(nonnull UIImage *)rFfSOLcYGxoaxmtIK {
	NSData *dhwgfUwzfzzx = [@"SEcUORvvCMCtluAXxBfKSfUWrQQTMZvAGOovRRkAwLeppmEZIGJLDreWaDwLBGXBuFIDkCGcXlTtOiDJKhITjtdHsUStKjRnhSdSIjBLJiuhWCEizUHmUkgHLuEbnaROBtM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TpcFdhekSgxj = [UIImage imageWithData:dhwgfUwzfzzx];
	TpcFdhekSgxj = [UIImage imageNamed:@"ypncRHsEMAzpZxkJuQqSXDwCzROhLeLkIUnofHjDgVppjNpWMTdnadTTGBXACaNtiRHWItYklTptSGmQpWjkWMBipcJQOFYIPDfwowQicukP"];
	return TpcFdhekSgxj;
}

+ (nonnull UIImage *)hVkgRxGBfcFBXuydz :(nonnull NSString *)VQXQqBlljYWmNtqA :(nonnull NSArray *)FRFcshBmTmqimtmpvKH {
	NSData *tAbrWfBEJHO = [@"lcgaOeOiOyYNwYFVidnePPehEuCMiSbOtEvslrchOjBMGvHUAZSRlZWxENuGbTBdFJgzXekjWZwgStKHpmyrjAijmDwXFoRmJoylvULFyonM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *UkLQihGOWzlHtwWz = [UIImage imageWithData:tAbrWfBEJHO];
	UkLQihGOWzlHtwWz = [UIImage imageNamed:@"zvOgefOJPISxlgDfkgCLRdAzDTbVmICojOHNhHRajBvKNsaitcvwqTGBmBFZYKlqWoVarNkUPsTFWHVCtBKHxFsywRnzMrBwDzLC"];
	return UkLQihGOWzlHtwWz;
}

+ (nonnull NSDictionary *)OwEmqfZlLbZEflPLuy :(nonnull UIImage *)ijtJODfrkddPM {
	NSDictionary *drnGKgQhlaIdWtKJ = @{
		@"XBvQVfIfnHTLiYolpA": @"LDMIfPLVKcJqlTwWTOgGsIaoeFXzmbwysRgYWZorBFfsMhPJrhvDSxvYLaErggmuLCcxSJZbJiNAGDiDjGMaTjqmNRqNShUZgasQIMwsqokbfAkgknha",
		@"ZzOozersrO": @"JHBEdEdnUjRkaVrDOkSckRORekVUbHtNqsAofKuVOkOSzviHeyzUUmXNRPsmNlxczwuoFaczOosDwngMFpdtJMPYPomBRbiPwdTxjLzAgoJsCJw",
		@"UecyAznuOwEtSigy": @"KEUKyrfyrnsBsewBfvknWtSdgBLvIfhEDxsAwgwYgeJdRVRSSZwoFpogMeIexIYIRYnIUJqZMxouMCvjhWKKMylwnSQqzkTWomZlqOVsbYHyLGvoHonzrGqkcUwAKMQd",
		@"ToeOpjHkNZ": @"yhTmyEFBpZzRWIUMLCwzvgfqrSksDUfYFCSgyXusxqQJJBVWyXWQmumhoBBXRmyIArCGZIixfsvyVUwutUbcspIKmeqRqutzysnWqZHnfDnGhtPWpkVFIQZGtgwoiOOVIsVSaG",
		@"RimDSbJMyNHQPE": @"wvZLmnUDIKaWScbVbzfHCDLoTluDwOXUrAvtSghgmtbwCRHUyujfDaZfumDwMENwUqQPgRWyrWWjhObEThbTLuPcjyMcCszIQijJeIzbfIciBLAapFFfpLJZmSYyXRhgzzxYTdcbstr",
		@"WnUBkFTYaLWxra": @"NMdsXDGxLXnaCDPwJLFMUuwPXYWxpvGiXkUXlsBJRLEGdnqpAhzZXExYdbJpwIMAtFMhWnuirWHgpZAnrrbFjCCEovKRrQEdZwBUeMAH",
		@"qnzgObOHGL": @"uHvxHOUafqtusKWpCKCkaVQPInATKmEipbyNCdbdpyYNGjfxEQCGayASHKImlrYADXNaJkvojWVaGtXNFibMSspWhhuAVgRZVhbIkZWzfoGKzxqgMOazPSrNaxcncjokuTEczMyOGuupMvStceWt",
		@"bqSPimlhxceoG": @"LwYlpeVsedJgrqVwfbSaqLaisazTTLJbIMvdcebKmNpxmZxpkuXevOoayIIPfPnWmkNwwynlAYOzMKSTLQnQHLkNuWrDEfWUBUFWccTzDEhAaSmPxBilBrQsBWkfOtIpjtVvUhRF",
		@"bLGNHvrxseXRtqMX": @"IGGYPKRLkICqRaQjoOmmwfxxKioCgbiPFnZYcypdFBthjqYRjiSlLtwLyiVZIYbnCTlxYRjUPCLgstlfViZXiduYcUTGukkrkMzbLubPKauDSgJcbFLUsDlUkSVSsIE",
		@"TspaThyitlaChUXdzyX": @"eeRVcZhANbDozLtocgukcpgawVIUsGxzbYUSBzMKOkkCxCFGkkPkxrwJGNpyQUUwglqHYhQpYmDIrZJABysSwWpWongmoaxChQsTPMPyqIeFWnCWioGL",
		@"PCioUFEAmTehmyNHIiX": @"sLonKxtmESBsiFgzCnbSAakELCVEcmGecaCWxqTjKwjaUYIVuhwDPDLEigLoMvkzGJNIDvMVjOObmjwsbXajSOfwFGPJrcyNmWHEvvPzOgShvMMEteTZRLpiBwwpZUCaCs",
		@"xWSGWMpxHtPYJVdEoPQ": @"KcuwDjxqlORcWKDfEKmSwGoyMdbWGoAtLHxVZjPuQqgpKMhwFPPaKarzLqzzfLFLYWCZiypJvxurrSAITtiNBNoZtNEgdrvNSaEJGsLwPxGKPzXNigaGCKlilSRTryKfxnl",
		@"IocOEynZrLKJ": @"mLGBZGJfPXmtiTRaRVnmJbQhAMlNfMuxgUmaoDHIWsfODxuSDCqMzmWgDJvPLFFUHWBVmjYVWVyRUdepzgEmYOErBowTVbcJTVRpNyynRGwwgkYCEcllPAOkYNwwpbGbgDLqGVkgp",
	};
	return drnGKgQhlaIdWtKJ;
}

+ (nonnull NSDictionary *)HyzehERPEcCmtpYb :(nonnull NSData *)YdIuFOarTbMCjahlde :(nonnull UIImage *)QgKNMaqqrvIZHwMYo {
	NSDictionary *PmflyMoZKtxDfVrUgp = @{
		@"FGaTZncEssE": @"OAiiaJAgByBioWbkrlKmNYqyXIAWPWdnRIwdQukdsvapxQzesiupxOYbFRoTEuuBDnVOChMTXMZQPJYIrKWiqDnPidjGxRsAlpTtbQXQakOSUWoqvjBdplTIQygAzwkDsXELemIdRX",
		@"QrvcFStyxmyLH": @"lJVIUWYTyjgzpIomrUpiARJFgmtJtpiUEjhULYRNIHszeCxeNFLlUqOleOkzPdkZzlGpmwwlsKWrrqTwAzNBHesfXUsgpidjupXrOVvdRFxjmuVVMlri",
		@"nCPYGJExkeGBB": @"NbELmfiUxLGVhnNbLXsQDBRQjUikDDSssJQsvhfuPhTnEjrrrXtJZPXwTpbRfArNioadjjMwLmKKntxdpRGpFvgWhwggYeVycuVUAAfzREYxMoHoNhQVHhQGyYWIXclw",
		@"qAMhhdBaQrUhBFIYSn": @"ketXIMnWAodJfvxVzUcyQHfDUnFXdcUmzGxUZjSzzgXjBAcjnTFIDZsbQjvjfGGTSgKgLVfUkPjBomoHjHvHfUWOuRAGUKmUvrliEJZSDnUUk",
		@"lqqjNNnJuygsWID": @"YFDJfWZkRMJflVEBcEQvRuXnFbKiREJvVnmNqwzemZaSspIhmpoDybvMPSzqaxFeRAksOemhfmiIgGbZXZEmJyjEZpvDatVvlxkvlqEOqFLpfS",
		@"oiPJMzDXyeiVxgaW": @"YGdAzmGoxyJbUDhaVvdcxfdbnUZFNaFvRIHpHWAKHMPrGnHGbTZovbfRjJCsVAiGXAKqPfkFAhtjrUoMNHlYBbEFlpohYyfjLknbfqjmgtytgqCAxzBGbQbtwchxtHTHUotDOVRI",
		@"mvpvSNxbFT": @"KkxdzPtvwZAwdhZyWgkvvIAztdKIaxEqwteZKEYarcJAyTGEhKVnzGGCCgcRRyJZrKzGmgNEKlQzLGReAkCSuijtXqFDLOfyegXNbkDDZLgotfenejjpXddWqlsQVwk",
		@"XRPJzgjEsIKxscTcY": @"rJnVkndaHKNXustjoyfOVRSYOZDyepLkHGfAucPbQYpdlPDOJiNpHRceQNRclUxDHdIkNMcDRDZXdRcMewgmNPnalrXXgUImDwhDkzeQZvhcznHltcZDZKpCnBauvCaLiYrBw",
		@"NLgBatdmWT": @"ikEXJEZuFOcbnjaXoUnrkOxSFFZryyTkjSburNRJJVveXGnnFaelksuOvbcXtcbukllawwzlPOSqlgHCIwtbtPXHKhNTbgNxRmWCPFxvRnNJXO",
		@"NVZFdEurOtatQZqCbGd": @"pTKyokDdHvVLKVtsCfTJtyCrBhwMpVuTftHiEKAuAJJtdQgqBZMTXPKkYkyMFwNVURIUzhSJFlYeKBwFKyLxBYOTkOWNPpGhlyGEX",
	};
	return PmflyMoZKtxDfVrUgp;
}

+ (nonnull NSArray *)VmsKzQFkUXRAjNsw :(nonnull NSDictionary *)KRxajlOPSen {
	NSArray *uygzFJnleyZa = @[
		@"berHMStzQzvsqwGwaJuZBeYkZbErmzxFrsArjUZGDAEGHBaoAmLYZUmEiwhIbhiPQDmOOjeTSfpkjBoDxzQWJHqWDMgHWHbhSVFDIaaJg",
		@"gklMAxmhASSXypJQLCdWMypsFiwULgPGaKTZzFzPHQTCxzGfatJZtRrBnqqAglVrDUjcOVUujZOBfORnJdoyPsxutLAVGvgdbLkRcJBkvnyGNMSpzTnxJaRrrCohTyLgPF",
		@"CQmVBWJhWWcovuWbSrRYDchUlbrKqMlKTBnMZWGVTZYapAPGBPHThNwplOQsULbjKutZahlVDIBmKwylEFtbrroHDmbvsjyxCRhDhQpuamxVXhBQoUqkgDqHcqfDhjLYrHj",
		@"RCxqQASPgCIlzsyXSsJUGPUFYipyIkMQznwSzhYSZRvrrtOqKPmoUjxRkNaidJgYAQIXDppKSzlYjtnxauVHgnZgCUCPeIArxcPCHvQYJaGOjLmgsRKwEbkILAtx",
		@"zgllZPOSOKRlKnzZhyeyJVxGUOVtLPwdxynawkkabejHQYHdZhRZLOXMgRsVIMjjGuofgJVpDKsWsiFrLEFAtTJPbRwgpEAwOQmuNogdlasoAhxKYxINsT",
		@"PaUNNwQOfOlPLVWqtzXNeOXETYbVgQOvMYToUQsIOtvRZKiPaYIiymXKlmsSomZMUnDkLRXxWaCPwVPnnqqpJHsBxyMbKzMINZCFfEcjIIMyPGEYAIiBfOPXHAEXIYIhysfSsjOuJrdxicjQ",
		@"PQiaLgBMOaRauIVgYbMseiHdIJAVRrQhDulatQMHcCwNwKhBjopUDBtaQYtlBcqrZgHbNqhPzjMygKTTAkdRVwoQkeJJqxqmJPnOktTeYUoxaNQoTFiIJtkueV",
		@"VErhAorFrThonkfeYtiQxBpjaUacefNNXMbFTMxxtsRcMXzkxdFitTvYtQowwLXLtkeVKTQCjcajYZemJnjaKSCQnAjJHzyQruPHQRiVPFXsswaeSxDwmzZVZnOPjy",
		@"pIMPovVogDGFwndeipjLmnALHohSIveIQjKpWWPoJBElCuhkfPHjAcYOmvhfjXsAEdXSSRUQAQBFCyTwGzgzwZgeGbJFyRAyJYMKfvIlpryQalKZYyAsatJnZr",
		@"fiVOoHliiaAckwiMInYlwqWFAZgfocKOBmUPOlfMpOFElDHbgiWErjqbeEtXtehobGgkZvrIqsgIfSvNgstsdRlwmGqoMqhgAngZuKjqHDeZCzKkGXYMhoSAHsAHWuzOzxGrpD",
		@"TBMfLQUNHfgYyxKNafanyUbPoQRFqxSQlnIQZLiFKTBvcDwVkUBwLjrlDvyWRbjWYQPFREuLeEhbdjMJpHRJAdERwsDclTTrlQKptXfVqSyPHwbcaukdVZQwItyzOpVRGlcAQmcKZswRv",
		@"riufCPvDljNLyCiTNBXyPNqrnGIxJZuAaMnVcUgnRjaQANZjQESkOvpwFkQUexyJmiDqsqxAvcKkCfTBsfaNQXUvIkyBDBIikMtaxlVkeMIKczQhXiiIswcxumYvGcpbdzWwJlsWYvuKSlaovr",
		@"LEHjYQcEqRJyslviqwcIHNxrrCCYTKAQHDcaPdeTBajetlNTUrZSqLuAqfiKXfnxMmkokfhlFiMGhdzOPZQJcvkvBQoCvQWTLSRfciwfRCQJCFJUJxjmyAQl",
		@"dHWOCOOvxCXsmrEPIpDpqqXWxoDnPliPIiPXgaYzPVXmiCmNqOpGTCaAhqOCpaNfzsyaSeqODeWOULfrwUMLEnQNFbXopQPlJwrUVmrOmOPRuVtiWuxpZPKYTLdKmBWeRKBXrWeEgHxyKHiVEl",
	];
	return uygzFJnleyZa;
}

- (nonnull NSDictionary *)ixSOSFrNFrjNrMJUy :(nonnull NSData *)oYsqqyubOSOcUO :(nonnull NSDictionary *)vAupNMdDSCHR :(nonnull NSDictionary *)IbdqjuBKGOCoohVUMfi {
	NSDictionary *KyPFwRoFfcedZkpTEe = @{
		@"JFuuPrIKsKyeyRe": @"obTjAnTuFXSssXZLfCtNkQufArfjjqUmeZEHSrYuAxFyjqQFNPIHeQReIujGPaHFvZSVXVWkyxFPOsfrptuuHhLQrqzpgRLVYcShqIlTMqxhtzVjYdvSgS",
		@"FKbMKleLgaNloQ": @"oxYNlDTmSSmVDFBrmZGZgIUYOneFJPjylBOSkKeIYfSYyWdkLJDMILspMRPQVfTsmqqzYpCmIfkCBEklJtAMOxDBdjECfRQuUzalVMLnVbeSKeuZAKDsshlxOzmJpzMWjZYCkFVdArT",
		@"wVGWpRdAPXclCTWNCf": @"znusxkLlgSvvvbZsWeWakgdgzssKWzDjmanWEVqIuEKfhSPWCzjkGTIACiNIvsGTLcraKTAZfSirFyCHCGoCSeuHBcOSGIRLwcHXVynXlfLKJeNPn",
		@"lMomdfiaQfyXweTfui": @"YjXeNCNANfMGMDDKwcUifAHQOzoUjzdcSzZbOEjBwsvyQeVqnnzxfhRtCzbHBebXCXZTeqSzebXXetzVCMmmQKHKkMqoUnBwhdmHWfjgfxrcwOkGUuVBs",
		@"vSEQKrjIqepiuu": @"VnXnBgIIarRroyiDbgpyECDzkNzNqfElcngAcNeflTHhwiVMohEbycAzVEXjhxKksLvATeQIJwNmKvnYUARNrswyZZCQCWrUGuGVJmePpMbwptUUIptQcQsfRdRgd",
		@"jUKNbDqlsnhnHLGhN": @"JSSQvlhUTyLhDrDfouFTRdKRPNvgvBqyJXakvAvXTsObawWFQSULxXVJkdPmLeQXBvWJYyVGiaKPkGYcOpKaqYWIiHSRvdODDOUyVvdurEiON",
		@"owhUzJWaSI": @"GdbxsWRuImdTrthWEtpUFwdpuFYzYPKcydFFEqoDbNMtjhDRiLqnVvxsybHqXFFHQgnyHqfsGNkybhbHbtYsbeJjnAlICsICTVQEIAcOrMmovypSMLXfVqxoorkhypaVsmugSmqhZXoSUZhhF",
		@"kxXzqZaFdnsRG": @"wdBkUFubpchaeYdlPQuqQSsomeVSSNovKTHmkzeDDJWmdvUpUCKhJPtVdoUBBjuVkZZDWcTzFkMiTSlwBJuXVXmjUqNzQBYkyflwExjRGIBBXkrhUUSBiPlzTnlg",
		@"AWKLKxIjmkKKK": @"mLgYMxIBaGrVTdETiXaqnZaFQFLRxbxxyYFbjmOlNkhoQxHpfUObuCwNbcTbzukoVUUCemZkZBEBbjmvRWBPuQxscxvdXZzBMXrxWfWxDsYbxrgrUTYPnm",
		@"kXsOkXoeaeNydLmsT": @"zlaRXBOwqLqVPhjxMqXePPPhhamaKljPubOcKMEIYwaqkVXdRBDLAlSnnYPYpfqEIBWJuPpNAklmQBSInHHCPZfLhWqBzSloRQXdYaWXJcPenxAZBnQyWIJzuBTgoYcvKgglEUcREarn",
	};
	return KyPFwRoFfcedZkpTEe;
}

+ (nonnull UIImage *)MEtxFDNZVNMqVqf :(nonnull NSData *)LcmAnMvOjjuiXfWzh :(nonnull NSString *)uvaeLdAkipz {
	NSData *yVYxjwVSLUQYEqeerR = [@"jdlmXKACpZwoyQGsNfhUOHiGFUNHtkSuBwtVIfKqZJKLYZLqOYEahVNbYRdnvEZwCOEMHoPyrJSOYoPiibrJbfaFhjCWwFKRAEhwGiHNZHbiGln" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *tfJXOxhujSGwnKj = [UIImage imageWithData:yVYxjwVSLUQYEqeerR];
	tfJXOxhujSGwnKj = [UIImage imageNamed:@"PymoBeRasmvXWCGUnysPKPJxQztVGakQbgfARBRkHKzcVHGPmSpLbmbhAWEHDdeNsoRLiACQeoXWxbokkFApkDgZKbLCkgSnHTpRFzuSMcZoEpwDLtFfOvgiaNLEoKqfZOutWM"];
	return tfJXOxhujSGwnKj;
}

+ (nonnull UIImage *)gFwODHPcMgUvqZ :(nonnull NSArray *)lknUSpqgsRYq :(nonnull NSData *)TrgGfzwkMgTKzJsmzP :(nonnull NSString *)ZbbTtdPgCvQDHCOXEeS {
	NSData *QgfRxvbDOu = [@"cvbKMNFJNqyhvwMeWTgTjTqjIbgVCHULcbMtWhKBjbXzdhEyjfxTcvxuQMTGcwYkXbkcMzqQHXpEJPjCTOuCkUjiutCFmYxVtEvVRetcMuWvvETZHHOlEAoPoVRYIHpmKPxamwIzIt" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FbUgfhbtdBcKGeFern = [UIImage imageWithData:QgfRxvbDOu];
	FbUgfhbtdBcKGeFern = [UIImage imageNamed:@"JNLFQCuAeCsviEjpNsMwbBZzwsmhcKtvytKUjfZyYpNxFUYycPZLsgEgTMclfjrrkvlKoSqOHDgWAphOaVTPGOeXbJXZZMVVzsFjFqvFkHwybAzRcStAIqlTZ"];
	return FbUgfhbtdBcKGeFern;
}

+ (nonnull NSData *)QREHnUMVFiuFskt :(nonnull UIImage *)qnkSWOoxqhIyAMw :(nonnull UIImage *)sUbaHXOHTCLRoEldwk :(nonnull UIImage *)tklnsJthoMPbu {
	NSData *tIZsohPhEvTw = [@"VFsUcbRXjbnrUYpQWnsyxOvpqZaTVsQTedJvNAaIAMOUAPmMpzldKCQPWpADxCfNPzNejJUNCheHZcHVPaMrhbhkenSIYqRNPHnUjjB" dataUsingEncoding:NSUTF8StringEncoding];
	return tIZsohPhEvTw;
}

+ (nonnull UIImage *)ZWhHmKGnDYqR :(nonnull NSDictionary *)ykxlHegQAFSGKPrjme :(nonnull NSDictionary *)oWNXsIVKMZBuBmobe {
	NSData *YWhQkfsfXsfYKYe = [@"wDdcPEaYWhQArFczkJvQqkCdJXndgjiNFLHBnDVjJScdrDQZFWPzpRchEKqqGiAEGAHofTlRQHiVlgRxtehbytcixLukSVcprMOFQNjdKLFbfqrgHyhPuhkVfUPvJd" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *gCAgvLWRZyWeenWSG = [UIImage imageWithData:YWhQkfsfXsfYKYe];
	gCAgvLWRZyWeenWSG = [UIImage imageNamed:@"QUbQZnLNRXAdZDNCEqhCndvJJMVZYdhEXXxczSfFNTbjQgvkSuETiajSfvWBppDZuekrvnTGpmlgqHTiMqDuSDHCAmqEmdBdIlhLqBsxbMisuZyDosqUqKIZqCZYnVHykCmdlFuevyuRmhL"];
	return gCAgvLWRZyWeenWSG;
}

- (nonnull NSData *)OMLCQoGqkagPFP :(nonnull UIImage *)bsSXVeIkOddcVL :(nonnull UIImage *)MYTpfzLaHZPX {
	NSData *YFcprEvsSkal = [@"OHRmwBAtprDixLaRNfImNLJBXllLrPMJuhdmqfQgiYUDWiVkAxXPiLZoQNiljzVBvrWqkTNCPqiwotLEhgEbxiefxHYylFgZqEFrhTYtdzaPxrgUNJyX" dataUsingEncoding:NSUTF8StringEncoding];
	return YFcprEvsSkal;
}

+ (nonnull NSArray *)ajbDwFDmfSEhEKwfqL :(nonnull NSDictionary *)EtSicSLTix :(nonnull NSData *)rgQXxcSxYjtl {
	NSArray *CuPQPsopUUrDZsO = @[
		@"seQNcZqJQluuNhltxOneSWkeSengdsxnXHFVpQEJYnRwnttgemCtuuAVTTNdkWCiMxxldShoeaoQsHIGXumdoBWymnzlmIzFmyKfrqEUxh",
		@"eRhIKKvLvBmUeWiIfPgAOaYqUrQPfASDONRYOXYzkvSrenlYbrnybNUqHFtVlHTBgUHaMpsvPkLzhnbMmcZIMeFHTSijEBdLsqSsmkNzwDcPMEUQTSSggtWiwhnXqfidxaR",
		@"eEBSVwrFCkuMalWGyKtVTTEoNrILILlGPGIpCZXmCvkioZQKVScXBObloDvNcZvctClWWcwOKfprvXHYGxVtuNVrcuJHgvabgVwDIW",
		@"aIBoNlbZRBzktuoBrHvyeMdPRmqpJOmcsCzgmWuKYGSsrNaiUrHHRknZsKDtPxZChRmqBCAyNhtlZtzHuWYFlXDhMLunCjEPUnEZ",
		@"yMUJmCqiQEXFptIVBrRAugIysNYAoXhCwcrdlQECSridPjTbKLfUjlJuFVoYZSuUISTeGRTPsmUWpavVxFVGKrbNiuFxReQwhASlDkfJXgKsFPSqfzqAVhTVPtQ",
		@"nJHLlexTQMSCotsImAwUETqYSGkevOXQeovCjwisLiUzXCizCoUoBmylktwLokZSsawpigjoNrwrPOtixBopFHPTOLAPWwboiqtanRzFgFeA",
		@"qAPaUdOFTIHDnetkgQFycgcGkRExwHRVHmsJvxcDAgMKrWnFBrQuSWCKMLgmQdzdiDLWkJBKFRRTLbQPSlhHVgTVWJSwbwBZykMVgNvZWYxgfKuKScBhUNNYVRmvkaGDcdBzfSjm",
		@"wlKsChSQQJjCgpYWJRNCxVUlKCbtFbHawbfHQRpkJInKoyiUrnrqZgJSLWBVTgstUgXEuxtwzLeoaHNwNxIzIuFVKMkYAWdjccZGfEksgaBegKDltVhWHWSumWRXcbxGpUIGPTxAGqpuNvRJGIjq",
		@"WTMpiOODEMWVGFZDeJwdVEvfHMQcIeXTiaFqtmbAyhWsXxhTztAxWVgGlXZiOeYYBxhzhSuritBHmenAKXfkGbVvaVTRNXlbBQQiOJwwqvBYzUJjSedaBLPZMJbP",
		@"XUSKRNdcniVdyLYMWOQuazvLbHcXeEJSWNjrkBbmCYAtpEFGbTtynIHVNZhwTCquTcTXhGIfOIlDfXbsqYqoBxdTdrkghsGYUJEizQHq",
		@"ZAfWUnOXlInsripSwNEIOfeOXMKWehOMTZRYKedwugKLQLxWPRGaDcbHPHdxpokKCKitxfMPbalkuDsuOdRJKHBdvIKzOGqFPYgEzgpaxCymLHtPFaATcaMvtmoR",
		@"EcXixCyigmdHyQXFdyKVYZFnWEixPDSVFiGuMGSRZSdvGQHZCTwNngGIlcbvUhfrOWaZPqHNnynSoWwSLnpDgzYlqVmXPRROuTDUwZDRhLiMsLKaDnN",
		@"ObGafRZxxceiJBcgxYXeGpRBtOjfbMTaKrKxzcnIGIWqcqtUmECfXijkcZKlRLVipEJewCSkTsiHadZnOmlKIFWMxZRSTSuutaIceeBsbReSwuzktxagWCHbHjaxdOsHETfkUNMeoUrpb",
		@"wtCMCqGxVnrBwfeQyHakfDtxyvkfUKtERshCkfCAKYrbMfFQtFZzHNinjQhnuvwnCvnqyDpuNhdnFfBBzkTEawdqkyOjItduwESxNIkYzzEiDNfKSrwosgPzPJNdwl",
		@"zHXMtIeHDBZhkfPLdUOeQbBlDBGzgXzfueUfhmXanAXIEcHsGWsvojEtIlgzzlIGLsgPqFUXLSwVMMGLxSTIfndCgBquUCrgXPaZLxNGsYxmnqZXwpB",
		@"wzjdrWjqZLGvHMBYzGLAdwaIobYVmzVxYlhnIklAozyZCdPewcuBQddhUqpSXmkHHztvclzMOoQANErZTNqJUtlJnXNNdsWMaaqVDcPnaKOWkBAgTfBYukaEcFHIatsLfaEn",
		@"jFVEMagXaKUaIuVymqadHQBwEYJoONgItTQLNrBBOLADxuxyOPDkGzKItHyyIpweGngYfoVdFHSURKrXiQBUGUsZymZHGiZWKlOqPGekVsRoWmZoBHdscIaKrpvhBhSrr",
		@"XfQTTDWGfxHNvupJTdIwlgWJwHyyOXyTLyhyNFmhIVxRNCiuaDLdncsFIbbYIjqTOSrbGGdxdkkCquSakuxrQfMjaUoXlyoennDLpOBZtXbqbaXS",
		@"dNPXAAPJBktTjTmkWzcDkmrnpSJLIUpiMLsdQXYwZvTTRmigarXaxUcJwkJOplUEozjeoixzrFbMuYiOiLOGYlmKvhnYfeFXNRCWnedKBrqoLXXKamzAjqhKsDzwvgMIvtHKqtghcxwZe",
	];
	return CuPQPsopUUrDZsO;
}

+ (nonnull NSDictionary *)YCuAwOPokVH :(nonnull NSData *)GZiXmcBcdqmEOKH :(nonnull UIImage *)qNJlPqxaqa {
	NSDictionary *DoizBOKKNVJtmOE = @{
		@"afuyJUoWTyQC": @"JzdochdzoAfhWLkEBqcjLdGdaFIKLprXEQBrjDIYXCKYDcTmNXgIgazLQAZfVqYoFwgahJhspwYqXkuxsxpiZcWTkomORtUkpbJfrWdGrEMjhgJiqPxPcIiJAnSKGveTsthpGSXjqIfgz",
		@"sXhaCNQMIPjxZLN": @"GQQtNzsKWkVTlseVIDMbuyZjiZJgyuamwXXZjZmjxCURiWkzVSefaSDJsAlzpbGuiGESHyTAmsGLSPJrAoOUcKRCEgQjLWcgktvQGwyuGlYUujKTsaWTgMxoIOO",
		@"oIBSByJlsntVGeqgYtu": @"dBTHRiSaoqqHBBtgPkxjjxCQUSKdbhrOVdCVPzoNXvfzrQPtFIcBWCEKOanIQAMDbcjarjyQimrfnIfSdlZvBEvuEcoTHsbZHDuD",
		@"fnkHPFaQdKVWYeCvmjH": @"hIiJSAZaHeJoPtpfeQDcbapBgDfUzdKUgpKKjnYpZttiCwEooqRsnIiGXPsfilrIvCLFmFtUzXMPvknTHrofsbrvPlDHxupyGyoEhjxeuiIXqqjrStHaiES",
		@"rWcWVhIrmXcLygAG": @"buWPxUjopChWWtyCypYZlBYHiUQutCMytbqjDsCImyLMCIBCNisRWXegUMqeXcQtRfOkSFJdYJVPWzuHMznypSUHjPoQAWnjgoDqpJrZHoVAtMYXGZBnhEkijluhrQhwsZVjUIi",
		@"gtGdquttBdRxdq": @"UTFXNzknxidTgrftVYqDoykhAYuLnajcqIOpsEDrsbdXgHLgmHpZgKGWtztvnYBYkdLUCtamOCNQsGYSSwUHdxYYSRPWDHBxNYfZdkddh",
		@"sWcjlzAvGru": @"ZTInCFGMqDdIlooPfJojxjKroCQMsGdwApmxNboqVSzGNBhnIiOhiSwZZaYYrjjMgcoWnLpHPQPtAtVrIiArEyMXeUXPApkiTMrHMZwxOHBDyKsZBNrSzQnUIprPbFqPPs",
		@"XmmtFXLgodJRdu": @"iYZlPGgDNOtmWuXQxDNuEbqWxAuddKxzzqRJylmchNFmyOqCvJxfRebyoKzrHBMxmCbkxqeiktinTMSEHbjrqMSBrikKIJMwKKTRmpurokHIjkexSnHkVrNycByqpgZWirL",
		@"jFryNVayDPeyVReJU": @"PQwTjozwJobKjLvRbiosAtYpxadtqlSRyiAJUoxrTOPhudAgLznyBZqjNDYhjJhyODvwUjHGTDABAUrnwXForozHLXAToAztBUqybGgacRSzwCIoFPessGXMrrWWYMFvJDjdJYBiOjTXXlu",
		@"SQaztgRUaTxPF": @"hNIUATNjFvHkkaJDGoZzYfebdBTXmcLHqmPdHJqrfABWqMDjXFznFUWcXdSBVIxvnDyAnGzHHbjmGDYkpClIzMwQArnfGewsXgWALciXztiGvubCXfBItCEXQRMrJWibZtcGrQLAKwueXMAjsFCfZ",
		@"vRjxophHVUkPs": @"rTXUkbhDIRaiSteZvfQxjyTTwWuxbxuSOndENAkWYFJiqFErolvzWeDtLrlwoyIqZVyPrXjMWdvaXqbUWjlkMRSSOVwyzwknWCgUBfPd",
	};
	return DoizBOKKNVJtmOE;
}

- (nonnull UIImage *)nqdZbsYaOm :(nonnull NSData *)SSGSUrfioEOVbvS {
	NSData *YbTCJixnqA = [@"sdGxDgxYxjRiXIGOmkkWOCAKsTUbWsqbDcODhFdRMnVLVefGiMIVMfzZqvaKAvFrWBdKNBvExazRFjkfmCjVcMArVXkPIQuVSgkoazoQkNtBdSOGjVKem" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ccujZHwmJAFinXrvpQ = [UIImage imageWithData:YbTCJixnqA];
	ccujZHwmJAFinXrvpQ = [UIImage imageNamed:@"oJPdMAKxgXjFrsMcobNOwmVNeFFaOYANvvLEfYiESUnTbnPKkTdAgyRAzeMTzZKzeKXxEDFKcxwpLPqKgtXHmELNEbKMWNTSCpwyrcMrCLKPTZJAzFFymKAASy"];
	return ccujZHwmJAFinXrvpQ;
}

- (nonnull NSData *)RNNSqTpxprXb :(nonnull NSData *)viOfaBqDTbiemI :(nonnull UIImage *)FwvkxlOctxqpinaxLpg {
	NSData *nbbuyKOCSDXdFERdLU = [@"vXXrUWIGJYQEdnTreNlQOLxINplgtHOAYdIcWdSjcBQBufCjNCyaBheEUofaJJplxQOOrjajbgfZCVZJHBuuSwYQPvtZhUWwszbIiHOMbdFtqEzleExrBZgkvpSd" dataUsingEncoding:NSUTF8StringEncoding];
	return nbbuyKOCSDXdFERdLU;
}

+ (UIImage *)sd_imageWithData:(NSData *)data {
    UIImage *image;
    NSString *imageContentType = [NSData sd_contentTypeForImageData:data];
    if ([imageContentType isEqualToString:@"image/gif"]) {
        image = [UIImage sd_animatedGIFWithData:data];
    }
#ifdef SD_WEBP
    else if ([imageContentType isEqualToString:@"image/webp"])
    {
        image = [UIImage sd_imageWithWebPData:data];
    }
#endif
    else {
        image = [[UIImage alloc] initWithData:data];
        UIImageOrientation orientation = [self sd_imageOrientationFromImageData:data];
        if (orientation != UIImageOrientationUp) {
            image = [UIImage imageWithCGImage:image.CGImage
                                        scale:image.scale
                                  orientation:orientation];
        }
    }
    return image;
}
+(UIImageOrientation)sd_imageOrientationFromImageData:(NSData *)imageData {
    UIImageOrientation result = UIImageOrientationUp;
    CGImageSourceRef imageSource = CGImageSourceCreateWithData((__bridge CFDataRef)imageData, NULL);
    if (imageSource) {
        CFDictionaryRef properties = CGImageSourceCopyPropertiesAtIndex(imageSource, 0, NULL);
        if (properties) {
            CFTypeRef val;
            int exifOrientation;
            val = CFDictionaryGetValue(properties, kCGImagePropertyOrientation);
            if (val) {
                CFNumberGetValue(val, kCFNumberIntType, &exifOrientation);
                result = [self sd_exifOrientationToiOSOrientation:exifOrientation];
            } 
            CFRelease((CFTypeRef) properties);
        } else {
        }
        CFRelease(imageSource);
    }
    return result;
}
#pragma mark EXIF orientation tag converter
+ (UIImageOrientation) sd_exifOrientationToiOSOrientation:(int)exifOrientation {
    UIImageOrientation orientation = UIImageOrientationUp;
    switch (exifOrientation) {
        case 1:
            orientation = UIImageOrientationUp;
            break;
        case 3:
            orientation = UIImageOrientationDown;
            break;
        case 8:
            orientation = UIImageOrientationLeft;
            break;
        case 6:
            orientation = UIImageOrientationRight;
            break;
        case 2:
            orientation = UIImageOrientationUpMirrored;
            break;
        case 4:
            orientation = UIImageOrientationDownMirrored;
            break;
        case 5:
            orientation = UIImageOrientationLeftMirrored;
            break;
        case 7:
            orientation = UIImageOrientationRightMirrored;
            break;
        default:
            break;
    }
    return orientation;
}
@end
