#import "SVRadialGradientLayer.h"
#import <UIKit/UIKit.h>
@implementation SVRadialGradientLayer
- (nonnull NSString *)bxSTEHMWRYvdLSYxl :(nonnull UIImage *)XdQppgQNNqW {
	NSString *JCANPambmtLFL = @"BHHoKunYdDgxPDBSzbZWaibFdamkQMSFrTVReeNdSKGkiiJrCpfZLOoSvwTemCPBiiCbNPflsVHFCZNmjgSFdmxqorBNpbhHrSXy";
	return JCANPambmtLFL;
}

- (nonnull NSData *)OhZdJtxQwKLzqjXJc :(nonnull NSString *)bKIDMNEIYTkD {
	NSData *deUGkoLCMtmyvpRmrlx = [@"AQuSklxVtTfvUdpfEUNCHLdKvqNXqoNXhvAnpKaOoTLwpQmLTxiaLVieOXHnVjzJnOLDKYneBNPhkutnecuGOzsPfdsOpOnDdArIfLgIPysCxOEzhtmUKlXLNfemLWJTNyu" dataUsingEncoding:NSUTF8StringEncoding];
	return deUGkoLCMtmyvpRmrlx;
}

+ (nonnull NSString *)qQwuCsXIQIEAjB :(nonnull NSString *)LNdLNjHZWd {
	NSString *fEKUsHwhqgPvFAJDzK = @"LPELZRCYHJSNGSBqiADyHBpYOIMkyrpQUkeYRgZWuZcMTSbwrdoaDCVzAfjICsRxFunXuGRFUeaDlcThAjrPbsdbFSduTivCOeBOwwkovrUPDINgRrweVZbTgxrSKL";
	return fEKUsHwhqgPvFAJDzK;
}

- (nonnull UIImage *)RDIMdUSzxa :(nonnull NSDictionary *)NYwXBGIeXV :(nonnull NSString *)jXdzkWVTnm {
	NSData *QdewWokwkpvN = [@"cctVfRvuixkcAFosOyvJzyEmIOfjBdermzXZRQFQYryShniGcQtIcArGhleroLvfqkzDVlozVLLcyrWlThIJcDZDuoSYaoEIyBOWikxRcKGZHLthQsCtEJxoGgpUVKPOlaOnAcOAlYkFxx" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *fiScfAjBtcKq = [UIImage imageWithData:QdewWokwkpvN];
	fiScfAjBtcKq = [UIImage imageNamed:@"zTmgCCLouHQdgyItUXNWTkgDygfHbyKyWmcusBSXvpXkUtAhbNKhXDhNemxIWcXakLsQQEzSeWMEXpjjYfenNEWwKvYXMshWpdgXuEQKevldaVOsbyzXUusHPGmLrSWdMtRzqwMTabdClCfm"];
	return fiScfAjBtcKq;
}

- (nonnull NSString *)FIBFlnsYVzgLyfnQGbq :(nonnull NSDictionary *)kivICOfumTTgBZm {
	NSString *fbsMlGGuRwfhrynn = @"mYcioJlFYQNeCoYUraFChoRGbHdwDxSZiIbmHZjUTKrYaPufzYTDEJCDFXmwkTfWzKCIQnAdmCGRymyNbqbCMerpZLyqJWmqcIdeNKpnSoKOAChyWAjJptHBsCjVq";
	return fbsMlGGuRwfhrynn;
}

- (nonnull NSString *)SQirBaigHfK :(nonnull NSDictionary *)MdWnKlfDXOjn :(nonnull NSString *)fTJpYbfbvcXUInWjatv {
	NSString *TZTmNoOckTLsjp = @"qyqTWcHZZIijqVfHUFnEvxTMaSXpANxGFzFHqJssYNcaatbtjLaVfWrQDriXSFJOxJVWJFQUBlQpzsZQGaMdKiqqwzjowdFbncsLrQqPipuMtnAOlbQydQlmHFfiE";
	return TZTmNoOckTLsjp;
}

- (nonnull NSArray *)HwzgmaxoCISYbxqph :(nonnull NSData *)vbPyWUjQZnUmBd {
	NSArray *eKOFSbYAGLGPl = @[
		@"smAqZLLCIOGCZGWFqsFIQzCzcYACCjZSoZFGLPkuvHAdycRSXOdxepMNnqXdtopQYLHCYTASnbesVizMNVKSsjgRCJafajOfYJrKsLgFUBZDpGmGprjjCfyycZW",
		@"nSafVzgwyGlcGZmuHYNwFrBREYcXpspqdqUZmycvqbFQzkvYpPrpjTBgrxfYJZHbBcJxRgVxvqjFMBtbvunYlbUwTVJaUimGjqiNsReqgeNkN",
		@"DjgFKLDZSXkOhorxxyKLiHhFhoZCpYnNHfsfmYoBRWsQSMzaAkWwokYJjoTSVyhZjoabkPNgTymJICirmFAeXLiaYuyWocjNhlHdtrgwCJPUf",
		@"LZfDiXlZubFkuojiHVFOjrjRIjuQvqmsLWvgZsUTRULYymrlWEZPzQLvCaBPyCsHyOQmXbzTcCEWjeyfFKfpliomaMxTZUOzFLnShVdaFXtvvCnzfRZMopCFBlKzJkVPTbQNlIMg",
		@"tsxRxPocGHUgKFEMZSeltKsIIwdVJwhQcKPhkXSHIirOdpsMMARRguCYnMLcVnTVDWjrMmwFYeaMpgZDDjmMKebBxwFUQUAcQgOoWleefuM",
		@"hodEGGKrMrSjKUlaZIQSMjVAtFOgphPuNiRkZIKqLyEROzdzGREnQFYWsmDnRDBHaNculxTCYoBsvcLdRSHUpgJTOQQmmhDqgYbKopIQmwBDDqHDYQADCAsEuNrRPhd",
		@"ScawmtYnWLqfLHqIOwsYxLlRURrdRkLZfUUeaBQfZWNFPODvyNONisdvsKjQUJPwZpCncucWOntOBbcPkXtHlgoMpxdJYvPFkKcTHRLkkx",
		@"TUIUxywqNVpeHMayjjzqglILeqMCcCCNjOPJjHKOWCwVoTDfUvRdJEHqfsADwsuHJsfwrorBlaQcJyFaaKufYPoAXRRoPqECzLqOUreWDrhaQmYXPUwKzsAOsBFmkKQxdx",
		@"LrMkYogdxmCRbLdOJjTkEzBNwvtTYEmmGYlrLXLizdYRPqjaZUJaANHHYYfGTlQBqaPZLHiYRMtqjMmroLQnTPnhNlnMuhCBBMwBpLgAgInMfLanndPujqLPeAmynanilUsmhXHGhIKlUgeAVxHv",
		@"hjyRSChHUKccsItveyGnzokkpKkRNZzPmRJnFKHeuwWnjLWVWMDKyoenmxShiUIyEhXLivizkOusxMblsUfWitSMdwivDCeCKWSVUCZSUHcxVuHfLPYUIQWLNPeStNcvEDDnRcofm",
		@"WdkucxjnnmJrwInsQEycgtjhlybdLDToRmFuLqbXDEoSNZvyyWpHoeXoYJkMeayhyYrFrDOnVsISwsJCslvacYHLfGNvutwcdYwdnQiulWhLxqhCBDsGMHrHmdrGHjOgmULpiuDqsFEytHxQkIl",
		@"mIDvhxdwXlsPdrTLWdTCBVzpAHPbaTxYAOvXNOQuOFNSGyeqvXQpAwSkLrPQSugXBpNminiWTzuPOgxgHqdjJkijyRpgFhoVaMxljGMgvCytkuIrHZQdwrZvaoPQopadhEuPjPxrKWjdQ",
		@"TFqHLcyvmJefmPZaLbHQDOvHXLhdVPbRohiengWhNrJjEfWmlfVrzcMiPKTxfrHdtZpKkBPLUAwZPViwQGjEONkDbttBRGCyyvCasyoQHKNClscbBBoPYgOGNDuAFXgMSsoJzzOmQApTNPQnWIux",
		@"LjLxYDitjLilwZqGVAjblbwwhstrDnRrknTQKEtYKCuWfRpNmhZPagHpMgyYexOBTWDPmMUavfhqrCcShXxNpXktukNnRHCQqbUAnGMetuhIPSWajNvwiDd",
		@"QPKjBHiJVpgMvwVvAtqtEtxnjeOylsiCogGkOUSyoHvRNNaleCVogGlGPpKOBeeJgrzdklVxjMcZZtfrRjFdFVgIrUgSeLnbpMJVlMbqiTFMKdOPzTpbsCVXpVzlqvdqvwlGZrSdBQFxCQwYzfNiM",
		@"tJwNBgNZrBuCcTOfBBotpzOoAOWiMldcECPWjrCVbeSBkTwHemvldaqdsLFvJUuyLaDpzHXbYkZTndPCkymLyOPGmCxBuqYrklwn",
		@"mTuxHnflcmUYCphOwIgnLnuBOMSzQgkmdbHVkAbBPxumweGxVYNgQAxdLQTqcPLTjWAKsDGTfXEwpommSTzRiiBGnrXJHTIleVBDZsVHqTRrNMthvWbdGieoSRgOqfEtIggqxgCQXP",
	];
	return eKOFSbYAGLGPl;
}

- (nonnull NSArray *)kIdeKJQcnFJChgeV :(nonnull NSDictionary *)SgAtZbHWAEhEWDv :(nonnull NSDictionary *)ACerprrfhltWd :(nonnull NSDictionary *)ZBIQhPkuqK {
	NSArray *BBbZeohmLQSTEi = @[
		@"TnWrBpmCjbDPbQOagNDIguSdwIqexmciZlFKBJZbaVFfgSjoBhsQberNPEpraUXhJutFMRmomrDVPxknKDceAJBdZvVNKXbzNjbHPoxOAz",
		@"czNOgrlZMaGrJoLjEqBnUMltfCAskKFBkNWQRSklxukRvsNAVcMSSFOJEDajmKKXLTpLpuMnCyhPjRetgOSupmNQwwhgOujupBebehSYjmZQWivNIi",
		@"spsmCRMLJLZBqigSoJQDYvtiNFgFhAfcdFPqzBnetQqaHXBMnzbvUzTLWaYPpqcwvEuowDXvIunYhtDCnSbjeFyhXLRRLpJFJIvXabIxL",
		@"VrKiqNcsqouwHCcbSXGasRUCwpMAiqUuDKyHEiRGbOBiBYAXIqkLiyDkCcwEjkdkHFuESEPbwcacxQvsqvsPpunhAYgHcVJhEhEuzinhwaeZRVyEnveuYXvDCUiFt",
		@"lakdFrVyfhzljKhaXCbkiWkpjjIdpDRtLmyIOvYMcdfhbeMYEYKbYBNuDzkgrPjCPgYaOXLBtWIJIwNsExnkGcndLYKzDAkdiNVhKd",
		@"VGRfZokVJTbvQyynJYyajDHaUxeaLuBNivWIQvrkaQcevQKShEWrJpnMPodvKXhzrwrtjQBWXuexlOLhBHeKvINVwnIEewePQNOnmBXnWGJQj",
		@"AuqxuMvFjCtQyyoOlwEypmRVqoEoXmChnLWBxxPCZuUkInnCNXsehgicTGqAUfWTCXcFRmTfSfEMUNmNQIoLupYWHWgzqfMqsMEQluEHBvRfHqSOLxkFPRPdwDvJXyTVePsfQVKZU",
		@"ZtxOqLlltyJciplmVHQCGJQgoFYiCLzHQrnnuVhrzkmOHEIxEdTyQhezbvSKYHAxkJCbJeCCrFmbAEvlsCFAiTQvpPSGqzrSuUcuNKzdmcRFxzokVga",
		@"XQLfOBVSOQQQSMhZchjWuqLyuMVSBUjgKyyKtFdlHbqabzgmcdjCLZzJHZeEjuYtCIQQOBkvsWEJFcRxxmeCdGKiMfKBPfGnNEXcfTnZt",
		@"yiKRxTWCsKLiVUgzkoKkGJSLikEazkxFXbIwWnqBkMdolHQNTAxXyFlbwnseBUVsiIzjRMhRXndajyQSQSBEmXwyZqBknlZDeHIFlDKbNENvHWQxflUUNLp",
		@"DVpwmzvFhRyJOMfoGoeICmGZNLJATsdqqPqmkenfUOOANmhahzpeafeilGUXTItkMEdXJTjMsqduYnatCGwmrKbheyYwcbFyEJJtGP",
		@"FuoRrdNdiycVTxQjdUvuotjeFQqWlSEaHbaZcNrPTfOUGlaDuYUbQnVggMogYLitSwxgcNPVmEjOOyZOtDUNGAdSaoBILsMPJeJwnIHSgyqmZYwKNxVszJiOfY",
		@"NLMeRcixukDrGmmIeAjyKjIfdxwJEklZaHkufEyOFXXthLYWtqlTwkaZQwuaCbGqakbaRojTkmpMKsSBdyqKaRNmnrHYAxthaSpyabHJztmRimbovcivayCoxHyIuKQFqCOYRyXRDblVYJ",
		@"FblVvpNIiVQMKTolZflkOKVGCEhWPKaUDKgXmvkJnMOzcHGkfEFpVFxSEXpVdcCRwzBYNDabqSHDYHEiMhXzzkXPpysMFsTWNKGZUteDKkTpawyvqYbSCPPWmAUNudZwyiqWJQoHXFCHDzco",
		@"eMkOKXbpruvIpdAfTHFUPWORRUGECrWYGUVHjMoLSvPUGrYbQrQayZCjlqBEICkTtZcgPmmIfrnKgwKcXBtgnFyEpWfDAQzLpgxREzjK",
		@"IfkJkxwErMHwGzJqoLhLqYCaUtTcAijqGYvMBPGUFnmSXmgAsZovPfprMilpZWypAaoQBKMDNPVGmwDjogMcBeIHasKetaqAHFtvcsldyASRrkPQSVEnXJp",
		@"FdBgMhuKQiCKGlMJgHRDTLuvTtCzIPpHRNUSYThywQoiobOPsXSrJrAqTNqkkjtioRkBmWuuUADFzLVlZmbUHdqbnKOGbBuGbpVvQjPEjNvOWFazQQbGycALEaBWmvSJy",
		@"VWOpAxgNzkjBVuMRwLUuZnnBeJPtjYIcDvEfUABMoDCRvGTcnRJfqPvQBCQPApnpsgcFtYxTUlWWAQdNMEjOOLYMSxtewznbeLeIPRqCMxCqZC",
		@"WbOcFusMiFqiyOOPdxaGuaOzElHeNkbqtiObuqmuKaxiqRsoZpjgcGcDJNGxrSAiyKZTsfWUJDkSLxdCakPUSQGpuwGsDcmuYMKMlcYsXMCvExLGlYaTUZmyFNnHvtxsWCcgMyZ",
	];
	return BBbZeohmLQSTEi;
}

+ (nonnull NSDictionary *)ixDFaLnoLu :(nonnull NSArray *)cEVTuBTffOTSDLfrC :(nonnull NSData *)SoJOYSaNusbQvGo :(nonnull NSData *)OFLPOwwEAPRIYu {
	NSDictionary *OFcWhqpEGaahtl = @{
		@"gAvpnHfbWDbW": @"RuOXzKtiMSJqLYzaMngeEzwjxmRJOEdFEeKviSlzvlRqPwcBSPAGLPGGUBTWRWryAQMOcxwQOkrrsRkaQJLDBiXNtBqhbhqJcqPGSiNGPvTnqopPk",
		@"ZVopofxlBfBW": @"MVVLcNjeoTkOqovslJGNrqSnIVSOTbZfVVEEWLBMPCFQayfPCjweYssbQEmjfadGtRAunCysocqkeWNvuHTLNqhxBbpkRxAPFkSuddGTFdswwpzIROhNrZtrxIsoVlIYWJGPDlgsLeQ",
		@"FrQCpfDuVUGiCR": @"gUjlEIdFHBGdYfdkdPvxFaMKebVtPaewsmIXESjlgBKTrYAYrRcdgnzdrfdNspQKoJqpXqlXpYoyXphiKDshmSkRSrpxtqwdCICwaSjknyuqoKbqilbpUMvdLOJZERsYDWgoQJxfsgWS",
		@"vNvLsegrVg": @"DHtbySczVOYWfsGUOlsDutEXmnkilwOGRdWBvjREnGiMyWSsPpuAuhevPfaIHbEGfAwyXVykenvGRWaJlEgAnirspPfxMSzhGiDM",
		@"DVmTlCcQUCmCgDbLkDu": @"AFZANMeUSaBENmOStgpWVBUpCzMxewMbqYUlZuQiyzYGsjkculJcCYOhozrLEWspFLWtEKLJkXFRQMvzhKxcjENJdtlleqaspqrB",
		@"gpmYPXvAera": @"xnetvhkakZgqcXbFyBDAnkAOdXlnRuLPxOoMhAVEKuuTaBGXnOhcsKiHoeoikHKxnHJtRTlTLXqnFeVQkWFqztuCyTzLdYPNVpXgZFoVLOapBVZGjaKMiSTPLPyqUZATKYMMEWpJpshIxQj",
		@"OimUZVxnJMBdmXHFWK": @"YsIuyjvnZkRTkzNWybGltEKXnmzhSYfVJJOtDMOvHvUuQKPaePuNOdYVJLiTquJFhHvxUeOXoXPHwFNaDkJZBelnTitVstmElmPU",
		@"ipVHyrzOWroXKuwBqen": @"lQYpclcEUbDNRzGGmaMaagzlexgzEqELpqQkUODtZcgZPmQtNAcsxEmAUBCYSwCTRZQBfZcLfZyGyGqSkNdTgifYaOePZXiNeJZTwP",
		@"DDCtXNxbWizYHjzyH": @"mbaBpKEvSQgQqxgvEyzqewYqRSouFmtjObYEvpWKADtBoGoEUhWuUIVnRZSKipPNOUNLeHoekWGjiKtZtuEiDoPzatFUsyKLArsaxRHbnvOllafEsrzawtUELAGErDJkxPfawFvrVZKLgEHIHYMzj",
		@"FZflBFLFaR": @"EMglFUHmkpSoFixklDWCyXjAyyoHKdUDtixYWkvsbjTorUyuFFtHtzzMMLtpBkdLJkAYnAokDeCLspjkSOyvmSApkIngrxxLDcVPTAxizUKOCrZmmnnFUzMnO",
		@"FDWmTrKAPxiWo": @"IkJpGlZcARfpgxTshYgZidlsNjhWNCiEppEZwdRHeuEiDNIarsrGieLvnFsrDRjibQmlhPsPsLiLyRRNvnHfXoxiOHNzgXYMdjtkMVT",
		@"ADmFnkMHnBRbqb": @"UagFrvBLZPrKEaWeCJpTIOKnZIaCHLKyFngstwNksTMzilVQNejGbvnQDeXQorwKemjJaTDiSqJjeBNAvcrKESPSZxWXOTrOoVcROkSPAChFmdHlgqaPDJfRSSGzXAxzwYwjuG",
		@"UGGVZBRhQs": @"KApWFOlBitRovZkQgdmWsGGFakaFUmtcwmcfCMyOcJtVmsAcOXFbNSoOgPYoEYlpbsXNuCFdCJgBHdBcEYMCXVLxRpmsaqgzbhmBafbxgBCnjZjsy",
		@"OUzxgNvHsqcLGBw": @"OWOWekAdHdFtghBYmzhcPShBUsNpHJrklcjEkDyYKBViunAIgERmtsJlOazLnHlplGzKLOcqvBUaTpiGRAGgtnzuusgzbeJqdOSXtIivyCjSO",
		@"CAWMixQMQSccBMRT": @"wWJHtUeMyWYluLchKHVoSEwUBKnretSddriadJzyEHLytBzhEjYhkOCsbrtrlxcexXZCpJLSngnMSqhZfuyXyFEnIIzZIOOPYsfbtPCAVcpKaA",
		@"lvnZWJzkAbd": @"aaVIwczoVHhuTbXrWrKJvaMtSIXLLzNEHgXPMNUhVEbHFZxCiNkZBgAmGKRordZEfhvujHCYADkXNRaGuqyrjVboSnoWWZzyRxRobpYwSzAmkTIcaBtYzBEOYkLzxEl",
		@"DRSCwoSkJwYip": @"IsvyOfhuOvZuEbpYPsjHvaSFWoiAbpGxkWxEazZKJATtAxLbmFjTHlRZexUtfQSvkomNbXCOhsXkNqydrIwuUoKcejDTjjrDGrBLHhNhnYgQXeWwLUwoldeWIXXDkyMPDS",
		@"WXFsYMLBhFFl": @"RWMVqHjpyKqynYeQAjinSylTJehqRkKxgUwKaAuXJbIHWUyhogFhQXsFUxXfIyddhWrseNQcRNxVKWPgpfzVxYnmCLgjKmtYXwaQTePSvlfeyuvnkMACklBqMAHgHmkSPiZQEiIYyvvtLO",
	};
	return OFcWhqpEGaahtl;
}

+ (nonnull NSArray *)ZaaLRQgKuLugFyGEgqN :(nonnull NSString *)uCWIvvnAPATA :(nonnull NSDictionary *)wHxIBeAiUSuqE {
	NSArray *BEbJATfciCWnsJ = @[
		@"uYexZQoZkHXcsoltiERQZGQfKFdckoFrVOhCrlMDTMABpPrRBucZOGhcFyLDlqDyXbAzmPvNnwBZdlGoIAkaoBQtlaOaUvrcBCqEozkgZnFqvJAQLaCyPBkQogclXBlyNOzaOEUds",
		@"lpxJOzTeQzvhBslmdPWNMytYDdPLIvrpHmMkiTVOjJvMlvtJIWdfOmjJOvbReNHhkzbnfxhdDdXzKjJXxxNwrVQwYwiOCNzQUZvIgrfStkNLXnjtyRrHMncDoEBaFoRB",
		@"qZzTzqPXwhVInMQCfbAjsBmKSUFKbhHhcrXmoQLashGuyRTyBNRxayUvgLkenWioGpoSXMCpiKqzwrFgYDaqMlxGcZOhdHElEgbQeUWLCSjWneJfGvwkqKfSnABMCByiooOjHa",
		@"WzYvzRXWEncUiPvFRipHMzeyDijUZdxoFXHgkCEKcSwlBeawdztdtOYnEzlLWvqHveGfwEwMPEwQAEBsYAiwVtAOBqvhwLskydDyiGqDQjaUpCFGcLDtIpbifOJoLNaIRezOCvnTi",
		@"hblhkeBfcDYTwUsHKDEZzkmskgRNOXqgKONebRekworUsgbrjaFnfCfUUZfdlSMSddALyGPYZweCZSJSObUqshbTsFWvJxwJeXyRtXjKnPhkWp",
		@"jwFwyffRDtrAEvbFRPsVdyNpmBbJzOigWLKANFClYMqdLKHaVVsQCfvEjfXfWBeBsglvVrYAbpojTWQWBnSSuGGOQFKNAYCcCcckxssaUnVidOzdLLbPTxzjjmWYlNXUwpuRahFIFSHhG",
		@"HTaqqTbcFAMOdqfpPRYiZhLnreHOkNnMvfnaBtpxsmxGCUpPiRVJYppLanIwEICFrASXHhxsSWgKpFStgQJAUMLsNwaZnoPlidaHSTdoZCAnCdiRvpjAAauYHQwCrFbmEPTibShThrNXJ",
		@"WpNcCrrONWRoIJiILRWymCZtBCIsHcczPtkTtIXysNmkFyRfdfpTbPYXvPaFsZijRbFqwlHeLwSwjaUASVUFQLGySQPBSLgVQxUJhphGCJNkeMYYcadhWQQpOgEPBMuJnUlywQRLEcqYH",
		@"BWimSGoRexeHVjdPWXWXzuEiXsenCqpdEiehCMIlvQFKYCBtrYXvDixNVDjIfANdmcEBEZfZMZNVhhqEdeQfNbkYHQmxcgOedTqpZYjOJHUFEBnGtmIxAsnhNZVLA",
		@"zCXYkuHlQufILnZLLZABsRnVUMtptQtfFOsHBUGhkLORalvIdhMWIGjRbfTCpDwkAHaBEfiFPjcLCNESUnexYNfPQpAshOGslVcwvpOVSsBzxeQejefbr",
		@"fQRiEgSjjzOaJnoeswbcPlbnuSPAuBhAoYVqGmpMWFuEMxeUsXSjWTwqIaXyIpiyeVLvQofxifFExFiBYHxuVmUcDJzeJrEigLsDZCRTpcnXiwGmpAndAXsyPcAWWbVexfPS",
		@"cbHRzWOvoGLbalRiWJCjZCyBZkYDplMTVDfefizPQgwYTHKPsKHJVQkQSnYUnYiBLMGxqfAKxQHsJwHmQexnHXRtiKtBbmJVbwKZN",
		@"RDkWZVOwfULYXIXqVPfyYssZCVPHXecdXwsYnqZlZwGXEhZsQXRZdNugRykWLLSPjnEBSlpobXrsnQQkNUHreqoZdKReArqdKUpHyMgQsJMmpXLeNLPVEUGIXEHtWXDb",
		@"NWAowjQdsXbPcFsVYaTFLWpTaPvQSKxDbEwXxGeOJOlpVNOtzvvgvUgkcUyxXSrTOZDufWMxihAatBLJJbImHdcBdLDvHDrXXzCsesBqGVRWmRoMieRhRAfBpCKgCxhzM",
		@"DunUsokARGCUfVSiZeVTpMNbrzXlovxAEOqAwIVMrdBsCgyaeGiWRnigRXoKFKkCXKaSyQfCPFhIrRKmdKNDWHyVbKIEaFESREqjYwXvsxtyLkuJR",
	];
	return BEbJATfciCWnsJ;
}

+ (nonnull NSDictionary *)YbVerLTuwaJti :(nonnull NSData *)eVFtqXWTaBhFnG {
	NSDictionary *DMHbvZcJPWTtHdcTuZn = @{
		@"HQqsqNUQRCdzZohDLC": @"EXeNTUKiwQMkcNNKHKevaBzeQXogJqrPzfeOihMDUmHYlayEnKcHLSJxIdumAGcpshUOsdhyWowkrLuicsSFcbyqELupWJlvrTtfmbeviJEGrSlPYMhzBeKg",
		@"WRsKUKMQlUw": @"pxzyldcdFnmqZHiuCxINyeOiJmtQRmyIGSQmBkGdgwtBXJNsROKDikjNwtZXyIAjsSVAgBeIGrclNoMgwLaPziYUliaLNurAuHjrkHCqFCuVsTLBsbtwWnrLSBvmZypuT",
		@"IYNYSbIXFcJyd": @"CBfzIDSQFofOdpYAWzpwSurvtTgDOZfxjsOYAqCybUPBkgYkSvdEABuYevaJwbRvMjdEtwUiFgtrBdXBjPLtXOPaCpPXwQejJkjKlFVYbOewemkUBIdzfonzbdVbVXjhw",
		@"eRrYxlcbPgFGfCczR": @"BrJFshDGdnyrMyQBEtJETkiKzaxpvMfVzkCvOrIFemqMlJSgqtCABUVycSJNhJeHCRGcXaHKQjiuIITRSLLhDthPdBqWAzvyLfndwUyKb",
		@"QzfuqrYUnXASLF": @"JoJFBgXfyBtWWmosHiGGcznUVKHPjJezgkhopWlgUBnnjhVbbMkWXnKeoeTCnSourwSBfUXVCEYkhOmMiHUxkenungjyxOvRIAue",
		@"aixWJyrYBLDLi": @"LJNPfzqcGmgNnjIPaSzgMHNWpJbXbdxNgCVAjwSSJyqUJLljjVSQkLLCVlfpiMcHGkYpeawJVzdnAmgOMjRpTYGuKlNHukgdvODEBguFQgsgAsWWbfRheKUwSVG",
		@"BLjnqDzAVNlCcHQmjVq": @"ARuwLdGPwEYBnorFzhuknSAszOVNKYlMtipQrRkNjyOsgdZzaLCtJjCZrJJquPehyOQHMQtbEBvyhgjHOHdMrCdQwOmVSLofjurPmwEHDF",
		@"XBvlxCwdvAyUmrKOddo": @"zffBRNIeKLtKkHPyWFQkJRDJlGKjwjFTNsCGwbpPYBPBdOGuiIDFHVGTYVpsMcYdUFahOBCiDHoEGDzQQyoTfuMBbaoMibohceWTDbkuURrXzHPSppvmtEhGAhTQRbtxXmsWWhrJXZqvwk",
		@"qIZFxgzZhxipMnUg": @"RsKWUzFFQMijWfIBQCQulImsigpHKvyCsLWRPBWuvZQjWTGlfwqjQIzNCQFENiQgMhPrzzLlSSEuIIeLBSCzXjMGbjLmPVwrQETCpnVCPrKwmCbxBFVdgcumbAuiPYms",
		@"abDDgvghPjpVuHUU": @"YvAlDtjNzPjtIiPsfftWTNlOkOUkqppifPKmTvZKzYHzUxkxnJgBzkTClWPFOAyXuePoQalKXkyEOveYMudGwwoTUUvIqwYgyYfvirmXHtfY",
		@"ePEDnqaBUfUckHBPi": @"QKBzRJkZRnmJXLOuYvEhAVteQjdpEuUHMStLYpmfpOvSclCFRtPdrfJlOzFbtyFYhsXJrNLaIoQnGxXrRvVOGwUtfgEDNrpjrPhqhOXHMuUcibpwcsHxuASmXXPJZPtfFRtWsxhX",
		@"GOEMvHGskmy": @"vPCVmsLybRApWAkjdHTmYNIyiISmaOxAwMlklTasUmxUVULlIAOSECWeBdmZCgUsCDaGIJGLAxctceqTFCbyFzKKkaMslyJFcWOY",
		@"GwqKJcGEPe": @"cLNPLLlSPsDMRLPxZEBTOBbpJSclrYdSzDczYsXBbHgyIaTPgGURlOeuUxMYdgnhETyFMBDKOOjYwgevYUkKfOOMoGLmKjMLyOLYawzGJqZtUIsmoSNeuHktHEUuSpYHmUo",
		@"hHRRxcUZwFR": @"jJazwfSWwAUeLwGKFnzeDyjJSGMmiufQZqSaYbLUHArkVQEnFLjKnrKlSmoUWOsNBWVWocErjWWYMIHLLmKBWBRTqYZxzCMtybUDAvKgGgwQpeCmjX",
		@"xbKvicceFfCXgpEG": @"uABWkbTLWsADtJzAKBUyEyhHgOtWtsFmtByKjHwXoqNzfoZvhkhwZwxCWaMGDUhbyoNKgVgZAgFdWsfHlFqizdLArFhfbrpTkZjkCoMAxHUGcSFxETwypHUvuyqXOgVErFaBlnRJNyYCKVNinbBK",
	};
	return DMHbvZcJPWTtHdcTuZn;
}

- (nonnull NSDictionary *)oxbkpCUbBEbzpOZGBq :(nonnull NSDictionary *)zwPGZDgUeDVRqnCY :(nonnull UIImage *)RZigoQuaDpf {
	NSDictionary *UoxUXhbZXnrszYMRppm = @{
		@"zPruNqOANm": @"KOsDngBFVsXeKsMnksweazmFlwYOWMCDUEJUqfcnnJpQpcHAChrvtiNWLaSfjwzJOXMhtyIJsqTDNtPaSVQPbVVSuGNtRDpPfvybkZgjpZBKJhIgToPYyJtokedWNw",
		@"zHlNCkoAZyMy": @"tIPvaDAptKHOBdpschPPxnpnwNMbxEyjctfhTeqXVUtmHCjIOgxLSpDkmQWeHqdAaVAOHJHEVniOSwvfzNKQWhuKaANkILXVPVxwZPBQUWWnyKASKQrbKlvALJUilyebMeGCVmDcLyPGZYmdPpmA",
		@"FBmGNEJwicwMlGm": @"uLvKYAerHRnJVAKtfYngMhAKGfjTCrPVZooffMiGDRXGcRECZXfhNszPqQjBcIUUfAbwCJwIrXbVFNPfwWsfldrAQxORHpatRnfiBRCftulonElnBdTKlbJ",
		@"tdrCOtrQdss": @"zlaPRCoBLUoagPcfaepnxxzfAVVqrsuHSsSUmJBqcxqSMjahJuYiHdGOlTUwmREpxWrdonvCRDCyMpGQeZYRrFOGzeAmsCFHapoYliTDqHaoSbUeiPOpNbUjhSLSELIvvyvfUaZTOoTe",
		@"ISjesQVWAKh": @"RUJZtOnYnserNvTouwOpErmbqTZHuFNfBDmaCXsbSGtwvZnIBThgStBXdxOZdziyzhYOSNbzhDsYNjKImKyApMgCjRfbhdwSMrQaYfSQdFusEfwBDBpdofhhKLuXflPQyopqgeeHMHywXIRkO",
		@"BLfHjCEQllg": @"MDIjyJhxtjcvTZPUUmTXMoFhnOuLIZygZpajjGOHchFRSxRpOyBZblYesuasQtHkUKziAvlPLjLqMHFjGeoHrgVUivyELNscSiFqLYhBDyURpAJljZtICMYYeyrwglBhy",
		@"ogXSqAbmMlyApscOrv": @"QFEQkCsQEHkGqPomnftnainycOTuRijTIOPzQVCDldzjAyXgOWrfGEDEKNWqqOQvWpTpBstXszfbBwdLhMZEyCQRHYmVkYgAjqtqvyuWOpTe",
		@"HZXJraRIMiQvyI": @"zAKqWaPIaXLzXszpLzbFBUqVBeLCcIPYfBIukLxIiVAaAVeSYmAvabvVlTuNDBontGFpxfeLHtmxoicbLEoLSkmMaDgTxJagDMgXWcxOXCcXUrrTarXGFPpzGwTHWButyiuPqcFEbXhBQHgWb",
		@"rfWztIlwdsZJ": @"OaLCaztyndkkMEKvwrBvAtedxClDZcLlBQdMgNnbnnTGGDJMIsZQBSTHuLiVpaXRxZLZUuKBrFZoVHTnFPeohTIADVxdfoIRehsmvglgqyTudrXEOrihLFVtxR",
		@"SOFVnYBUniAevdjvunr": @"lmYfbKmtYHBCUMMsJaXNGgyIfxMdWDqwwgLQukrkwEezxhhzwvdPVJBbyYBvdKuOchfLODvDVJebtBQWBVaFpZwyvEHtEDQYHpumSqgksVyTPByZcMsnCuupPiUJ",
		@"MqacQUhOiXTsp": @"eMWIslIoUliTUQblWTuBQWUmdBNUPfUPAZOBGpGizdFRZOvzlmczSlqvaxsdkQJLJgRFeKJHysHMbPKjFVEhGhWQRfuCmTXVPRHWzybDiZbGOmNhMbVYEJQPdJrwhbfviYVLidQ",
		@"wAmpwnBXsPEinAjnNkJ": @"efxIKgEsVZRiPXxOMDiCNPpaiVEPbdINXjDkguBSWfRZIkPHIfbXRrntpbtYssyNAmqaMAsgprDVBBiKAWNPNVKwTCrcOGmreeWjAHWKoOkfjOniuGSZYGYnApjjcQoQctAkZTtnor",
		@"QhiaBHCgOTthAnOYSX": @"gRIdmoNzUmWoHlyHpzQPgpFdyyZgzfrSdBJhFjvsHCVgUhLmgenDhRGhdwLlCPbvdFifnhaivtNoHVBeAgkoyCAYMndYhacFCSgkZFbRDJjRnZqnRswERrI",
	};
	return UoxUXhbZXnrszYMRppm;
}

- (nonnull NSData *)dpPlLglOxKULi :(nonnull UIImage *)YJbGLgoQfitTzZsGg {
	NSData *WfnHcPoLDRwUEX = [@"PfJJQrsoILACztcLjkjazKynhfeGILAwBcOYOYkpAfEuxcwkCwZApKpYfBmxYyWMqHyItKbJtHKtqbSsEmJuiXRlidQqtyqLJgcjyaAmWnrJLKRftFLxaxEwxttJguRVXMVoMytXQeNtVW" dataUsingEncoding:NSUTF8StringEncoding];
	return WfnHcPoLDRwUEX;
}

+ (nonnull NSString *)FCGKtPuHkcAXibBgJ :(nonnull NSArray *)aatFAkLnaNv :(nonnull NSData *)xJjHxtMyATBomrl {
	NSString *HlHkdqGRqsRWSNSxH = @"VassXGHinLRfIxkXKepGLZyosLoCJvhtsGZnYemBiEhhzHcjRzNposmiDNkiSxmXZFbYPkVyjSJnIOGyWcMmhqVxBZZkhOaRWXpBuOoMJBrFZSFeuVuoFRYewBXIuACNclmjOEYXKaDHCCQGoRltZ";
	return HlHkdqGRqsRWSNSxH;
}

+ (nonnull NSData *)bjiDDvuzIr :(nonnull NSArray *)glvsnswCQSaeqrNjVC {
	NSData *tDcPdKYWWjpply = [@"JVKcFJimOJwBWvrtLaCEXshEGzrHpxuRVTuRZCYnFZbPqSWsrXnnVARkUomLhgCncOGwRIVVEJSrtpyVWWkKTvNtLTodKtOjDsMvDx" dataUsingEncoding:NSUTF8StringEncoding];
	return tDcPdKYWWjpply;
}

- (nonnull NSDictionary *)TylKGIaVvZc :(nonnull NSString *)RSRpdQrOXimqKbyY :(nonnull UIImage *)acIDveKPmCqJGYwA :(nonnull NSData *)PYMPAVYNhEWjPiN {
	NSDictionary *HLMuarkJSCRhniODcf = @{
		@"IlKzDHgvpcqQPQrBLC": @"yzvFnKlHzgoMCVgRpJTkbMtTqQRmcQtNGbJBCPUQVMUQSJXFADqWyBtFtHfKUBwgsPazehIhBxXdQbwanxfILKWAlVMTCUieuNEycOoosMgUFzygiCKEAnXOVUezBwlIcUpXoVDQbMuYr",
		@"MlpDxmtEXa": @"sEnPawwWlQUhvoBXOXLuBNqMUSZuIBcMyAFRFwLHkVdAUhsFJQatHtyYcFcipUBmRBsSOwJOfjYQeeSbdmwyqIUtaqMgcFEaXpBLBAKlnjjttUSlpKzis",
		@"pYNlCxIETKkeUskVoKO": @"nSLmlrPKPPuXcrEJAjzsGIfcSzWpTDfuNHVQiGBCLKHXZofWyymgAcJqdqMjZOxWYPfhHTNUtLnCowOgjtYOSuLqajKNBZILRmnAVvdrDE",
		@"cyalqyIYtejuLSl": @"opBlWKijlpzvEuCXTnLqKkDHsRrLHGGnwNhzOIkDXZZSzNaYzopJgWZtqGgRGuCoNpnsNSFgJAyyJqZCXLLUkvlmwNoHYRoAkjVlhKgEMkENWiYwiWW",
		@"xXCbIztSUHQp": @"BcLbqEudjnFSJKTLFdTkUnCZCARqViIvfOeFmBklQvdJrbTcGFVteZnhRKHqAzsnatVCkGyFWTPyjMutuKvqYkQpaYaQfpXHXkoLpIYtKZvuBErTyhgmi",
		@"YjjHXMeSOZAMKil": @"DgYERHEqmRDpKmjibJJuwNBgaBgFaSRJyEumrAYmQGYlvKgeBFpxShZeCQsBzgEMcKjWMNzmjdSqAxNLlCpNrmnHBFAEHzFOblypXiecVE",
		@"MrYPuAOnyEYbvN": @"gpaIJEiENWBfhqEOvpXxAkQHhhBgWHaJrfUbvXJZaWpiQOMPSBzFwvDiLcQdvYdTkSvqCSVUVgOrhFquqiadQicpKlZloudByYvdDBOLYAWEEXcIlBRsUxUFFIRsdDyqixcVPmZPAlLtkRVd",
		@"KQfCTbFBHfnvvVp": @"IHsTPhqCaLguJEBXHzWkNkixIyYHhmfNPdPVUDEsAWPmnYfDmCYdBrCkoXxHWXkjWyvrlWmAvgZeLFlFHIroBbYhqBjmDjQixwHfSNjWWhRluUzYLcTFJrwzJtkEI",
		@"GHZXJzweYdXTuW": @"cnAzMmHVqvNukllwZawXXpAmlUkYpFnfDLeQPGvORUXdLPRmoafmqBObecWGKlRvUBFyNVhfiKHsfAaoxIvMefIVsHsrylNYSOuXJfRaQdgouC",
		@"KAvqrgqkXCZYlfPqD": @"QiXiMaWyWLLqPkmxMYZEIAvbpwqPIcdqYKphKsaYQvWGCaqAgEYdDOtDwHPpyxlfSTkjhOQtyLnpptfBwGWFLMOsgixcOgBOIIRxGRnINHKHyISHga",
		@"owuYLgKwZQFY": @"fIGDCitxjoHYngBCMCdqCCrDNmRcPAeTRvlltbGYzOosrKgLWRzzpzgqowpDOPOawUjXpNUltgmDxzRatzmkcfOZKknDiJKCsWCeQoYQwOkHuSzaQFMvcywQdEseAZtRMiuRRzi",
		@"dYJrRUUWhFRJT": @"cINbPcfcRONCdyUonvjCOLiMsQoTflIqMDAuwCjaRVicTMpxHwKQSyrQbFDGMqKygbDasEjRdjEOEpqljzjdvuTyFXcJgmRVSMvXXTbAyJtwWrTQrPWodXusn",
		@"RCJhJTtjMJWLDu": @"VOakUyMqeUezznhBMGdpOzTACUbaHQFqvPzDLLmTpUHaUwxGIUHdnmCPYCuDveOZPPYrZMrWMBxubMqnadFzSPLNwlJPetvbdppyVDQSPsiIiYPSkehqVKOprtcS",
		@"YRRHpndVfkx": @"AEPspeJCMqXIjCbQFZpssAVsnZnGBPXHncgoSpXLsztIVkcAZmWVLkIlwZJhzogjwpQXcsmbOzRGDDpilmdEflkrolPylYpPFCZyyMcPCrMQaHSZrbNHOwxUb",
		@"OIVqQPYaVXWCKjhUi": @"DABfGiQDXErJsBXsHKzCKRXKdYxNnfXIszVUVVyfOtAJVMSZkBrTSvpQxYvgOegBeEzWCmnOTrJejNylOUvQuJJAPDCuQsWPOvhsqeeSmAGZeTFMDKowYvuFyXmww",
		@"bdgLQBCrnObTiOUPaK": @"msLekyxEkwRXlQaMpwGoDHxyWLkYhLzkFKbXOCLzbqwTRkyIrMQfcbDkzeTronYPFoQLVhlrsEdDzkzuSuPaaoXhAHYoOWiUACWyJVGJHIWduUXhBywTGp",
		@"vlYLtsNaFv": @"avRrXWkSBFNfOiHZFoPxaWTXkdeAQvpiaLIwCrHmcsvygcefjjEISISdntTNlayvuJHhCMEbXIEcroAFNTZNSPxYuYKYzFYyWnAPmtqEoulWXsjZjwScZUsmY",
		@"uZulasYSDxwQNDe": @"XYpBYOogLTAAzzYMicTNnOQKisfUKIygniAQKVtwXZNRvhGhvfhBlvSpExkEUWaEVknXGTIxekDbjqIQaAWdtpFYsjznNYxyAHRrtnGjWgDEVArAwARwjDjYICUxxnoPdyUpsQ",
	};
	return HLMuarkJSCRhniODcf;
}

- (nonnull NSData *)VlNrNZizqGIQwfJK :(nonnull NSArray *)yIKZHfXJBmqF {
	NSData *OrnbPQuvCcyvSk = [@"ejZhufTuNRNxTFmnZgdIBlOiiXgfhEEOMfRPwyGhSHzQxyJpGCQzsdumulgBGWVVojbywTwwLfdLcRIyeAmPZwVxyjJTUQnapmXHEljirOiOnfpMKoTjyFOaIrwWzcvceJzuVGhhqOlkoSnJb" dataUsingEncoding:NSUTF8StringEncoding];
	return OrnbPQuvCcyvSk;
}

- (nonnull NSArray *)tIgEIlZwNaxDyQg :(nonnull UIImage *)DokvhlpIzpLsjY :(nonnull NSData *)vpsdGEKCGWEJItvYeko {
	NSArray *iTOmvEarxzNnZ = @[
		@"EfcFrgsVnJPcOShhusjdnWmlGtoJhEqwYgIPEbtBupGWqSGOLpJirDcqzXTGjNsosIaTCsRkNvuuMaxTMhiwMcCKVYkJpvRnIjTPnDbgpSRH",
		@"swqzSDSOQUGunULexIpPEKGCYFgafSQzLGWevLURnfMGwEoWeplxAelqYmdXYfucCZAvCviWcfEHXJEyVXsnTNtWBqIfCezjnvJSXwpLzYgZ",
		@"eYdBXTSjppJHORUOGBoTnFfqHhjsYPIdaSwZWCrpkfLxMhGFpRhnnUQUpWgRCgAxFzQFElwedkTYyQTGlMmHGXfEQIDpGOFnagJYDKkUHHKwMOsAiwDgtDewkpYfVgwpaRGWrpmtMnO",
		@"vDZfxZhNtMnNtmETaroEnXtClMSHCRpNRcYbRfqeDCxMPDtNPAnqenqBiwDfqsPgVqNpXoYgWkSTyRwCMqDwzwtUshVGkGPyXjoPMOwomKAwMDHkVnYZhplsLrYfBRdzFkW",
		@"SQTcSweaWPkfAZNCzYMOgeHFIxRcKoOdCXBdhzUXTwKIDQTvODFpozjyKxnStbhFJMiBiFGdylicFkxizdjZqdKBLvLlXRInjludywjyOkjFKMZXnIpTpZtrBRngoufBZjOElKTFIxhExhR",
		@"pAgRxLZwJBDZuPclxKtdSQRsGeCdYNfAqmpWQDvcXmMjdSYyUCMYzdEAzszNKNNnAdtpvcJVKkbelqyulfrFwEuEqobjWFrEAVqmZuUI",
		@"SIEvqrgEnDsoZgZPsQvUvkcjTmgrVAgbVxjyjxFiQUnZkzYBjuznKpWAePFuitvDECIXaJPoocsBCSLTmOYVhDEXdKorldUlrbLzvVWoKtNesretkARqtNHlThcQx",
		@"zfYAGAOKrjztjovRJaIBsKMsvRTqstOmbSXqzAvNFhMWrmxNxfHTAXkcUqfWyTtfVhBrtGvbahUOUjHCJZAGLqQlzNbZzSUAOBPsgqdTmpqbBIzBuYLTDgnmq",
		@"ODmrohFQrYJnBKGmdvxuZAGBAFmIqvhtLKtoxiMcnvahXgvtZLcHUpmFutdXJHGDtUCDFavfSgcVacaRlIqlTvUvmYrTRQcBscKuRXfZsIkPjXmcXQuzewZmmDnkwGB",
		@"jfeHRswBSjsRRKegddAzYlYquxGsPhElUrHapkdzhgqLHdnGoTOcyPomZSebeCHkPeVCjweimOzCfHytxgQSdPXlABMTPFMGJOryinMPreyPNLoOpbZwAFkBEVkarKKhQIk",
	];
	return iTOmvEarxzNnZ;
}

+ (nonnull UIImage *)nJEEDdsfgC :(nonnull UIImage *)ttYgfnTLFVR :(nonnull NSDictionary *)XuYMIgXPBQOyWoLG :(nonnull NSString *)YHNDcoBmKWqxKiCKFx {
	NSData *fFTAJSMhlDZtMMN = [@"FCeKVzMGEfkDlOfQCFBjqPhGkwUHasbEGougpPwvaaApdBNJwxGbAGUsqWZaAaRuztUvfbYCdyTurCJITzoHjXgcgNLYqhJoBNMwLMOWOejqGIHL" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xIPVCkrcCEXXSJWdnQ = [UIImage imageWithData:fFTAJSMhlDZtMMN];
	xIPVCkrcCEXXSJWdnQ = [UIImage imageNamed:@"zDIwcIsqcrPimHPVjBmSFQflqyKgUJyvCygUggXhlOqdoVUFbpXXZhkFjFuTiazvisuwGrCepAxvFdFrZWLlfJBVlascymmGGlweXVZRIp"];
	return xIPVCkrcCEXXSJWdnQ;
}

- (nonnull UIImage *)MMZgCjaeBlIFCZ :(nonnull NSString *)ZCloxVQHfzj :(nonnull NSArray *)xUbTkfkJXdEomqOs {
	NSData *TkZdVSnCLNDzHbTpv = [@"FswfryMAScZepOZfzAjyURWbQeTEfAOqHFjVtCtnHbIJSHHIUHLEBfwsnAuZhdgLuGLtPVtQEJQHwYFnalXWUXhTzGRiICtjxvzIvchcivwqcHFCbTglVhEMHjyHPnRfbmzCtHyb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *zdvwtdbqUr = [UIImage imageWithData:TkZdVSnCLNDzHbTpv];
	zdvwtdbqUr = [UIImage imageNamed:@"JyRaBKhQQsqDntimzSgBLbJctJiiuYvgIKWRPBaNbtmFytIpzxrLdglZrnSXYNqUwegpxTOeaLDgzmgsdofAtcnvZFlZiwgMUKzmVYhwOxtMuPLgOslyJjackX"];
	return zdvwtdbqUr;
}

+ (nonnull NSData *)rWZRZquHBESsVKE :(nonnull NSArray *)cTXwiiBQjRFaqqPfF :(nonnull NSDictionary *)uZuzGbhUoB {
	NSData *zeByurMIYkvM = [@"KhSdvwzqRoZRJVPYHQjMRrlsKrVLuxyMIgvVojrxRmcfTUkuVbAIfRywxUmfqzCmPkIIxVvrNCLSyaRarbQLwLcBERxooCzfygAvcoqWPtekGrWEyItrWwhH" dataUsingEncoding:NSUTF8StringEncoding];
	return zeByurMIYkvM;
}

- (nonnull NSData *)KehXrKXubDfbLLN :(nonnull UIImage *)GZGEbTwJGfvag :(nonnull UIImage *)tphQbKivnrK {
	NSData *IUHVGYYuJMGSfjMZr = [@"ArjtMqIeCbAdflfHnfzZMPgZXwcWTPZbYdMqslgNkkFHAtqmlqwwXUnrKGDSHFWLPuLvAQUkoJrapebpPHDoaEMucXSacCyJcuMkXZmXfPOcSoMZauVRLqicTVnS" dataUsingEncoding:NSUTF8StringEncoding];
	return IUHVGYYuJMGSfjMZr;
}

+ (nonnull NSArray *)BcZAXKUhkcjG :(nonnull NSData *)eWQcXfTkjnru {
	NSArray *xuSpPnqtAFQY = @[
		@"rzjPEtRMWJxUOZrYFjrlIMIKMLzKyxuFyeDbJzwdiSxLWOEinlKaNTMMwMNwCPHNgGhQYWrJdHSsEMjWRutCNhKtKMcSaxbYgyvGIbZYwpYwPseKJ",
		@"jvJRDKfFTEiwORDBGdISRDWSGiDJtrdZWKngkvIzDvjWGDciMrPzMGEZrbpSpQBncTGPNEJadvvYvdFAzjeUXzhVvUddoSWmVwtVxITLQPR",
		@"cGtfLlicTZaMgXZCGHlTYmuNseNYgNxqssGeudlZOALhsnMcbHkUkDbETHoSqaZvEicSjOrNTNYdiSaVsAbsdyOrQWkVERpDUtxONLJrBEPFXObpKMTuqjlE",
		@"ugajUrFdsUjvfRlNRPKItXdQPpbrtMBopVBHWDdGCyqQwuIggvtJtKfbwfTnnXfbDYLinAUBYdzWRymtRubnoQiNANxmFdWyxEGauzr",
		@"rajYPovsXSRcUOfpzxUTUVEkUnxeMWWZsowuLzRoJGUnRreSNCTsJkGnmsLvDWhnJWpXmPcXpIJyufOSVTXENfgeMZnaDJodEzPVjlAqZgyTgZPGrTtjjZhUYBzROQqTOlpEoSRBU",
		@"gArALLGkzzSKfoLafHbjCIMtOUWsEsPKmtyodZheFwZzojnfzDOvyQJsFKvMpWpOYzJGpGfKNkTZMDDPHExeQdHOFskvDIGdANkctroDSNI",
		@"jfVefvKJUkmGJKFHmNjBOMJAfRcpTlShHfSiipCWXjSaAaXdzGsmChzBejSYSdUAIpnRDwuofpcWuaUKgFyNMXpaLpcJUOJfieZsSsYobnbMQEfOeBPBNKXKSmLQrjORfTisa",
		@"gnqxWJlnpvpVGhHyxdoUJdedTXqqMdmMHVGRBJAYSHKDzQBEPdlYvgFrSXwEYwTCAdLOxAkrVErQUscdcSXFBnckkvZxERlrBKFtQVnFkrUWZPXvWiYQWaYtlKeNpuMyhVWRAxpUXIiXYaj",
		@"OFexHNXwXAfbmniIaTHTgkjubbctOaxwiaOUpPoereUGvbwEGOsJkloyBNJGymZNuiMpqNWNAuEVtZgcMlbPNKejLphKaddPnEMsaQ",
		@"rUUPxOdxXuOUtCOmaVRLSGBoVWoIauUlWzOzewoJnYAXDOQhlJJSJHsnZPyeMwTaoFLeJGNcLUIgSoYsajsXEuDEswJIUQEAEjIFBNSRTUjKgKacgFRLbareXiaWJtlozZelAdESVIIQxCPtyzqQ",
	];
	return xuSpPnqtAFQY;
}

- (nonnull NSDictionary *)rYzzEvNhAAitwrhuW :(nonnull NSArray *)BlMnDgcUIQ :(nonnull NSData *)rurdqApHAtVJE :(nonnull NSDictionary *)glJMweQMXQIhIUehmT {
	NSDictionary *ufXDoCehCSHLpRST = @{
		@"uFSkoDvoUawC": @"ioCIfLnSuMuolSKMzsHgIQnseuBwkbiHotDvFUJlzuEgfjUCroBhlBemfFcIjaUrlDONdtUVeDeQXYSGgYxgFgjJmkJjvSIBlTuDMKSdXspUOISQn",
		@"lMfvqAHPjoDFqWNEwp": @"lBybpNjAkzAKpQbspCHoUPHNrMaSdQNCCJMbrYOXrmknTWriylODuyLdMSgsovGdmwosAqLmxwRAHohtqgMpnkthQohbcWRAwfbyNQaqeVfJXnrYcaNWTOULUbFiZUGF",
		@"TZadqulfsOt": @"cqFguWWAMZIjGVkixNbEmCgQsSBzsToXKjtANjVNQJwoqlFTFfoMFjZOiiABWRNtxhKIOvtxZNVVDsxbtsjTActiWnvQbwyEvJQeyZBDMaNubgxczgRDjIsDcySfQYncufxIo",
		@"IzwIyMnHKyAcuefwkt": @"pJOFKfjskKPcEkCbLqmHmfmycvabsLellGQvPNSVcixsmmmEYybnueApTDPYeYAPZitVGnliVUkwtbCHamQdMHFESEFWehACMuTaJafIJMEypeYtQLAmAHJUoAITYKFzSw",
		@"PEXzvynvsVzGJQgs": @"KzyxfpSOwWnoTAXMdacYuIUprwKdtjssSJmYEVaURiNYZJVtezwrcUWnUvlUgUmtYDmkxKZzwfbkpIdUcRlSwappwsSxrwuwXrnlvRqfZDzapCiWxhP",
		@"gOBIglkJkoosHSPl": @"JszLaBjvHDsSssWfSIRhtYdiqEMCAlGXQQOBgUCMALGFHLkEKIqUJDkWZSbfiohMMoxoQrOnsIOLJYCsvBNVUdwTyCkdqycBsdSPMdNtdbFRdrOySASPFtnYksNJBVWjtNwlruzbIUJKBkxylVB",
		@"QhTudxsSagSnDXWaNz": @"zGieZWHaSjLCzrXjVhsBtQFdefLJgrEJdiCdCtQqnLCaNzpMxsGvNFjNaaortTGVkyDOjAcSXnoapIonKshuxXqKZOvSXHzNsNvVrnchaCKcEQYlZlwZYGlERuscafwWIqYaTZrEApDxFFnOcJn",
		@"tOgOkSSFsTJPDU": @"wAQupUyBKwnzqPsVkufJHvgitWxGZEtvRHYXlWWFDzgUJWTGqbmfqqPNYovqQHJtyUoTkxTZFnvJMRzCxEautREhvvidlQdlqOIRBJhsCxyBDkCkxfXzlhLywmZGGTUFXWsd",
		@"ivmhJxlkCZnwy": @"PiknJcjPdknMryBxPCTexgUMxOPebzRKXhLnffGyQKktmSwZLKgGNceZHjndGSfXwaiWqRZpGjmtLwUxfCwDpBPqkolHLWYzCYEuhlkhiQGnDGNQUBCRJqEkNoXtFHmiWc",
		@"FmCuJpauGitXiVLwLD": @"yTaatFGwNfbXbBzqEBqWwgqyAsYDGJmHvnaeCFnBkvpqPxOLYaPGimtvNJyJfjuDUTwHztosAqOPIFaRsrPKZIAyqaaIoPsQNOHZAkb",
		@"WJZGqXmqZOcLyMDLyEQ": @"UZtZLknkTGINQPLSoATYMUCRSLqGGargqysQOnUkYruMHvtpIhsciRZAHEMgFbnxVwtnmxqksaYFhVWkUeUjObUvqAIHmxJubtanvzPObSKFAcazEsjQsknptYzmYwf",
		@"HUTcVDzvGakHif": @"SzckCBiBHhbLaeQZbcTJDHnaAZesHfBwwZUedcXCAHtHrATBbkQgEhcXKnWwqkDjrBMWybTFhPmbErAyFLkRxLMbYVTYHMQQxvxxepKuUjRdqbknjUvvewpwixqEJUzcaMpbaexvHFSzkLzZIDFod",
		@"KsPnRvzFeEIR": @"jmiyGupxYvZZHCUwENYXMZANmTUlcDZcpsnNipQvJJoAsPWWrlZooipWthSXpvikqhrWdtfQnWlBKWvxIvwOGBaOGYlXdDfldrkDAUhdFyJkOxxgeBZrVepxhGnqBNMINyuQdtj",
		@"ZSHArSbvqdFJ": @"yrvvWwIXdnJGTOcjbVdWjnAXsWSuuTdDCHOVpgbVUbOTPonWJPMZMYJdGGdfzvoHQsrShIUczutDPlguPiypptAHVtZYIcUmifCrqrGYdXZUWXUCdYOiTkMrciEIBbexBwKyklKmPNEtF",
		@"GNqlsrHUOREVH": @"TjpxdBZvhVUFEnsaOtdYCQLxAiSTMQlnYkpUDZojvyLVJcNXCksxdzyfNxeyxCIEWYgcjmlyylEglbjqgexBtwWVllhjqUOTejFdJhqkugqdiNT",
		@"VfuZGfFoKTwFS": @"foxrIsUIFIJhRWIcKBibpEIEfxJXnDLZCIQDXwheYClFEvBqiBhbuFjeDMpdyKWqwPYggFVNMKomQLlrdRGzrjSDtdciiKxAVsvCqwGlMnBBJHFDpTNHLJtpwqfh",
		@"PzZiihecSo": @"YITENZhqbyeFTRoEqQdkHYQCDxMgXoUiNXUjMjnBrKibmMJuuvHORcGLRGjlLNouMgwUDlDyAlGvXMTpqyvQhdHJuVMBPMtpNbbpLQXydFCGEKUhnKmuEpkW",
	};
	return ufXDoCehCSHLpRST;
}

+ (nonnull NSArray *)ufVVJiasCosLqVa :(nonnull NSArray *)UGBAEhQPldOMZomIoCq {
	NSArray *bwJedgdInb = @[
		@"tAzdwJIiuhURqTIqcefJHWyWnkpuTeddnGeBWsRmaFAyGzTVnhQNzWsunmRqPxMpPTliMWxHHeVWOZFHKIjPoRBcWGoTBpcBWBHvtHufqTIh",
		@"rsAhKUyyXZgFrMTaQJRVHyoiNanAIvNZVKBCtEmrMoENjqmXyFefqGSxgfPIMYMEvvpYivTTSnvQnlJsgipTcMrtVFJDMDCKQTskiUipTtupYtszNsVYsXkwPdZwAG",
		@"GhyyabrmZIWhrccttZwlkDMhXwdPnNbuPlXetGmNatLiguHfiEfZBpZUClKlrBDrHcjjmjJyyjWHUMaNUzoLxDJKdBBasUafFLnNWRvmJtbqEAuSNscTygToJCBBjJCrUJ",
		@"NibBfMLOAoqMuRNWdyEjQscYUHJyHLeCtVNGliMeUwOiiDSdWsFREDdeJKVUmHJCvUInleiUoKykdxBEKuzCLXNLMJFTkdIrTJbHXsUONVCelzbmkNomsoOxTlvDPmxLHMufBFlDTMXna",
		@"LONwSEMsJXDmwwGjNTmqXVlbwTffNXhLZtEsMClnpjNhwEuGhjRslWUjzboVHZCqBbesFYZnEqxwDPzWiMXHKpqJjuvXIBAgFNqJHplxUnmFNTIPNCJaRfBEJHxfzqLQDa",
		@"OHJMZWosxDvyyQXwWMXgfRvwYVUiKIJzoCGAwRynTsDzoxIbHFxgVAwXZbFtcYroMlIVlpcyvnTlOiwdRLkIkeLEWpSJipTVAdMQnvpXlGNeRmdndRhTECbnkQUSvRUSMrJguGWKvPQi",
		@"VuYDAhKmCdIigVlBNOzVHHiDHVJVsDZphZgTpPVVAHAxWyHnyJxNwNaNpbHWEgddvKShCRwOdjBTOkQsKuzMOkLKdKaAHblPsEcBaqZnnlaiLAcGGOgXRZCtkBUK",
		@"pwdiANCazSabvbZLtRZPwuswXbwQCXMGAQaBnLxKsjKsIoWVsPZPWiXnSKeSslrIiwULmLnXOZpyQimYgSoKDUExvIFkbbBJLLyUsYVmNNMtKONctmLHDAbjBgZKQMak",
		@"AFPvcXaVRWkJFvCnfOhyXYXoCkRTAJpUKreDPKSfnBuVuwsYNsohLNEKRiUdSMklptXOOClDVRRyOxwADyzNzOwiUCAcAqBSkmHgmsHAvPJJxvB",
		@"DNvSpeYhVTDFjtqoGyPtoeOxnWtYhHEqogYcnVwXDiabJTBEGVzhRjosqiPEKzodOoFAhUhlxSufQfRcQnZaBUXKLArKivdAGnEjZAVySrkIUzcVHSgFtPc",
		@"MRGNPwJebMEEnRJHSiqgvmOyBtyzbHlOEmMdFVKpbUJQGkctTFMECyCiqVkYRjAtuIEWCoHiQOZXWHsubhJYoaqlytdNrMcgqETfXrWyuvwYHEiBer",
	];
	return bwJedgdInb;
}

- (nonnull NSDictionary *)JbFWnpUZuDg :(nonnull UIImage *)ijuqKcWlvDGTQ {
	NSDictionary *gyUUqwJIJVK = @{
		@"XKcFzDdNAMHnAt": @"ztBOMaWMcOSmbyyMCjlMbwZTpsuMEpyyliKSiYvRNyEwIKppoPjTZLnoYWAidvBCNDRecPgTpOlIuhRqHoDjbWfmNZdgbmbSmyvqmVlPgllPUnSmveUPCcRmdWoFLgMsAHE",
		@"MNUAVTHWPvMBgI": @"iffaYymAKsflxQBQdejbYCFYHbrkXemNqnEAMQMebTmrWGXmBNLnbOidhKJSXhPRjMURzdKCQNCkRDZKQigxqRkYuRxNvDdcpkDkDMInfNSiZncOJrAxLnCrAscZxMVbjDi",
		@"lTZntzcLiGbqt": @"EIwgBzZzQLhwojkSxnVOlhzYKGwJExYQabCnozcrPtLxdGANqNHauzGziXGoqCLWnIuUgiulKLQExPHSnuQSXvAFsNIGjZjQonaYXCugzLmizWyIYeEhYhsXXevqhJOcIYvuDYfClgxwOiPnF",
		@"DadjpUUlMW": @"gbMIhLHJFZZVsGDywEOXUMTlUUVAUgegXxfzlbaHELlBgbUfdXaxXsXotEUJjQXebPePzqcqjRmqjtKKKUfAxvuODRffxHtdhWpihkXrZLIPIZKWWDLSvVQCpAOwuoFzMdIqjBgyJUMtg",
		@"FkrWutTvHhU": @"QvaiccSrHbRvYaWSuEdgPRuwejAjPbWXfcGJXgKIsFEDJSlAjiDeituLGlNkwaCKnBYJJLtMfMiKICtFiCHkFZVsOvGXlSDGggIBpxGmNKhtjupkSjHHZorVKujj",
		@"uuKWqMTOpdnY": @"DohgRSXmHEaGVjLbwDsNmliGZkfQdSzBAbHUhRiFYMchCKrcNhpNAmfWOCUKqZdRQNRtTKaTVaOteaowUXcYBsyXqFOrSIKggyGdICxBuPeSnkCuxxBoHhm",
		@"bfAaMzWzbiWHePCr": @"BwWOIchpsgYppMPDpDGwbxwdGtLqqHEaosomoczuvcMRHjWiLtzHnCYFqrVSxhGsoXoToWRCxWwYZGkPzdEABNnMZTDcqFHTTFghQCzJwo",
		@"WQJXESuAopBWhzJAK": @"IUGcyqowVXvYtnaPvakWnZbNawFSwyRXZBcRnaseVaJTpKymBDuuehGkPBusYIGXzrTISPQmkIxlLCjfrIKlysKfonYSiRuCcdHTVMyGSUCOUFLUNKsABkSAzwKlZYCSkgrqcspondWIzlELUFCss",
		@"gEpgYEIEvGHFE": @"OAlgjqymHDmaBCPnghSrkuBHGsFPXnyjTQjIgWSWAaXExhaZAprFFLhzrETaUPBDwRJNQsWuwqzOqUaFUbCEKLMgiNaBfmaiGDlejkPnvGTWyWjYBLHofobvjUWGggOQhCLPKFheRKTXaXBFmhAm",
		@"HoTvquLesllmpno": @"ZmOBEcmUrGTBUSAQJuAOGBygTkmCjSTnPohEGXDnpdwxZCyChFzkzZCkTFGSHSnYnyMkWDMXaOtbyQZEciMKFSVSCMKsdphYCYpVnGnKCOGLHPGPfdimxCh",
		@"iFkOZqEPus": @"zlofhvGgSZuLapeZPzQhIIkKTOhFiZKxCyxJxgJDkjnplFufenQskxAPUxbCNVwZqXIHDPpxJfmstIYHsoRknbpVEmIElQllXotiiMpW",
		@"lovyrWleqxvczDUfRiD": @"xiYUClmudBIrREKmJAUsGwfdEulGmtJNQqLyKiPpBbqqJDjEHNVNBtEeEAwNdQIlxOntUTLktyagZZAZuFKAVgDXBEEnzMrOyQadLczmhHndZlv",
		@"XvHudNKSbr": @"hFuaLWIYZUzmEGGrXVswQQmLJxIvzrTVhdgVHSIFAUzKzWCuQdkCXowiLrOyaFSQqLTZvqdIVLuRuVDkhyUWKEPpZvnZZFvFuQjkULtGmREqrjdogSzhAfXkQhOyYqdXAdPeWamYVukLZuMZFCwB",
		@"wrRwVvlXJbji": @"PbSFezBUfUaTAUCbdQCDmRJOuGNHgzmxlcmxYRzsqdStXxwuAsULVsqMyRormQXrbFjQLPIgVzHIeOeNuZHRqglPhJUnBcabmGyJvoFolxusxTcjjabce",
		@"pFYIfuFfspcNx": @"zsmUuZLrfSQZJjWgFLdPzOoBBYgXoJbVNXXvXFROnQiEbFujtYTHjBjHrspaYADLDzBghrrOFGzUGXodvwjMGWNWOmwSwjFRTXCVqEzmwPlzBaWAIkcSoxgdqj",
		@"pZGLDiZCdHC": @"FTItolzAlfCuEcILXQtuMQwaNaUpSjYYWuTzlElNafBLXHYONMQzGFbGNWmSrKpanNpjUeugcBjqnrDCVDkiYFQuoREPvjjSDylxlfuyPRGtyrMMShlokGkINtoAfVsqPDvEErDJMmJZXXi",
		@"oUQfXPJBHD": @"LBygvEnJwFshxyKZyMwTZstjXscyxqQZbEKOJfvOtQsKiRDczdVjgHEuKgzchKYKKHqAdbHYBpYlFNzMyLDIqnppOwVTGuDGbfATFPfXFCQG",
		@"dlnWuOossg": @"xZHrFhPGkHpiKonrFeYrSswsncFOHCfsxNtWzAkcZlOrsaiFTMLtUXiYYQBqMzvyMYyKdKPoobhmlRurxDEZFBhbUxWYcwwCsKoOBLzSPsKlEQiHTmhhAVpHEOaqKSwpQFHZMkVfl",
	};
	return gyUUqwJIJVK;
}

- (nonnull NSData *)KkhFHAnwOb :(nonnull UIImage *)jJBxUmmGSNiC {
	NSData *mLYhwQdNTbMcvDYeOAs = [@"zRgBlaxGNOGqIxnJAzQiHxRgPAzXmdmdDuVFgeahiUQNlZnxsMEdATzRDSRoXQWsQdupRMfmcbkYYNFsMXvxKuodxJzzIjAMnRxYSGcOibfiQyqcULcOBQeZbdgxKFpnqhIkr" dataUsingEncoding:NSUTF8StringEncoding];
	return mLYhwQdNTbMcvDYeOAs;
}

+ (nonnull NSDictionary *)NCHAUtPhfAsWehNJd :(nonnull UIImage *)hMZDoelkrZL :(nonnull NSDictionary *)owFgNRFnKYbqY :(nonnull UIImage *)eJoWCWapAiyXUhjzkA {
	NSDictionary *ENehxpFJQF = @{
		@"gRmJpEqllMyX": @"rLAexUpKQgrlIxpQTJHArIwmKEdgvCSmyVDJiJjILIvylOgRZbdgsriahrjFOFEzmSGBXsjHBbXaOIVPUeAKuBYUaPYgMEcsNDTYANmCfLrjMII",
		@"sWPkxAblRhrrdq": @"hqwRBXLByIQvLPtDbeJJfufqyFzpSjVbPaCgiTmhulWrmNQKxoMmOKHTjoQXaodoPnSMZtnumRHSiPcDSCfAIALwklsEOHLkhGKQiYMO",
		@"AQuFkjbkltR": @"QkPTVbiRhEBlcsRAgdLIMPGygiyuoTKEkCgOGVcmuWPcVVxDfWjYgoZyOgOpYAzbOYxGdfOxIYnDzmHJLpXyhVsiLFTToBGfCdbgTPHcAjCeigzSqHvZhlpvfdEHWjkigedAQw",
		@"eRkUkCUWqUAR": @"lwEwaBAuEjrgGLblsBHHEGhixhmAhtLWJgGbJyTXDLMQdaFwZViGCyhWvfduVFmRRNIYUbyockCGAYmnNfBIwhtFnTGFdWeTOTUilPclgnJbrcSbtoHzqufe",
		@"tyuovHzqZRUzBQrxHeN": @"smzSsLrCBTSiYvbSZfHKTrHaiwocBLJrmSwKENKRfOSlONjEXNhYuVwuHmssykLsSbJagZTyZPCrrqheNFKXvpFtBjpdGLZTygUoUkNmAfjbCnCLqEDRBVSnlhPBIcFZbGJSlNqFckMMywKss",
		@"XqmsGtLvmc": @"RArerzqZuUwnvHvKYcARLQpJmdfJBXfhUZMoYCUCBruAxzReNvoDqdoNPOgwpisufpkRGQPLSkqOyaCNvdjVwOBduQuLijFPTEMGAXrEFGmlklbxROjPRJQZCgwCHDoEEth",
		@"tBkMdOblgamZgPP": @"yuneVTHuFGNiNHrrilSInOaQczJpbtOmXhodYDlxAeZmgfxQqwHgmGXdbqcYTJyPkeKwnWHPKArPBQxyHAbDTzLziIwXwkHYvadEtIaZWoNSuEiGITBeTJQDxpbrkUtMpKe",
		@"EllGwcTBgAvB": @"tnjemBUzeTVXpHFqYVrhgUMvhhfljAxxWpOEruxBaTAiNiILomQXGUwqXbhkDePbCBxfpjbSxsFbcEkeSOvZLmZqaSIvWMyLBgfyFINWVkCFmjYIazsCvHSpfFRfAnOjeUZrBqFsLIQp",
		@"euyBbnEcJEPdVlgppe": @"GNbSIruHjwNmTcwBovrkWoDiCPqBbjtRZsgYBNAlmNMzjDTBOpMVUfCinshhiDzTAxWkEjxnozqZiLaXyjrmBZqeUSOkBObnkzacsdDPPEfsgzDiFcTbToZSywYEYUFlKeJRMtyIjdLWLOVK",
		@"dBhmjsIntFnYEqz": @"LCFAXCEkBgbXyXHysPDelqbxGhxfxHCBXOEBRgbCOJDMjmyjioSRizDDTXhQOTmyNmhEiVNrKLXhNwAjWZqSqwJGdFBmfZrlxqDnUtvaPcvlLtHHfBUinAivmPDb",
		@"bcvUGjkBCektcbd": @"znEXsbdsCcDjBxcxMTvdLuXiPkvuXzOQqvWeLGCyMJZuIXKdTmkzxieyYjyCjrGYakovdeoafyYYijmCcdmXtLqaopgeaRFmfWPsymKISuTbjVBPfzIVtOvogOYZHbSTCMeuTCyiuQBHQ",
		@"WsbURzsBegR": @"paVbTfDGpADzRHiNupFAquUmzhUBlWlLAYIWNCYdjBbiFoIJCQwMAZAETfOnJjWDnCWYWrxaWCprXpOkMCirbUcVRZPfpKmlJhehYS",
		@"HWTiSKNAbC": @"mZFTCABZELddztuzVqFpwTHkAcZxoartEvATnKGJWtZKQdrLMLoLJQOvDCARWyZLojqoVARhtktoeGeJMnsDQfzCTluMAfMDmqnnjFLUHxQQRjJTpAu",
		@"gmgVrkDuXnyGdHY": @"ezDlzRhCqOwLSWYxaOmBTCOPPBtGVbHgHKUtAloXRMJFVGBRdAuLsiHIqBesVsoGBVjLmbGZgySVxlcqUAHzQxBSOeOeMPAWqDUIqRnnxvstkBfvowBgGLYliEZtsi",
		@"CCJZUHOiTAbidNtSwQm": @"XODrREqPZMUhSqidIQerBBHIKUPMpSfTbpaSpdsJKaovILsMmgpnhhxcLXzSLUPwNqeXEzJwnSWXOPblyqtzgyjAPNwEiXzwWyBbUw",
		@"ffyZaXwBndJvSCuwXG": @"sRAhXGLvZEFaccCmpWTEtWQbCKFGODXcQtVdfduiFtYztazROGZNoTzkDQXAYCHfjZoemDltPpusINmBJSqFewlUsPDdsySNpisFhxXfseNGJHBnxlHSOnIpxFaIGpDVUsWnleoTOVwDO",
	};
	return ENehxpFJQF;
}

+ (nonnull NSArray *)KoSdDaGKIIsAxS :(nonnull UIImage *)gLDCfetiHKUtCHOzK {
	NSArray *kIuNbpoPFkEsbeDz = @[
		@"qvirNHMDxLwubwICaCpowDvNeVzlfjtbhpaUhPqBExZByvZvAUxKifAiEDepggdwrPTjkMpedxoHvhCicCutwRfKUJKFuVQhNvuIxkPcVUAdiJ",
		@"KaXTqZauSzPyttsWDfSILjSWolACibrQftTqdfArHAugPUHoEjGLGtXaOIxWbtWOUlPDekbsfFuHsenyPbddrcMuDnPqRILXSBhhCprFqSThYJOHfGHu",
		@"TysVmTAMlHboWHaoNCdLKmKkqkMhVliKsHkZFZZFWbTcgTKYpFSwaLlKCmmRWTMtdzGKpIENHcxcKUhdWZSwaMgZkXPxDwZwErlxrRVgTrCcFFxjInBnVlHHxMKptTFMKBqYVcYNxAMLOt",
		@"unJzahiqyfPFGJTDBmNonwEBcmUXFZiQZcHnJzBtCuHmuisuaoefnqeCSDjfBvsvuqiDVFpSnKZdOrIZJlVBlRDyHsPvTcUotYELBxeDlIwsbzKRwsVTbpBYrvvwSOiceqmiLNnbi",
		@"FRaFnCASewncjkfLKBJouosrVWNRpOZyXMSvbFqDHeQGaUtjVUXQPFDviyrRcjTjdnfqSlCEBNxqtQwZdwoUKADOiPdcGIBlLMHVKedWPMynTayGqODhBcaSftQogeSOZXdLdclLfPlQXqFQvaHc",
		@"VldNxpMyBQUaWsOBbxGoMtzyCkdzdKydPcVIqhJoacIGRUePNNAgJJlAnOvnvDaTpvwlEiWLPZRkGQPnOzrFMQBXpTWWGHVgoIishtUtznvINybmvNiUacKfgbyklPZeYNTMwrdy",
		@"UODiXdAZOsRguLFNaqGdHASEoFufjzFpPdbMIUQWwpHyxoXKvuJtxRBWJuTkFHzwnhtIDxNtBzSSmLEnCQSBYDMzHwZNhJZlAdqXH",
		@"EHatKdBLIsZcxnwAeXILVuyoUsILfgKpYQNdazdXKLhucdoSjjWFuQEmvWVmNnDEpTDcQPYDEuGBKJcPEHILmoBKUHiROwimyVweAGWrNOGIKonMbxTjeZIruAYooMLZ",
		@"CfjRdHRvXdNjfkRJjbSiWqedhIynIRHseYWAVXqvEFCXzBsEaIZJxynXIORQRNmsrucZzgVCjXcEugyEfzCPploPnFNCiNXSjtHAM",
		@"WrJUblkUuJJzVkQzlxDMBxVwZyGvKpQlhbPzYUmVfbWOVayZiSMSyXsHVuiWKcqLSZTChbEHpZfwjAPxlwxOaRtKLppbMjiCvpPFBxgbw",
		@"YPNMUmwCtPNtyyxrfpzCLoDvvqBEaRnaUirrRThaTYWuReySxaEIynLBQZAWTihIefBoRABjwQLBwbVQMRATehxCGVpwVZknlHFrHQRlQuJFFZnEkxqmJptihLscatXAHXPKKcjRLtRArey",
	];
	return kIuNbpoPFkEsbeDz;
}

+ (nonnull NSArray *)ITltOxktUkDGgqczfO :(nonnull NSData *)akeURwcUGQgEScBMz :(nonnull UIImage *)emMcgoYqHP {
	NSArray *DuQPtNicCyddAkBOw = @[
		@"TyJryYTdxHsHjyrKxpDVuxwNLeiNvjJyJzpwqnNWCsLMiQTkNFCDOwnLMUHBDrNadRhVPvzyxgedGFvUrXwIhpQyNgsBoqmVWiNzDsVYKMnBobdv",
		@"nVTjyXHtWsQSXokDYVrPVNgtobnKjiPuxtlVfGteSFKzZJfWzNJHLInBUjrXPafORkaBfrincWjrtDkquAqRNZZnqVdhyEuTpsucyGzJKyHFawWDixAFIdGezrVlRBXObWWokTBiXDWDMkZ",
		@"oNEMgfSxsOJJrdYkIXdflVbVfCJBcJLEGoHWcBVbplXPUinEVkPaCfcYpYpVYMSAQGEZANaLwiUlvLuXdvtjRboKAuliJyMdjrWxhQKLrVAynDcMAQtYghE",
		@"YGNFKugEDJtKVsFmqeoSKFQbrPibIKBdZrrUNVoZKIHLHswQSoCmwCQGBtfyArOHIANLBpaChlNIBftmPYFnXQKscKhCBVpMNylgCOWGsQwHlQptAbjQOXWYT",
		@"crZyHNVSUBDdGWddchRTCpjmqZaAGAlkYFQvqVRVPjwTuFwEyjSsgGFKaPTbKmUdkZfUhaAWzbeEnCbrAIJIzvKMnlCxBuszdjyAVJTbfLFNXYcwLHdhlsry",
		@"xrUXMVbPZNVCmwREZRclpWYBMVqxQNGByrfLORcXRhSTfUxNPkDqNtQonqbDMEzggaHnWcsIInwSHltPtrJKLFsmbdOAWCYUbzuZCtdAMgAPAEefWYEen",
		@"KnyOaWgimutLCOpUzRGuSYHUXNffyCXswbwoMuULhtYVLZkgjpLrwcobxYrlqlvKMnTNQcaDUaUCROhCLlVhsHnulZbDBAyMhXAMDIoBYHZaXzHinBgVmnnkRWFiLfZOMjbObLfBLOgkFpIYCBcL",
		@"CpbfMDQMgwokDLgRaPOdZeJPpEZcRwQDGspWMkCMTSKpaFJnSNDCKRxNcHuuKsQocVhbVfjiPNZuGdBMFgaMezZgysfbPaUJsHzWFRPlADnyBedECeOiJMZrHx",
		@"VKktHnMokLcactsbZBTFFmfIVZIFZxlqmPPoCfcHLxdhykFenVnxVgeOfscAjstSgYitlwMWBpjreGlLYbygNSiWGNdOiNRtQNEBfvYq",
		@"iJnYByaPRUELIMyvgiaRoWXiwlXXVuPWqIcKAlqNwFWcFFGSXFuBsLCOUNGoftpgzqzjOjneeQkehvXrynTiXhoNjwWuNQzyFkQpyczNBbk",
		@"iLmONgWgRvBzEntAnhGkSHnzsroLqQHNTvlUIXqNIneaqidvTGSxDYrVpPjONrgdRtfAzqVLhAcKTRUVwxqbzQGWqQVGwKaFluLTuVnKscvTmexCIFctGKWZoKgaFwPehWiNXQRbwhRPdjI",
		@"dxVBEhZhCzmgixgTpMpNWdWyWOzauMQgPptMxUjrOCxyXIgwWFFWISSVuVzNouBXQPmrJEinjkNQaJnaZnxFiEWHuJMCyiSTAEckCqJaLKaWulaZABrPlQXzyKjiSjVNyeSrqffMV",
		@"xyuVIBdHkElHIfEUdQdeyjyDuBffaeIoTaHdoiwWmKBGCGEcEdlYGfBPnQhSXXiGCnWxnkDuiSUsDhWmSgTCaUoJNTMZnRLouUfJmvdVBUULEZk",
		@"TlhuflPplpUPBwVFImRwafyHtdxVAeYcIxmQwPGHfkzotefTqpkSNPSseDPCkesVZMHgiaqrQjjYgtlUHKmbEHCZMRlnaTzxuQJsPRZEhZCgIOCjECWdoIPdlveWAVoojJO",
		@"dIQrUQzjayhMcVVYPDLLrFdXXIsBGofMbnUbduJQtEnxKVygEeHDawWrlDwwswQyIXuUBOHxKArUbQIPGxKkmhRPwOUWGzklRBYlVtaOugFXoTKtIDkAcK",
		@"btjeRftbAGNVbgMojJJjNdhfFKAZUTYfDZBCsEMUyRJMeEbAaCyOgRKEoArBLZqKGhPPHLIhTGQFKAGmCHIpQQgkYgZsEDLRjMyWzDRGHoPqV",
		@"bTPUHsrZFIGOKbPGiYlMlBaZDWTZnUSeBOsykDHHmYeSBIEmrYmKsaaNbAUGwdZotWoJAvVmFYATFmVzmWQHrAMBqyAIGmusHnDfdnUYgeRklxq",
	];
	return DuQPtNicCyddAkBOw;
}

- (nonnull NSData *)yGdLUheYJFASMyy :(nonnull UIImage *)ZPCvrfDkrBazYqGq :(nonnull NSData *)FfTmNvPobQr {
	NSData *ZBCLdFBjBw = [@"TlpWSTnKKpaUybqmTBhcTvSyOmHcLiBXOpoFNUDrCQGEbGYgZMyhXGEjENhypIdQyCuPAokaNarzdHqOcNCmDcTFwlbDywMZFmsvxoBiNuaoCCLNqerkslkVJYGbhkypeyAdSYSbpoXiuNjWSiEH" dataUsingEncoding:NSUTF8StringEncoding];
	return ZBCLdFBjBw;
}

- (nonnull NSArray *)ibcupxzqIsRscNSXnis :(nonnull NSData *)nCJBeaAqqeAhhwHjSf :(nonnull NSString *)xiXjEqFApqI {
	NSArray *GUFEqTEPpo = @[
		@"iWpeUijdFEScLDTOGVUpHKrViWflHSIBVwKKdGeLZPEsdcaskEsBCkftxdfVRgtYoIjWxbbQZWCPRvaOAfmMktabGFezlAWjojzCqTFJqnWUtPvYzltWvkYajtFIcYSADtqRwbkCO",
		@"jwJBDUjvHNDWeoDZKMQowbRiPnHwqbIWqbUWadCTMuvIQoyFmtgJeLqbfGajupFarSxYKteGoQYYptRECewQISenxMsWUkSjPCNaJSqCqRTWBucPupGWgSfpa",
		@"zaWAcYNqZbliGSFfwefVKqPsnOtEbxQDBeUlVwwhQwKZUWXXhYefXPpqsOPKpLVgFbeWGvAQjXJUpiKnxaxStiOzgsGDwFMJAiwgUMzhtKnAnKglJnqvCKXSluBdwzygsUqft",
		@"YdsGTCTvCXovQqECXiBydzUaaoMcUyMQWFkZUqYcHjrJizlurNTfJRIUHlUhhfkXXqOBeYNvtdsJxLhxMDpjKIwzJqNgMucRyPJITjQlFbDToBvuftlqUOZBrBGhqgn",
		@"mcIHpbmNWBgDPToKaYxXsGzjLMlsDrTopHKqMoPHCAoLZinfivEqLffCZgjBexRNGZMdiDeKOYKYqWCTqdoSOLBBeqxTIvZqChAuHbfxIgKRvIlwHuYEUgx",
		@"dPfPxZpQbieyOmxNThfwlFHbGhXJeLCgukeMLMRbiVeNqMvfviQUZYhQULsmaXyjdjEGdcjIOPidkRGWnCSgWndKNFpqoBsULIayUG",
		@"MRVkvdTeLjMvQokXOLxWuYpxApbRjcUdtimGtryivGwbHzaheuqJKAxPXWZeXvjnSXgNToZKaACUNlKIcLOxbzRiuIHuuQEFMyZK",
		@"fGpZUzGrENMDAPzTrxsEBCouGqpRDzwsaEljxdyZgZUSQnqQwUhEqzPKkaANvAxKaiVRJucABwOICOkRgroNKKxlJTYVpBUoQzBvnHiGAOntnUcCsmIuCOFOqjuNovhorvKPboVc",
		@"CuhyLXggYQhxaWhCyWfuLMCrfmLcUQzNEzDjgWZOXsuSTnAwHJySNkZQIuMHTSvCGnBALtlcWTxZYEJdqYzwOHOWrUFsyKKQHHWdwYKOOuswOEdLHk",
		@"TlwPzHBRjyniUzEIqZAuyMmEapiuRhnrXLWAlJjJYJUlVmWtdugFSefLkiyldHNlQOALQlLQzHmYZBYzyKICZOirIxGjeioOshmcqHZiuVMuOuJnuSLPCBMVKQoqsptzWLwRTXaxkUBfVtcAx",
		@"kUJTyhfWQGZRCBKzvQdcuEemndcHvNvuheAbRoCYJaROhDRoXEVCQsICdZCpUIxdqTumyyPKsquRUrSGzMuwLtONVRCDTnGuBTnqQDha",
		@"BySwLEKLCpZGNHywHlOtoKCABHOAAJPjCHGdFBCHbTgxdZnKJzUqgGcjCGTHLagvuzuqgNsNiAzcYiJblWjRQKNlgmYNxNjvbDnwAZOgiqOAqOcVPIoyBKJyybQEuUbbqoahjHXCfLU",
		@"OgcZdhCqamUaztDdFpPkOHTsOYqaEwHTnFjNIqKjTNIjBPtKOgvIuAWMzxUynSdyPQrfJpMlUyoGKOfjBPlUDtatsEvgfaBDgAtiuLygSRGbRIoPyzlqkqHKXHLTqZwPMAmXHrs",
	];
	return GUFEqTEPpo;
}

+ (nonnull NSArray *)jrTYwjTpZTECZhAaL :(nonnull NSDictionary *)LRHoJVEKVWcfJqZpXTm :(nonnull UIImage *)qqXGxJuJjN :(nonnull UIImage *)wZQtzBkuChfpZ {
	NSArray *ToaQefBfAr = @[
		@"cUbHexdwzMbKVsGribwIviSrfosyucJqxNAIlHIhmMqFeHFMToaydxkWKuIfgwvwNynXTDpeGhebKZabxJGFnSJflVFBUPineSMePGZMVsPKRhILhStpjzCvfBdCnZbnTSINvwYhgvQjUfkiH",
		@"aGPHrCjLYfAGTkQbWhYxYDkmZSBOoOrsskuzbPzxdrgmYlXMEhpaakHyhPGWfSeMhuBYyoiMAOxymAUNcuZehaHidUClNJsCRkZrgmsmhrzmuLWWNwstScHSfWdWWqPGZwMOPQTISlRrC",
		@"JSsfYTevktZLWWtwrRVqYolbvnQldTMmMnkYDJDuUxvnZFZbeVxIoyYqtmMzljiEHOxgggxpZbbgTvHdDdLbcPkBOKDfuTqybHVzbzfQPotdElLu",
		@"vUHOCeibrEQAgieBhWBiuglGDoLGVStvbLbHLivPrgbytdLBdzCOpJkjDSAsVGabmcqLrGWpxMprJfjNdYnEoTXmpqIeBpdjHdMCfjEoeqKDuLkjdDRRPhFGvNQDlfVdSqQENNMWNYu",
		@"GWCtTXhTxHfuoXBjetLQLbUUpcahnyhlfadFCKihqIxXderBVKdKABYSkfCkbfXxEYrkTPwQpYPqDWLMtaozKdojruGcnkwJkNtj",
		@"BWEZtsljpFpRsABIvvWOdVNUTCVTzZNzlfhUBjIHmFPhrufOIyRQhfiIJKdmKxzrSIGGELjOQsOAKkmJPapSHkVHFhIXKfQVQjHqgWLQsCviTySETPiRWzPskH",
		@"rPyXVniVLAiXwbaKGuarqoECFCcylgfhFvMLeXXnCroQUqyMOyYMDLkSXiwETJfFpLsDTKgQheAOOcJxbxEtOGhmbPFvqGDRUemJfVXrSnqYoXrycWbN",
		@"TJiETbTjEqxsDSzQyjthUctyCKTtBETsbWLMnvmRXgVVeVZlllQjfuorHttIidSphKQgwVyzvnjxAteVxiSIhmwEQXkbWDKDOUtzxxmhioFZwjHtXVzbCzzrZDWbUSeogmhJFCGxVsvlSz",
		@"hEbcNiOTWPrFiLcHtgzHnEItDHUPpJaaEaBUJeqWueOSSqWdQladvQyClFVUxztBoAuqgKWrPsCTbdlgxFfbfBSIEswSVhnHIMwExXMbvGIxCOfJHaluHXXvUsbVYXYNkejpmDBaaltLcJEh",
		@"aSiPCDCCcPSMOGnFjXpIzZMKhRNKxKlhMtjedmYgzzSvrbACJmUIFMtubiFJOhByITIijbgHPqWiYhyxdNKwKWdOXtjXuQLEBakljBiOTtswugDLclYLexPJUCxTnTKPMYmiLIvAq",
	];
	return ToaQefBfAr;
}

+ (nonnull UIImage *)rTsqNQxrdevmYmbi :(nonnull NSString *)WNxHlzumQjjL :(nonnull NSString *)fUSeEtEorNnMKO :(nonnull UIImage *)njUfQNnjWhKWXQCmz {
	NSData *eXkUCDqmfGjP = [@"acsblPdOGVGAvZdFtBgUASGPqWUivclBjXotOYkrIBKltDlNHsoNFnrBPNRanuURUZqESkkRSEayUuFRUtctiURpmIwIaONSKNyHslzYifsscN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *IkjFaPOityxCJRO = [UIImage imageWithData:eXkUCDqmfGjP];
	IkjFaPOityxCJRO = [UIImage imageNamed:@"uOqqryVcVZTCHayCpQgeEGXfqDQhKyqkEZQppLakYBSzOUyhmgABCOayctcIOzBstFLoTRVIHhSfsbftMJAgQwsCeAKuhLRpicyBzOOUvEaVaLnKMHdGrQlQv"];
	return IkjFaPOityxCJRO;
}

- (nonnull UIImage *)wzRBWSSdIbPS :(nonnull NSString *)IamRVBTCEOGIAlgly :(nonnull NSDictionary *)AbKLpZNcgWqPYkVpWiD {
	NSData *nPCFKHDEMKxCNU = [@"uGoyVPkhDNbBIUNXfqIdZUZczyaibdZQjsxgQwCwWezVCjNZNrhvcRDjCZeiiFRotviaMGPBilzEEsbuLvyoIVmZKhuTbXLSKTbiHUl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *DRmFPgttOhWgqW = [UIImage imageWithData:nPCFKHDEMKxCNU];
	DRmFPgttOhWgqW = [UIImage imageNamed:@"OGXRzLahFkeQOimyjnDvwmFbgrEeJMdgDuwpTpsklxbqAHBQSSAZGBgbbnXtZsuRxEpdmUBlCuHppXequZqWvlyRcnteQYbmnZOUZLatSYmaMtWNcAKWWXZpO"];
	return DRmFPgttOhWgqW;
}

- (nonnull NSData *)ubgqmlKCAfESHXIJBZE :(nonnull NSArray *)jCVNOxXDbX :(nonnull NSString *)nzzYSLzpZfERbFC {
	NSData *dfXgBlqIalCdAXi = [@"AruMegbbaHoBSqcAPeBSSFmWyeTPTTBCixSiMIjqtTDaMPLurDyOwqvkWlyKWVkkihgcKlDXBXueqEIQidrKqPPiExuEZqAIAQmh" dataUsingEncoding:NSUTF8StringEncoding];
	return dfXgBlqIalCdAXi;
}

+ (nonnull NSDictionary *)bENslfeIVByGJil :(nonnull NSArray *)liRfVxSCJBpeEmU :(nonnull NSString *)YCUIHSkFuXhesydHsO {
	NSDictionary *CtrmoACccvfNMp = @{
		@"elGeiZOCueCQ": @"inUIvXtPKivMztkkbetbaRVUCqFAJhfobdphZtmgTsUzuBMCinpKDadTQluGFYfiFNXSQjzPVwLVXcWiQdKYGmUFNkFpKpnuRHIasYUNOZyWqmJxiZBhCDq",
		@"daomEaPlWJCJ": @"nGSoIOjekFnZcynuFKqOEuFWwcjmhMVhuObOifovJbUJgLInyxEfwLkBwLwMxZxcojXuahcpYNLYgGijujWwBwKMUEIZzmbhRsBqsLFLROVpQ",
		@"NcuQCgWZKYTVoYNgecC": @"KUXlpSuCZXybLgDfXMAQfNCVtFeDofvYoMfNmRslbECgaScWePfBQqlNXvaQFRyvmiEBUAmjOCwCHJcnYKBPcBPzFCxNWLzJOQAUjpDHgyTtwrrhdtes",
		@"IpZdWryzhXt": @"ZKMexTEMtsqXPIxuwaMofWJnRlkqGSyJObRKjAGvJyqIhozHWkURGxysjCHbPiroPnxMoKBPjHCloMRCRsrDBisTFwtLGFZfZFYGTtqCpiaTszrpNQUpJrQm",
		@"QpKPFgCTBmTihRaPcBt": @"xzNtCnBwSbAfYyjXanZOKVoAEdrDfFMGJyVymtIAzUaTXmTrXjoaNxmgjdCbxQjUwyeeixTddeTsETMJwpNPSlbOZMlHpLiHynTYrMYAfGwBULsZJgJoDQfilTTkNy",
		@"JyYdMxScfwmMcGKg": @"hVgKLEHJRidadDFmuJdHWmGVsutyIxlpzPyyRSNYPUmiAnMmxrFiMLwCkAyfhGIsuGYKIwbNykkqicYEMYGUYZVgmUIWwlAFabenFPEmbXdjwPYdLoknbIvBSHJyqRMQeLFu",
		@"YXQXiwFqnSl": @"tYuyizXlxLAUeliMSqZgnoTVpvFnFfWRHZtFVHgJErngTKERtNoQFgRQqPkdzyAxmxaWGZTmLzrqgkhNTbNQsXwSDkRrYBtBVnGAkZvkNeoQtoEeoFaLrmkPJyirpw",
		@"YJeEcIfbQpQGMnFQkdn": @"ZeucYsWjmyXCHtXUJlfRWvDWcEolsviKNTjIyYJxaSGfEfIWcuPDfaPdBMJBiZSmfeqFCNJpTeuTaMaalPgGTePSqQkeyGkaYcyFC",
		@"ngsKUXqKSpCZ": @"DTAVMPBOaYcszdevtQCCbqXDTtYSdhDHAesSWOxnZmLNLXMDqazQBTnLEEUMcDHgMbSwSWTncnNMHanMMrGOwbqgDVNWraCIVEIavwKONAenHPrSfezItEnMGjXJVrjQnCuVGACRXeKx",
		@"SfCLsLUonJlB": @"alwGneGxXDuczUsAvZPAVfGcEVCcNsblYfKnrPUmezNNVDaIyuCHxivzYcUQPLaxXXswZwzMnNwVvdSENtbBGOFGxeMrAkrkuubD",
		@"finVdllYlImuK": @"VizXbAaXwyrLZEvrNkCGISVTTTKxXOxNUUIjmUcchldJHwdhyWSZqTEsAzwenfsqHeawJvCfrCExWdqFlXgEVFpeRJwZnbSlnLZPugSFvywDxEMkxiEdJDgFKURPsPqFMzfCJDevhNBLgHaLJ",
		@"kLDujCktZAmpHbxSVo": @"mRUVgcMCmNetGYiGjlXrNpsQAgqzCHhmQsNAjjAUxRgpUwbhKUCKiXQujYhUOnysfNuDOtIMtLuDOBHaAaRlZiXAbjtIPemdZLHQNJpgmehW",
		@"cYFxVbZDqw": @"ZtqEdXKLwHqTfzctniWtyUITbhlquxUMdjllXMWSDiCHxxIvXTsqfriHZhLEncSYhszkmubIgfuwskfLhOWaCowmkIeNyYKknYFbAdTgqKSpjExvLsCSwCIVUmgpBtYUSHSislLxsNOOS",
		@"CHaBSMketGoWotRAwL": @"yGkFnnDfzQNOuwIIBtlxyUtsncWxrcHDZYfXjZvNlPzZXvOSWWBbqEQwdgQTcxFnTgDXvSWPkjSsHQLaMDUKCdBCDLVmiWxSpqbVjWPpnaGP",
		@"dFEHGmNlIrPUuWTTgB": @"ueyyTdgtzDWsQrAimKRsBDyEFlTcELGZzTAUjakRImTlnNmouKhATPjKxhXhoHiyyyQqasULjhXYyonoVkAphnkIAVtZYDGNILaDXZCMfFXAmDsgYQIRvvayneVX",
		@"hVHmdOHQfkeAHGu": @"vfntIumUEfeTQQDITUdVWhrbPByfTqYaFkbMjuKbtHmijIGKgkufmHTrkEojToIgZADTwOGQzkUBTRndoXSzrvSraXbIdRraijbClECvWoPhxfE",
		@"oQsclCvTUDQJPgV": @"jITMtOSKzWxwGoAsOhPXSiXjoHlPjYSkhXLrGGlyLcLWbVAcfcYzJgQnXjkQndHxoJOmWJYAKFHXgFwPhKqxspsHbSNLXuDeejNxWINigGEWYQAzzOxnesSVaoaouRCFkge",
		@"uCylfkGhLGmeitkaKp": @"IyrKKeyphAXbyoIxvAUlMaXyBSDoyDInhiAwnutumEGqEOHgrHWcrKrXCshPOoIxdLjolOjxgRQvUAjZdIuovzhIYUEbhXAGBlWJIWJR",
	};
	return CtrmoACccvfNMp;
}

- (nonnull UIImage *)UiztoLDXBIaNVanrY :(nonnull NSArray *)OZMMZSeggXjnnrSE {
	NSData *xQldlfmbiXQyFCICM = [@"HOUwwPgXxlqtZwUEhfPOWTxNnccZzAwMGJtZwMyPBgAMKMWfPFQxApeRJHxFflVtKiGMgdrNndpMoqtYYwxHWjDKoqqNtuhvwkuyaTbCSYmLXwddVS" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *TkwcdriQxIUAZ = [UIImage imageWithData:xQldlfmbiXQyFCICM];
	TkwcdriQxIUAZ = [UIImage imageNamed:@"QXwBvxbTQrmJgqSIKhsRqJndyNNEthHOilOhzHdzjxXPFOGDwakxtMGHpvsmGOOfaGnSAFxjCyuIGycqWCcCIcyPyhqqmZiGqOyVquOsLUfZEsrghZYGTIzGaqDqGOwUNhQylRQR"];
	return TkwcdriQxIUAZ;
}

- (nonnull NSArray *)AXHRQpsEuTUuLxY :(nonnull UIImage *)SJjqWMSKVOA {
	NSArray *AcSsNbkHpXxhLW = @[
		@"dnlVqneHbqMfRxgxIsXTCxPHLbhEhMehADalbLGMwEHnGHBFEsAUYJOYKLJmqIzuvzqCMOyDieXysjoHuUNSXwzQlUIYcZBhUjzDBVrQLnpbOlyZbdcMKZcE",
		@"GGxMtbUVRXGjLXBAlwUiftRCzKwCyOsRjZdRzbERTqSmabavAKZSGJpTWVFLOVDjWlUwVfyGlzkaEwpTjAbJoTjRaVfDNmBcjuVUniZpYDe",
		@"mOfsPdZAKDRXMwskRWNpwxhGNIRlifiYnwFhGqGIMXxXEnrYitiVpBDGjyKbQmGhASXwdbuLyXWVUWCiLTOXvVmIimWQasybmtgMXk",
		@"yXEFisqUFhKqzgsBLVHOTremNfgLnbkrHOzdtWDichjzGEkPdkSsODtJClwNDOKWPTGFTkDrtHsmVcOXwnPeLgtDCYTMbZwKyPGHnBGgY",
		@"VxKFSpdWbtPkqIlcICgBtVSXILNPMbqwUJRWnoTYUKHJmcOVjVUKETjWqXpwdpdKrsbCebuctOLYYxAKpBscPFVlhUTXZjMlYXKoUuKXUpbQEYKQPk",
		@"WdVVWxMhSbBHWqckhLDLQkLUdPjQvdzBQltPStcUYWjFAhyaQJzwrGnBlRAJNRfVdfTMbzMsdSRvxkCaTjhhfdIyGFtOEFfiuaGUpZloSDpzIruivbGTsOCuLjDlW",
		@"GEqrTJXtrCRzTDYVUEYvCpPlxNAPGfufrEqNRzoMlMHDkDRbqUtyKVUhhgkaxCPMXoVeyPHZhaHzAwVHjLBOsQKSAPfdXJGRACnCVi",
		@"UGuiBDOjVfkqUONCrCxZQsGaTabWaMoMUoYLvojdUQRiEiZbkgmheOzFvqjEformbjXbGLuzjEHmylOKZvOkSqsJdWOBcIGDZUpsBinVyBqQXrOSEYGFSuKLeszgCMUo",
		@"sFGMEXFkfWIdOjHXGieTDgPBDLOJbfutDzvmFioKcjHWWkTsPKKEMuNzfoJbrzhXxQqnxziQuWXaEdYxscUDlgvqijliDKMthhdLAmJZXhEUUhfpqujYpRjhAaAsrSaaHiaUN",
		@"TNxJNlNVvGDqfyiWrMDRmnWHLbGZgVHNUDbsgUbtLGyAFricvkastIZhyKPEOdbjYmCLwyLyqjcvhRBEVYsGljtZXTzqYYthexMbKCVSxXrrwzXsufmrfxfTBOa",
		@"SFYwDlClZfeGRmxTCZpIeUUKpayIYsTmtDvBmXgrpCaccBIUrqpZvOEiFBakWzYQzdcENDAAgLveMKhzZqwkMNGblawQOgHlMydbbFyIEIckUgvvdxCgRyGyjIbz",
		@"LMHhaoXXoLomCUkYEnteQchbQvaAuSlVtKyNCleSXUibTEUOCuhPDyODNwPvUEpzTdERLiXdXKacyhXSffSLgSkEsbHzrseAgxFhiNx",
	];
	return AcSsNbkHpXxhLW;
}

- (nonnull NSString *)KAduQiaGvVv :(nonnull NSDictionary *)rQDnpcnPXxU :(nonnull NSDictionary *)byPMhhbPQBG {
	NSString *vptKxLvkCYuevuFxJ = @"PSLhojdAgSQVWUzUzeTFgZyqQDbIwYolexqqewKXOCeVFJhMRAkKlcptJOqeWzDrmIUnEWidRQMKuCcVgSsiwMBMVQaZZLZAyZJLNGMcIMLzCDPDXIHLHgyAcvKcqWfzNAByJXtDVZvpwZzBD";
	return vptKxLvkCYuevuFxJ;
}

- (nonnull UIImage *)RMsZktVOPyfjdEx :(nonnull NSString *)aCpbSMhUXGJcSKGQe :(nonnull NSString *)ZoatOevuKdMUEOWTgOi {
	NSData *PPHJOCmyYh = [@"sjVvGkJYMKwcfMKYTWzNVHHbAemlwTqWELizfVqKJaDLoJLfXFslGjccXPgrOhkJzJWCePAPghvnFVQRLFYiKdaxvRWGSHPeEfJQPxXkabGRr" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nxghUwwOboYZvCO = [UIImage imageWithData:PPHJOCmyYh];
	nxghUwwOboYZvCO = [UIImage imageNamed:@"iaBcfKFjgYMuCHHgGzVilexuIPmWGWvmkiIbkiwpZrcxltuGKlFkKHXSXNSdTxcstcXsanshWpobdxFxolSWXaKpTfCeVZVdaZoJmuZhtDTXpdYwIr"];
	return nxghUwwOboYZvCO;
}

+ (nonnull NSString *)LSHdmFlpNcg :(nonnull NSString *)qpflUSqxeTUvKo {
	NSString *CcBDPgyQPIClKppoNk = @"bSkjUOWFVVFMlcUGLQqWmbYcKEPYZFDMvzhbbvZoRTUuxsSPWTDzKProANXteoDCCXyOzgEcVLMzHqrpHPtwxEjwGwTpwjDCKdCnPFLPkcIZGXNKvWzGVwGkHePVzFvhUCHjAMPyxWRGACOZ";
	return CcBDPgyQPIClKppoNk;
}

+ (nonnull NSData *)qPGPwMaDqdI :(nonnull NSData *)buyraSnvPFcdsjAINz :(nonnull NSDictionary *)cxiLjjkEMKZOdk :(nonnull NSDictionary *)NbKutRFUEgRyFMYWQ {
	NSData *ZRaeFddVKkyQZv = [@"fVjVVpwfXkKJtQPabPRakoHjFDGzgqSlnGkMtuuPnqrlUaCQkOAIXbKcGlEpatTQySMmrEpwMpcVjoNroxXfjrNGLMIwwuNgCzeBhgthNbRKLn" dataUsingEncoding:NSUTF8StringEncoding];
	return ZRaeFddVKkyQZv;
}

- (nonnull NSString *)PMIjuOWKzaOI :(nonnull NSArray *)hFTddIMqzCH :(nonnull UIImage *)VuOxXYdzog {
	NSString *ElFFRMojZNEJZeh = @"pIQqTyetvdEDZGwDdTXRsdhxGrOOrQYzyoYNnFnmUovjIkvpYZvojCwtvynNmxxlPJOnHImyQiumKUWWJrpeTBXFXfZqfhYxVUEC";
	return ElFFRMojZNEJZeh;
}

+ (nonnull NSString *)dBcGZXwtFuzlrgN :(nonnull UIImage *)lOqsuRLNqYvNYauJ :(nonnull NSData *)UzivqNGzOIKqUqN :(nonnull UIImage *)OomJzDtdcWtFOSqwnMD {
	NSString *ehiPekHaSGJFMzEC = @"grytqxSycPiIImCVVqgkZRNqHlmSTtFVENKZPYAkuyxzkofmbVysVdZttpEtItjtBNNKqNdgEtzXJHAyHTDQtuYbzYxpMoLaJcjFMQsUOVbYJRRuyDNxzcFhQuykDr";
	return ehiPekHaSGJFMzEC;
}

- (nonnull NSData *)ynUhDvEfgsfSOoK :(nonnull NSData *)AaGsksHJpuNUTlufNJ {
	NSData *xUJQLceVsrjIUsgk = [@"zFzIEGdNbWGgqNISsHGtszfrcrHtCpYRoDpbRaZwcmwImerazdbVUsqitdGYJoIWNrwIIzrZdtKUROceMnZIGvHSrFNneaRGPqbrLrpVZsfrnZRysCi" dataUsingEncoding:NSUTF8StringEncoding];
	return xUJQLceVsrjIUsgk;
}

- (nonnull UIImage *)FGZJJqrGmMRFQE :(nonnull NSArray *)tCgTNVvrFHescV :(nonnull NSData *)rMKYLFGRDmtAITsAGI {
	NSData *HnFeNGAGmm = [@"fQhADWqMDVmRwHgnDTLtXYsYDLBDSedCpbSsEIQEaKaDdYUgtdXtwtQVpATTeaOHROXaiwmhrHjFBJSEUDwuHqlnpxmnuclRywJIwaJggmLmmsoeRg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *PYMOzBMzqKMFS = [UIImage imageWithData:HnFeNGAGmm];
	PYMOzBMzqKMFS = [UIImage imageNamed:@"RuptaFriqjpvjvkJpCEllNgFuspJJDKCaGFdoiKhvkGzRNfPBQvaDYNzsUlOXawXbJOtQMQqsTEwTjIqGcckFYVGgYgfflmtdVHQOVByqGxwSqB"];
	return PYMOzBMzqKMFS;
}

+ (nonnull NSDictionary *)sttXRQrfKwlHTFRcYo :(nonnull NSString *)AskRanFETFXJQ {
	NSDictionary *KUVsVQSinZuQEDyW = @{
		@"hIovPTMVnbJ": @"BcRAPsYPnliktgqgTCBiUkjOfmCqAvttEDWhZLfqVZHKuWwxhGTNVQglXyHECliZQaAEqjYOkPoDvfTjiIQZUyMyDKmeAdUbEAbmDUMReRmSiHQOpRfrGdEwDadLYlzZ",
		@"RweGOpXAcCjCJq": @"cmkSJKFHOtKvSOIAyuGKRtzwVqunbUdBCUlPiiKuaiUltzwdHJAaAemjieyLVOftcDxEiFzFJNBZrRgkNbOBKcIYCGMUCcjdbkPoO",
		@"hHUSXSgIoQ": @"thmFSUeAwoTvcwLoOnGIAcmbcTMkoYtMVFQRkgIhoEFcWnNGmbOfWPQzqpqKNUAWAZTOBbajpmXuChPpgbaNCzDRrniVvKOBsdIwDmKvnjcNQosfbKTXFUbNFQNJmkGBYeX",
		@"keecodXVwclPmqtelC": @"AKzxYaAQtljXOwPMgKSEGSCSzDTJcGCMCKXoteYvlVycqMEIHeyCUTWIBjwigDdPUGgYgusZxziWdRyyjimvEJalTBUSMukmGhUNnbPFNSeRLCybLIwMgGPqRSZFJZHLBCnYBZikUyREmJY",
		@"afQlJkSDyVIgQWDtOji": @"wgrLFVItfdauZhVbhgiRStzyQPglhlrhEAqHtzNuAKWOXYgaMHdUbpCARsodWKHOpaBwpHbGuVODfTBGiUjURrCUdjrtSuUTnNCVhHKjTtvoradNAhyWRYTlXnXpxZNJFt",
		@"XOUTCyXugvZm": @"BthOfEkHcuGuHxNlBJiScTKYfpDwkMNIqbuTVCkkybmKIXJuonMwawlwXjTmHnNTvILkFWpbdScKhIxHrRDqZagHaGxTzqMtNddjSpuZLfaiOCtHobui",
		@"ZisShdPGmkPgHCzzCz": @"YawPZvQILtKXfWxQeTNzWqwZMOqYGCKqBRKaJvrfTUuGoKbuAYMVoQhAfjUsRdzahGtzWaUNHXQRRQZnQRJnWymLxyBHfLSwuFVIPHwUJNfoXPPOKtWLXBSSoOoTyFvLVficZnrouIvXjGhaGLUe",
		@"pNxBjUcjTFSLKt": @"LoFwQnbqWYZcAqYbiWnQTBhIdGvnLicgZoDwPPBodFwNtdDqGLstFmRGtQvKMiPFbyMAfFrGkhOgYIPCZKuOPEruJZOnlzCALgbLslGpHAUZjRJKbhQrM",
		@"tbstrGTmBRhtFyZUii": @"DbuRCnWGMdjhGbeprWLmXTMpXYOudkWVYHSQCMwQmnFsRsPSmlnJvqMtukXzURUlYnbBPYTDrEWeweyJopXrsigRUspArAwiLDAZdIocZk",
		@"mxVFzKJMoST": @"ClvrHvxpIlrQdoSgUVBqCrfwaxtfjzbSlUZNFrkeRrlrIRMhsPxEkFoWPvrdYtNLlCeGwSlWSGDGqeftpbanwgrqRobSLammxYOpotLCpKeeEfulKYS",
		@"ockPRhVdSpOvfR": @"AfSNGfQpvYnFjLSXwHXOIrZKeFSmrRzKHHZLsMmbFVfDyzGMUWJVBHPHwTTdpGMHVSRtmxmzHeqfCyVrOysIlBlvSXoBAXESNFQwtPwUDshiTIhnDQIkRAIoMurfRSEXlUDTPBD",
		@"uRoviITRlntyQ": @"BcDooRmIcchIAElyJzwCdxlabxveFEaEwGvjHYxxveNoOSNoCdeVzEONiTPBeAIzReDdQZkZbAJfcIPdcVnZJeECfQkyGrAdTcCybhHZLfoDUEyOWEgjIskHiTfgsnsiHxlmQxUjjuOpi",
		@"maGNFFcpyNTRQVJHTf": @"uvgSDmFPCfmqscpiMqiyDARptJqnTRgyDTTkDdcTaNYlPQewwhtvLHmjgxerqIVtUKevPzSBcMgxAeJFboGAOqHcrQnotNRMxyknJkSLqVobOK",
		@"kGNQPasgWYwR": @"WbwecPKsHCmtaxBqoPIwLDDgYRwgZSkpkGRrxGNtlngrlzAitqXQXFkihlEsXOubPWuiwhAgwwznXhhJlpZNqHymFNpeNcPKXtHgFYFfsURFVmNJrFEyvNrqyNIXhmQWlgEbTIvLiuBtAFgITBZKU",
	};
	return KUVsVQSinZuQEDyW;
}

- (nonnull NSDictionary *)EtgoINgrtcCGsmlX :(nonnull NSData *)MxRWEpyWsaLMYO {
	NSDictionary *jzeqYWjdBCPaNhFoP = @{
		@"gIDndeqEfKMMk": @"FYFuFyYtfqUOftVATrqVYPLDtjlqXsdvVxbYJclhbBcQjwFpAtFAYBLTlqJJRnKPpHdwxEaAfQzQrnneFEHmFaTEglvvVujvbdrbEmfrmBOpBreTJIu",
		@"afZJWFgncynEYu": @"BXQxvbJbtFPYvxiMOjNuCMlxLJpSjJPaKGePtyRvGHkSqGBsXqGABcHcGHXXxxOTuwyQdKQylzIXhXxisSLgUZiifYisktIZZmFTDPiWdEBlZJSUPRjMaBLtlWJlINFXrlfmMdGaD",
		@"ANhPnCXPbTrF": @"zREAYzOvSYMWjeyAtrcscRcroszBciifjywqHRWBqxMRipRPYqgDYfrLUlrcjcvrdsAlZCrIhhgnwxNSBtpUlSaDtORELibnrWyCt",
		@"IykYwZcPkLrp": @"reWjMXOsCFzopijjMesyEaKjHmELEwYMyeDuYxkfgOvauqRBCOFwnyWTOiYKzptVBgttdmTbYzLhCRWuwCblogNgbkieBKAggoMMDoXqXhdJpWRwcPcHoGtSAamPqObhNRgdGexXHTzSQAbAZH",
		@"uCDKrQgWraNz": @"PMFlngLUgYpAjSjqYFQcphIUanVGZxJutcfdJzkNmROdkXoViRkngcihlsCRYZyKRBQKknVIXGfABOmMDggKrFtfMhopugMphkgalUYSkuKsgOwmqaOuGljYhLM",
		@"rIGWJNosOWfBpQZBzT": @"UsxFBqZtPnoSEraWTkpJoLgumgbHuvaVfZbDGMhqAxXQcnNquxKmcnGZigQJHaVOjVfNPTNmZWaeftYHwZClIYNPLFZDZxenqPuDUopEXYhxJEFmBfAufWFynBzKkFwq",
		@"BZnNsaCGrMOSM": @"roofHirLZtWFkMIlpFoBrrHcpTaBYTvEPyXWTpxYbjjULnmVsRkToMBEPJngUfmpHOCntTriCCGIDJBfhAekNOfzhCvMfTKDzhbyQrmrmXsbKfkBbBTT",
		@"nMHmiaLlDq": @"gvyGLlQWDowFyWQMCUJztYbiLUjNEHvuDEXsIxRxqPZqwjuidWozlJuEoDcChWtOuiEDtQlwjHscoJBZkzfmsiRBupwsotTFncUvUPDDYlNqXfXqNNpbXEugWqQKreigwSJPfeTHwMjeUJBZ",
		@"SgWJKNoGUU": @"TLHipgwGeLDbyTblrTUkYiqCwgmquzocUdJfQhLmlVSSkCNovcagkZaKjvzewYDhoZAOSGKaKoxMTsKVSRAoUgSgaAQfQMNpoETwnndTBQOgwjnbantHiIUqoeauBCACLepK",
		@"bACLsiaifjo": @"XNyhVUjoLZkWvkMmrUSfeNmNZkRjIvqSEKOeIswAaTJYKNpVYphNeysdnmKZOolrRpQijEaxpVmqQnNxkneOMhFQXgfKoOepiTNcJJbTEAaugsHOzgcwN",
		@"mCRNISMVNSGpusyk": @"XeqwrpTOLtOPYGBUXncKFDRwTjWrTAibmJYsdTEvKEdmsoBHPSmcuDPTeXIrhDSsCMnbEFUYzpLEVxteALCOuqjjDGkECeroTCdbOHQTjSlLMI",
	};
	return jzeqYWjdBCPaNhFoP;
}

- (nonnull NSDictionary *)dZTihvIkFste :(nonnull NSString *)JaUjDnRjdFUiwmdNLgn :(nonnull UIImage *)DMbPEcneskCpEOh {
	NSDictionary *eLhcjccMiJhaFhEJ = @{
		@"wRFhsTrgDjbEjLlS": @"qbgtbLsnBKUdBsvlUdNmDqEFfYoibfhBChaFkqZYwZNrQDPxqKUmKUBWSNGUDKnMhCyGxRGlUheNstqfEBJSTkZnYdsVKlgrEjFFOJOSEWtYTlfOOATvGBjBpsXHOTLtOtTlGfrjoUbn",
		@"rIWlUsKxIGCqQFitQ": @"rIfEIIrdkOaAwjHNIUDDmtIFQLYMXpIxEksQynkUeVRawwKyiSHMUUGwnMjAElDekpfjHtfHvBSlrqaJZYrbrltLSbyBBJVJBXLYRNQjyXzrYgOhyPmWSnTZSecAEClQGlIAshqYRVUyHTWkxsg",
		@"LxJROihZUrLqs": @"uwHYRYnIksDYLLrMuWTWljWhWNiaPTKfZYYQRWuXKDCWwVJxdUEJNTxjUgADiAkFnMQqcdhYeuGelZSjZOcSvKDOVZCSshKuNvNRzrozmSzfjxofjUrhwjWJcxgxKleQMofOlOJxwgKGzmHP",
		@"rIlMuwxlbLjTJWJF": @"HAASOQBxzaVZzLTyfKvwgmaPaMXUSPGyxCHARsRgbMfRzqPyGFCiCMDBxbUZoIQkJLxkmhtBtekYTmUidDjmHhTzWkoEVsoAPdheZEOOZeEtCwatN",
		@"CPRStuNjPqkY": @"MOBxhOOXGknEXYVUjsyWoJLzBPSWanTPZRUYOLmQDnLLrYtwBkFZZrRAhSUDoNKMrIscBvaYnSIxxjMjABXqtDFvhAGrwtnlSsLqFPTFTZGbSTSXzETfMvrYbcGbgnQItwQEUkrjNJzRBns",
		@"UpMbnHMfFYgmAtIEK": @"CbqqoePlDWXXuwADJvGskSrBDnywJIAziRsMTLyDXsVpRKWBKmAejFTnslwhaCjILXxUdhDVYTpRphTIGjvhACcICETzTAZVPpAGXiogTkItTild",
		@"cnhRFrqtahA": @"RLrqSHbPmwSyszcQaqvsdzBkKRMeSUXmKyXkFxWnNKeMPWXqUSqZJADRFaYSnFcsPrWhXIDbYEIkZPPmKSQVdMdeCIzplzgTmrNqntVfvAglfoLI",
		@"NzCNmTRkEFCBbFoDSCW": @"EdFgXxAEUQQutOZeUvHsJHUgFEoHuPZBBUOoIfBgCvBuXBxpjasLXEILpdeMvXMUckZlxYeDRQNmFBLjtJFsDiBJGjKaXQokJFCEZKjIuRZjlRSaxSUGfyWOGyqwuQmpM",
		@"ucSxHtYPcF": @"cGSsWjwNKoNRkpBzogDhWDpUqNaAZSnDydtZOqaTKkEJMaulzUMCYVRVUSdkAQuiRHjNCmdDPPNYMuDgfdbExFpcxxVOcAOiucyA",
		@"QPHOdpUOXwQSH": @"tvGyBWNBvDMhACYZvspdhbgQwynGrMNIeMfPdhIdXJsPOJfEUotphkxNSZPDVTmlfXFHaMKcMsDhHDIyUWSHmgaIoHgEwqaBcvlEcNSOtYWFo",
		@"qEBpdjzhNn": @"zOZJODoAAxdjVqKzBGvmSGPdkxecYLWJztoucSlioKPflMhOsiGbcXhVexOtwvNhchdnRrKKTKQiRTnlJFvvMlrbwtoybXhayHKjPHzJdcMdHtGMKhUF",
		@"kXBCRwjFuy": @"zONiODfOOHiJugorLlVVuFuioYyJHvhHqhWwHoMpaBsHVHGxGPVJprKDOhTqmMVnrHlaYRnyHaFfUEjoZctlrojPCnrFydzJKMIOQggJYlPQsThViUCXg",
		@"znFdPVnhWeRDZcIc": @"DBFtYLXplUqlijkSyyKyFVcDLFGdhSauyGRtsmxjjBtgWDQxXyWciitSlXKaVYdiQRKrPkXVrRTZehwMRurlMBxcosmwFdoPPToeacONIIZiUHoAiGcOqITMTGyaD",
		@"LGJSwXPixe": @"zrYJwRToWbqApLBQCJjqWPxVAmamIiweoaEYlwEfunqHUnRpvmnFFhWpQAcqyrMXejCQXjoCtTuIgrKbCYceYyaBQCpPwLsPHtgpZpyRi",
		@"HMHfGvppjRJ": @"FkuNvFbpjPoAEjPpFfIxXpGXHdljdGktdKvxVzRjnlAulBRCiZJEKBaJSgBGoQaNYSBYNgCfeudIiSFaYSvymdPUdeijBXGDHgWkQSRnysIeBBXbCoWKwXlrJHzmX",
		@"JBNZztiZGDcGrsEDKHJ": @"sKRVTPEahsqmnokRTierfswqkAvOzjIgPkwzxiYZzGVcoHVUIKDRiHkASIKKaKftpYIMJGxwcXKapSkMrJkZcEnKlGbUpDPqnpoMLOFILhwasoeWitqAEYIhiubDBqywzmnublvFWvVlZ",
	};
	return eLhcjccMiJhaFhEJ;
}

- (void)drawInContext:(CGContextRef)context {
    size_t locationsCount = 2;
    CGFloat locations[2] = {0.0f, 1.0f};
    CGFloat colors[8] = {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.75f};
    CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceRGB();
    CGGradientRef gradient = CGGradientCreateWithColorComponents(colorSpace, colors, locations, locationsCount);
    CGColorSpaceRelease(colorSpace);
    float radius = MIN(self.bounds.size.width , self.bounds.size.height);
    CGContextDrawRadialGradient (context, gradient, self.gradientCenter, 0, self.gradientCenter, radius, kCGGradientDrawsAfterEndLocation);
    CGGradientRelease(gradient);
}
@end
