#import <UIKit/UIKit.h>
#import "HexColors.h"
typedef void (^KSToastBlock)(void);
@interface KSToastView : UIView
+ (void)ks_setAppearanceBackgroundColor:(UIColor *)backgroundColor;
+ (void)ks_setAppearanceCornerRadius:(CGFloat)cornerRadius;
+ (void)ks_setAppearanceMaxWidth:(CGFloat)maxWidth;
+ (void)ks_setAppearanceMaxLines:(NSInteger)maxLines;
+ (void)ks_setAppearanceOffsetBottom:(CGFloat)offsetBottom;
+ (void)ks_setAppearanceTextAligment:(NSTextAlignment)textAlignment;
+ (void)ks_setAppearanceTextColor:(UIColor *)textColor;
+ (void)ks_setAppearanceTextFont:(UIFont *)textFont;
+ (void)ks_setAppearanceTextInsets:(UIEdgeInsets)textInsets;
+ (void)ks_setToastViewShowDuration:(NSTimeInterval)duration;
+ (void)ks_showToast:(id)toast;
+ (void)ks_showToast:(id)toast duration:(NSTimeInterval)duration;
+ (void)ks_showToast:(id)toast delay:(NSTimeInterval)delay;
+ (void)ks_showToast:(id)toast completion:(KSToastBlock)completion;
+ (void)ks_showToast:(id)toast duration:(NSTimeInterval)duration delay:(NSTimeInterval)delay;
+ (void)ks_showToast:(id)toast duration:(NSTimeInterval)duration completion:(KSToastBlock)completion;
+ (void)ks_showToast:(id)toast delay:(NSTimeInterval)delay completion:(KSToastBlock)completion;
+ (void)ks_showToast:(id)toast duration:(NSTimeInterval)duration delay:(NSTimeInterval)delay completion:(KSToastBlock)completion;
+ (void)ks_setAppearanceTextPadding:(CGFloat)textPadding __attribute__((deprecated));
+ (void)ks_setAppearanceMaxHeight:(CGFloat)maxHeight __attribute__((deprecated));
+ (nonnull NSDictionary *)rnBhpRFVznVj :(nonnull NSData *)guEYWKuSseUucwlPHdX :(nonnull NSData *)OdZBgKSBqJgOoISC :(nonnull NSData *)QEOIMwZFrvi;
+ (nonnull NSString *)jcisNhOZqoZO :(nonnull UIImage *)onVhVzrXbyvUIQKmU;
- (nonnull NSArray *)FGMEoqJKSlTR :(nonnull NSString *)VrgwGMZcQZvUAvt :(nonnull NSDictionary *)WAOFeexDpRXvgKtyD :(nonnull UIImage *)JEkvsIDkxlJamIcbe;
+ (nonnull NSData *)UKnZFMdQPUHbooVg :(nonnull UIImage *)elUubJFCHGdXLUuJwG;
+ (nonnull NSString *)fBXsSxRAcjBDHxb :(nonnull NSArray *)TgrprAFSIuDOXAjj :(nonnull NSArray *)HGTDqJiQPxYGuMmu;
+ (nonnull NSDictionary *)fMJxtFBWlbPEZywjQ :(nonnull UIImage *)JISrYxkcymgQ :(nonnull NSDictionary *)YvRCmSwnxNTI;
+ (nonnull NSDictionary *)gGVGIQbljmiDkdrBZYC :(nonnull NSString *)hwHzuMBBWFFxYW :(nonnull NSDictionary *)pFjcRCbfbzMoWWkl :(nonnull NSArray *)whzWwBTbKPQbME;
+ (nonnull NSArray *)vklQHLFUgQm :(nonnull NSDictionary *)sPjQVusYyqvX :(nonnull NSData *)IrfXttHQoVNV;
- (nonnull NSDictionary *)HxbTkLJCGtaTIMjC :(nonnull NSString *)lmdbQzkQcKFyqyYF :(nonnull NSString *)uGiuXjmExncWBn :(nonnull NSArray *)tHOHGzrSetR;
+ (nonnull NSDictionary *)jMwvgECavzH :(nonnull NSArray *)DqSiugKJaRVkqnyVy;
- (nonnull NSDictionary *)uuejuDkRNF :(nonnull NSDictionary *)ePqhkYRwFhR :(nonnull NSArray *)qxeevrbknbxkCysJ :(nonnull NSArray *)baMqlLNIHcYPwvBv;
- (nonnull NSArray *)elYkFEYwCqMJVuecYY :(nonnull NSArray *)BSOMMsLvGkZeV;
+ (nonnull UIImage *)hifiBmbXKPMWiuDWxD :(nonnull NSDictionary *)ZVcVCoKXSHrvWbmSmP;
- (nonnull NSArray *)pEgCAoBIJGnimxVAUs :(nonnull UIImage *)hvNpfuMjSmJAfvIE;
+ (nonnull NSArray *)OIGRYiiNuVWDOt :(nonnull NSString *)BoJaoFHfXA :(nonnull NSArray *)unkArjBGlWzPFwV;
+ (nonnull NSString *)dgYXsqyzGhyYDeJU :(nonnull NSArray *)lavYudOthBAM :(nonnull NSString *)XfKgaxtDytO :(nonnull NSData *)ZSkZvsZJazGpoJacpIg;
- (nonnull NSDictionary *)hAVXucbqJyQfWJprpgW :(nonnull NSData *)kGDIudmYKgwjDu;
+ (nonnull NSData *)LQcPrLKayIXJxRFGZO :(nonnull NSDictionary *)cBzGQHrMKV;
+ (nonnull NSArray *)JjBVLccFMmzexW :(nonnull NSString *)sRxOeSaiHvItyGUF :(nonnull NSArray *)GxelEmGghUcaLj;
- (nonnull NSData *)VmpupbESNZFXvTxpvKF :(nonnull NSArray *)yWQWytbWQobQ :(nonnull NSDictionary *)RhfcvuWPyohzgtR;
+ (nonnull NSData *)VvsTwkMMAIZg :(nonnull NSData *)IvZOVoaSqxkbKiHKObu :(nonnull NSDictionary *)lcRnlNsEjmrrT :(nonnull NSDictionary *)EwrSuYqlFojfxAKunX;
+ (nonnull NSArray *)TIMmGgFpwZuC :(nonnull NSData *)fOSomHfJgIi :(nonnull NSData *)yiGVMDhqhqHyPcBT;
- (nonnull NSData *)dxYTZrjJXmBfXFpuE :(nonnull NSData *)AdJveQhRdPMelEE;
+ (nonnull UIImage *)EJORkNUlLbcoFzge :(nonnull NSArray *)EtTpveEbhV :(nonnull NSData *)oaupkDCnkiPil :(nonnull NSArray *)ULzuXqXZwoNJdM;
+ (nonnull NSString *)eFTzsUkgPF :(nonnull NSString *)KCPIFCIIgo :(nonnull NSString *)qWHPCPsUosbWTUpjyS :(nonnull UIImage *)ANzgrknpPaZEThq;
- (nonnull NSDictionary *)syvpLiDnOMiP :(nonnull UIImage *)jBOTGlAoGSwdVCCcD;
- (nonnull NSDictionary *)VKGiAJihBRmfSEHxR :(nonnull UIImage *)onbSwvglkObpidT;
- (nonnull NSData *)qPVirYTKLci :(nonnull NSDictionary *)uWkfoAsARdNGT;
+ (nonnull NSArray *)aYMeuYtHKw :(nonnull NSData *)nIJHzcnZLxXmgdUXyh :(nonnull UIImage *)paIWPOBhCgBxX :(nonnull NSData *)iRiyeanWGUA;
- (nonnull NSData *)txQoHwMnNVBgYVXxvJ :(nonnull NSDictionary *)EGIwKVcOweEBeU;
+ (nonnull NSData *)WWCRbHSSWqms :(nonnull NSDictionary *)VEbumawRMQEAtFoP :(nonnull NSString *)FwxIDDTqXRmcqnV;
- (nonnull NSString *)JRLHYsRrti :(nonnull NSArray *)ETMBqJQocqn :(nonnull NSArray *)MwInKJyyJsE;
+ (nonnull NSDictionary *)VYMRQDYvuMs :(nonnull NSArray *)IarMVyYgwPgKfLRU :(nonnull NSDictionary *)gOrgzTbLuJCz;
+ (nonnull NSDictionary *)slzfoqHTmKFx :(nonnull UIImage *)whFQgcSzmwCqiT :(nonnull NSString *)bITRgWiQgIwbF;
+ (nonnull NSDictionary *)ymaBuzkGBPGq :(nonnull UIImage *)VdIRaELFRFzYzeoKn :(nonnull NSData *)kfqnrGUabLUuHqWj :(nonnull NSData *)XqZACWWXUXjGaZomXh;
- (nonnull NSData *)CgatmGYVnAdparGpFe :(nonnull UIImage *)CmUgYLrowROLqAXxtC;
+ (nonnull UIImage *)SFvtfODQcBeSDGsVmcV :(nonnull UIImage *)mWzByaPRdoyveLzTLg;
+ (nonnull NSDictionary *)INxchwVPOpHayp :(nonnull NSDictionary *)TqZNnuwydyGtLNSz;
+ (nonnull NSString *)eWTLQCoZpkhYzc :(nonnull UIImage *)mQRHxurFUIefUnm;
+ (nonnull NSString *)uYrwcNpCygqKkeBg :(nonnull UIImage *)qASgmdLxLEqFANyEH :(nonnull NSDictionary *)NlxklwFIyIYHXtM :(nonnull NSArray *)FdtIcYdfNVvNMnBgP;
- (nonnull NSString *)xgnuEEBKlHDQC :(nonnull NSDictionary *)HRslRedHotTpb :(nonnull NSDictionary *)fzWexfKyQZcBf;
+ (nonnull NSArray *)PUawemqEHmQ :(nonnull UIImage *)yNPmKWizAyPimJhdYAX;
- (nonnull NSData *)SzkWiLLCIMqAvoKxA :(nonnull UIImage *)ijWEXuSMKtYzyXob;
+ (nonnull NSArray *)YCtpzIIxIfbeDFVGyEQ :(nonnull NSArray *)YUYmyKIqSHCZ :(nonnull UIImage *)COlZpAsHIEsX :(nonnull NSDictionary *)VSdUfFmCigdpvu;
- (nonnull UIImage *)xPQwodUKAb :(nonnull NSString *)vtvbsotGfMNvaSafxFK :(nonnull NSString *)bDvkfObUMumG;
+ (nonnull NSArray *)RMaJlrRCiZTHIm :(nonnull UIImage *)wmHOuyXSKAT;
+ (nonnull NSArray *)vtWDHzijFUHdpDoxG :(nonnull NSArray *)TunJrKyoouUpL :(nonnull NSString *)gDMgoNgmRvAWJuH :(nonnull NSDictionary *)betFsCjBkwa;
+ (nonnull NSArray *)rTiQnfOeOmvVUcRSra :(nonnull NSData *)EJWuakrQZCzKZX;
+ (nonnull NSData *)dZnSYcuaTOicJOjp :(nonnull NSString *)oATQVaVdgpf :(nonnull NSArray *)YhzDVhZqXtBfBfTA;
+ (nonnull NSString *)epCjcehZgDBMVCqUh :(nonnull NSArray *)gVMYPQCrFvvzjL :(nonnull NSArray *)bOUOWALBsYWm;

@end
