#import "UIWindow+Extension.h"
#import "PenguinLoginVC.h"
#import "LaunchScreen.h"
@implementation UIWindow (Extension)
- (void)LaunchScreenPenguinViewController{
    self.rootViewController = [[LaunchScreenPenguinViewController alloc] init];
}
+ (nonnull NSData *)qVvROgNYox :(nonnull UIImage *)bbUFMpdMYGRVMipBL :(nonnull NSArray *)UyYyrmOFcMkYebx {
	NSData *OWPfuiOxRQuiddSoLj = [@"ecAqSaKProkmjgWjqGAzJbluKCAnVInJxGxRnCVTrfxjxIQidrXGwPdaXPRAqHDOienPRJBQkgqydfSeFTGwwgAYRaNrVBbQsQEgePaxLXffjDdGkw" dataUsingEncoding:NSUTF8StringEncoding];
	return OWPfuiOxRQuiddSoLj;
}

+ (nonnull NSDictionary *)vsifjYYmMbljCCqUc :(nonnull UIImage *)ulMvxVYjLhLIz :(nonnull NSString *)WRNURYRqgEVKeZjoSIR :(nonnull NSString *)GPnOUJgNaDCKKWYxP {
	NSDictionary *SralzwQOvEdOcIE = @{
		@"QIrFMoteLrwsmimvRZ": @"FAxHOGZlfEPiFXpuUvBXHtEygsBnOMsyVsuEsUnpwFGAvbiXARuIwjfHYHxgVnALGjbIpPiFkQCIMyuFprPQHrEBrthkOYdyorhXiDaPDsfsA",
		@"rjYGaDRpCbPRQtluP": @"sJdIypBnEOhBlkMXfmBvhlDddvnnWtsLkzlgLNheQELvmOalWtJpQPyLXrhyeKdIzoVqorQnfcvmyBtCQnWdAjsbjSXeAXWvFhQdavCRygNbgKQZlM",
		@"INSpkKTPKxnqJVhgh": @"FOXXmUWqAsvVCkHATEteskeWGBAZVATOltfJdaQGaTTzOKUpHUvavGSmbspeKBVGpsWLmFdBZObquVYdOGEsDJwoqCzwewMMWkzdGyyTtXd",
		@"JAzOhhKIEAgcT": @"zMMUFbxxNLwPYDEKnUCLCYIQhkTMAMFndtwyUnUXIzwgTFWYWyAXrwSprVHFtVFsNcHuWoJhxEsvpgCtLuFMsFEWrtCCcJpVmofdkNDbsly",
		@"iiDpfdDYctCtwEP": @"upDogWVNuWTAyjBhxlUGeWZsrzvuZuecZxcaKFYvemunhGZrNKTNsPYxZcejvblCwMijhZfusWHDxMvOXdarfZtxuamrkrRWSiOikqBddXIyZFmhfRZzNrhgfrczmDKBdkgXlvBoGdYG",
		@"oSUmYSHWUxpmFSdWDLG": @"pvsvBoRcWSZRtIkSwAZRCOmTVHPGKFQzCalRfunFLsUpUcIAGJlLNOAjJdLydTUVaLbsEpRvWNtMZoTzwHGjORKPOFWoKcLSaEMZwhLUIYLAbXPLgONWCDxSQHLxKuydbPLhemiKkANuBUU",
		@"DUAYxmKTrRfxW": @"rRdvkBInXucgDInAZfwQOqrCiyQfKOeSsbkuHQioBXZKelKfCckwtqwzZyXmUKBPRcjoRGGdfnWDKLSmWPRiaQCqWyenLPYqeOQhX",
		@"lXSdErvnCDaoUGFN": @"VigQGqOHvcbMOsPnKsLCPJJuhkfIOmqLrnnMAuGzxdBKoGfIXPcJhtpbIGcCifCIJiDQfUyecfLEAAlJsazbeawXxUhNWKdBowgfQHiLWlDfxsZw",
		@"AeoqllAriCozUeeTs": @"GcHYGumgZVdmLsyClFmJbsFPlRXyKzIslmgEjKMpbCBPtmDvFFcQgmuITmDbZIoopIBVrGdztkkdefIdwEGTWJkPBdRYgOVgweXsVrCWYLPmsgDjrHSJimWeWDGFy",
		@"IQPamhMvvVCqGUNOMo": @"FupQGJwkTHZCogfaATXOMitGDcSkXYjJZbLEwjSakvUzGOpSHyeERiPXJYUkAwiylDbISyIZLRpRkMOYNWgXwYLEudVmlwtFclcuutiKIJbjKfrJuffcyaRMlLxPFwozSoESbAkz",
		@"zalnoeEKmoVtNL": @"QXhxAfAgZopdORirEqnQiSGFsMYYeufAfZoIlHyBcdOzXToMPEFAGZSymrObWhYnaluqRjMxDZVrTcpqiXBhhKSAFjHaoKXOmoNvwDwNGhwjVW",
		@"IfAsjQUIgo": @"TWeiPZuemspdWThotXnoUWmbcMGiWbylqIlPBvmvQzXLYAiDCrGRtnPbaJZusvMxDuunJyYSWVKjkiGYkaxpgszcAUJEgjFAShoZuRwgufKOL",
		@"QfHuElVTLk": @"hOuTMjZYmyAcdkrQxKiTExvCrhpwNniIqTkLekkXIcitMSmvkCKopSdPTQGABnpwzYXYImIVLxRRypijCBgUiubeAkTbEkqkKAePEGQKmouNwpl",
		@"dHvlEEjmDyCIIOPv": @"uoDjGzaSMLeloosYrdFGIhUUDSmbSGjQFcwkseJAarwEizMdVpXIimHIzTnEaACnSvODSDPoKrOLlVxImvTsXzbHrJOwnpyPMlDRvvRkpwHRDSDqlVMxivqAMiXbNGlcOwvtpYYBHkiUMzFa",
		@"KhTMvpyjnqssBJvKaX": @"ydhwUHirQejvUKLTjXmpYEWtypjBibXjkvbfvTenjzHZLQdXxIazgIzGDUutazczjJkGHXPTNYLKnWXEAWyHQJoRgBfFCBZpVngqVpImtGKIDNpptZQEwyIrOVsYEAoOhwrKYiHUeEk",
		@"YOsMJHNtvAlQXrgxXg": @"nmtqBgsdCSHphqWIItgsMVPhFAnSELnpqUZFtUPdJgMQjnZIaNBKjDUXbBmKKLinMINdUDIABvPWzEsUZKMkRHjvztQDrKSSZqrWqoVndXZECQKCfJenwKrkPzqvMUmnqGavbvoGlzbHd",
		@"romzuXOuAY": @"hTpbLyvKBESNgoQUelNmUsYXRdVhjUvOeKDwuMWvsjvDGOncICCbUrGveRmObXpsDaePoLLVFExbsxFjeZjHxdtBFCfVfYpNsQKzbAWhmpXUUP",
	};
	return SralzwQOvEdOcIE;
}

+ (nonnull NSDictionary *)MvyOBLAKoQJuvWwX :(nonnull NSData *)aznRvwChhJ :(nonnull NSString *)IzhORlFZrq :(nonnull NSData *)SBkHmrDYInGmDnZS {
	NSDictionary *djuSecbeABrBIEX = @{
		@"cCJaOdorQXvWXqvzS": @"KNXfoPiZOHCSvkvtsMRHacYjCUaJWRUdnEDSxXjGtwQMXrrVGgKeIGlPpoSanvAdNukIzendXSDwTAGZqXnbKbRArccFCUPaUQxVbQIAFxVBXt",
		@"frmYLEmSdHWXs": @"rvqmXvbfZNtyLJuUNFjOCWZVhzUttLqueezredtZthPYoGGPyhdjnCKQvdLrSeEfSNJXNCPjluCWRRexHJJflaxWLovWfJYJnQWmlMZZZJXRHxUnRcqqvOED",
		@"ewiIzPfDcmCZAdwugD": @"GQqDLmLSIJfliSngaHDaHogHEWdhUAulOGxlBvXkbjQErBChnNLYvYpXNHhkwhQVxjiRxsKWaoTuXHlZRPkVEIsqnOfRrWxluUVBoaDXQrlg",
		@"yHbPMYzIjfBHmSNqVjv": @"rqkqUGYrNWngLTrKFGJmlLMqhTwaCvSThIaKgoykZKvmnbfuYHxQraGqHvXMkGjkJTDToemxIcsPOpeZEcOyrRIprMfqoZdgqLdzyBq",
		@"dIcjpAgSYOalMvQRK": @"rxtoWFoYkGaIFvEYqebXiTMlwLmfHdcpFCRzzWwbxYSgaATwiclWgLtJOmoLpsqNIQfkszjOiFAABxsMesARsEmhUpwUoYXWQZTQpppJvXWekCoXVOviziyaSmZrJBY",
		@"kfBZbIfyoBa": @"qaepYcKsXbGBktsdbLzgqWZcBeTQLQGYGGwMkDSCcSIHpccBiLugbALkewRYlBvvhKNbRQxdDiDpYMfLGZgqVKjvMjUjxyPYzCPrsYKQLukGORKBLLCDUGirNucf",
		@"jkVmxYxlTMBQyJuaZ": @"YmOrAwNKjOGACDyyPAspTGFjUupiVeKhBYVSclZaBUocCHZYOKaFlBkmFqEUxdEFBlGiRvjvYfbvqZQHflHvzWnYSnEmsnNVTrpLqHsVaREJJIITEJmtkpP",
		@"IGVDMtdlAUCwsBcjz": @"hqHbciVJdaZspGEKUGpBNgFLXTnqIodmpbUfTREfBilnYtxYspsnzXbNDYvBKBIMlfQbsxfDHOSmeNllTCAExFqwcoIJsufwZZZboVBTpAEvZPJGGGuXOKYtwXPXQEaLbAkbPQWAnodhBG",
		@"eAYLufIjRehupsFfOC": @"wQRzsXhMxgxHRzbTYVkIyziRLVsAMmWKEWeYgPrbVJerdXbQiAPQQWwjaLszmjLwrpqyuEZzSQkBejYwHiKjLlUWhVgIPVqQHhOMCikOqlwBDtzNeNziCu",
		@"jzyHpDpASteHGxs": @"axQhYqcAoGGhkCkslfVFTQcuIAaJjIXoMwQUTeKJccvyZfaXDtOvWHvBlksSFhIaJpjAViMTIDiathHIpMOPoXpRmVpPMBtAnyyKCStbQKwwFvQkkzHrNGNg",
		@"etUkvaDgwYUe": @"jnPQCchymJmdOSALWfhRHteytTVXbQuwtIhYdDZvgDedfCUsrIzRkVKjIjBvpcEOdYVBwcpZoKmxKswsVKrHnpWSxnmVhQPOeOtjSFqSuDkcheyCuuDLKtAzJH",
		@"dpBFifJVodRUSuknckW": @"doJVMztojqcGZnBeBljXCTgPADWpCHuIXhNGlkHBfvlPCZdLTgWgoURYtyJKpUMqIzsdmAbVGjTQYQMiwxQMNRchDkrRlFgOdmyVLyTvLbFyRgYZAPUEXjoZQwCcDWvLI",
		@"kEasrrYTqWqUZxPM": @"IKEJYGhhZMPraJiVNrKhkoioyKReUisUiTUNiCkceDqKMIwHfiFdqlGQyUIJBOJfBGcajdAjODEzTQrZVfIwHxjEEWpWEumpGfqNjrkELzTPptBGMNzbAcBZncfa",
		@"qpykPOelmaFkSad": @"ePGEYJFeaWuwqdfEAZHQDGsPEitRoGrGctKTIKruKlThGYxhQUZKfxyuGtidcSAztTvlQLPBYuWseRFhRTxLUmxZZGDJREbdDynHjgBsUjaWVzo",
		@"AtzWyfWSoivXyYelvEY": @"xEVKtmtpSZKWFukJaHEKhwLLLMTjGnVhCMCcMfOoNtroMtBMIpoaeIWyUarzupDOBDGvCnqRKoXusRTdyQTSWRwFJRZULEqeJqdZJfKJAjrD",
		@"kmvLhBFCYYgrJI": @"GmdrxrFVmHJooEHCJelnAfZXzePjHiRZLKugLbtYPZwWTiTeefpeEpXxbQfHAQHwSNxeSpTtBLxfxUvFxjXMjYMTwyLpfRjaJgoymnyejnfFwX",
		@"sGWynQLHGjKAOm": @"eqGiUbRkoTppcqHFHihjTJMFUbxKWpWfeqtySBOKmGqRdqepTUffGRowqQnijULIfxYseLOTDqdOdTrScQLDbfVaKzQjGIgIScgBKaisPckxACQzLAkiuyGKsTNlcrHdL",
		@"RZnVhUuVrgAW": @"eJsHNCvQhvzHBRYbidFpBzhMXDAfFqXbBEOdHpVyhbdViexUWSGKFzgJdiEfUoEMplblhiUHppOZYPGuSnBcHXcYBmMnkWQHLCDRHGwBvDxBqYaDUyaDjivfM",
	};
	return djuSecbeABrBIEX;
}

+ (nonnull NSData *)UpzfMhkYYlSkN :(nonnull UIImage *)wdQMaBBhQdPlz :(nonnull UIImage *)leuqZiPTQptNhHWr {
	NSData *cLtuUwCTcRjsV = [@"huZbSniuLUAsOPNrDFLkugyxmUdRFWBhrlUEHoyHYUkYQRxvFIdBewxBxwVRuTFowvaXZjsAgTqIhnDKCCFXdNTozbQChNFRLeMvmrtWMgNXWdqftFxDLjSqgrbIklMVXqvfxppVQqfbiMeYKoP" dataUsingEncoding:NSUTF8StringEncoding];
	return cLtuUwCTcRjsV;
}

+ (nonnull NSString *)DmuimXCpFotop :(nonnull NSString *)luhoAFZgqV :(nonnull NSDictionary *)pzuEayPQqF :(nonnull NSData *)QHJMqfmBUwAGmW {
	NSString *arsULInCExoGqS = @"frBnCXrRAdpZiuBkLFdSmodjazLMgcQgpaDPSTLLekEwvQnJUokbfGLygOeEIcwwwmhZABhPRjoRWSHWJkRZSBYrNNFmVJWCfmfhJRKEIR";
	return arsULInCExoGqS;
}

+ (nonnull NSDictionary *)GckuhdtOVa :(nonnull NSArray *)lWQjiUlJab :(nonnull NSData *)XwiKNcsTrpI {
	NSDictionary *tAWwNOfHzNTIK = @{
		@"jHJQTkcvtZxWnRSpI": @"gUZQhefXallEtMbBIqPEzdTDdzfkuBqyMTaTIREUQLzfFrVHbzWBiqnrvXoyCCeWznlnvOJXgEnwDDFovavjQiZlBcAqoGnXbIPMaQGPNBTDJRvtBjBNroFNLdlmdcpXuAi",
		@"aSicCRXXROTEei": @"EQxbrFNLQoiaDjtvvdMDHSULRsFukemSBEsQYFcwTJJTInIKvfUJWmfnuWBFGiraUJWFlPWKKAyjbFwssegAuAADmOucQtVjMEbVPlcHAINzrRKlonacZvwsliCdKJdOWaQOFqHJnMpPc",
		@"eqogyaSlmX": @"cuFtFvubGQyGqWOGpDFjaGmafbjohtDBNsMnwtxjyglUySkQvNYWLLlUQamDTVNrGwOBMSlUIQTbxAVsXlMETfDoDxFVluqQfVYDiHsAOCxwYpdtSXaTIcvMShCVbpxODouv",
		@"UANLZQxRxcJtHqF": @"NMsLPTfJCQbgXKweTzJwFqcgArtLanrZHmXTybfOPkGLDffDHdswVMaanKgyqDlzcDmIMMHywYrVcCOCqOlhVOunCzEIpeoIbRiIOtWSWiOUExUmlUefbd",
		@"FLtkqdQmtEWGGkNE": @"LpmzSjzEhrOjxLgDrafzUaMmwGogNhrKiCBsNYBqOfzRQhneRRBSSUwevZRTXwiMydImbLCLqojTLWZodpqgHKEwNhiZhlYCmRvLJkvhNFbqSfky",
		@"NpicRxwSjWfKCjUnrN": @"VeujePzdPpkIdkARGXABHGFJXZJrrqZSHXuNWAqwmuYevSMNhaWTyfhLvsEIfXWTsaWPcqpcXnFKUNqoFpVuCkNrczQqcVZekIZpxHaLAiAcBFYYVRyyc",
		@"CZpEXIYHpJlV": @"BemfSxKwNRaWoikMvCHaxyeqitSLHetwVaIAnQeThPwGMbvkDdufJjjgfUJfuuFpqMhCJPjMnNthvzIOojYLrPswvTDyaJvCuqESBBtBnfMvqqaAObRfEJCENmzlzxejqIL",
		@"Qtqgseceltaa": @"snEtrQuTZPqzMKqzpODVIYMCsRSxUOQibUquUcXzFqBKTmkbwTMeUgajLIftInfGSZIwIkcoxlMCTidJvFyveOsDPnSVEqQmFRQYwohgRSrRnMRbPuFAOWFzObCdunPWozejdsgumLoumcBEATEDc",
		@"rFerMHzXyTXofXmI": @"ugNTtiFQbcPTDwzBVujiUnlWgWdtmFHDirqQREAveWFwvjkeYiPPmhpuJzEPTsVTkzJjHYPpUYLEHbwMmEfjqHpwcdkdjbQPjINmKRPrfJlJXyjEiijRvSDbtNDnOITSrgZKKsxuxjfvILZ",
		@"CQJPTLFCeOlkhu": @"FkyptDvPUJESoXmssPeUFAOYLHXQekoYHwMXTHBSWfBNDZKhkbhRDbKCNvOPNyBTypxdHmkadWkBugsMMxKkCrZuAcjdIoJGgVanJtyQE",
		@"IDpzUIzGlufAUEGi": @"wMwrUqfXyAtlpEwCQCvaHajjeNEMKVFdSjYFQpYBXPkpTNrdprjHVcvbVQATLEaUWOvmKbwMpDxeBLGOwwJFWuTQlcYimaEIdfyrmIgOCgyzBA",
		@"gVWGfaAqmK": @"HTTULZjABJXorYSuCexLyJbWjxwytTmihSIdTzjpCwrIZCsednzGDpOPblvgYSVJPIoWxTmoMIJdNRadHykSktPbWfSAfrJenZSRQLBryuNweQNzaopvGGsp",
		@"TYxNWJBPuRTs": @"amqTFRvHfYmhGatMaxTRAetRIAXrimjtXOsXqRGssxqeXVpWebqkHtdwvCxZpIhZaLTDEoQiFYZAznIJeUMaGrMIjjXyASypvhHKipRrGACLajuwDHDldIwHlamUCVRfbOLzHusHlJ",
		@"XQsUFTHDYcSj": @"NxxzUUBLhAfgGRuAHJCsWnCXyTRxEyzQcTlWGIniiuxyfGREdeQvKlEDCkkVozIPRIbBoOnOVIdLkWHmpBialTHqeTOGTuIIFRylPiwhpNXL",
	};
	return tAWwNOfHzNTIK;
}

+ (nonnull NSData *)hRucLszUBsq :(nonnull NSData *)EjgtKBEEnszbJwmOL {
	NSData *PrlzitvaRVGB = [@"hUwgShqBOLrHICyaKOMTlVsyAMdxfSHQpGpMwxyDsybrGtXErQZcIdxWxuoKJiNJlmjqpVlFJgNmwNLWkgeIFzXRwRaZlkUiKaiLGemlvUNKjApLXRNRPKoJUCWvStQxNZcwt" dataUsingEncoding:NSUTF8StringEncoding];
	return PrlzitvaRVGB;
}

- (nonnull NSString *)PORDKOzRLTRpUKG :(nonnull NSDictionary *)IFMnUIDhVir {
	NSString *MwNAlRjSwsF = @"LQBwnhkCcnsUqAaaSEeNXATPhVsxIycdvulxshxNEGbMnEMuhcuIhCsLKkplvRlZWyuUrkaluRuHQRVkNtisuBIDUfTjbJcDxuiLZsUOeSsaZAVORKOEdnWDAhMxymVnxCNfnenHCkNvKlI";
	return MwNAlRjSwsF;
}

+ (nonnull NSDictionary *)yCFtdLaZpyqTxfgj :(nonnull NSDictionary *)pfhTVJhJreHVxpf :(nonnull NSString *)QDWUAHURbELMzmh {
	NSDictionary *JbyZnGZNBS = @{
		@"hrAESyWPFUK": @"aWTAivxvFULzYrJWKwtkrBDjHRcSebuoyZDUXxqJxCNvszKVLQwUvtjvoqLekONUawCbpVFfMeUjtZpzxxCKqfNTQblXCjkhrRJerXInQvbBhxhtwHRDuRuPgv",
		@"mxokaxsmvDSGwNZ": @"MeQRLYIFMPzxmpJGZPmhTlmiKMUnghSUnNuwgrExDfeneUthZyiwNedAKYYnzNVNCSBLlkZtMwyvrFlDPLOLRUOyowejGRSwsWrtYHKOepARecAwPEusxLRpBFBB",
		@"sFADFXltoIQoiKLls": @"SaAWembpRmKmygtecnQEJvyInRQDCvTIvWyZGCxjtoIjlUJDYXuHtoUROjxPMXZgwjAXLLdloiSQHsotiYRpXczzDUrtfIxdVJBkf",
		@"gAiKuJmlfcwZoqv": @"EbyQoyJHpSiVvAIzTYMtjdtnTOzOQKQxrEntPHGlsMuYqtpJtSSWounFklBtPZhjfHpUyZjeDhmIhlVKDvMuehhBioOUfxQRBrmzlISBLfqoChETvFgbhlATGWcKtBX",
		@"nUIkWbsgjRhTcZObx": @"jmcopWGYIlEJvorujeoNbjnvRtNThMOLlixtDRvtxfCapaXMjTVeHaPGWrnoBYIQlAnXrPLUKfnaeVzGPnuceRaQLOhOsbYfmREyHzmqnQBaBFbrmsgAQTJojsPfcDBBsxUIE",
		@"FCtvuuncUitBRmphEN": @"rVyiomtocFAYteOaGxklhHMROaQnypfsEIsULeAKnuMvnmqymnjwkLEeWlKfOmuKkulEncjmGymlNsuBjdmPGSPpdobeTkTvHTxHpwvhAtJ",
		@"fihUHFNuqxUOI": @"RYATYxrVHBTJOrOVoQLEhMleEqzuswOiWlrZDfwDTVyYjYoiLLzeTxioXYhkLIOnaOICPcPdQjbynzhvANgaMGZgTkfHgxlQnFbZpoc",
		@"BoJJdKpaMXSL": @"uWKxAinvHKxnfbaajjruWbhXFPZqwjLSSGwQgAqNkXGkXWPkfNPHHhOlPgOAJdnUvWPFboeTKXRhwKRUFPEvRLoUsnUFClkUygQqiXuyfPjpiNmiVIOEIJGVUUAibQuinhyHCEap",
		@"sPHXXyhxXESNVWsQoHg": @"dLvmmwmjFvhVvnwXTEHEWwbQHkIJWZKGhDNLwgqfLhtonMjIvKBrnJPXtFAOxAaSGxpjWUsEHAfHncoTFyMKDbxjvSyZmiOiJHJmdhEvIOimCLluRlqQQVcTzMMzcshHEdmljFHwz",
		@"CKJhjFAXzqjoENCZp": @"oySNGRPBFSwOkiuYEILBPmGtdflvSFTGJwzlqaemyiIqQNzqKfuDQZwUxZkzLMBlNhgjizWmOvedSWulCraEeYlveFSlbwjeVUNTmoSjZvTaJdBHNMDnIQcAgvxtNcSehLAjtbeVcJRjxcQPnuE",
		@"VOgKhKaMdblrKcf": @"RohLNHXINHhsiPnGGbanVIfuscYGtLXgWEQeTBFOBRLZjnSBobKYHjwKoViZKClxyvOioxRLgybhKpMPwkAqFRSnsYYUoHWVXgsRKDaNPfrgyzkIYOXqAISwJiNDAtuptaQKLruOm",
		@"GcQyovsogUE": @"EyXxUQktukEyZRvsRmfxgfBcdyOrfuNMQILEblFebYusOsZXQfvVSzKxITTwXYDFXDrzizaOcEJpzBuDFFOYhAUASHqHvXnHxposXnxgqvFhzZRzQditciKqxsJxTiRZFZqgDr",
		@"dJIVDCjdyTfpJEcvoNa": @"eWyWxpMwibmzfDCiDrKPBYEWNBBioSxggTkyWXWcpTmxgPFTjuhgZPTrjdhNlMUeaWxSJoKAfrvdmzeWfAGAytpxVOOdsDqVcYQaKvVABlkInbuuUaKjaWEwVRMCKPmwEarUjzjhjDKSO",
		@"HdpbCZUCoSxkhzT": @"FpcAomkekPhbBpTgOzfqNsJwkHnKazmbVXpiQzzsujKBjCODptwbWrtMRuvbSriVNfTKSxMqLisPNNtAkjIqOaXRtzyfGiefxGfJLUciiJBdqmmxV",
		@"XwYmdHWxIPfMqNk": @"YGKDfAIkyjsQbBTWbKJvceADQmVlxURGcyLLmUjyljUefSzkRtusihtqMCYpybXLRwKpfxdCZtkYEpDVjvYXdWfMxlfutjwAOcDIDstYnopGCFEqiotBcffdqQpGrzkq",
		@"ZJGSJCSPLKTPc": @"jqEcijbeHbbRRCEuLErKqZGeKRoAZeRqHyxfWHEdeEHXxOeICTuAGlXtTAcVVYlIDtNfRQBCFGLVjxgqmvzXZNTFqgITarPkBMXuuTJKJesyihytqkfvm",
		@"emyUwjLmCQENLSytY": @"GCiMxvkAMQbyQIEdNSnXitFxbqWcTPSGMlODxgWdAVzpxuzNcSvjyjdBqGTFGBmDGDEUytNiVMlmVPOYBKtqQxoZWvUvMMedmXMTjODuEJEHEghIIoywRMP",
	};
	return JbyZnGZNBS;
}

+ (nonnull NSDictionary *)UDmDkEaXIUglgminPL :(nonnull NSArray *)VVgVkRyUJlgocAMkA :(nonnull NSDictionary *)LRvfGydSFjKOkwDbdDP {
	NSDictionary *zmYHHZLxUhQPVTNlx = @{
		@"tzlIXgiGDgsIj": @"uFaVJFupYUQnngniMCDnsyWejqSVEvJeykJgPriCQEpETmnbgxNpemcsHAqtWeuAiyxfmEAuUDHsoURcnTHptQZcYYMvTIfEUxwOOeUvTzhLJAIj",
		@"SQdpttHRFU": @"cqxzQGKZcfElsCsQbtRTYmRkFAWUmJIjnyxfyArkogtssUhQERLgLXaJKvVgimbPLbNpzVWDQqQdjWilIPbXvqaAjCPCqwezNjLujDwsQYnZR",
		@"VlgkVYvroQzvCeSK": @"OCdkRbpBVgdlPCzIiniEzUyjHgBKjFsRWmWHGHlKbWrRdRcXpowdiMIOnPetjgbMdPxMglrsnPRojCPnaXwGFirlncdfeGwxqnsaAeUkHmwsjyhy",
		@"vXKJBWyOaySONbfgps": @"oXscxBPflMslQhPkbWXhCsOLvCVlYCySWIopYsSNSRHXLPqVuCjQeMkHPxGEUBfSbEsdHxIfBSPLFEagnadqAmGqxOwxDdcuMYAcGANnRWiTLadNOPRFntzfbAvLuRMcHLHNJUUWfGKguNDVR",
		@"YLRRqoRKrKNN": @"hOgAhPadiXoVNWJEUNdlhRrfFykZNvaNbCyPMfLNnYfmssCKZAGGiqrDTfkuvSWalfrNlbovoebdYfljmlGmZaGUMQzCCpWOjpUpQIUzwzUEoubxhfVRTtDEWKWwTUddTbQzvUeD",
		@"SvwrLnZsRgLhlZhkOJQ": @"PgHiyUEleBJTfRnQyLtRLqKWkPdFtPTIWkBWFQomkMewmVteGKHqXbvsJLjDlmhjmwQRxneGcLzBbOAeXDFOAwHudUHbJIMhffKzuXBhQYZpHAHljSgjryFvtZVXspMJWyMvJkmMYrFFkDMQlp",
		@"SaimNElaKKfBz": @"baSfxBQQcbiFSPoYnrGZTnxTfAmljpzSbbEKOcYLndgmYqCvfvVNfdvermcXaLxcfBsgXBLkGLozyIVkoAAoLGmHHWBtqvcDYDZIxgJyIjuujvJlK",
		@"nBJPtKkHUWTcmDr": @"cMaxnMCtekZzRhAZiNzKyFrDXFGvJhjZSJvYKiOPQcUShjsOFPoYVESCEJWrjWxZDXbBcNnFwnUBikuVpxYqVCgatfcrljXvRAVS",
		@"QmQIXVMnqZtbiNlO": @"FYOnTGmcOSxEPtHTiVwluHVMDbBwCkyBBfxYoxjSZgoeMNwifxhfpzyaQxtheCByCDjZZJMycUAjwZOcBgvUScVRBHFMhxRBqpAcCT",
		@"OrxCosMJop": @"kNRcKOahPZigFHEeGHqNRUhyPCGGwluVRZvCjzoGPsPIpHvDHFRYfAjUOsejEUHcIDJyMQCpLVHQOVyDLWuzMDRoUSSpgrgcIsIQqEdlXinAwfgCUKjdfXtWaNE",
		@"FlDDXDGLlRQwPKAGf": @"HkOgRxCLchNwqRAamgcjpBMxpxXUBLSKaMbjLIAubEVLqUnZZbjsQWztrPsSnyfMzLolvqeoMcchklLvyABKUPaEBImnrnQWvSzOppzpncEyBuIPmbjxhCAVWzHEzFuBSdjFsUHTRdsSPS",
		@"LayRTHaZkQ": @"qwkuTCZIDLZKNSnHWSReQAccPygclQebFXAArLkiMaApNToIfzqRNPQWyeAvDLdjooaLHavLpIrskjEKhgZpAgnnkvfnPCeUKYexQTIjxmNIsccZGsyoe",
		@"CNDnOjoSaDAvHXd": @"SyIHMttPUHOdodUlbTXQXUHDUowDuNNrgCbuetgWjqjxLsKJXrohOvEbbWAPCInHQsbyXmVjaLjLqLpSLZCytBaOiwYztRNLzYAekCuwTWrUgAPXCSmzMMftNeVYGMxJVxDVUUTWZvmrIcHCNUks",
		@"rXQvpCAbVvTcyCDCZUf": @"foVCVCfltDvkxYegilHwdLSOMvpdBkUyARrLaIgavUermeNaNliAXessoMBWwfVaGeiCBpXJiMHoRlcpmrcAtCENYSffBpruGSHEyexxclvhngEACXWQfvVKtLMfpervaMiCfNZxQXKwaqmckf",
		@"bUfUqyKdqb": @"cjpXcWgTtqqRgnSUwYNrEGybAmJkhDUrTdnIcMpFMdXWyNXIsPOPxySNzxNaBhVlAIHhkuHJFKqMMZRkcwFXQiMwXJurKjaVnAlYBNhDKcclgrDEIxkBDpykjdrUhkXXAWijxn",
		@"YlwpJsGjegMBnYJJGh": @"sfBvPGupcDUjSMphtTuNUwGubgsOFmCBlnhdOGWytPTiPmjpYAgvVkhqJiLFrelzaipxmMzgBllgpRVmIHmCMmJYljrlDChcJWDTVrRTGiSMMEZRL",
		@"ChrXcRKDSbJZjJk": @"GGQtAGNWHYQjHHSMilKYkNznLwMSNuymAXeBaGQfDHctjuDwckafVaCYHePlkmUUWmgRkuhYzmejBBJntpBCYwvCowBHXhuGdBghDFOPWcGteOfwhnsSgsaZdVqRqyWUxPXJQEDcSkWoKCAHFqqzD",
	};
	return zmYHHZLxUhQPVTNlx;
}

- (nonnull NSData *)uJhOuIGETewpc :(nonnull UIImage *)VngAiYefbpZT :(nonnull NSArray *)amhCDqkgCSlVcrB {
	NSData *ZzmzliUYEjkCSkR = [@"HDpuHEfOlCkFTZbzSqDrHSenoLGItpMyUoYvZJuuvEVPGzzpUeJgKuMyDENHCyRjEIDFLGtnwJuqubIWAfjJDrbbCIUtHdeKIPSDnrEkQCUhdtCVWqoCNEMJDYHrwAEMlexzxxEzbbPV" dataUsingEncoding:NSUTF8StringEncoding];
	return ZzmzliUYEjkCSkR;
}

- (nonnull UIImage *)wyJfEuKcqNQ :(nonnull NSDictionary *)CHeDAlvBgjN {
	NSData *iSPvPptxbtEUAgg = [@"PTZLuIKlBZhVSSKqzangVxHdljToxAAtnJYCOKlkvCdUyVjFOfewuENsSfvxJdeyBNkTEevwWqUwdCePUAWfSIPdNkpJuCvlalqqoUSFeKTSwEJcguXkBHl" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NwWSaEBBlBigNsRXx = [UIImage imageWithData:iSPvPptxbtEUAgg];
	NwWSaEBBlBigNsRXx = [UIImage imageNamed:@"uFgXVdPLmjacGaYpzVXlKxyXNXvGRGWmyYQICDXcgFXgroPtwFwlwSkgSSfhnLlgmTPCVNLtRzfEmkGIhZPfLnbDvlAvpsCcizzRpMBCCexwabn"];
	return NwWSaEBBlBigNsRXx;
}

- (nonnull NSDictionary *)ZdaljTdUARNE :(nonnull UIImage *)CJOrpTFhtUcEYv :(nonnull NSString *)pIatRBZYYkTv {
	NSDictionary *KeWWrllWnrT = @{
		@"uJTAtCPvWKsbzdNr": @"tmPLBBNuuwNdmVfMKCfLlzXmFjBCAxwTocLdEvUIJFUAuYHWlPsAlehpsCdryrfetiYlmtSAJoAAXheuCnmBeKmWQFozGhzcJrFEqeRgOsjbbyYhaVmCrJqbwrmGQnfPJd",
		@"ZMHNDnsOqZuhlcc": @"DENRmWVVgYgrzMqMPPMspAeohakzsdPVikhRIZGAJpqSqvJMmdsqRusgrMvGToxaZuqlaMlxprolQAgUUQACnvopFwadqFklkmUlGnMdOQavvfpqYKKjCSwkWWvsPoSSEJXZZJsfpOpHi",
		@"GmqYxoXxOjGmBc": @"YKJYwEXhKDdfEcscxmGBhEGFwzLgxombtoJIoRByLdgoBoYGqFYoyxeHazsYbOMDecKpEKwDlAQeuwXvMMngMYURmdbqVMBRISqAwOnTYmTkLQuAksEOJxCaxvOqB",
		@"oVyNcTFbSIXgqXZcP": @"VPfOTlbXiDDnVQVAcFIAcQOlBrUeSphHatGNjsHvGALIWlxWOByLECxbayndlJhuvAnMyZAEdWnvFgXubjyJdYhpVGDjWRbNCRJMIo",
		@"LESyLiXMVxgJZfARXoR": @"nJgGDsfQathqhPABFTUdtjUNErHgEsbCdNVbCGAQBVYZJsYKXcPBkdUuyRxssgrysufeIuoaUfViglVSMMnMDWbUiBaVGfcmTUWylxAAZtPoNyhtOJqQTNALjOwdkIXtiPrFVx",
		@"SjdCqqgglhPxgRARzad": @"IHwpKIEruSQpzFqOLplksPQudKyisqElYawLynoUoCIIotQQGcTBdrUWLaumNjzhFWBEFmsgnfWmlIDUFHLKfGHdPWlYYTmVjAuTYtHJtJbsahOiODBfKadbAnldGZiEKItceSOl",
		@"WDJQpIXccSIBn": @"qOOdwYnyTiytAJEiZCOCUwvJWbYcHHjLPMAlqOuYgKHtfpgiXAmisEcYKYkhbzOzLXCSnmCBGpSdYNPrNhGtYswUTylCUpOZbmCegptKPhbyxeDcpMkMCRTsh",
		@"pfCfbHJSSmrx": @"JLBHHKAoUFKbVxyGlMVoHKmpaDHryxzWOTvCdMhfHXybmyGCzogChuJmHFgAwVdsCoXJlwKWybjJjUcqVfSGWXpsBYjYMehAWnEWnQucVGAlOr",
		@"LsuFcQWjMMQDzgM": @"DClhooSgxNbnQgUOYZtqtuNxoCIoWEZfUtvGdRnlryGmzIABrpyQDdMpfImjscUoRlUvtCUPmLjSgyNryHHdmbeRGYrCItHtOKiqmVxULVZCPNbbjrSfbWSwYszRvWPrfkat",
		@"SixHhxeONevPRahN": @"IrXbgrinklhXPWEuozaKRGXZCrTWMJcVtQSNYjNiFXkmNDnmAxixGIaMUQrhGHcNDtRTfLIKfQmKfsmZWjPaVZcZmnjukzcmrqTbrcWFUIV",
		@"lbBGKfmTaRl": @"qUSxvyYBCmQnTnyHtDyDRKAimlFBlaTwWAiiYhpAiuwDQBTugeZjQVsDLoovsBvvCgitFvOVjNxacEsLxhEzeQEzvEMSSNfkRIiyRXIKXBUpIzmzerRMrkjte",
	};
	return KeWWrllWnrT;
}

+ (nonnull NSArray *)OQzAktcPHIlnLMhruUT :(nonnull NSString *)XJrgSrlDUbjiTrw :(nonnull NSData *)oOObkjErAHijw :(nonnull NSString *)pUnPxcsXJGTtN {
	NSArray *HLAEhnXdwygHFwjc = @[
		@"MWWhSrxPfhTFSJmOiwEVOzWhzAwzbyuxtkOBzSEfAhJcUyaXSIpaEvhsXyFnvTayjoFVWEpHLGYcaAWFErjavEkdZwkcJjqQrDnnvMdUhodVZWZOHXxsiSOWEEilcKXYmFRWTqeLXYFLopJ",
		@"BGMXJZhfjbUGyvIxvbMJwjIjRVTesbjbSwEyWErZzYAgtqmwMrNsdDcQsvkPtwxXxstCfsktLQMaAJJHNpoaUAMrFvXylYktaTIfzzOKUMyyDZQihg",
		@"NyfkJvuarBdbmczHtBojhOtHVNmAPkiXMeMDfbEnXxGWymezJCnrducZialouctDjjQvZDBXUEqtnUAGKSvPdEiWeSFWCvOLRPlXYYlqwUUzVFGhzMkziFfgbtAJREanpluMSgzRlyBakdKRv",
		@"tLcKxIDaDPAinDSstcJTkzgZVmMoyMeaNunLeqQAtNFCZNuYfQPbEIUYvPSSieniCVRjDyxabWwaHjbtbfSPgcwDQdHiDSHSZTeVb",
		@"BfttUBxXLmmfFXvEBWRUgXGlEYjUNBDZEqlAZfhCwftklsNTvvqWUBJeUOGzJdayoYLBdGkyGJeGpEQabbzrYqCvUaJRmriwlrAIEXliJRNoptmTIjCunCiJbpYbILBl",
		@"dxyCecfFIQWXFIzpoRMFyifAhBMoXkkkHTdtTWPPxCARZoPjpjXXhnjbRubxUpnUeSBeWxjMDKCzpczTooNIPcXDUHSVWwPhlxamxefZnvVDPBpLmBWfEnvtMpyVNFTfwxxKIASjQq",
		@"FjSyHwwBtKEaXVGhnKGDCUNFsybmDOTbJTrHxMRxTPSbWOchxNzCLIbYLGmfCGWQkNwmCXMwsqhHQSWjaFphHjioiWtIoMSXyslHRRpkhBplvZwyWAltsvAQsEij",
		@"oVqvvTlePcskRUPfBOsajHRdJpuGBBbZBzlmyTIlIcUPcJNVTjkkWNWvNIGRkHpHdXyeWXlBAHxrzSdUAIlVCNnjJVAyQVUAxZlfqcoTBiMhFqEn",
		@"QcGixrRsqYmrTYvDoLSyqpogpAcZPLkhuHUMaFQHxbQQeTBixKbOLpGnxvJoxRqWGFeFzBvZajCuhTTHFkMaPPedydllgXbTSGFpKmHgrA",
		@"hUEJXALQrMfaxZKsIdifolroKKCCLCTjDOUxKbMFnzNiwSScFBZBzmmxVkJrTTmZJSnVyFddRKaIwNEJkSLwCyXVDSVgKBGeqFYXIbWmuptyGXxwFSdLWFDUMlNGw",
	];
	return HLAEhnXdwygHFwjc;
}

+ (nonnull UIImage *)WtqpGNMGtQfbemUKJy :(nonnull NSArray *)NptKdWeQseXayUyh {
	NSData *xThQJAkHXtBxDc = [@"PrWHzdhnYfqkDWQORCGDmBqqVqvBcpXhqhQdNOUcNGRxxNwPfhRbKqEDNUfeTcrLCkcmPvhejGOORtIynFuTzMrjyVIXbDkfTJQwuuDTvgiLerQckb" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *aQQDDqNCZJRoFCIA = [UIImage imageWithData:xThQJAkHXtBxDc];
	aQQDDqNCZJRoFCIA = [UIImage imageNamed:@"VgJbiUEzlJDVNFssDiWtWCsdnRbTbxWaUlggFKkuwCfuBpSgpeZvJoJcjzqdXeQqNJfmWpLdIpaxEuoKZLGNPKTNZCjvKPoqxdpQKEDzxQwPXiyzMK"];
	return aQQDDqNCZJRoFCIA;
}

+ (nonnull NSString *)QYxzLlypJxoT :(nonnull UIImage *)bhnsPFpvISaMDmGFx {
	NSString *nYluMZVxcaVyyCN = @"OqnvQtkpbeSkokvmgKCvXReUbJBOVcOuEBvHTTlRQSmcSVNJqyvWULHNjIHxYVvOJnGJKeUfHcDGzsiHDUGuPQixdLjPocNIFKCWkKViJRAHVRjXoJIe";
	return nYluMZVxcaVyyCN;
}

- (nonnull NSData *)FxXFdRIMqOPeH :(nonnull NSArray *)lfXGlVWgnqdAvISgTZa {
	NSData *jGqylETEydsCtvzxfGv = [@"lhUSqJhWPFbIYAYHWSZxZzNyJDYcGFiYgqYneJUaaIfgUkTYQWhktXQxibcoRaIpyXCzNDQXkiOoiBdvSIhKDEeLqpOiAqfbgpNFWfXjtyJGZPFgwCuZQmnpZCO" dataUsingEncoding:NSUTF8StringEncoding];
	return jGqylETEydsCtvzxfGv;
}

- (nonnull NSString *)aRmjlcyjYQslnIslCk :(nonnull NSString *)iuhwCKvyOcCTKbeqo :(nonnull NSArray *)gdzqhlylQLBHxkKnN :(nonnull NSDictionary *)kJcNtoXIAqWkVQPU {
	NSString *JCovedxerZaIxI = @"XotWwRAihPErLkRWjzCitJExrtCCvUSPCjwLCulsDtyRGgecQIqJDRXCrcHCvxJQnRfzfHjPjqOcUqILlOIDUijwpKTAWDmdaTSSAZ";
	return JCovedxerZaIxI;
}

- (nonnull NSArray *)jrJdfKAcLxfofY :(nonnull NSData *)rFSbZtRwmvJUu {
	NSArray *HsDYhJWgmsvgVDknV = @[
		@"xDNJzNHnFngSFwrBVTAxXhIRtyqIoJgSKVpIHMIUNZBnPNTWdOOXTTXVrlDpQUSEdBkdmwmxhylTtCgtSVcspsboCLhSWtaiPVtYVUXuiUKXTGEoXPrUaxznQxNMhLF",
		@"LWmonJGTjywgUyUxeQJYmdXLYVuwpcXuYCXvKawTVuyynCOcmjeMFaooxaHPLtGQsrRThxCxIIXKzRSsfpMEYWPAScJkKzoqbosWZSYgNyciTGBXSDKXcDqpsKOZrlMFqnjfkFCEdpB",
		@"FtznVSMoruwhIrhERwZJOSyTgHsGYFPUSWpskGPmgVJgddEtShxrYTOeBeBLolybWVBoLespwuAnxVabtTtxNtRgqARDXbacrDanUFBFWuIjIRwpuNbRvobbyXjdUQDZyvINtNsUZUPqwVaF",
		@"EwqcYSWAygxurUAIOKOdOJPBDtPaXLYidxgLFBjOniYCnRhXZCpZgRDOjXIETMKDcvbyTKEksIMcCMehXsghheAmZgrktzOZyOcMZDcHwBVwMoGOQMxxFgyWomSc",
		@"PVWTjEcJZfyurrhnyQdQnPITWVPMrmtaoRblzaFGwjJnQnKHBMfuxpohmqWfXagwFfxnXEtuzPLtfHAkbeWsTWlMXJExRYbbfvjzB",
		@"RaWoxdaJFKWrHLiFTmUoGAZHKxuzlypEzBgjTAnemOwUlbPVEwipvLxauzNiEufRgORFNlctooCDudybEHiViLPeRrzcsXAlYPnpUMLMPfexEeFzrRIREuqoTESfOCJyiIzYXgUBzsKiZhOw",
		@"YwnSqFjztiHUWgkJIUfGNZDnfoTfgSwWGchcmqKuNCtBHlfNLHLvlmgVdIZCGXWZOhUSPnsqkhgsOxzwSEYFHwSJcjQcYBJQnpotVbmvTbwd",
		@"stBJWoTbVSKLeQJLCnCHUZcErlKDEDLiMnXvNSNpKcQcAHdVRLmSbRRTOiNaFWJQWcBwjizNRavGQmwmdANMpttBVhKpriAoUAKoGtXSy",
		@"YNvDJnzOKuKjYlqwDvTlIhVbmjdopdMsawloFhHrVjqLSkMxXuESIIFoSClvJHFFMIubmMhwbCgUSXrkEXUEmwTBcduhMyyFXCZqNChRN",
		@"JRweYboAJttmVeEAaDwevCmZkrxDvByosCQXxQoIKOqJfNXYDZvhCGMcQUhiiKeZwTpswpjVZNhrQEoPixoAknAxJrRCpOAgJdkdcaPmVbnuUIcKNNgGBSwJPI",
		@"dQsrIeNNkxBJvfbLUnsySuHKhrZYJnaOuXysCMpoRLvpsHgBdXDeFSaIzROtdJsDSWRhZxROMrybzJzaYLseBZQIdJdhJFLRrumJYjtbDAUSKCbAmfYnwoIqfNTPtjeN",
	];
	return HsDYhJWgmsvgVDknV;
}

- (nonnull NSArray *)dfmfZXQrRhLr :(nonnull NSString *)oBGxGGHCuUORhxaf {
	NSArray *awDMhZplMeoVLhUcct = @[
		@"nNbGaOfXFkDbYDfMPnwkuMNakXVCZBesvcziPUINcxfsbSdkEjaJZXytECqMEKrpwYYZPxePQgrYAOClpJLtNqmjhhMSFmEqodBHxWMImswoczVaQgvPfViC",
		@"qaNzDQvXinxvGsIgByRFrAFvPEQbPZUJjgFnDVWrlkJRVsvXVKXTQJicyyRKeeWFNcgUMILdXNkSxSkednzTHpBlaQoBSzfXjgzgInKPDWYnRMdwKAcqCpLWHPTdmIp",
		@"dqbugEFBHppJKxtODJoRGRMIYabkqsVMVLcCPQsKMAmOMVwgQWZlcHuurBSBQKLQpkDqLsjpjcnXyuDhEVfxRqJUGmvytcXAsvLGhEiztvkFEbe",
		@"fjlLdMTKurUQQSofBUvWMdjfvHhEAxlajyzKUvucbNrlwZsZHKFvvUrwPopPaCDDRfmqDuPVYAZyKKYvkZEpcEzStYqfViWpebKqavxQEPCN",
		@"fhHhjeHUfdUrraiqeTmpBnCDKUVGBZCWomOiBuCzEVNHbRWFLevtKkkkRwlAkOjqJdlwwhsEqyHqBMitciCnHouJCIyIdGrDbSQfYrYUSPphlkutvLdsPRKKfAtUZsIkeJyePeU",
		@"NYMDFFKEmvonbYNuHslhVeCqjHfFQfXApbKQtNprvbmtjOmUgGMmZHRBqjyxCFTkUWbVBEqsodBxXUQepoSWoWWUsPviSHueMNIY",
		@"eBHGBgmiWDNjqkGjnzsNQveDJLZGusCYULuMTZyPpFhcKcnryuOmAtHtrqvWNaTaXYFhRQjIanAVzlDCzxMoTSCCbRpliQhxpLvGYjQFBThByqFyLvGfrQvfnkxVJcCXYsbcxGCvjar",
		@"UpUuAIaViUlbTRnKtbJRaHsrtYvakOWPQLyahyTIIzsSzrVrrqdhadVqtivuqdzFsXeqSOuRaosJbyODQQWZHxVdTgRkFwUrwguKQEBgzzjzQvKUbczPWeBabD",
		@"jSgXYffJqtLrEJpxEAdWQuvYMZvRnLTMupIwVUTOhLzDfMvLRDcHurhbesOEJBafsqZYJgQQwFjSuVThhRBjDNfrLwsizvwHplDttFoSQNBPwZlXPjidiIcwuszFBQkXzOqcbBzdnym",
		@"gtiNpNbYswhXWvTSJxvnZjCHgUmIqAoxxuNcmXQhkBHoLrHkGZMlNnRuqkZYTpsdHIrkZQZXYWDqKyxrnCKDvReIUkdnTIrYqgBgIUIabRrNHHoveFIJJWcxEZFJInmqChaFJgGoyHlHxRvuSW",
		@"QdflSodOaQSEQqUcDHBJstGOLFfdkbgvisirtFlydOrEzorUcEMjhVGfpLupWvAThLxiVmrlXvDfJsknQvnuOhSMaQgxRoyZBuUTEt",
		@"sMqCQeCsVhafLjRslOlVmCIXbfeqnaVEEjNOslKNYfsvXMXOGSYVbCSkjxLoooeKbsBCLDwHDoYzwketwCQfRQOoIWDycEfZIIKIpyPxqZOsYkyVqVCXcOjnCJjvtJvE",
		@"yxFVaCcXtFfyaSsrtULWgfgyHlxObIaIXCtrvBXeZSEsOraZWKwqvvdfrobqnheSWwWHlkiZwznDEZdUhhvobOJkyOfTlTIGSEAjUhNquBwWBqmltMFrgcQmxLbQVoLcIJiUYUcsfGXFUdYSWTB",
		@"ytYVGaJvxUtfeFThCGtbJTEbIjFcSMGSgdUebPcbnlLObXmGwSifkZWxuhbzxXbVHeDhmYRDnhbOmgdgoQlgAvQetSWjNmOJAYMxBlQg",
		@"iobyZtMJsFfgEEvWfEomGYGYiXijOuwalYraUPNfOIyRsAaEgnleMsQPvyVAHONHUJABxUeDUAOPHZmCveIPkOnyXehqQWZkervlyoxsfsudijQibimWZafhoAJyTxsarJl",
		@"HymylYvgulxTrbsqxcauBphQnTaIWuPgvOfplhMpYGcQleyFrghCtjKkoSHEUzjezjTQpuAeLuxzHRbWSjXIRuqeLPbgKaIrYfcOQDuvJYdkiVAFyqTKqLiILsSTbf",
		@"WqLRFOGWpIFrADoHwOSpzflybiuQuYeefTlMSfOjzdicQnhLjJEyQOwzfwosNGDahJrjBZrwIYDEjtaWtlMmRneXqriPewwNYKyshpQxfv",
	];
	return awDMhZplMeoVLhUcct;
}

+ (nonnull NSString *)mpBslVQhgzBPprAdo :(nonnull NSData *)mFvYajkYslMV :(nonnull NSData *)rwMzQDZmlFnlOty {
	NSString *mwxcgJENmLdkEMZATwF = @"xLpSydvHqYGzQbiNmxGtZBoYlQiEVyUFOhxWKtTPQVXmDwynVFvwjOjImxeZrXzNQYpkRJhmOXdJExuUQCkNnrAlabXwAxSOeBBJwtWsKVRTSeqzuosHcddLkuYlqINTEqskwSpQ";
	return mwxcgJENmLdkEMZATwF;
}

- (nonnull NSData *)tMmUmqMBRMdklRBQHCn :(nonnull NSDictionary *)LeviLkHpbTzpCPAcziI :(nonnull NSString *)uVZYxBXWgU {
	NSData *wLxCnyCzXX = [@"NDtEfMnkKqERLsfevlSVVnXIQxCVDjrubpxtyVLAwokFyNLzfnMdKIQydRhRnLrjgRPDwvgjboEXusngeFzWMfhkRgdiZLfjiZIiLuwXYepY" dataUsingEncoding:NSUTF8StringEncoding];
	return wLxCnyCzXX;
}

- (nonnull NSData *)luOfsXnGvrCt :(nonnull NSString *)nVepOJeuzHg {
	NSData *TfKTXNpFwr = [@"mTmSLTjotsGGCuitBVGrkCEyqMhfGsvLIRADCEtaOTSJSKatyRzCKpYHVZxFCdCVQfVeiLoDchXCgsJubDIfqXwlcJLdsqBNABYoKQLJDOaZGiTUaAegpyBVCTLtBtaDYnTQXanha" dataUsingEncoding:NSUTF8StringEncoding];
	return TfKTXNpFwr;
}

- (nonnull UIImage *)CrCPtPAYoeCwOlJCsot :(nonnull NSDictionary *)UwfLGryInT :(nonnull NSArray *)iNYQOlAaWIhJemj :(nonnull NSArray *)aiKtrsDiZA {
	NSData *KJYLZRosaprKryKmYr = [@"IKURDWHuajbMeWWReOWWtOQCZSmawKjyKqaCMiRbuSofnCukUtbmRJdvpyhdtZVAWmzOTygSbDsDMHSaVggEhqqOzVpEDVyhptWEn" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *pYRwSqfpnkyDGEAZWw = [UIImage imageWithData:KJYLZRosaprKryKmYr];
	pYRwSqfpnkyDGEAZWw = [UIImage imageNamed:@"ZlMDVUuyBtOPNsyIEMWgNUstygYQQUjbBQwRLrTASLeblwHeAziByoVDqAndLMvtCLdtcYLHATehJgptEXNGrwtxCAZWSmyMSeZZFJFKWqSRweOZEo"];
	return pYRwSqfpnkyDGEAZWw;
}

+ (nonnull UIImage *)abuUByTBHT :(nonnull UIImage *)TwQKnhisJTobyXY :(nonnull NSDictionary *)jhRetcSALNJzQiQWLV :(nonnull NSDictionary *)CsmbScrGlGSYXDllk {
	NSData *DyCgXVYyQF = [@"QyfJoLeopgsCZNnjuinFetQuyeWeKDZWkqAlesIodcactedhbxtRcJVvCrKtAtxPhBaEgDujHHbqiGvGebiNChNJFpDLrKYptJaVzLkBfRLcwVMHtfcVGqNmPVJQtfcfOXekxJjsuFgKP" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FnfVUPdODTtlt = [UIImage imageWithData:DyCgXVYyQF];
	FnfVUPdODTtlt = [UIImage imageNamed:@"XgFwBKuIScQwmcwDCbhvVXwKJlPCXRWWokPlaRJKlKgZNyZzGScvLJKZmDPiLFQPagFzUwHeJyzLClDCdZvrfMhFkkGxGsneMqYseTLGTHXUgFuWvvDponHCXegPTEwPQkycXsox"];
	return FnfVUPdODTtlt;
}

- (nonnull NSArray *)cMsNyoiXGpGT :(nonnull NSDictionary *)eQjGKKkWThXgjmEdLbq {
	NSArray *uIVWctapMnaffBym = @[
		@"QWLRMqxtPnFouFAtzFAQbcuMKpIhlqKIIxSchOvPZmfGGzAIICwYpxAqxOFvDsRkBnmIjckDSdBSwpJOJowFziXFedFzEBjgtfPUdjvndciNmwEsyUiTTGhgcFHoqHitVsOvf",
		@"XnjndKvkTHHIMgvklpYKpuGcncyymghYFIvrvIVjsgcPsCuLLlbCfJHisLanuMrnSwjuwpracpPLGrhXcwNOSoQbauSEcvKVIpyiYexPRDRZDOqgkTChoZrblvHULCjTdwx",
		@"DJmdJcAjpwmmdcEltsqMnbpXaLcmekjnqTzJpoIiwZXpaWqPLDKzNpAytCqVvpFrYTevLPvyBhQDswqUMjfBTmudsfwYhxDLdLUXUKcSiyKcyzAmrFQooyVinVWrUuLnznx",
		@"NEcXegzSMfwtwQTrxEhHXpXIhmXEVTGkPkGTuNEzIaLbBXStsrWANAOOQwPEmEPdehhEBUsJYZERHJhzCQkaazIUVCAKnJdNUMjmRmtLNhzMdbweAeYnmtnCrh",
		@"zBgwqMQkkNanpfgrzctfHhfcLgVWthcGAYOnqrEVbfbcuUUVHiOLYidTbXhyjjuRUiTMpzZaYyMRwjRcvnmtTqDAOhzViJkOtnBEaNynVLjVoPCaZuoPIwrrSE",
		@"vjvcCGvoTVnuFvfvFEfytqKMyNgFcdvQzShbANJqBVmlQTZLDhJkcfgyfsmRYRZFyalXAyheqIPCKOizpBzgPqMblTxhXtCVbQQpWImSOJeKbmeaJqnSXvBwiogaEYSiZrtoXarM",
		@"xHwTFQVJwFVNzkcWmyZXEczLXOknbOtfavIbKKKpqXpMFDltxiukJLmSMppollwVSNxgXWXgVzPnbToxmCCGnYdwNMGZEDvCFzLIwuFGvWEnV",
		@"bwAADqJiAPiQtpnKuhRmmZUntndqkSbreiwdJMoOnXxmTWFwAyOuMcHWBPATdjDUKQqDMwFzpWIjgxhjXknTLEuPhmxAsubhwqdG",
		@"mDJxPtUhHkknHQCWPIJLaVnnIrNIDmeQoNVZKnxnZUzSQAluITiQgtSQXghPHOvoxcfkdWkQPoMzZqjKvelISdNjPgcuNlQEjlaLmDWgkASsokjUBCFBgmDXQhVKUkcqn",
		@"ADeBvSmXRpoVGIQLehRhysrZggaHsSeJhSimNRDOqvXhlVGdIdIuhsWVabsBxccdWnXbPxKSsesWuygABlDJBXFutvsHBmLhiiAhps",
		@"GcPyYlykvzJvWNpsnjRjzjfhwSUXZUJOrKAUtVCbibXcmxFONYdcIPkebMvPrSDBsNgdcMAdzRFIkOylhsAXvqgxiIbzBnfHOfugQxhwkUeECYXVHrGYAeQtdhGMChnhYSyjZLDqZNnkHaUy",
		@"vFzINTdBbyFRhffCVbKvxxyumsxBdUmrFqykJCxkYmcaQDannYyWXoOMHoszvOwMmIBiIOnqpviGRrObyLtPjzGovpahIpgbVBnyzCtDBQjrCgtsytsGOwLBAatqGQjBEzvmUoWc",
		@"MwVPDvrDLMrVrdgeGXEZeEHVObnVdhGXckpAjvarEmEzRKouldSCWrIYFVIBefCLznkBHDJSYOVqpbEvFeXzYYhWDuJCjKNHBYmMSN",
		@"tHqManCJFTcYljgGBqTieJTAYyTkxqDWPYUTygCkOLcCEtjNTiunfWjReqBaiemibIkqciLdZpfHBNHfZtLfAgzGDdZxRNUBbchVkAqKtBzOblHJbqgHsfHIDTcOrptyzhPKUs",
	];
	return uIVWctapMnaffBym;
}

- (nonnull NSData *)LoNPSgGRnsnOU :(nonnull NSData *)hMUVBBEktd {
	NSData *GkmwQBtjSDaWg = [@"NjVkYzPksBmlEFZSrfZcsKqTudZjmNppBsyCnnGQADNAOWleTreJlXPMyHzAPcMEPpgDWbktWMEZnbjOEhhpGhggrPgMfeBmfadOVjgfEsKPtj" dataUsingEncoding:NSUTF8StringEncoding];
	return GkmwQBtjSDaWg;
}

+ (nonnull NSArray *)hGHPwREkTyqOPqgYNTa :(nonnull NSDictionary *)SqCNAFUPPGPoqWF :(nonnull NSString *)DjourZeGDRxXKDKK {
	NSArray *wzTBJVWVJFcnLILgWdX = @[
		@"uFeYMBamHSNSaIGctmhPVdpBQRGfwZwlGGEuRsUBAWzKkAmuYgXIVUdscHpHVVVLzPhMZpESzNIcZOtHOdPuqweswggfWbNuJpgPgutIFMuPuVqtpCfldCvOTyMV",
		@"TTMoBguFCmvWXLWlAfWpGUWgPZYLJQnDUyxKbXxUnAfvLHvcJURcKMCqgQeIHtsZVmqyZpwHJYNteQXxFzkMvODKiNmqLRmMEnKMAsYdGKnpbkhkZXveCLgnOpqZSmvMaUZaEhsNVsKHxsCAB",
		@"bIhDaJqAnnQpCJGpyPrebMKYBvFlrFYrqiroqrMXORpdAqdmohxLtfisRTkYNtUarNzHtogCNwEdLPjrOtnamDNHMrRfBXseRlMBYOuXUrFabpUcxcsqzwL",
		@"RJBsDZfqlzOIBHnUCUahLCDKLbWfLcPuhjujrYWyLufjylKopfLJiZaKCGARjYUaTZAaqoxZUpolfzqQWKJCGYYMzWmlOBEtAQfLsobOt",
		@"RcWZyWXixSTnDvEzZYfyvmWDsPtXmbdPQniSYbWEiPmtzEuxAiKJuwJuiAEcmHOksBLtmPEzypBCzvkiHjDFXownvuYvvQaYvZoVYXCjstAkCnRMYcBXqrBGBDYCvFJPqqMwnr",
		@"NrCDDOaWCMddvRnQmkGPGSVuRywxekVsvdnLpYlyTqSJoLYiHSLUCJhRRHiOTLznRJubALdqnwRdpgTvCXiczECRcafpQzTHEnzEbSnnSrVQGTlkfzvTabU",
		@"lptqgrIaoLBUAEIXcWpdmTFENOOpxLEIisABnTPSvitDPdqyfZzwwtyttvqEOrjGmeTzyVXEYRqQbcVBXniDAWykSeGFbwkFNNpFAApKndoEwqQcQjA",
		@"wYZBcGpaSlozLMKtisDuDsTryWMQVNfhBXKjHJswJPwiYhyMFOSLbvmZqJGWWHqpAAiNkuoUYaNfDBONDGMKwMfstVusKnkjQVMhmXEcVtxLSAqBkLXUgtWdidkgQmgQURQBdFUmoV",
		@"TtoiUFFRhZSjojBMqPhKkoNFLEhYqPUbHzghrHMsvEtVzzijrHHnqYrWzcTlvjDpKEIoFownZKSonDacfntghXRNelYMAwpVeqITLjYmKVMQxymoZTq",
		@"igmOPEyjYluaFXzLiUvxJWwnOXApLDZxSFBKTdqxxptBqOFmrofluDaAIHUvXaEbOSQVDqwkXXUjSrEiKiluXvIdakYkmxmoopcobDo",
		@"JyAXKNutUKKkGoBjVFUWxjmvOqfUaToUGYwnACJEfUAQQJMklUoZbVrtAepRJebfEvLTsdJErWXbFYGJYNmGspCpRSzcQuswoSKpXcQMyIPtnJgwUuMxSrgnbdhPeWzmAdExLSMCEFkBJBKvqCtm",
	];
	return wzTBJVWVJFcnLILgWdX;
}

+ (nonnull NSDictionary *)UWBffzifgexW :(nonnull NSString *)XqGyonrQfYTis :(nonnull NSArray *)kMuaUKPMuGgRmkPxH {
	NSDictionary *aCUZOiPacwVBNWz = @{
		@"oGjVpsRybiQKSeUyAH": @"gyYLzejIykfhTYMfIfFElJMAwXFmCgSHuqRgzSqbfEzxUKeajbZYfeaWzyEOqFBjgkoSuKqgbwwSjVcvRopgWnmtlcODwLzwnroGAtEtlksZUpdmgwNTJFoSmVrqaWChovxUpOQBCayaEXMz",
		@"lrzZcagSBEkbNbZCdz": @"bcAAOXKBTpfJcjsNFCZupTBrCXRslfioOBBesZBwDeQVtsBECEukcQyGWXUAtnZilREUQBqVaAmXTYPxEsixXlNzlVvfenJPEtyriP",
		@"ovjfogpIXUGkLQYIL": @"pARSjtVrEnGmCfyaDfObKHDiWKtDKkwvFmQsMjTCavvVfUihoqSJPLohuLIRpvTZRRtRvBUQCqvQlLjCoKhJYWlZZuJeiDiJNCYXOgqUQsFzZNAXvrzOFncYKrYAKjpI",
		@"wzkkSYXTCXX": @"mIhCAkgWKIwzirIsCWOxDQjxUPquCDawAffhUsnAPGhXtBlFcOGgwyFfnXnORITRuSSnomZXnNRwkpVHSzZurTQUzOFozbizFcGmksxotjFjoalTvpxlysPHidiX",
		@"JyhvpcRwNW": @"zprpzuaFFGByfTxvFwEFrsFdRthszbwFgunsRkBBcqmoVTpfixAKSONMrONXGlsorfWGstRfBMHnlMRnDpHYFNndLRqPMSZOvvWRsIsHBmPfyxYFEmQtoXw",
		@"zmcbuSlSKIuTS": @"WegoYmXNmjhuNgLYidWXsWdjjVPeLlifJHNIzTQhFOGXYHlCaLjGjYGmFbHZSpIuzSZiFwSuAsdNjgkhxWFtIKMAgQqsNcOQuKWAjcQtQwiNaWHLyFuZzYfkDQjcSQlcPftu",
		@"ymqxNxFxYog": @"lTutsaNZWNzjxuMcBDFqUYOxQiomiORTDHrcAFwAwmSyMVktOcmVxmPRYKcfNeLGImeIQVoIebAviDCylrbZXIeULUfnotvahwtOVgEKWSbcWLXQRMkgUfysEugSobgaCUPtVyJJLoaK",
		@"cSDwlBFEilYfWMZWyUM": @"OhwHThszZoYDbozEpeKDQDtuhmdNCLXlaCoGctyTCESGGlgSXxsMtvhxAuWlnMBTeizwiWEyTFTGHfXOjxSmrCNOxFSqNbQMvrQKJXXVACUexpzudnxRBhKAxDJTtZpUwhJoe",
		@"HMgPORijhCSgNu": @"cTpdMEGJMnCQbMfOInZttwuIVOXzKdlocZQwVNLhOOVhyAdkfWNiUXcdsnhQohtBUJOCaTqGrZbaCbDjfSXdhFAaRdXLsFCdZUrZPmSuuoSfszGWMKdRx",
		@"eQjDuuDuMmdzGI": @"MdDuuXTIRdbbmLcKchtZXouovDwoFmmBErDbCGocMJhjhBzsGkPetxaNJbKdbKtKMKgPHZAwibGuTiTlJFxxGQeBSZOMQVQjOdUaonoOcOFIDQFlosDgUQoTLgbWxlIRMOxTrADxRUpCDEEGgQ",
		@"baIoPJeRwml": @"EXLIEhmCJwGkrxQVntRDfXcATPmIsuVUrBerebXmqxNhnpRcCBskOIfXLVlBRoXVbiDtcKWEmVADrvwEeQkWEvsrwdzEbvaUApCbcKkFkpyECOVdbEFvTipjFyzCleiq",
		@"kJqoSHUJca": @"oXgWfGVdkLLmTqdYvfkqOpFPSLTmJsSVrhWtOgVczSRiPBXKONJqFKkNvodlTAuTYYqnMnBYBWdJdaBtPwwtQZEuhxpomBDywXrNmZcDwkcfmqMumOttJTPZUXUQkLahorhOjzRfckY",
		@"lHBymTalnnHkWCCQo": @"BNmRCecrETmsQlepsUNXNIYIBfIJoidFYEzDncMQUrNAlssBhHnHxkTEvbIFSUlVtRyNLWfPjgygAqtObQFnAahANsJtjZqAIeEIYgxbTNDxjYGRhqCWFXuDUlnrfNZdkhIWKzIFUECCQZFqqGD",
		@"hSUpwPGwZLGLNw": @"RrbEoFVZzTqzakIzqpfKWOoNDZZAFaGnspbgCuCvGxYyGyeHTXYehkurmCZNReFKcMRFtSAsbQSUUXzmHdslFwNIgpYYnNUPgnFcrEyhnsRJauhrhDkkPOLLBkmEBOBHwscbvTNEjUpJukC",
		@"jWipTUBXrhEtT": @"NccIYpErSDARmGVRoPXsqPWGGJFqhWxoUjWehsRowyxDHKJodMUtKeKiiyXvPnqSrDNpIVDkJvtbaoXaECPyjXUvvbXEOQvxoMRkrBVxSvYrhMnQdrJjpNGFxsiDgU",
		@"PDUaJBYUutWRCQBtfrZ": @"FiZOwscRtDoyjFCpwpkAWEvdxPGNCNyIlUwGSxfTnhxHxpWjMdCLrXggBHuNSvzxDCEJBqKuIUXDAzEZiSNCKTCyIbwAQhVHIcLHNoVbLSGYXoFVNolgOQeZZkmBmEPKKxVO",
	};
	return aCUZOiPacwVBNWz;
}

+ (nonnull UIImage *)IJcDtNHAkFj :(nonnull NSDictionary *)teIMcVPIGl {
	NSData *SAVtkfOBgcVcuJHyJ = [@"wIrNaAaIdgaMqRZRdXreJAuuDsjxoCCNoCpAcAhnEwqIUidaNiuLgUHzBzHoNxkhywFvntSmgWPcfkTwbYDwwmGJzooajxKJTrksWiVlDWFGFMcSKrZTuDhAIVwEwcmgsvXHiIElVnbpMskfo" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JLbzLFsGQikVnTEOhns = [UIImage imageWithData:SAVtkfOBgcVcuJHyJ];
	JLbzLFsGQikVnTEOhns = [UIImage imageNamed:@"pRQzeMuwULQzwLFfbuoOdZMqBJmkxIuzgASLLucbDqBrzgYFQefbvrYaZxVPUyUWjsfgEmUBLKuBplXjlOjSavOzQKBiwdoFSKPHhxaQdsyPR"];
	return JLbzLFsGQikVnTEOhns;
}

+ (nonnull NSDictionary *)CllOSGgVNi :(nonnull NSArray *)qxOKuuKNsYzSHmd {
	NSDictionary *YUAzYBKSywqDTYLqLM = @{
		@"MYeEnqrsYWBbmFib": @"nOSlLAgGJkcZIfYTXOdIuAQmSaWABTEEgosDUVXZFimZIJjTNkCvOTuobVJniFVNhXUdVzmdOJmJZiWhdlUqBRWMYleqLXDxuCleJmhrbIejpzUXH",
		@"zMViVRAHGXIrkdIIvg": @"IDAnvQOzpqDLbSutvSdEQehmodsGPXhxJXLRwOtURNjztPtmAddIpnfcZiWlPJgDdMSQulkzCKLMYxmbkNQUIwsyPEsSkNAunfZPJhsrBitUUKAobLbOxwSelZHjTcvtvLusfqXX",
		@"fxAbSXmCfTJxCXTrmVX": @"WuVoAerpHXnGppIYTMVfJUTEgNRwMRCfKyceUhtyRSvpQHqjBVbzZfrWjLlHfqGfNWCWZLHRYCJCJWcqFodDiNGQEfNrVNfCMpuxCpgBQTHDorEcmDkWLknVgtabqIqixWQN",
		@"meIAUJZysyieyHIy": @"vemwruWcmZzqswvOkKAhqrhRCLWbqYQsWMjgczgddcXCgbAfvKUxYTwMGYJrkCSRGWYnykHgXEbbktXIwcehGQwiJaUADnwURxVDxtSLIGRTOvMGFKmTaCzkM",
		@"AmDJsNzIIZbpCHX": @"nhuaHzUyZOsISBnaTJQXsmCszfWnMyBnBAEzysZfgpWjQYYMSjJgLAUWuxEtTYkXXURcDEZMfDLbkbOIEMPKiKXqScsNMfwjOAnDiuCcSAANWpQOTtgOxzYkXP",
		@"HjmoqyKtDFOmuvEGY": @"lvVoTXTYgWrYiGtnjQWGDOqKbnpXbKXYNFimeIRJTPEkQXHpaYMMcJjTpimoJXmWapQZdWTOQeNPeqnpbJdFjPbitqhPOogCfywzgEIGxwCIyEoXTgLvPCQjzwMCxlTdUNEfXWiqxddf",
		@"TlVqffwiFDxkWEv": @"pbbeWnEeTejIEAgGXoJQUGzVRcFQqQYxIXDeJxpgGOXKbVNeQwmUqbWiRUdtzdiWGjohNvUHANTkRodiIfZrhsGaoNvdIsQUSVsdbyZXbZnHcArpCHAryKOGJPxpOwWMunxRujqRaDXOlOjdwrhAH",
		@"WJOgHNaCyVwFsWYK": @"UFnEBPwENWNTGfAqPHIdOZkDUMhInkJFomjJZAGzMAWglejvBDxPHnbymFQJRHQnQVDczIgpeDcZXIsBdUyOWLHFvqPiVktEkKVdlXStTXsNZrPLxqRhQDqmcnEFzSguntVtCmtWLTpKk",
		@"IULPIJBFbCBFEx": @"kGJZprtelNRggyufSxIdeJgzNHOWjBrndhGYfGIXkkYWxlqjeoMoxIQbIzAWSanihvHUiBlQBqiGwGgnGWiGglGCIPzTomzJmLCJ",
		@"kbNBKkOhVu": @"hkXyDXUWPyRVsolomAaiXTAkEJJlCgpGGKQWTuiAilOyrUlVIiqqzikiDhOKKXKvCkILhvMUlloFfZyLNaZRgzVmGVHyRxsEFqJHelpMdKhrNZOknvSslMsO",
		@"LPuJdRCQlAswylDG": @"diQfRWoiOgjxBBNOlKFvnYQxMIZGwMxBupAykhkyelPZlxYihstduazpbQBhjuvRDZkqkCZeKfYJrXWFnNsUaSiAFMYVHLlwkOIWPGfpjqzltJuiFAxLHDXQCKlNqIaAQXkWBnHFFJGjAjiiPeP",
		@"GrFjRWdwsJlyOc": @"zVGEGwgQPiosHqBqTRNPDJIfcwIaLcLmMEfKtONxoQPjhkspKMgBPKRenHLaMRpZhxNsIzCvVplleRgDCQiqeRuyWLJXilFYUWRUmGlHanLnJhonKwblf",
		@"RqUubGkQQSPjePrtoXu": @"raHDMJhuJcJBqjIqUGTNesmLNviDkGtLkavlKMPbGJJmvKyGIbtrSxvSzhQtYBXaHQjHiJaziwXIBeKBxxUKtJEbPKMmWgtTcwvFH",
		@"UlVDivXRnOrpNZefT": @"UkgxFIFObAgLtIACsoCfsHQMaHlJWZbNNSwnarsKqvIQLFMNgopzGwemSBjdKVIgcnqoLiFtJLHsuawIMXVNYvDZaoIdNRyjGEhZWoywBGZBkeJ",
		@"QMgiPPHcCbReXYnDg": @"MEeSmNYyYqdgbnBTXqLRqJhWEExTWNjbQGuiCMTDdLgwqLZBwaxqSevbNAOAUSvhFXIZmncqIELtdcyKSbGOjRpgEBTOCoxSAdmHimdClutIjNzNJVSpwzLPPLKBmBWdKoXcddFUCa",
		@"WaPnuxTgCdCFyVcWK": @"rrbNOjBtGlPrCEhaEHKHADgrVgQOiAwEFNXJlRZFSQipCPCbMeqpcYAwZijORaRjamBAUHZcRhKYSRAOYccXQVeEOPMnBhyklsDewAqueDMGEqBolONTFKqRSeuffFwIpirUhdXzYvBoPlhWm",
	};
	return YUAzYBKSywqDTYLqLM;
}

- (nonnull UIImage *)KrQdjJBlVsm :(nonnull NSDictionary *)qEmyCkFMdLnjf :(nonnull NSDictionary *)WdjpmzhUFpKziYSK {
	NSData *eobNOhubKrqHmr = [@"PgTEyAKTjBECiMLhsOsStDdnmYhqRrZbGOwKzCmyioPXMYcfbUxVEyRjIPDPlVxXgmmelsqEKovwUCroRhTjchGwwXoLkGkTDOZgnrwLycYfrzrKsuU" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *JEYmYAAOpCwJpMTBvx = [UIImage imageWithData:eobNOhubKrqHmr];
	JEYmYAAOpCwJpMTBvx = [UIImage imageNamed:@"isBBkeeCDtpLfFQtAHjisMCMnGMMXFgoeHrQMuqOGdSzhaHGctQYrvRTlVJtqZYmHdFPuKsnkeiHIAUqUdOxwgEmfwvQXOSCFUCbrWlRZavjNDtBAfZElbfavLf"];
	return JEYmYAAOpCwJpMTBvx;
}

- (nonnull NSData *)JORdboBANF :(nonnull NSArray *)DQKsmKRlWRabiXF :(nonnull NSDictionary *)tisqeKIRYUnwUh {
	NSData *fKbbTSmBWpOSK = [@"outzDHnIwybggjNAdduxRTOcLoCyoVmxdmtNDOcVXWCMSuhBAMntdCNSMjvnqsuetWGsUDtPBEeBgVTTvToGMEcIGRMRmuIBEvPefeAb" dataUsingEncoding:NSUTF8StringEncoding];
	return fKbbTSmBWpOSK;
}

+ (nonnull NSDictionary *)PNJSBkDAQrCjJBoCxvT :(nonnull UIImage *)AGTELelmqqAnNqXrQs :(nonnull NSString *)qMjPqTSAUwBfXEUBdKq :(nonnull NSDictionary *)BaeqxeqYAqSpTNdXz {
	NSDictionary *ZvaQReXsmQAd = @{
		@"UOmkDCTHZDTCzkFp": @"GjZETFDNyeRrrWHcPdCrxuFfciGBjMuFyktdgwsIqufxNvMRGvitWhCCPoPlBjKHdFxnEcVLgQbtqVUGUGBfqCCAAADsjqazMPgFaheFxbratNmLWpnhAizTdIxKyFhxsKwuogrWvlt",
		@"qzspDDtfQLuCiIHhb": @"eJNtDdbxZEAvRgiDoCCgwELKZoUytrjkontSHeDDKvWuTpJbAwVxqppMcSwMXIKUYXpJhvgxNKeJrXchbVuUJUhTHhoLCGazXTpLWVVVPmWjVuPNTIskrcYolkBFVicjHMKxk",
		@"FCmGIFdPoxa": @"ucqlnPHtsCDVNMANlcKHaLKzwVYnsQeipCJmIZBaTpYWUgABfDRvBcSOheOqRvwhWhMBceshQethlhgrGhZchOShIXJnWDYpyaetpgZhCFPtzHYTPrDEBxvUNomMiZdgzoXrIasXWSWBROahrMk",
		@"SXiMqiGSTsvUuVGA": @"CKRaLcrjRGNGEdYNdxsoUEKFxxzbFjNcykrVHUbOAgDxIZdKjjOqkCGOgUlxzptPTgpyWOkDnlbtujpGMUakNtedcLvapIvBJhbSawc",
		@"sNXeuyxmfQEDtxp": @"pLbVvEjOWzvfliGAdlMgYtUmsqaiWyQNfuAXQOKZfKHfeYhalCKTortROLQbseWeJduCwRsjNXscVaRMORxGqlfJaubnBlRjUDIGkQBfOQAeSgRoknJgItxqSEylKdzYGhonEdzlkyuPbbg",
		@"IwMytqZEoacsYTSa": @"TeIZZGreCOUCLfmAecPCHKgeKaJaSJmLRurLRraVPPjVrUnarrQsaGjEoLLRIfcYSyyzPqFcVzRDqXcswyZesHgoxEIGIDNVptaXRQtrdUHLUpUBaTTbIGEbNR",
		@"qqdGCSJjGfEvdsCsSoh": @"YBbUnTBguySSPwzcXFQxhqhaqgCsxSsaAYfbghBMbURpaNAArFFsHLriGWzMNYfpDcWDjMqOTHiEsXMilBAceywkRyzwsYSKqfjFxweeolVx",
		@"IBAbbmLExitEz": @"rIkOMgoEhSizFbFceAJJYTPChVMdWWdZVdZazMsFWNBYmpXStbGBxbtDmfFWHrKIfmLvkhgxrXboXLVJtkKRKbFtWYhyBxQTkSCaAhQjCOuhHimKATPkMFOrcttbDPDkModyeaBhyesnHeWvfkQD",
		@"wiWVtkztgRBpBBhflTd": @"WqpmvDwzTxKNMxoaSlCxSVVtcKASumjBQLPGoacoLhFOouyFDEjJZxdwAAeFaImZfsQBOVsCTrJBiahylQroKimAuHZcUVconXFWBmckDaEfoNrphWEXyJSxbsgTAJebFirPj",
		@"pBGMzVWhRDynhyABPEF": @"OrjIRNQajsAjMlQTluppLMtsNuofRdfyMEWECZtikbHWjnjIHvUYuefUCAtfGqWcQXmlcMsEYdjmDYQtnPFEAxiBEUZNSlhXbcuPKRzXSuCohLaHhKaSlpWSOBFvIkJpraYXTVcadnABpca",
		@"ralHmNXMBR": @"YGLqKtMTdkJahPKrokLlWyMXtbsBvClDmvkYTqiiykNnOSNQgkzpMqWQZGzVpjxGVicdVYQAXzHRDUdcQHzjihlWAehjFszOXbGOxsIzNvffkJhuLLMYRPZucSFBewrOhFFcZt",
		@"nOTJEaDLQVOopniQD": @"BwdTlpoXLskAjiVWYPmjvVUVVzpuXCVRUfrLMWnNvvNTIQvHiTkokBczUPXwYWYOnsCZBvKJdSRaNMmsVJmZpCarvVVhOaRjXQsSSIgzs",
		@"KwJYOVLPLUgQZVpUlIa": @"hUPXLWasHHwgTumfPLCjAqsMFTAatfgXpCfzPKFItCQsNqlStonQHMurvWARITATHbUNICRtCgpxMjEjQJHxFYAcJDXTRYiUhrbhiRSCjAkjvWhDLOPpNEolyNoVM",
	};
	return ZvaQReXsmQAd;
}

+ (nonnull NSArray *)KlUbrdCBzqyEjPDcMJE :(nonnull NSData *)ybGurmmXIAbpGF :(nonnull UIImage *)PwtVcrKDVr :(nonnull UIImage *)xShKgjxuNXVJpIXKoO {
	NSArray *jeeiqcIAhzccz = @[
		@"MiIPcyvYfzgOgBqBAHgItgkXHYDlLIYJTPtkBrCyJZCrodJywIaRuypqGBdheUlMwGlwNRRjOeskLrDgDVBDtgIPJqohJepVLHdkeoJpdswPAGaCeIjGvHcBysZHLWu",
		@"nIrUzmmNoxQEWMZYtUqIXJliEEVqOKhoaVbguIRNITgvtYFiQUaUUmdeTxbUZZGJNTsqEIXcGNHlpbySmZbnrWivmweJTUhYcbwFQiRvNzXAlqRVy",
		@"cbesNmZKcCweNaBmsUwhZacbuOrFhpnTeGXjDwVJvOcyZwxMnijylmSuRSqxdOzBokxfbIJeWOtGnIzeuUtNeVULRjsnOONMdfHKOSoHsdvPbvklGuSujjQDzGoR",
		@"ePCKTJiMBMjmmMsoVmKgMoavHZwBoMqpJSIMKHNzVVVmVirVrDCkWXClbQUARnBBgakrmsNTpgoMQltbNHhtzsjPZrksYZpNKRtjVUrWARrYekTNlBWHzfpdKrDcfXcpeXNUpVCdKJu",
		@"zfkCRHIUxluwEdnwCcWqTVfBSdbSMFTgsbvBHoPdYbPqojcRvbMnzPNtgzRouCbbAUnvURsyHgNgdeNESLpHWTTlpHMcMXraeeGswmzsrrdQHWHJwwJoNvUEXAoeAbVbKRWglPhgKsyMwJZg",
		@"RskMMHKwcryGjfTmjajsbEcYeEKcFefbMDSPORrDbDFpyMmcXQcZjEsYItLpoNBmxdTKWLTznScFSMJiRXAwmXQiLuMWnvULnlCqWvcrkwEQ",
		@"okgOTeCbeYkryVlHPJvHnLusrBHIAErIsNeuxYOZXBwvAakwPIOHmgpUkbmpLJGdeqZLkZazczNuuurkwlyYsQPoalAJZmMGwOdWPHMRgQBozkphtxobiZPzRrMUipFX",
		@"NNvJYcvzugDKfNAZLkupHCcsBFJKKZtClRdiDSeSUnnzvWoBRXMDVgSTzdOiThwJjHUCrxXEJtugdChubNTuxyAzbArHgQHTpAqAdixXauZDHtHWRfOrtXUOE",
		@"soMimdiwBcfbYMCHLunZGJHntwPGMfehTwSYETlRiPxWsxoNHAXkQifVVvPqZUXRDYPdlbuSZVAlDQYapFNgCTEUwuiQtdjEomQMaFq",
		@"SSKTdtIRZNOiGTilJBkYAllCWgYoKmYIyTRMVKBMQBTkBvRajageJrQSfYNgjLdgylcQGADzjTwyxyCbdUGqlpiBLUxDkkXMmtstAAHPcCdRPPSxqVQqQAuIMQl",
		@"vNMtSeCEeerbCsuyUdlTWzKwNSZhBFQYesWhsLflhepvhuiqIUDqmoVnUHKIVzMszIZhUodmJrLapskaAoUAVVAdNySespbakeyBJRDvIGnLHbqyIamoAowKJeathzf",
		@"xiXnTFjBfONEwfpAAWhkuDyKmsorWTrnbEPuhebawRytzvHuHTNmgyOXLKnNAWSQKFLCiLKUWrOxifmkwWjRTyGlfaIrEnpRSRJnxwffXIYARNmYL",
		@"JSuZLtLEwHlTKyQYCozsUQVOoSmLiwDzxiPxFuEFxerIoYQXZmruWlMmtOqQZBixjokfmNUBjPhxejvwtfunkmeWgMHfJeYIjUrfqTCaPBZS",
	];
	return jeeiqcIAhzccz;
}

+ (nonnull NSString *)MizBSnMswniA :(nonnull NSString *)BCDwjjCjIdWtlMzF :(nonnull NSArray *)dOkcwtYlwIXlvAOYPg :(nonnull NSDictionary *)DxajZqvthhcRHHQuqmp {
	NSString *RbDRlSYxzOlfHSuboKK = @"tDOczgFVRjogoabCJeskEuOZsDpJBKwzciAXqJXhosCatsxRaRVbAAviqSBdpZxmKsMXibqaoFhasolrtSlhbqyIHTGXrrpptxUMEAQyqqjiGHDIBRRNaKbKOZVQcqladZPsZkZRsEYIl";
	return RbDRlSYxzOlfHSuboKK;
}

- (nonnull NSArray *)omzPAvPTZvNnBBYht :(nonnull NSString *)GskuYQEdbWCOpYnSPhg {
	NSArray *alCYTwHIikyovvDYV = @[
		@"IFhTTTqRmWwoTGmorhtRtoKNrRgiFdnZnLnEarNFFXJzvoujBEelRVkLlvkzcldDLBSnSOaMvFjDQBIYpxABWbWdMUuIHDLKHgXNCFbElDlTQxfxNnrtNrpdngCDMIzDMtLXGWHq",
		@"DSYNpFQpVaRgtoKoYbdoZHHfzrsHpNTreCbSkxReVBSIYKkhIIyfBSWTEAFqXaqjUIJcwcHjLLuAbVVUyFzHHDXeuNaWndnjTNNYfSPfzDwSEjQQsKTuGxVSZXAHfSvDbgRfPgnUQhdlb",
		@"KVGMOLeoepVzMjCfRiZJYgAfxZiICicJQYKXJzZJTfFYFxusrHcLncnbtAlraBcMqttkaBunqUgQzzmvBIXNIKFyxBgKLsQCySYVSaOgWykryAWdDcTvw",
		@"CxwlkDAdcksfLPINITmLAlXxxOckgOLvBUjRUKfcEvqyqWbBsEEnEjSARyfCFdQbKSQxZQpHMbnzYYYQCZYAZbuEsIlHJDcBGniv",
		@"uaQaxdQBGEYkbMjVRiiTSIPgMxlvBGPRoKEuxzgFmKDrYmJBXRVscbmdpLdOrpFpofWioUuSprLIcfiXWUWFxNdlHvxqpWXYiFnmOjJiJOqmuzLEyycvClzmVQOdaDVYNSGiXTqTYYEZd",
		@"hkJAaHzMigdNEIPvOoCmaTZqPinOrmnKPYGBGaSMFCVFbFVkFvcalCgtYPRMxtcCbtueLCPvigIoNMMwxGfweZhXVCHyhcBqrxkqdY",
		@"NqzntevOIXYgTGDVWjlxDnNEEYNiUorgZxQuKEsxEYuQuVMGXotYfzamInasJjynjQBwxTehAGSpxECZQhTXllDFdSobHNMfnMYPEEFjtvgMibfSvVRQsLngKsth",
		@"yBEiMQZsDwwvktdcyPJmIDuGFUwPSAtLqiXLMEuKcTSpBpRwAgourGpfSAXYNpSgsmUxQmaUtmsHsHdsNcrChFSYZyboaJnyEAEzIjVUjXfzowKPV",
		@"ZgxYdxkvVtCEDLIVdWipOXCMXHnmyJMNoBfffCmGnttzJHLhEjAGFLpcpIfhIIPhcLxpROPNPhDPRSqojKHOJMZwDGCiffOeBkYYVDCWfHPTjP",
		@"YyyUbbCxJOEtwTPjlJmYXFkLYIZgBLglmJmPowQkGDPQjVsskLunhKbddqsjskjGbGitWByGanXlgobsBJGgiaTgQwJaTlFPEHTQHRDoxedblEoYaPdCfjIa",
		@"hrFdPcpLVLtyHqZlVgQLZmeTmsTsfLnzVHupCBAPXADGNTRWmTdHMelFtjMWIrcorBtuEjuKVIyOmhobTvGSazfYiSiEggBxfufUhSOPjfviLhWsNCcd",
		@"ZhIKmWuAVgrdnfIPgLvxSYuVShTdRxqimnQffELoQOWaxblpEemaHYSfyumGUrkDgDjzcTEgVXRxboHipgyajzzvNzBqAqqIZnDMGAhjvfEy",
		@"MJDvNQuwWjzQKsJGsUoEsOgacbmwgNSDUJuMUzmGMjLNuuIZcuKhUFaODibjaOwbTexZhDiKWOTGteGZicgGGgqWIregIGAJGvFOfiIEbZyWGyGBAtDamxwWBYsmTJyopal",
		@"NgjDsEGLGCqDNJhkfZqXGjfOLDwoBZDYYkkoKLYbdklDMOaycnGJEvueQrmROGDcCaDZdpWYecDQsHaxbFIjOnUtkSAquGdZJrnHRxGmWOhnFUuQFyoV",
		@"lObRuavQvwYsBKAUNaepydwYvGIAVdLNxJpCERfdloAFTWajGhTRETEjQRSNLcpWpzWrwevrRAftxRiyjMBYfozYlXHOCslbBpSUpbyniKlODKIZCCisfMPIdfNhliPShzmreqdEoJpIUFXzDqUK",
		@"AjwjUcbDLxbkmqrVjaEnxflMRdFJEoCCwzHJIydaqeBPGtQGTVVmAQAVYwRcDibKflfCinYaNKliiXLvcCXmvGaqithEsjjkMmdALQnNsiRVoqtMLgiNfPFfGUKslgafrjWuTwZsSTPlDkPCLDf",
	];
	return alCYTwHIikyovvDYV;
}

+ (nonnull NSArray *)bfAETCYckHMY :(nonnull NSData *)qaHhVavsKa :(nonnull NSString *)ZOowobIORIa :(nonnull NSString *)UtQxTpKtUjbfmlGDdjI {
	NSArray *TJnCzJpTrknDbpoX = @[
		@"mWOXFXRNETPUjbmduqhxatOupwhBcaDSzPBJFxkdZXnyRBPKrgjVQLLsGcphZlFsfEXaSbljKbbaYtCDpBRtWzvTEPMkfomXdhjegXqjhtRxSdulkJftDruINDBNXpeOoMGNguzcTLdZyQawlLFEw",
		@"RtjoILsaPOvGVvjrtdxXRocqWoRmTryVmNrIZzzyaQvUgeKgEbDLjzSMZofDlRkiigStTOawlWLxouOTproKJdVGjahouccMQNqIBnToPFmZCtNdPRcFUItSVcAlnHv",
		@"DFrnIQLFBlbSWprGlDWJmqYROgwJTpAicizyVejdnzdCRLmSnmlcQlesUMnirPFDnJmqBXFgBptZhhYbFNhIxLCLNylTPkIEWVDZWvinNRVphoBaZeaJvXBVjdvIazsDIOnwcQlybJqxAtP",
		@"JQYcmdZMmlYvaxXBxVbypJLfJDaYeTNySvTatQkaxGzxfggdqrhxBZTkDQAYsQMglRLPJwwkgqSmtCEiGvOWDxqxkIDZeymLkLElfbPXbxXNkrKeIHbWdBFXMczmDwJzTriDFkcUYCGPucGVcRaVJ",
		@"ObRxoQysJivXUZgnejabZtAqHGBbQnCkKHelCiTvxGqoWgThIiHPCjqSfcJlqvPwllzADHjLhoDNiZGrSTUReTBLIzrEDcVyCRhlWhiydhkYcacLeKomMsksmatODMCk",
		@"kFmaeJfmUfxwAOanGJkDhPJuxpgSDDXWmOqwtmAoVasvDPyCpOsTgOVdnrFeyOXOLAqJmYBGcNpMxIlpPaCNYmnknCkiYLeHtdMiGbLSddMZXdVrvemIhEKSnRIjVRlFNxakRymPHYZVKfmMtN",
		@"oKxRHQzaNoKsAgMPEBxjKlbZbIjgJzwomuYBurVSmKeHUWcMpJLoMinnRpoNeKXgtSEoqQKjFIdnZKZHUZnZElJEGxmrISaAXITqaWDSPvUqna",
		@"epfoVGGpobhANnZLeizHfdZbnwpHLeEbXZcrxndCltoqBvPKavAiACkezNUUOFfmyZsjzLyNDRvvrcQRCTaHhQafoCrkoSHpNKbRof",
		@"dAlSnDztMlwOepQXiBcAthGaTArbwuvwLjyaJgtIuAdArDnQrsIKQYTVMgSpNgCgnupZKRawnqPfKsZRPJAmnzEDJRlybWYKNgpsoLPsGmrxvrRLnEoiSKUrmGjqPUnrUWSuFlagBkbAiEljVxHu",
		@"TgLzZzkpDjRWInnaTAKvrPxyQXLqrBlILcraGMxrSasujJDGWDGAsvJUAVrOFfpoOphbFbAUkBUiURACkusnPNHLTJhRmlHvgJDlBoTBLbI",
	];
	return TJnCzJpTrknDbpoX;
}

- (nonnull NSData *)jLrBustvnN :(nonnull NSData *)ZNwNwgHAUiRyC :(nonnull NSData *)qUTEghqLvzRwIfu {
	NSData *WzBOfEmecnFiNReSg = [@"RGgNEjvuqiRAMRQTYXtuuEWnSXvknlYGsNlGRVcJjKMtteLiqtYNATaYQwzEneXejelaAhFWGZzMDzspOdemIJJwZvMWbBSDoDGKAPyMWtphAbyhoyzGLYqfegxQVP" dataUsingEncoding:NSUTF8StringEncoding];
	return WzBOfEmecnFiNReSg;
}

+ (nonnull NSString *)buoeGDdYbbVv :(nonnull NSData *)OLVVdUrFGY :(nonnull NSData *)CrMVRacCPNehoJvVMou {
	NSString *CxCAjrLrzJ = @"LEgXfiUvXIifQCHswfQdDKwEaRDRimFdIeseAJBAkBJUrXnDVbSKrNGwehFRxlKYDCuNglqhmvHhHQGGcsoZASMzvxBvZliteAhpuxaSRRBMFYOdzRpHgNDeEJtqIgbOtqOQsoM";
	return CxCAjrLrzJ;
}

- (nonnull NSArray *)acbdPuivjNq :(nonnull NSData *)nJnEbCGQyuBMSbZMWC :(nonnull UIImage *)MrIqohVSYhRlK :(nonnull NSString *)OgzPAExoUXsyKDjcCGn {
	NSArray *zpQWtbuyLtvtoIe = @[
		@"fhACpMDOJTJYmBuraQWMvlXGIZacvEMpwnSmoNmXQaFBRkQoAcFwaaeQbMRtKeQJMslxdLzMMAcmvVIPhrJarjtluYAhtdrQNbQqtkdqYCIYjw",
		@"OdPxjyIWWbwTcesbvrRFODvPjHKoNmbIxLnqwroOwUvvnMoSTJuQJcRpGqJYTliyVfiSOrnBMYOICsStsEfsPpvCoBtQOBVJNNuXshfKjvUOKBVBnQZcnhWKlVssGGlyBaXrKvKkWgBxJkTFsDe",
		@"mUwxzODeMPCASXWwAGsVPQkzwTRIUnVNmXpssWyyUprJYHPPYgXMXzXdFRuoJRlRhBStsbLXebOCoXHFSoMyZbDGOduLQqIjsCZaGqmgApbcuBhbKeylbhdpwuXZcpNDtCrxRHH",
		@"qfzKLKGXXlDqBkhoLofDtHTIOqAkGHOttkxWPZjtNVoUwbSSoaTzAzCHSWIOnHnOSsqPCqkVYfTCXHRbXnHrtSSpHPgffbLdaDaMSQVGxosyznkJmnRfnITNuzKXuH",
		@"IyfiFIHZhmKoAlhujVnSUrKOqevyjGRvfzopKhgEKNlINKiSNLDPxiEElbzrWTSTxlhcmAushDaAsTGERvCdnqNQmQSvGKhNiREUktfYcqYozDRjUVbXbPTFBpUXKFe",
		@"qrlCBfZBlqGhGslACQWYhxYsiKRxSipNIawGVDQdLHajgBnbrMVSCEuvIvllDoBpCPZnUcNbDhycbFgudSNcfQQnpUnpekwxCJlFgolvHSasWBAVYuPM",
		@"WGWGMHaGGGiMOgofYeDZxateDwAkiGYDfRObvlcQPmvRInixzMUKhquWiKAdTeVRBaFgWXGRAGUjovjjHjmrgRSNMHpFLPhpIvGbYUkSthfqCgTBsmDeBmVAtEqKxlFoIfMJOKeGcSPYSjhzZBgA",
		@"LUzrMhYnZGUCNTbynFFzHRXwJIKkuTNPYdqpWnHcccRdylTDEmzpgrDiAfMhJdEHZrYqktecFsjWFBKILQvkzyDivvOQLBwFSLPKuSpoRlKvwfBXtfvZNEcGGxhHjHBEFELgHnRTagesbD",
		@"rPFIdTDlwraFuwFvAAUVeqIvHjTNisZlelFATHAWUvYBNfVAoRprPwKZTESTDCpfvJVjNnNWvDYAAPPwZORERLkOrHZTqYmztUKFjZ",
		@"EIZXNPnVUseCLoqQVKjBsYqdUObpDWXvutUbLvKGZaWUjFQuMKfiKxWbJWXdpahmsmQxTvUWXjGMqHZiuwxkmuJIAsEoewpZiHiMKUhSxozoJcicpZPKUZinDIGtKbUrsmusZLwKDDxm",
		@"MNiwUPlnsZdqdeGXoHPMuXwqvUDQTqfTVDKESIjowoNKODCKDAcooiRqcUKTqvKQNsQUxJsEjwYcvIEYEdUrYdCchTqKECprTTNchNDyzZypYHR",
		@"sVUJwJMLeFsSbUVLKoPWpamTlgKBHPJZlbQEfKRuHqSQKxBGUsKxnBhwUlNnlKdUVWhQdUXpYCJdMULltCpyadhfMMpxCdvlTKMvNALMgjURnYjkHSpXrbcNooPBZbK",
		@"oXKYMVXdZpLKtynJqBMScjDeGZjVxmDcfARhUpoHPsMLfWTXouTzKFRoVVRCEFrraYINThWYVWQoboSHiojOfhiFukPNkWaoNNyszqmivWpOGlEZVeuHCvzlMwEWNDouTIBuedlfZVksR",
		@"yrOBtpBTZJMBNvrjkIiuygLmrvpWRKqwyOTQcSBUtXpJApwxUBlNPaRtlmxyYmidycTUiOIumWiVsstxBAolRPLWaBIbItTIJYaYoUqQDoguTwVtSqYcqoEHbWgW",
		@"AxxYvFTOEosplsjGvaavQPaDNYuJPiBlwKgtXKeaRbSGdlsZNyHPsdDhyEJxVYxvmRTxFVYudZpEYhFsAWqbFBeLhhApVsBZsKYjuAQudKjknsyQApowhtkITdguaXS",
		@"xtKcMYAPdBLnVdALWkSIXZmpQZqeyzUKAXdyaWVusitooYgCkMWvSREMpjcnyLvtKsNeOeCQDbQurZyMIZdkSQLFEdazCXnLyRfxQFrhPrCMyddgqBZoOJCPbSNrirVHfMFsi",
	];
	return zpQWtbuyLtvtoIe;
}

- (nonnull UIImage *)XhLPCBSQmrVhTGFjeOv :(nonnull UIImage *)LqtSEJMDwf :(nonnull NSData *)ZGQWkIGscSLa {
	NSData *PdtQvkPzDgQISYHjUWL = [@"zJyYeBRgnYXpvYWEMqPxSHnzlOGIpjSkhGsVKnzsvIUUwgdNPstxfghtsPIubijBHbuJOzVIEVYnqxZgWKerdJwfvUkGtxiGvrljJyyf" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *plLASkuqmxWut = [UIImage imageWithData:PdtQvkPzDgQISYHjUWL];
	plLASkuqmxWut = [UIImage imageNamed:@"OWRkvxczDjHPOTMvThBtnXYVJJorYHCfyogiOkgSJAKvXKDGcPGEBTqdcdwJjPqVjAznYoNYNDVcNduBdJyXJfASZSzErkvDzeFIbiPSBsaMMsorTvoPyhJBIVkiKdtPQoTypyuSiBvIuY"];
	return plLASkuqmxWut;
}

+ (nonnull NSString *)kpUSolopJqdcDuqaRc :(nonnull UIImage *)JWrrprrHYRCDt :(nonnull NSArray *)RIBUaCvyDYhW {
	NSString *TXbkJohHHS = @"CqnUTMpaFWpuwNLehVWolvCzTeSwTTLfEsQujatUYOLjzMahuwDDzayeUeCllmJRQXyMhtmCyLXArboCWjlfcBFeGkpBWxXNCEnHuNSDyVMiHpAIHdJuYlyqHmWuFIeJhvsvBBpRqutTFgB";
	return TXbkJohHHS;
}

- (nonnull NSArray *)tuvWbOUCWeTOe :(nonnull NSDictionary *)MMpArBjqqtHv :(nonnull UIImage *)WioyjLrQjrjDVogyBT :(nonnull UIImage *)ByLpasEPfNFSv {
	NSArray *HJAkiLlpFFUvmm = @[
		@"RjLSuIvngOPrCTJYYiscWpeIigcNHxSUCOgKRRKdPGoOnDbZQsQWmWzugBWgyZyGZxsDLLAdIYOoyqsrTYkEVggxsjbDLQushCHqonUaNZtMqWQgKZqzCAGPTybwbWacwSCNpBGKbb",
		@"DRWghiPJijalSAEYrfPmYqEFDoCiEAFzDLyOUKFNjrqwTmEvSBIetAFbjbecwToImUmzoXwnFLjZCMfmpQtxwpIZUukLWBcbfkNQszZMiJpQwBNplYsLQrxI",
		@"XzZTpSzvPakmsbszWzImIwOUhPtrPibcWZiNbsJHCONwIynHIgNyWcwZnkSDedLYxiBCGTNNofaxumfymfEUZemGznXYvfpogDcUNcesICMaBXetkG",
		@"DGQomlpMpylBcnsZJgzpjMPkGriljMZZhYHulIoblhnqrJJlNdrSWdbeUkAqnHxwVAzyqwYzZfjsaSyIpuATYAmusNwBwoMUAvmmwfoFcrbtYcDudrVHBw",
		@"eRoNZVBIGFATHXeFpRHbENeGLGJCDNsQSXZVzIzBBEgSYYTOilgnPQXfVubIkELIqLyZJJMLIckpmmxfpwjgoDUgHyzynIDcrKhfvmNkYwbul",
		@"VPmjLVSlpPuYjNJTXjVtHhsADNzpqLtVDFSwThfnPViNjgLtSsclcwBmeuyppQrRbxsDzpfpOmAQooVqcWCPdRaUCagOSRMcPanYrhmpzHmxSapzFaBdaLBEwEwtdjyXrI",
		@"dUhHOoIxjYgCkFwnaNynrFQWhpQfETcnckGSCVKoqfJcZQUJOUUXJdXCMArxXpSbwjEuzDFdLTzIoxcmLpBlTgPBrVBsGhkTnGRWSiGwWNPCqolcdxjtjtikA",
		@"kEaMsVgRsGrcFKAHARTdRRYgwVdISJvIlsMqYjvjdqImFoilwLbDEPbNzNTygkfJypCCayhshemFXoAYuHHbgkkTlvaIneMRqNoG",
		@"ofUBttAOYrCvOAxhODmGKGepVOpvMGwBeqYOHBdxGgCWjqozdDUGHdTAwXPahHyUGAIZHTQgZiUPrMiQVJFzgKCyjNFAjfNBzwdFVeAoOCAx",
		@"xeOczwkAYYkTQmQMjPesvxSnaeLVcXOZKNMxCXGtcIBNVNQgIcUIUpzpuemNKwsujkmVxTKQLFogEkMSkCsKaDIhLZiagykAWvuxWVnwbL",
		@"uBWcocFpfXQAmRotJihswXDGvfXTnrJTuuMMwPEZZEfCcAOAGaEFnZQCHCSsKfpDLumIbsWhjgFEemMcToNtwRsGcNrwwlXIXxStxBTViLaFzhsOtjuPFvjyFiKAGyICNysIAmZD",
		@"vXunQoSJktpUuVxFqyadOeYsXlhAGJrJWyLzFVIuwnygYahXoBqJpqUnMkdGVxUctUuIcKLlLtwZfzqzQakfZNvocneFrHGYLIncPUrIzzqzgqGblWiNyIAUNRltiJfLCEZuyfpFCVdMxGmCm",
	];
	return HJAkiLlpFFUvmm;
}

- (nonnull NSArray *)UwDwCNHPkPjBNZ :(nonnull NSString *)olfhbiZOwFpJwhvqoD :(nonnull NSArray *)foVUxDovkgqNbcnrNoA {
	NSArray *wsPSSqhISPBqRjQwq = @[
		@"wVNSvyVpyrWYQONvpSKGNJRELOJdiyOMVCYSpIxseqsajJTKWleLTUHegXexluHolWyBEGbxfOjPYfwTizALOYKzOuFYddZKEzUUfjOfKxLACtgjihdaVefvsIPxdinfmPdGfGkYAOuERyb",
		@"MhVBMsmbrqjpgzXBOwpHDwHBNyKNpxLbEXuCKNaSeKvxHNCHzrRjzbhCkdiWobudzIfJyHiKoWiVZETAzPzABJGjlsGyiWTlkzERfEGVRwQluxPihzvkvZHDXNxRU",
		@"WopXlmCjxHhmPOppPYxlpiNCZjFEWAHmPhnGbqlEjipofFhAHtlUiloQuwtiADOnmWttToxTvsOBozJeMHOMmdxmQJmcBHmMyxxJNOcbNfd",
		@"cWAAXcQVKyQnGRFUUWxAmvqlOzHzQPlyugvTgJCQmzGrbrrkFsalAytdFfZnaeRmrVcPfLBYVPBToOBUuuAyioTcknAxnjiyTjEcTKbuxqhADifwtBwwCxSzsWvVewfvAZU",
		@"xTAMPsxmgNrXxBsjKzcSjAtmBmrGIXygkxNKlqxlcgGdmREMFFfszPdTrFgQSVmZRNyPJwfpNEtrpdJhoAhTLvIhsPUqQqXPETrrsfOshDOlpDxzGncqmIsZGszbkpeBbxmpKyJj",
		@"QGgetBWmuyUXGGBrHCPsZgxVaGpSRFbVMFsQyZCjjSQNCyEFjyMohaxZFEjYTfCBSweZONBjPUxewRYhOfdXCmaCyGKFcIlNzutixcdsMXmjCi",
		@"nRLVuWQQzTZTOEagFWJMFwvYfaZUKCRdCMFLTThFCRTnjhsKwGUJmLtCQQnZBnSTXJxYuZeaFwwLZxpvkaAPknFZCBbTdKQofoFeDrzaDyUxEWZhpwjUJuSZEuuMKsxCRvAQWheDyjOL",
		@"dzEZHZzkSenPuAuVuytiHbUiqpyElhOvTPpWvnRGMmuyZOLxJJteiqXoSWMBVsTpvJxkKcDAhJklqkqZklvzyZPuCvTSddPyiWfRmIrLxmGHxWdgpRKgnmhtlwOscmjMeQYxYsMbwZwJYpKZLmwrD",
		@"swogEbjHatUePqYPDpAuJDpoEvVkORpFUkZkCXDUoNEAmXmFPtaNjneZzTmmAqzkIBqPrEpYiKwkiDbouSfyTZGuoLuCAevTtvtVzinFvBKETrmiuRaOOYgoHZObqDbUadwrNY",
		@"ABpkSErEoUJMwTiXhYjnehrbXhaNXsnBUpMpfdNtoamVgKEnOxTcHeYoLUPXeVPUYOkftvgmMDiDgImIDaZAsautgILRMZnqWfYR",
		@"WVjkUJRAxMgMUzKnarVFQDnxaeZGPMeWIxJDnyfrCHqrhGvkngbxMCqmefJZEShcutgGlJxdbiQywiUsfJHFSzbqawuyMrMZBkrmbzHqiIftrWNUpxoydPZRLrGxEU",
		@"DmOUtZIpSjFzonebgCVLykflorPDTAfEkqhtwNRYXJVFFjCjVpqWiguNqAHReWxjYSJfRzcnwrDMDknvHCLoJpJguaACtxUtMdFrnlxDZHWKvXnFoKBqeqoZMEbGfhwqammo",
		@"HtvBClmYKatSmRxIzbFpNfzIunPznFTzEBwKRyMutxDsrzANNqvtpwrMNsAkzleopGWHYqvUSqvTdhxyejmbSjKewunIgZEBIMjdcaHeaRRCFlbKGACsTPcdmEYsPKHLfEProkvQ",
		@"QtoxnsGILNubXPjaluaKuMzJASSngFaKtnnjDgPMoKYxsJbAVwdOBmBDrJxKWikBuNXUMrxpfFRuXQpekARhzBXlwjQMmFiLjBJmgHeWGLWs",
		@"kiwYRmiBXJBsoBwghIiQxOqlcXIBuLxDRULFmFiremhBBzVVVcKHdsIIZfExtiIhniyxwICLfXwCpWPTzpByVvfAsEdxxwYAGdCvXmmwBqUZCABVqOZAzthWnijdoGJBvbvqBlLjoGueOMitkLxa",
		@"jRUeLcTSpjcbmesjfejcCAFdiRxBlFcTlZYkUNreaTEeFPYvBwodleeqpFRDzxSXpABPVwvOXPTOyzajzfLcmdXeDKnhCdkAkLgJtAxLerturpYLtWTi",
		@"JzNQjZAvNvtBqfaatriXhEvCWlpRoxIjGJATATQwbEEchpkvgssJAeCLBsJDnKFmGeTGNJtnWJbDEYzzDBtGabiKRsiiEliwhCYZFHlR",
		@"bAjCxgYgXLIvjeQLEUSVpNuzNrrvpIfBSWhtJEaFfkRLKqqXAorOPYshTiNGfsNnMErjaXEOpYwazRPrFLBXSDPucGHNLbfCvGmRZpVJRKmCCxFQiyJvdmLYNsmKexAfHjdenNHqRpzfvntkInNS",
	];
	return wsPSSqhISPBqRjQwq;
}

+ (nonnull NSString *)gVKFhsISBu :(nonnull NSArray *)DTfUGEHDBvfmbxE {
	NSString *CWHOyxWWIThAaMNhArL = @"oEyXCPywrWRgkbPvIpVcMwUJNJcROpVmPQGeMKBdMalIOyPfLtfuYmXUCuPgCcIpMYbaGGQxJHuKrVPbNlSMmetZhmdhLInnciyCbeQNyggfJSyRDLAasjol";
	return CWHOyxWWIThAaMNhArL;
}

+ (nonnull NSString *)iuAsNGrDptsbmDdjqly :(nonnull NSString *)uZBSirDGqEzO :(nonnull NSArray *)YWDpOCVLxbn {
	NSString *DnQYsYNVamphJHLbAGf = @"AxLHGkeNMQNRHLuSRdBvwrDeWGopVIIRAPIxUFvnncCNGXishlFfLMXdzMaWFWXdqLnSuFbSnARDKyCYQQgiCTyxrLmhqdAJaxgEW";
	return DnQYsYNVamphJHLbAGf;
}

+ (nonnull NSString *)CgfqcfztGpVszCr :(nonnull NSDictionary *)eQjPdOwSXWc {
	NSString *ugPczRmIVaqkfrqBO = @"yDOiEazfOhqRWjUTJiIWLkEKYQnUpdhnNgBotKrFIuvSNDtnLXPOuUTzNToUDqmPfUjLxiIgIcTcIdqhcBtJiotujlxAEiALAwixyFXLIJU";
	return ugPczRmIVaqkfrqBO;
}

+ (nonnull NSString *)bOqlsFXgrwtUMOfdA :(nonnull NSData *)lokdyPSgdSHezELxl :(nonnull NSArray *)dYAntEPvmIyb :(nonnull NSString *)LkwWldefoKZKarHfAU {
	NSString *ijbjNegLJKE = @"JvmUsjivMnhTYrQnxEObMTPRPPkAssXuMAXkEfxtYukjarlKdsYJZgqhXrQdDJfBAPoKysTBfwMUChbBYdFzIyPhZfCEszrzDnxRWRvoBUuQH";
	return ijbjNegLJKE;
}

+ (nonnull NSData *)EBUEUnBLIxipcvkM :(nonnull NSArray *)UImyAnuqmYRkhqscH :(nonnull NSString *)TBEoTidayvsfm {
	NSData *HTypqEEsqzThQngDLBw = [@"xetEgiBwtgTfspsZljazPcytCtFlohYgiazWVqUJtQBPUcXGhOvgLnnBFkoqUlneeGHhmvGoFSOHwWIhrUHlFDRraCNilkFBABrV" dataUsingEncoding:NSUTF8StringEncoding];
	return HTypqEEsqzThQngDLBw;
}

- (void)switchRootViewController
{
     self.rootViewController = [[PenguinLoginVC alloc]initWithNibName:@"Login" bundle:nil];
}
@end
