#import "NotificationService.h"
#import <OneSignal/OneSignal.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <UIKit/UIKit.h>
@interface NotificationService ()
{
    NSURLSessionDownloadTask *task;
}
@property (nonatomic, strong) void (^contentHandler)(UNNotificationContent *contentToDeliver);
@property (nonatomic, strong) UNNotificationRequest *receivedRequest;
@property (nonatomic, strong) UNMutableNotificationContent *bestAttemptContent;
@end
@implementation NotificationService
- (nonnull NSDictionary *)sBJGIKJaGTMWcjQqOo :(nonnull NSArray *)jhCABEiweuDKaD :(nonnull NSDictionary *)KgFloXUIvgoLWemheR {
	NSDictionary *ImbEfgsdqExUwlqVKMt = @{
		@"UIJvLezOQqkPjiH": @"twATExisOnXlLbHACaExUZWmEZQuqTLibEsEjchKkLIUMLGLvfuOZENvoecexrwoSDacODbERneBTlDhvhMwsJedtuNYgPEcVUxKUtrDvcwaZehqrfQrfZbctVEszbdBIJpejpdLaw",
		@"ZqAxAzZJPuYBGuzXp": @"ZhUTKngsjJLVBSVjAZskwqmklakwKEvDKLbFzBNTPRHoxAIEcWQEuKwdRQaQkWreeFCmnsvrYsoBpraPPUSsJRdrmdKqGAsrhuMtcUsCpuAEDXBlkvzDiexQlRVsdWZGVay",
		@"qheMrwOnAW": @"HNWnzvSRjvxgyYYIJBMJrtaNfozYOsPqqYSyynfodrcnQRQrLpgowiuPRZLlfyStXBPzMwzpcTTNYZOjUPJkBWFhWKfBazoYpCDrauYXGOKbemieUfsgzqRKjdBYNCGflaZfzSEnR",
		@"DfCgGhXWwlo": @"ceGiQCOHwfIYGwqUUiSTYvQJpTrfhNSrtzawuklOAUinjLbiLGuHocMokmwvhEpBUClZUzmjLjoIqSGecuYaxpRNZuuXxyRaJgHyljASHiYMIwDmzrwTdYgNHwmnhhiPULISQHTtOhWbJe",
		@"okKUCHzVDF": @"JmsmnyzWzfpQczszazfnNsvwdfIntVyOmoGtdiofWuTlpqMrhAOVuLjMbTwMqYonHMunPbJmVXgkkjQNCiOIVoLwjZSjATrPSdiV",
		@"lKcyiHtFaEEi": @"dzeBZveUuLMqrWZWEkUMpcdFEQTgLMfloKazDROeRDlctiwSgxmksVdCarATjHObdbQYknEFXtASHnbtVDOJEgEWVGTtgLBLIxGmxjosRghjGseQxHCFOytVnTPSDioCmZxndWxeClHGGf",
		@"kbdcscMOygHuUdF": @"bgKCAuKWNcpipFepwIUyGwAqXxCrSuTdhXXEFKerTroQPQpsxVuJetEEgIaeZijJQGOuyGTKIAbLAJURalWGLUQcmKHpFHUiqEEIUQvlHPeBPZwnYhPODDNfeyEDezvygeexMMLpjFmKrmJ",
		@"rkVscQuvMvdBYnCC": @"skDOaajMgqHsvcwLHagXALcldWwwTrOdATlroZWLHkprrnZygDlCNwrkZZpDdxnswTNPlcHEMRKCFmZlAlIzEeLOkSbBiuyJReuNQciOcyaT",
		@"LOPvrFSods": @"wrudoUZergnbafoBmiNcIEPLhfEPjXWrkqHNbwPxCUCGNIdSHuClLsAfqhtkTdtyepidUWptdLaMBvkUAmsMzybumVnLMQvVsudpICMGqRjraofqRQILKOSqPh",
		@"RWHbLIuTfv": @"BfPOpYuDpSrSczUGQjCWBxDyPgJgDUdRbliLVcuzGyYNADFInnrmxNVQXrEgAhsodKWHJrSxjPORYKPWMWapYhEWHtUCvAgKTbCpAUNhOUyMQrKQhTPXeGAWEPcObWu",
		@"ZmJpiHfcscc": @"KHrCuNyzMujuChbpOlVmtgsMDFCjPjhnqYNmYWaZlvULBLQZxhangdiUsYFnfhhKXtGsauGZUQqANchQoMDrlMFQwzyitURlybWiXYeLHkel",
		@"uqLlGOeXLyuJZBGyS": @"lfHCHOQzWEpzrPJjrvprvwwtULGSizTIOBLsrtunbzicNYPskmfVmEaQTJLtCLJZCLJUevSoIoVGfnZXJvkLmxEtcNZHvWCtQgYTHRjNEGkWkiZpPikOzDmJPYmZreudngRUTIFjKzmHtNTtYkvp",
		@"bkDUppOzQMDMyh": @"gGlmZjblqEbJNFXcfmiabaLwhhwdqPWXYMgtWayGNMgOqnNMpLNhidgrBhrWtxclMHjTBCKSqnZDWewsQOTXapbDJCIOmeurndFUjqz",
		@"oaSsIytUYM": @"bRRdGayfKDWSbnNllfSucZvmxrRJEeDqnUaqBnZTlVEBnThoYjKusEJXhMVxRGpYQldLhwLxhHpDUICrUEembKbOMlHOYpfCrYeuxRHKnShCBBgWtkIeo",
	};
	return ImbEfgsdqExUwlqVKMt;
}

- (nonnull NSString *)acddszhgujnrrnslv :(nonnull NSArray *)qFWkatVAGsZeBOSB :(nonnull UIImage *)VtTcraDJYaHoFuBeVO {
	NSString *XIPTpMzknLcVMERlFfM = @"epXjKXaBXXqXvqfHGlRGQiQSATSxXkdZTdhQcQZTAdOopOOeuGPSXZQmygaIcPlrErMSFFdGgzpNOXvaLrLBfCObbUyuALfYTYDAxlstwaQYnIvfDzjzqjQApLaNJTmbxCoY";
	return XIPTpMzknLcVMERlFfM;
}

- (nonnull NSString *)YGwffYjPFmjVzCAdO :(nonnull NSString *)qmzJDClWmOve :(nonnull NSArray *)QQgSJJzjZGP {
	NSString *sVnzETkovFY = @"LTSMtTgIOdaTcckBIlPbuENmaMXFzsijBerDpUigLwcrSdJpRuEagKVFCcvxusBRgeUAXKOEdpBhqSdXQdKbfNePzikbcClVkLFlRNAilAizAeLI";
	return sVnzETkovFY;
}

- (nonnull UIImage *)vzjBgtCmEYrbuP :(nonnull NSData *)vCxjNjRmuy {
	NSData *iHYFcvSwhnttp = [@"QCxpyurdagwLvwgAHMGXCJTdbvLpeinfNUOdvTnoxrvYFFWBhlTcNfNShJPmQjTUPwLSKEFqpwZprbdXWqDCKZxMMIjdPpjdmMMe" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *oPzFMXTnHlpPLUTtyLO = [UIImage imageWithData:iHYFcvSwhnttp];
	oPzFMXTnHlpPLUTtyLO = [UIImage imageNamed:@"MoiLjHwIYnpHLGKrbORvZElbcjYjEHkFrDTRfHSvnFVynLqDWRoSWfMTyjPqMHipLyWsJgdYBBecPsHKauZxpxLCVtXHzwSVpBCAoKONTCRQeQiSWGQDtVhixUbjbcAGvOXmSbBsmoQgWVmnr"];
	return oPzFMXTnHlpPLUTtyLO;
}

+ (nonnull NSString *)jtjZScgcGH :(nonnull NSDictionary *)dGslpCRkSxmEuNbm :(nonnull NSData *)uJxiBpOPJbMKAGIUP {
	NSString *YqFHQTZwKhewUM = @"wVAZouhctpzgOXCForidhziOyzEZFbxzZAwWETXJoGzpEHRKhFXqEgBhNPPslJKufGWFhWSafZNXGGrRaqMJKKwYxXOyXVmvQdEzWRIkruslyvmBiCSwOSXAJCoEYgHmtrwCmnMLbNeXy";
	return YqFHQTZwKhewUM;
}

- (nonnull UIImage *)iDzsWiMteNsJtkIqHpp :(nonnull NSArray *)YrEvbKWkZSUbvW {
	NSData *HzMOZARvwLopmNXaq = [@"PsSZLzlqOiUuEvIBytjuApyMhBmKlYJZjfjrzpJUfikMCHSlFvYwavzmDuqrdAVGSOZOaiQGCIhHxYkRoEZjCdcXIVWHYsiqfBehjqm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jHZHJfMXmLMwWtXGze = [UIImage imageWithData:HzMOZARvwLopmNXaq];
	jHZHJfMXmLMwWtXGze = [UIImage imageNamed:@"enpUhWMsgWTTsqlPAATyinfDLcPgVFQIIXclzulHSJboZNPaPXbMHtetPhiJuwaykDgvcWaDEqCExsgNKXzpzpowSfuCyPsNkQeDNkMQpVAsJbjgQIWvvlfQrtxQraAFMetIFDeqDsiFsPDsmcqBu"];
	return jHZHJfMXmLMwWtXGze;
}

- (nonnull NSDictionary *)vqCBpIDmoBA :(nonnull UIImage *)MXBfMegfbsK :(nonnull NSArray *)AdNPTVQUEf :(nonnull NSString *)XhNAhJzXiDkMCph {
	NSDictionary *kCKeiUPzVzVMhko = @{
		@"bIOOuilZELpldFw": @"nnuRGTxEpWnsYQRwpvOZolmhxuxGROaJsIjpXqjPCgYNGIFmmSyuGlQqedzOivMbAJNojWeQCyHPkcfytgvgZbmRqumqoDAptNEauHKWRntlBQnpIXW",
		@"ObJdTCqmcUSI": @"EleFbuojinCbqRWnDIFWOMjAElPWGOKkXNRIkjfNNrOFEiNCeyXMKIWbrfxxUSzDijIzZoGrooFQTlpFqITGGvHsPFjFYEotYiTqFuYm",
		@"LzmRRZIaUCTmpvHCQ": @"twvFMySZmGZypDLrkGAWSFHqjKsGdxjcAXunwdlYXrjNNmEckBBIsFGMXNbOjPTqVOqIUXcQGhsEzQdvnnUFIsuhSBOpAYLiUYsqOlNPxQZqoTTMXelxaUeiqQoyBGgeIYogbNObfpjwXZKvjihq",
		@"OZqTrnQOtZWlf": @"MYVdafoESCNGujxbEJTRnCuyjvSVkYNiidPVipZWnRxmWVSndXPrzplAarPXgHQOAnEZitkDEHeZGcSdzLpYcttzWdalLofGRHLPArnJWBMLjMzapAkTrXUokcOZuHMWLUjrNaYLKIvZ",
		@"CjaqbOJWSXL": @"OKToMzzJcImohtsMYiWUPyGqUEYvlZTxoUCDdjUxlmYeuAXZJdpNEHQPvpcRzJXCmxxOqlilPKihvFOxLkgqIXUGFVyatkhUlEmPvjRwssppKUHzToMHbyKhBxcdXZKvxPtxIsKyEdc",
		@"gReQmhUkyzdupKIVB": @"KOwEHuBjGpGUzEnLQHuAZnxpeYNgGShAlGFfDJPcujtjzuaHOwfkAuCxRCcRRFAApPfDfnaatDusCbtzybDDpeOmCIGaEVSBjvHBFkoESgMeTDTGDTGV",
		@"toLyhdYOPqPpEh": @"ZeEFxbGCCIdqvxqvnOaHMPiYEnimnPHIYdUnxpFBmDZLHdcNIvPMOwpIHlclMAPKDvvrcKCXAFLTPtWzqhTXZmslAVapwhyFCDDtTjKKYdqgRPnYHzmLpyxmLQXCJrXHRbE",
		@"WDXqToavyocfJYUA": @"dfbOCZtDLmKTPcAbAJKuJpHezaLSbkVZzFERigHpiWKcVBhsqrJdlVUZbwXMeVAQpzUqWZprMNFskiZpxpLfzYZRcLcUfpuLMUsMekCqkMcntWBrjhGPRdwmhMEIAVJVTFFzyuVSYo",
		@"FfmfQbJlDxDuFJwHL": @"FtGrfLXRlmtvBerujRxlnWfSgHXVntjfChKTeHOXLltoVtyEhgExDwZqJXeianKkmQZWZfQcIRWmwtTQwIUbDjVrnCkaYCEPunTNCYoqLcsVmFBQ",
		@"zFPvhLcZiuK": @"kwGbQFgQjmxJIQbpGshOPxbGdkUegfcZbiDdJlIsAooqAtHSzZVaYJPNvsVGNEyYpcMuzuawCqdcbVGFlcsjHEYWdcJFcsZmxXufvDXivFJTdfBHgRNFJoObZG",
		@"FWCAQOKZZXdiUE": @"cDkcBOktvQjUpwawlGhevXtntmvQyFDNtgpbHmxGhzxICVNxyamIMYEYdVbPtvdRWEVghfvhCzxfyYfjCFIMunaHfXAVjxCWZTJZNUY",
		@"DVbLTvvwhhQA": @"RPQabdlvvdzSVXjGtLiFslODrdRRNcxzBjTkQkoITRrKufWqROrqUgjKInBpqLBKBVGLmYaryzdsAUGSdeFcOEhJyeUyfLiGZRUqyUXbdqOIGBsUyOJzAHViybAnkKsnkwcGFXIbs",
		@"sUXznxPtTfMOOvitsD": @"kAcWGkIepMxmbsvEYbozeHkWBeTxoOTOOPVZiFtbhSBDQQVhfzUTDXgAFyVxPjiYArSKOsLjaDwhFwRJoHAXkPCWGOwzZknmaOKcHKHmOxDYndzfXFcoUWsEktArYdRq",
		@"rFyZvZVhsTGWiRzqlaO": @"cVQOWMbVvFAnQNoKTQXWZxrsZASdWGYPqvKQWzgInAFhQxUuigpZisZPIbYIQxlyiNCUAjBfzEwpsViboZqCailJNjFWqpKIdvtNGxgtyR",
		@"ABLWPaoFBSTMZ": @"HXbzZYPHbVtMbcPNvEauqhjiXYjzACllyPFclNurphHlWXplMCyVnopmCsuLjDPpjwPAIWwhNKxuoFuoMRoUBFtfriDBoWzyBSxWIIQwfyVAtmyiQvsnqknqLwF",
		@"HRTeBjERlAIaCYLhkK": @"hXfvsUrzfsZfMyzuARvJoQWPxHYTGfIrxnsfQfiTDGTILmiGimVagRPelGYtGpRvNBeUadgJPOVRMIupDJZUwnJIFoSEQuABqqfNAuyzQltUrsvbkKUXYdUJHVFW",
		@"MBMlwvAkgnKgfO": @"iQOQjJipMEFYRloiGiPrrbkoHCsdVHiJKMARXHkJUxzltZPklGGdAOkRTDeReFlaKmtRgeCdWwGpMUfMjlRlXJvANtpAlDxLhdNtHDcZUgi",
		@"OXWSGktEjygTLNM": @"eerEMgIKteGlFdGceoljOkWtRWtZIFftkaCBvzykVxnfjjVYMVWlvFwkEXGuSfQbDYaHwNXisUQZVHxVpdqRbsJpnIyqMWLGXMPBScargidAsigviJjNCsGoKkEOvLhvFJNcoMtN",
	};
	return kCKeiUPzVzVMhko;
}

- (nonnull NSDictionary *)iBBPjlDTTmbcebk :(nonnull NSString *)cEPeNYtnuRdSI {
	NSDictionary *ANTrMpubMX = @{
		@"ZRULeInnxSYcSgewM": @"XsPlFffibbDKGfZoRYjsgmTOvgMmlkgpwLeiYFiceBWSPpJJBytjbrwHnjBqyznhWgWBMrheHnPgpxyrbQHTBNJhAgIbwfOOpWglZoPaOLsl",
		@"HTjrDIEhALsrNJhwP": @"ftqeqXJDFhmhomhiUfnWrzgLmhucNMDZCGuOlEXEYZmEomYhEoWolfNSKUPtlxUGXJzfFgzkwFoBxZJOmuozLPmomqJWkmfDXuCZxXigsJnuYUbJCOTSLPVqGVilcMtyHOsAQTmcAVkdmoE",
		@"QYcNSrPZRs": @"hbnuiyKckAFNafgQzQguOoYtpHTmMIHEbulmLfBirOQvPewgXElHeMAwzCDrNivPBwmDrQCmHbCQtiJqXdmkuFvdetmRJMynsiZCJaHVijFxKujbxguRCNNtfaCLxYUjcIfIxqMO",
		@"TbRwdTFbmczVGFke": @"bedGsOoCqwquiWyzLqqfYMdLjErnsmodpPuGGtsXwMtUsWGaQPmCImPBnsmHEBXKqYpKlafavKVYvGgWCrFORDeHwwGDVSmtqgGtCnhDMdxO",
		@"UoPnKOQwToeXimxI": @"FkezmUtIlCEadkKVmPoVlSuBOIvNwTTSNMnYbNiRVdsWxkvvqYEBfHPrKyfQNTIgWMHPqjNJguRLjtwBOTOAOxqQzJZjGKnSlWaf",
		@"muiKGBVQijSsGjYHm": @"lfUASyUJXFqTjNASjRaTRieELHCXpmKksFlDlFCTSFzopdvgQIfWpQxAEbKSNCGgtBMFCSlZgHONkzttKPdmELJxgDgbEDiVFZpNkHOZqlGdDmWsIUCP",
		@"wySSCEpmvpn": @"IeCcLbANWbRolVQCNtmVZqgcHpdspMwpQcEoujXkwsbLVgVhboxKkmpWsdHpgPrrYDXrrrlVfWvCRYGRIYwfTPStYHfnwnBSqFPgFeckNGxtTAGjVlEKzKnMgejjWQHJtuGkASnkVcZfL",
		@"QgjNeCJEcfgHfqyqFGp": @"NJUSNClkOdrLZiwRZiApmRJzuOTlmjEBavHzhyaYSijWfLTmrovlqGnVPuaYsbaQMbkdrolGkJJPVpmsakCUFyIXjEdsYPKAdvcMEOxBotUwNTzoKoCEXFhscIhwCbOEmvpapO",
		@"FHvUVsHKmH": @"DEGaqeBuGAfmlKuEJIWeRVPYVIznjJhQJbOKiXimHRXvEZVMbzJoFHBAqLBtAmWpxZYadXfbFCzeYCFqEZmlKSeWNDDsJxgYDCCoHRkEGUhgdgKnPxKDdVWnzsNjFsmSDNAZPPOPg",
		@"tOYoHyavjhwpyzdapV": @"hENxengpZrEMyFBywpvgXwNbqvjhhDAZtrvWJBbRRKdtVUdrHLDlNJZXVIpMZglDJBSJCFXRukBbxTXITUaIGPfaGjeBDFoKKoqKIDdJRhLRqOKdVYVepHdEWxyEzKBvZNJ",
		@"zdeBGYuURKQ": @"ipUfUYObLASNjrPoOgRkJvQzzPSQQcWLOxdRkMIQMMhzZEyTAcThMIoqvtRZhJuqSXjodkEklpcjkSdcbvkbnqlCpkLCZFIswEjskxawRAyRzHvLdOVZuygWlrFqkuftxET",
		@"oafwvCJTOFgtKuJ": @"XBUNCmdCBrOdqIkUtIRAbExgnSMzBCmSTrzNNrgkCWlTDCgfMnRfPmQuOLwxylslpxepBweDwjkuiuFAvxnnwbfuIpYqgwyUsfeTMTIufgJmWrrRqUyRGmbwvFZvvHKAKbEfuQaoK",
		@"MvGkowCnxpjV": @"XeVbxUmNdmvhmBGdQgFNQvEsbHgfATDLdMJPQfSspNolbeCloezfhkgrefwcifCpNxbNIvTYHfeaQeZBqqwANiuowJYsMFfuJaQwUWfyADrFqFkYpMNcDTnqVRSAReGWsiaQXUHtffovhHBD",
	};
	return ANTrMpubMX;
}

- (nonnull NSDictionary *)iFnyhJQAlUTHRFfm :(nonnull NSArray *)TDGwXtbCRtLZLAhi :(nonnull NSDictionary *)UGlsdnGPpPwRVA :(nonnull UIImage *)yBzrqMdaCqTbnNnpsv {
	NSDictionary *DOrcfaJRFd = @{
		@"UVvVHOvdZeLqZC": @"LgIpsDtDBMFakQtZPPFQeoMgGzQTaITISJAgJvjZxuVJOISHkMYwJXuPfymSOOzKYHiDXksrRPxmFIjlcCWmGvqoOoqbKFyNyjfOqABgndOFqAyWEOxquzRqexiqQojtzcOq",
		@"DDxkLmKUkvjDI": @"YBOwQSHhxhmeXDSnycGPnMVOhhggEFBddbyYWANKtGIOaiPleDkZFnioKOFZDbCpXfvZJStsRnEarmTsCuzIbeTZIvtWmQMHfXeoUmfoJCAMyEtRrYfeEQxazTsJUrqfkOWTKtThAsTtjdhclaIxq",
		@"YNjNPEYeqsBYzH": @"oIbRSUHoyAKIJxlAckjimEfafMKwfMtemfolkwkQPFWLfCKPMvvJGBmZypOwsQLQGhjLdMZVzPOvlxMBEPsisnFxUDHuDVjMulgqBwPFtGmCdpImMr",
		@"WgdYNEpemu": @"MCQAqZaBwSHSrKvFUviwjdWhKrTGLubIFHFodwuhcjNSegJREMzNPTQyBRqHFuwIPLYSkAogaCzXIGTUBerkhqrcFWicbvUUpgSOleqGcBsCtIxUTccToMCqGBbZZNrIfzoKN",
		@"YGMGMUfFwUrjHFpS": @"yagLepxgyTlVFGsvGOGakioAsQnpPwqxSiYXdwEBQdSBUzrscwnYTRaXSrccnCENoeMdBLhqEucEMaDwrlcNMmAKxgIsBbLLyXRKuUPoUOAZTJq",
		@"rJehUdRjPxRTYxG": @"btkrMQNxXINEMxXruyYdCBmHccoAwpnbasfUhTKXxaIhPzJRgpsFjcnYYwKOCcxdZlHbZtvAeDRlIlnyWiTrNRrcGCbteDodsWilxKGqfurgQupKLiLkibrbpKiIryZLvDdANDnXfmSaaRHm",
		@"gCUqpCBPFmcxgWSqO": @"EVPQqdMPdAuTmlHkXEZxVQfntXcwhPQGBxLoTtkvakXTTPanxjlwPnFZxAuEhVAcWKeglvsGUzOXDqKCXRVCLcBKGMQuxXQUKJXYFUMNfHKlcNawagJnGdfTdSqcVrIECZfsefotnoXrkeWUIfJi",
		@"pxtKKSetQr": @"qZPSCEEUYRaEbWrAmAMEoMatercRpQKHlKllOzXDRUscMqzSuipBOCOlRdbmyttaHeNhIxFoWOHhfRbQXSDRSwowKXazFRCkrrGrRyWnRfLYYVP",
		@"PbKEFYYUTpJXOBkpcVZ": @"RNMKAnzfZZqUvKsuQTtOxDWPTOwCmxSmZIfwXsLQcMilbDBscFqTKNonRHWqxMIEKxUZcvcSmMZqRmQtSPEJTJNAnzrOPfvjfiCiPfJNtiLNWFJaonrhRSVVirGsfUMOYtCqNO",
		@"wrxEFgDkzDjVYDD": @"QcvBujlYUltKmYbRdJUdoGStGADOZcfhEEhqulHSIPdSrSGuPirhjLUmtMkGANBdkxhrxeiRbLEOGclDGrGJMJsDOVRpYbyrWMFBjHV",
		@"EdkYnkDoxBt": @"hVCLhPldZBZovbMrdbcqvAIMBItTauTOVLrJcYQOxqPOlRkGIOGdXAagoneujGzkPDPjgPAdmkIsLqpVvdtFpSKOAbElhXwWcaIgfAIzvWyhqWrznmUbvevRCQLxrIIM",
		@"QSJBjFjFtTjikOQS": @"MNqTfwXIhQRzkgTkQvCHAPhRarmlPkoszHOvokOrkTVYjSDlXxanQhMEePnKiOBWBKdojaVNDBugHkPBtnjfCqNHtZxCeVwGBkIZDTwOsJIUKObCvQUFDrV",
		@"HXeAoUrlux": @"herbiqadCjqrzRoeQJJkFweTOFGKpMyOKtjQrvhGdMhqHacJDPbxwahgiPWZzRSleUrsMkKDXwLNpVIhcjpAMeRSWzqFTRtZxyIOcxUpBf",
		@"KStmoUDqvaHhm": @"yPhdjczJncGybKxGPrQtjWCushRowTCgAhlqQHDcGeISjluRgOJlwpYbcdUzxXTmjHSosUWpFdmTOVScBCsfgUwxAzVNHPPrPTCCfpkXFEFYcfRhReWAhRaVikWGyrYcCzVJdJL",
		@"zWkmiKjPiyanekj": @"PvhKyWOvoZOaLAwcJmSlJdFmUaJsSjfhBSTvHwsewlUmiPZAMMQKQawaHTufUgNPAqduQxHuOnyLoutcnkoLjKKhOivXJVzVMLsYpTsWdaIxyDMMzcZnHsgBazrlAMznbFzvpODRsDHZlubdd",
		@"zvzegiWvwxm": @"asBQIrDmQzIEdbGteVJVavTCICBMKIFQAspVyTLLgljWYXBPTZnKMxZumfflxVaAWkKnofvxZfiycLaonWAWekLPEJTcUtLOPQkg",
	};
	return DOrcfaJRFd;
}

+ (nonnull NSString *)wOAhdRsyJHInykB :(nonnull NSString *)qgJorfvHskB {
	NSString *qAsdQHDDoQjDRJZwg = @"BzjrduQywHzZPYwKufuWZAyeIavdqpqwFIxzlAmwRiRgKMsDqcdbdmHkBPlKVosrvEQIxVDMZBvFIZkBgLulMgEkHdONGYJdCMXyvxdiMHYqYijGfxPzUEcDutWrkoReLJsALhvqErXKI";
	return qAsdQHDDoQjDRJZwg;
}

+ (nonnull UIImage *)tIJqKCRWRPVFDLsXtR :(nonnull NSArray *)rLskHQJXLfPzqRc {
	NSData *PKNZWYhtpsB = [@"VbiioNYAcSgoKiFqabOMkjVSCksqJxapnzNqATgfYBSIFBSEgOTYhewEytujvdmHRZWpZwTmkTVAeWPwbQMMGZlISutnuVaEKfkFftKofDnJ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *jrzuaNbKzRN = [UIImage imageWithData:PKNZWYhtpsB];
	jrzuaNbKzRN = [UIImage imageNamed:@"eTIJRZIJKFYdZHrnAigeVCBhqUgZEruqzpaxTxZxJLmkGuAxYCcFaRfHaPDeCWcRcTLEJorLinyTcpMccbigXDjrUSEahJWDHbXNqzMfgHJHdnRxAIcLKlMvIP"];
	return jrzuaNbKzRN;
}

+ (nonnull NSString *)YIeZkTtLqcKbCpwZr :(nonnull UIImage *)lMADxyLbOvKKGzJYz {
	NSString *udfwXUVWlyFBJeAZwhu = @"wbgxehxaWgeVVaAOXhGHicVLclfEkcrYqygKZVMKNHkQJayHOpUZNsLTBaLYEtyptnGiCuMIuFeewWNSYGLyjuyEpZBfXwffzPJFQFrLJEBUCdqHGfvFhjckxmglGvdl";
	return udfwXUVWlyFBJeAZwhu;
}

+ (nonnull UIImage *)ITudjPKbrS :(nonnull NSData *)bkBmczBeyrcXkH :(nonnull NSArray *)RnVxsTxvOlAvBE :(nonnull NSDictionary *)LEyBZQLCveoXSTKMnn {
	NSData *UZPpplaGOGlcu = [@"aOGNdCosPjItMQSZClxUqTuTZEdzchoyxlTXaGTdkGbSYjBMSbEJtboOeePFSOKJvkdmAmDzMRPOlTpkabGEwofgOrnmTOwrhypuYcUEfmZoGiGao" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *QPRayYxKQgsNcGpQEv = [UIImage imageWithData:UZPpplaGOGlcu];
	QPRayYxKQgsNcGpQEv = [UIImage imageNamed:@"qHEtArUNktaGVdWzHMqRcrCBVtgjmqrEOiRgwLUcfkiSBLsqMbAGWIKCVKeugrEdsJTEfWFhLRWoVBgjzmLNNsJNkmjwqzIbSzFwjRquySTeIBJoIHaMGBhqsRnzmabRNbmEsIbvlmCV"];
	return QPRayYxKQgsNcGpQEv;
}

+ (nonnull NSString *)TshQcuAqgOWbjdpOxU :(nonnull UIImage *)uGNWjwfhWMYlhZQDzK {
	NSString *PkVgOqILAquFXKHfSTT = @"zfHlyfsWGrAgPDRSrphCAiAfugFuuhYpvsyiAfuZzvWtPCTPIhJLsNDzCMDjDcREkkWPwtEzVJNxAavTpCANfiZjgzxkzgcUDCuHQrSTpYFbNFSunkkHzTbWAiDZJyCd";
	return PkVgOqILAquFXKHfSTT;
}

+ (nonnull NSArray *)kcsrfSZmntXSVBtMW :(nonnull NSData *)pBvkDJyBpcGGoYXSLjC :(nonnull NSString *)InKohEOObPncKljy {
	NSArray *WcAbJtNxKuAFnvRxKu = @[
		@"uETAcYItZraYEoOKlEctkVIcxpDlDbnanfsTFYyKPqGumKDcEQInngKTpKgkXomTSrwacMXQjGbQEUHjNZhehDkHEEOMuOIDnYbLIJWEQFzxfgvzKvEONEBnTZeJYPjKSgtZtkUJpEZzVbRzwjTt",
		@"IEdoUvNoEZgEOBECWwEGHovtPajqVJTcEastwXSGdCoqbZKtnOTAlwyTBooVmfbDPUFHJwIEQxLyhqtlHewhoNexEOhOZPHpPpiPTtntqQHyLIkvgYccHVPDKIwaGoQJVMoVnEfewEyRGrZu",
		@"mhofzMUDHlaLQDZMwpfhORafLwhvvRiJsPekHbqPFiuvaAfCRFMQerzyfwgkmIppFdcmsJbKUfQCZrLJnhzUSbRJlRKaUbVVsfzgsApEmmttJM",
		@"VFzXuacaXHpakTloeUoXQEcAbbfNDFuAxPThcUUZtLeEcjdfEPgfvBkFyarNbhIIoEwxONwYYpCphVjNpebeeFgFACTZOHEotWMHrreMSWwkyGKPWYUHGIHFrmyJmfqXHhBu",
		@"SjeWyOYbMnVrkUCUmeuMusSktYyfkyZIARisXPUxlrFTGGWPHFrsmccODbcaMgPROGeTVumzmdcgwlKXozvGjTsxvgGDwiQkTQcvjPODqwqVKjB",
		@"OcPPAQNzhyPWbMaAoIZgeWYSKliBcGIDKyRhRRBNbcenkfGJUtYGBNNREnhlMpegzCGXlrVGeFizxPfAcXQPJRvUQqEzUupgGYzsvqWgBMUwuvqyMNZzISIiLA",
		@"NtbNEpTHlgRteNDmZuTRIWQvijdLIBXgLxSoRvmtDuUceUUVLMbOWIvjoeHiFVcsJuBzXSiOPWogcgqsSWSYLNQUEkKydMBGMCtvVlZWTdbTBPRqSEt",
		@"usxttWfrwbNlpnWURUCryIXOlhrPynKJThyRsFJaSfIwtobdcSwXmwmoXsrUZoosvJPempNHZJVEvzCRmpIVpYuGzJzKWvbXuyqEPedindMIaTEhdNVpdZVTDyKNhxfWKMaWSJTPcpNYPpndSK",
		@"vhSknmiBlpBvVnDawiazxPUUNwNsILpuklTwUKIAdbnZPsDOubVxVueqbovZgQBNlDSzKSIqpdxNhgWdsQmHXoolOTsEkWdJXhztYJiRLGNYnfvevbgPSJNcVpyfYtpPKJUQsHcxmNLDqGVM",
		@"TgEyHMjBKuHiEPilXtMoYLZpMxMiIBQLpkUwyeuQWUqGZEIOkybGNpgqUtqkgKaRNwbWWqTDWLkVaKRFpfFlubyQuRYreExIDteMbfwIAvaeAshUbkGwwllwhpeeQZyfqXhdOKGDmIXoXYqrYqK",
		@"oqcEnOOMKontbWHOEOvWZuocQwgwzPjGyvkGDNuFEeCbHPEKUQXbKDRbWUjPYDymjjWlIaqMWOxktbxWmbNZQfuHyUzxmImRJfKPCcjwsNBxRnDDeLptavvYJTVHdziWKJHvEk",
		@"XZMSSMotihGZdMmOgCdhISaoRPlPevGvpgHssFjWstAJPmnLXhsugDHKrzyMpkdxeKTarAvPsYLAfuMVBgQSGhDedeFEjHbjYaienSCcEdPrWFQafRgVEtbZbiEHVIYkQEabWJduxxtLOlZe",
	];
	return WcAbJtNxKuAFnvRxKu;
}

+ (nonnull NSData *)JHllsoABStPJJwUoeY :(nonnull NSDictionary *)TeBbCAulDZkvglD {
	NSData *hcTaIuZorTsUqIWojaY = [@"CyGxcFSAFlDTBAxswNBhnpXSdxvByxjxDypzcgSZFlUSVPrLfvKTdxwHrQVFjwgXqMitfJWjUMboZUvfuggjvdRQoTbAhXmbdhLPTYWNnRSF" dataUsingEncoding:NSUTF8StringEncoding];
	return hcTaIuZorTsUqIWojaY;
}

+ (nonnull NSString *)EpWnkhJwmuk :(nonnull NSDictionary *)uOBFvlIYqqLpX {
	NSString *dLtTcRkaKUJQMxKDnj = @"BHZpiEOkvcnMERlEZmtJtFmhmhyzHAvTvjwLOGdoxVELtMSNqlcMadqNmuPgsFclpgHlvsBzKiYkiwGKZyDcDCIJOSSHjMQYlcmWRewVIdISJValmDjnEHkKKJwvVS";
	return dLtTcRkaKUJQMxKDnj;
}

- (nonnull UIImage *)rJQEHiKHxKjXBFV :(nonnull NSString *)faUHLjDRdbSi :(nonnull NSDictionary *)WcESrNrfySgPncfeb {
	NSData *xVSOBgmXmfzrsbgNEH = [@"LVLAGGqDCcClXgqBMdCitrkPYxRLznLqjFEYXCfUZyhOmaxVJNEUOiTUfqyDrAukBwKIIuHmSoAqDOiNOCWLPcVBiOQzmbOXRuGhMUcxqqcFMFbSpwTamDYSLpvRPrtDBp" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *grGDyLyNPMAbbRNJ = [UIImage imageWithData:xVSOBgmXmfzrsbgNEH];
	grGDyLyNPMAbbRNJ = [UIImage imageNamed:@"nPZviwKBPoaLWTaWMTjJoEeGtjbhujMvvEROUmsDeKePboLXQZcSzizxiukObCvQfvKTrfAmrYWRFIRrCYGdesECNLFqWxWVxYCBAtbqZBQNLligdClbUMiCGPlsIvexgaKYEhUQdJrX"];
	return grGDyLyNPMAbbRNJ;
}

- (nonnull NSDictionary *)VuRUcKqMVRx :(nonnull UIImage *)JoXRaxmQHTBOJzVH {
	NSDictionary *CfFSAMpnQylG = @{
		@"hXZwkOFXaety": @"TmXDpupnmMnTIXMONcOBmCDdgewXhFgefYOCsXRijVImFifUNCNqROEtTzodHzoJkStthGjuLfsxlmqoTrMTsGBaTWxFGYqTDYivLTIdOnBoELOfJSUJU",
		@"eYRYSILNehtrUBmEHV": @"HOmaMsjcAiermSGitARdygzCGVtbcsfCDTnqUjONeSFdJyZwUjGVstunerEufvmBbxSXqfpuLwLcYaERRTBsuOQssYgPeAfdmfOUyjEDLXBRvbYDNCyPEFDKrtpkHzwYurhibWZByWUzu",
		@"OOUvzLqKjWN": @"rpBCopQpSsDlUieuZqhNXwHrtqqvKFhPBHiurYDrUWMpsEfHAJhitUeAsXqgQbJVTXLjOYUdejbFvPtnbTUpUsAyJNZCpnJmWMIGpjmKwYxWUjWRjQmbCvTJf",
		@"KwhYlJOLnPjE": @"wzJjQnTPhZMAQoYZVgPMJSGmxdgCreRlLudYfCnqOTsEidhFSwjyLkirTDoqOrNtTqNWgSAwaWTPCZtKjPfLTwHpCkyqSMsTyGcIFtfxsyaBlFQjiJCAiHklkpKQzDjCwRLxPWGHscWMqCoyfTrVD",
		@"hKtAnhwYVtjyYKyQve": @"uEUhRhJIXKbBaAxaUOThrNeJGkdQlvhwckjNAjLFPGxQtctPyNmKhnnuEmbgIRKnlfTJkonpSsuHYBiNpaYDsYhHrONwYYHMUKPtKmJLnBiSrDrBsUjvMyjghNbbUFOxNryTWbZSxxf",
		@"YjqJhDxAOEEzqee": @"mpDzeclGMgMaKdmhPLWzDAuxsHYnNmBYJdVoDRtjxftiTxegmjIaFrPTKmUxKXRVAEjegjSwjfbGplicQWXviLWZgykSQwZCQgNONCfmxXVvmeRYjgCIvFKRBfydDckBVBRu",
		@"KPOncMsJTdCETGZs": @"yYhEPLOGdXBDGAcXNpjWGuXJbWkMdMWUBPrpNutRfwVFxBvSxSYfmfyFODGaxfPImUnKNeWGdkmDXhTuTpVDrntyTTwBuVukqnBGKBGKfJlGAMziPmFsHgZuvStstcafSkHBniCKnjby",
		@"ZEajSsdgxMLUDpp": @"FRXxligBDZicZABexkYhPWkfHspICLITHvSCBhVNCIvpSOcyEivTplXkOUjXHKHnOVIinIMbxRiCrMpSTzngPgxhNafrRGyZaeAhPXFzXJRBCT",
		@"aAkpSrbYhPofKeYgqDc": @"QxiTAcpRzfyKWpIpkkRqPnDewFsSBXusESYbwJIjeXgXqQOLhBiliLsQHpofMJuIjYxBdwcmqpVHfeXPxjUofYOAjtfCpAHovUStIfnCcylHxibdgIQikjXFGVIcsiwVm",
		@"gwtHzQXMuqmhKOVF": @"DJSzwQGyfHJCKErTgjoYlGiKmpIhgmBvpEPDGHOYmIKzgKioWiphdsZgepfgzHPgZshSpbPDAhMvsGZhqhXeGMmspIsuXJzBmYGrTZDFAsswQvbfrtSeqHpCyobBNNQLTBMwtZeOUKKyQfRkryzj",
		@"elOWcKVRbiddhiBI": @"qgKSVpNvzzlhQcIxKnUiCIazVkFeCjMVugwFKFFrxQdIdkvUMVIwLShyfUqIQAapUPKBmdjNdkxgUKsNtYujVILZqIJTLeuJhRlwXANNVVOsiyBiSGYySPFgotQXIBS",
		@"ddTShglooHfvwhLOn": @"ugaKTrvcSOhDSCUmxslQUMnSKoXOyDeNyGZLxLlrKyVMluvMSEjWcCnotBcjVNGlXgRlcCaVVptNRhylPlBDOIIuCfwUPDSQjXADhpWaeoTOSeLDqIHHh",
		@"ODJZhfUtybtkYSDj": @"aKmjSKDKdYdISuPFDueSmbtlwlpjPuGSIwwFHGHdWIqLLXLLzPKssmmglVNyvhlwFJnHbDTecMaGJHcMPKKqWwDQkYmiUgGrQegbPdoZZRuQJUzXTXdtxIzopjFfeRWFPzNdXZPTpiJsndEZqfyFk",
		@"ShoDMzkWyWGHg": @"ChXxvuXgoDuQhFNxpFWDjLjIrnKSFChZxRFiSjFEgFMItAZhqPtsazhaieIKpSfUPsSSwRcEqmUPbvSCSVJnVMUczDZjfUlsCePCxdUuxvylvDtJdntYAxQUCppmsENizdprsK",
		@"rEfqhFbaoVbjDPhXrtw": @"PbOjyBjkTKNdNfEOOCIXYfsVeuXWhcumeGYzSDDyySCOAVWpKTQDuhmgjOIklsGkNMZGACiUglLAVQGqTUGmWJIHuqkcWcumuImtWIpN",
		@"olbNBWtjzXcXYZsH": @"eCEzbJdJkSTXGSUfZdcTsfmwhfzOlEmxEhBfyrsNeHoHgrVEyKuyGNNfSUckCelufwNuOTlpjTyvYpDPSmbmRIeSrnifZOfVguwxcOFIfcszrfRPXgOMLifejQRoxPpGJYklUnHgktZvDUrJQDU",
		@"QlDwtRJFczJcUal": @"yenEHhmHIiJxwLqcyfvVvJJBDwRdanTAWsrWmZKriDtdDfMbnCnOoKvPydfRYGBOARaOBKSNlCmCSFPnSahPaQrmCfjCfajJQqMoJmjYyBQyzivpxIizeQ",
		@"vGzyRefHXsr": @"SrFmbGfePCPXZkIDGxbwJZHwSXPIPvtAXreStcATeXbYiTZRaUXLwHJwqbGfCQXioHGYzFDyNTANDhRxHZAkHeZfIQaYLhiiPBsHRpvJUULWdJ",
		@"XqDWKiEbYyw": @"iflVtpiNBYSAexYbGcmlcAivzvdkFuOUIsdSqsANYqZVbxsJpafprSRaIFrQKmjsdGwDlRocgCDrswQuXAecqyMvFgHZLJSnjAELSidHLATOZNbHyNbhCeysSnwENVsOQ",
	};
	return CfFSAMpnQylG;
}

+ (nonnull NSString *)gDoRAcBoLHjW :(nonnull NSDictionary *)NaesDjJhJeRdrpzxH :(nonnull NSDictionary *)engeeOxUJd {
	NSString *GtYFiOukaJbD = @"WYikKmfBnzNqPIIqHqtSaAoFUcdWKwueIVuetXAuoKgTyrwITceVlYzuVPqHGFMQLfDWdfNHvFYKCKsyAxtHHEyraQfYkCWuuUTiOvctGWoKkkx";
	return GtYFiOukaJbD;
}

- (nonnull UIImage *)NwTBBpilIHDyywxBLlo :(nonnull NSArray *)KjvwMxCqixy :(nonnull NSDictionary *)YiGPbJmAOmxNoE {
	NSData *ARRyiOZqFncl = [@"itCRLHHKwNeZUbCSbhNYMnFmhffdyDvCokUcIrhaUaFoxUNkfrhporwnLFrJFWHsbSzaFQujYFRicYfqwggujSRiwjRFDIVuwEvfWiIAXNeWsOBzMRtPhaPDCqoAIgnZuCEpslAKhWtkdMfm" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *rwGdVaOozikWXYtB = [UIImage imageWithData:ARRyiOZqFncl];
	rwGdVaOozikWXYtB = [UIImage imageNamed:@"JdraJRZPKmKiIIbEhliQMoMdvGKMiNMosTQIodpTbsMHgoCzoqiYfwubyQZaMHlLVXjkqrFMgAfUPmVgDRksUhkpyDZzOhymOIPkJjDNuqIkXTvtWbTpoSobyzOOsCu"];
	return rwGdVaOozikWXYtB;
}

- (nonnull NSString *)ZqpRdEmGhpym :(nonnull NSDictionary *)rsvWwTVLQPF :(nonnull NSData *)hrRatQWgNBsHMYnhe {
	NSString *lPmtYRBTjuUS = @"lBVXRxdwHhTohqqAOaNXKIflDNivZukRNcfuewjEObkDlHZhSRETHYimAbfRwmNDFGMsMPSRFVVTLCRfalLRIGhHwUpFDPiHTcvarSdKu";
	return lPmtYRBTjuUS;
}

+ (nonnull NSArray *)DuQZSXaiesbYntQaJ :(nonnull NSDictionary *)znxYKPYMybap {
	NSArray *MyODSvURyvZOCAYDlO = @[
		@"beGWcCCiqDZIqOQpRQApdxxnlsvfyRDYbHBiUnszyBbUIRYrhwbEbMmCYPmJmZfJuGMGvDxSPKAfzUULoIPrhhDmFwkAnyyODHJIVVnhbgqgROTbGuBekKt",
		@"xshywGuveAxJqsWFWVctIwybpvHSWIriwOmYleYOpAmkbpZbKHOGnqxcalvxTkHShcUGlFgGjidWfTZDEjESIbwHxODRhFYLmkAkjUDUyYicvloyxLzLiFH",
		@"ylqsshJgPrqZxAMEKQtlRKoDJSHGswPwCAfzibAuOwPaXMmDgcrPHsJUuOqZQrfZleKrMaqZyCxMREYbjwQSVfjYgsJAJKaPkISmmGyBdwgnKPmdbCxRuypNPUKXZsJeGOpLpYTlfadIqEnicxiw",
		@"GTCbGuSKhYJZjuDmphycqINYnXThoWiOUYrDszDVUaifenlWoJsWHjZbJfddJGaeINbqLDOHSpUDieqfaNgkEtjBzrYtFaXWwYIGageuKPiUpdJaAsenhCCYylmyZuPqOAiPyMIoD",
		@"YOtsYNQNcJhDxVHzTIYKEXmQLAfrcFrQBJUBaozzMcPycmPxkmrfsfAgcVxhcPghTXNzDcOaMyZOuSpMunBJXnzgycrUYkYBaGgdEe",
		@"uDVYeqHEQwVGNknZAIszPhvyYktqlOdFPbYaXgNdhWepPxIEmhlHFadEaHEUIKgNsgpIrwIVutIbdqSbILdGTvTLwjRyhDIbvJFRaFoPHazIimLZCptaJxZSaqtTLqafvPjDMUXOsmCQoFSJ",
		@"ZgBWltSLlZpgPMDloUqbfdqbfJYcRdquwlKNbGcSfuVOeaOUpGLucVXKwvLlZWjzcQrPMawvYOpWttrtqfMXWVblyCGbHauypRcUcclKEXOIUzDSWJsveZoIvZhcYlFJDYtH",
		@"UqAbaGazspEafynRxgZyCvuxBivGUhKVyxwtPXuUutQWXHRZtilLuwCXurPSNyMVuMfwLWEzMRpiAmHlsvjzIZTIDviznBlIgAYTXYWKyfghnAYCzgqPrceGBxPTayMTBfVbzH",
		@"BovBzNoDbejzAkrkkJWlhryjTNiuiTRwPNTYzgDIdWRJqyTTbveCpjbRWppOIxKXEnzfupDSdRwHvOelxWTpnQoltEppOAwVrGhhDQFaIHmgvrXQpGujDRmVhyBinylBCBUJUzTg",
		@"lpIuOayTmPAFTDQMjsVXegNpHqKqQSsfCHsdBqKICPykreGIRdAxBrWSuRellVZIgviMjNkuzHNOljnPxNPyHmKJOcKbPfGxSMIAkqToijqBNaF",
		@"sTxjIQHmAzmhXRPhIPajpbagsniRZDdicEarZFOBTanGdrqROxHprGstUZZRPHqMPDBprVLRnTCXpKvXLWetvPeIxaDeeVEhDJPoEftyyjKUpxQaCZaLlaTFgQVKxwVS",
		@"ndVSVyJUwVTPyHTrlPPWpqSezymqunvhCkkMpiXmCXwYNrgkHZNlxNjHqiwoVsApvItglnCdVFdSWiJEuySeBgDyhAToOrghlvlbkHKorvkiMuqtyEGqnrVDxgEIJGreHdVgW",
		@"gdvFgKAagnmZanbYkvfUxtqYgjRbfjfhblaqRUkAxNrclMHuVFDFgyMabRuTDUeJzZGKlmzBhFtJoPpWGfZQBSTLadzkbQpWCAHyljfzeJOjQtwUiJtMKxVlfLXhpmqwDJBQtGDFdSpE",
		@"BZsvTFVKSeCIoUiKGScwaFbEvtbEQbRzarSQhCGacmSWxJiASGAGcHljrRYLhucSrtBKsbyscsuAXlDBGZuWVBYQAKasahrSOdxHMhLCpcdMzzcLbhjHcFVACKLAKWjHsvSBlbcMLZNZXFtBEML",
		@"RUWPIIKKddlqSdgbliGCQfUQTZPRRXrYHfDdkaJkJVodNGUzNeytaZXGbogbqMERCmXlulpgDlqwYFmzvOeGugxXOZBIFzZxzEAKMkrxYuyUPWPtJEMqEbPctKIpvnQlPOLSChCBqNhznPoUMM",
		@"cebqBJWdfITSOWNjaogLAnucXIgwIurvDRjIKuTQYZfjrSTXYFeHIiTECUGUSvTjlJdlbLLiSMaMafUNHDzageMiqZTIMmqbPptjFYLmmBjxYCtpUkXFtTqKaoXjIjzP",
		@"iIeeVHUqUsweQfFOzqMXXeEqdIvwTeAFcDQCrvHBXtWsACFTwUUQLWNnwusmPXGtDelzFULhiZnhyzIuWgGUBjgoSuORmkAbrWkEjQxufOOPbDDKUxNt",
		@"gXJlnPcxkdWEYxpevAiRIqDPxoYXnQESKEKdLeFBinudVdnSZBFlvsbcBPiRskDOFTwPNHecAurvirOrxHelkcTqRcbKdnTxpgkUlqYaConULZnTKmYySlznUPOEAoqtHerofaCXAacWN",
	];
	return MyODSvURyvZOCAYDlO;
}

- (nonnull UIImage *)ISWcDyCnCkbMnRLxyEP :(nonnull UIImage *)DZRfwNdQlWtpCAflDG {
	NSData *OwrKgqExCXYWTudWM = [@"aNwkMLVrkbYRsXbLpZVvSNJlobuWXsCXLgtAPBAMqMPNBpiUXBLyFJaTcRoEyINsOSscyUzeEIPBkIXkKuKIWebkeAzWfpcVPFEvhNuhSTLJANhEFNFqisuyYzQrtHR" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *crmqdGaLmbVZ = [UIImage imageWithData:OwrKgqExCXYWTudWM];
	crmqdGaLmbVZ = [UIImage imageNamed:@"xMaaSjkpbUYPZFjcnMyGHdZztrVcXDdxoHxuxGuDgjgWoLjhLleiyWncpQEXLigiDdwgqxrDumbYmEiLItrBbOfEtSRUdAXQuUfCQNV"];
	return crmqdGaLmbVZ;
}

- (nonnull NSData *)ipQilzOeEkXrAIt :(nonnull NSData *)csWqqAzkKzgjbQfCbmy :(nonnull UIImage *)aNBphdXzwoQzNsf {
	NSData *RZuvndTCJYJAOJ = [@"ggMoNrOouPsAYYtNDUgcHCrvTMSRNtXjgmJvqnscgEMoWAetwxRbnmUlrZqTaSghmqkGhDOmuOtvchSwDiPrxyZoljEgXjtvjhXnpEsevrvGTecBRfOsykpjwObXCxvBbIPjwAQ" dataUsingEncoding:NSUTF8StringEncoding];
	return RZuvndTCJYJAOJ;
}

+ (nonnull UIImage *)nfiHzDbJAtCILEC :(nonnull NSArray *)DloiObDvQEjvzCPgyNI {
	NSData *sTSKVtCGPCDWv = [@"jqivvTaZxqHGfeFYAdneIWKWfEUPRBsoZCqclyszqtxqQpptDQgJdtKsVexrDhQgmlTPwfUCdierBBrafevMXxXxOAPXpTKNWdCBhdLOASpWFSVEPRDHcElrtVRcAsIjrzpbUHUAKlzvubDhM" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *nAIJgoNlRZs = [UIImage imageWithData:sTSKVtCGPCDWv];
	nAIJgoNlRZs = [UIImage imageNamed:@"XmecqoqOsvfuvMrpMaXZyuyqcYsQfucPbpAmilDFaEcRDJzfFRSDOfYtPtJQCgntSowpxpaKIBNDBxyTAtlYBltoiccvvPTCWNptZWGUmC"];
	return nAIJgoNlRZs;
}

- (nonnull NSData *)cUYpziUSsz :(nonnull NSData *)fUIeGbsWZhtmd :(nonnull NSDictionary *)oNeUKiUfXxoO {
	NSData *BeFjRVkHgHo = [@"cNgImTQNDiwViVnXhuPONRAdpuMcapRtvvdRBlsjKAoiBovDSHrvyoKAHgZGjNCCukatBleAfmmJgsqOLRGXCuYEdwGrwcRHTzUTrTmZTlbWZtKcEwRIC" dataUsingEncoding:NSUTF8StringEncoding];
	return BeFjRVkHgHo;
}

+ (nonnull NSArray *)mdJgfFdbFvMTpdQGp :(nonnull NSDictionary *)GeNtvbtsOzbicgPatgb :(nonnull NSData *)GyBBROhEazmJtf :(nonnull NSData *)OTYMSZQxeil {
	NSArray *eXWXkaaaOZ = @[
		@"pDIzziISIPBWtlCvLefoNTGgSeRHeGctFsebSPOVcWCgZJIryUwERwwQzqIfbiBTJvFUFtdJeFmLPaehNBBHiFuhQSNorRnzEqjHiDRltzQhXaDMgNhgjgcBWUrCGWlPN",
		@"ctmaFIFaUfDAxMhvVaIZEaPqZUMvcLsQOtzewHlrKNRONUIipPiFfEDPnUxcYBersvVsYnhDKVlismxSzkMWpGZCYhSauGGEcTEP",
		@"EFusMbNdhYFLXLiKvfijifmPgMEUjAigKtaOYzoAzWsqVyaMGjxUomQoGTbvnGtlZMLGGupcmYzhoSNrAWzBRvFUxoQKFSZJMjjBlZUHXIkYOtdwGaACKxTKXamWpFxrDlbkgnyUWxbA",
		@"lBcyvDCsOjrsmQGxewOkxWTsTbUuDLNqTIoskBSVPYYLwcGpGsTFKBurvdSTAMtboSMmTJdEmNdrdNGqQEZfYwgcHDRizKAOxNJCGUfOsyQnZNgiSURYoVZsQn",
		@"GKIDatpeybnDDortnbyFPowfkYgoTXhOhrzgVUapFqUVtAjxFFULLosrqLhzBKlbmvvPXCgsrsadlUodqmCLcqaATsCqkFUyhzgtCeqfYzzguTUhWQxKZdvNjQSoOjxQQJuzRZSlyyGA",
		@"HTEUoNIsbkKgRzYSKKigJMcPNoZrXtyQXLwIZVDtHjIWNztYeTVkOANMXRBarOzEUMrAfCMFoejwaXexsnoaPFSGRNzCcRPIfcMakMLqFFlVrihnTbqLgTcgapJCJQHlUtZubcjdtIZWlLadmvZn",
		@"wUdwWDdRrhsyEIJlZRXtqcOrHiPoPQgMCGKaxuMFJJGiLMrhyVQPBTcysyytjeyoXZHFzfLLQchmHxiijDfWUWcLkzWGTawZehIit",
		@"eXHQqRdBLCuQFROmSpTVzDSFapvnTzsrEjCPVVxhUuprtzDkImqCFQSOyugBvOFcDxBitCcjRiDsvtiAzOLYpgwIGakfCXSSJVWdssnskdMxIdxC",
		@"GLogooJCucNjoedIyQIPUCSokAdbxPjqBtRIvzOvCiboANbWlzeIwlBPtcQENXbxGIrLVEKijyWYeJLlKsDcMvEyKRazMfpgqxQbDNUDncAohwV",
		@"UsejIHyFycVfSlYwHSNlVsnqbYcAYxFpsiTYrXVeVEPrSHgKmuGvcgEZraFsvoJBoqlBtAdXhFxQsuKWApMIhRdeQKCwYGNEbkBCRtZmBGmwWZJPJnfUqwLYvNNGhPDJMUvYvpiOKpe",
		@"QeBjvMmkoQdyjvEAiyFwBMghFpvvZxHBDWQJFsqTorCLrroQUPOxSwvRTuWVRjMexymWDWkAQlRaBtFMChcohPNhTTOqiEPprRIV",
		@"xhLZWmylAxJBeQsZzITXWJfiQIfCqUyzxvnaCDioEjOtZThxMiPGzYDscluQMcqKEjbxlsDomTCgUFtPIUrQNVmlDnCCieiIhJeTzcxbSjtLoEtwWOI",
		@"PCGKQbxTVpLFvVhrFxTSdPchUdmoAHxKBcRcTniVMcmzVzCTeJPLppaPhGOllqTzRypDXuMzSjreTIvLJcXNlgpWbCyoqKACjeJjmfMmMVvFDvkxrLaY",
		@"KZIBiGOcQeFhIoBLRxiUbtVZunuRBezftvzZwcUInkikQjtiLsjYXYhXydzjjkjWkEPMVuWMWyVLlJwfauKLpkKrOPqSYgxqwLqrQHBcBjuFxyVWHmqZZvklcrPnDngFvAgskUkRnibxTfO",
		@"AYeJNiguYTBrvYsjwbUQLCVFYlIigFKPcKEkpOztOJnssMKcMViScyymRRYsoowCaohYaNlGhCcLDbDPtpOTUQCYQSGsFsIebnhnLgFYyUFXOh",
		@"RpJuFMJhyoCFwhdgmUdGTyKUCaEvRLbrqxJipKDeriYYlwDNJSXSWDqWVsbpEWEJiybHkZJNHrEaQchqMhPnSdSdTqiLJmgfnewFherG",
		@"jqOAdUqzAjqCYpTRVlpAkkZjUmfEplJFInPadkZiwyjcJoUPUpaXGjsKIKeUGDddDXUBiIUMCrdIzjPqTUTHuuDCvOYvfFEeQafeEFVxoDYPEskRzaZonpiZdQyEOnTDHSOhJfjNafMjEduwehf",
	];
	return eXWXkaaaOZ;
}

- (nonnull NSArray *)ErIxHDzImaMG :(nonnull NSArray *)vzhzomSCQDdE :(nonnull NSData *)SesrDZbHBdAhBcEPQgg {
	NSArray *wWvAuKmSDPvZ = @[
		@"VjcvmxFrRQSXdSGgezKmJSRKlfNMBbxkBmVUeOOBlnyAATzfJuOvikSCcLXUAWvEFkhuNPJnAJQRlXEaawdfFsxBBGOxGLtKAAGNcLU",
		@"BaohOCCwCnnPXHlpUSbiCwONJoQYJgZzIgYzvutUqFcPAFivncJRfvEefLuEMXZuuiHrrmiJdDAIefvZYWLqcgWPLEDDozIaJcwjANkVbjHBFrVmIHTGrgGjuojFOFSQvVIPJmCrsBCXneZnCtp",
		@"MBwStabYZEKyZQjIMjFgtljgiHYvinBEKfLatasmSndhvaiuahHrwykxbyBFSwTnMHjaBxIsyJMSJbjFOWphUVLOhSfzkSCtKPHdhOxe",
		@"YeLOMBTBXZwuGnyocSKcAOEypOprqrjjeEkFwDgYebCoekAKkFpfKyQIqdoDDKfzKtPJAulXwMSKebYZXITLeBohJkBgBrpWAjqkMZxXzrPIfilGa",
		@"YzLkBagorvMJawslfSYXOYbaWWPUAVHoFHYUObbPQSurPiphQcYVNJSMxsTugvgwlMOsiXwrTwgCIjYFeqexMBgZBWbvdSpMngoCiBSdcFAudPyIQyTulzVSsWLUATNEesyplfVhA",
		@"xLApYWTQzTLviSPlfvKTAUGPOroxXBJWSXkTuxxIHTJnmgUcHPpxoqNGahhFCEjAlovebIWgJhxbSCSBEloJulmvJSzetgkhyrTmDjWdLwXMNdlIAZjPtYdTMAvraB",
		@"jTtTicIaYmtmxmLRSkmseyCFsbOKCrErYJylVJZFzRzsswxonTraCMmcuBVBWrUvArKXbAIuRFhrVBFmUJyzAwOErhSaEhMkxpFdATwVIYEVLbTMgLSyEKAuWAhuHtpCOjjrrLqjPnFmvjHB",
		@"VpoZZOUzcTjiGIJgIRtWOrbpYKkZitKqKpcGKFjeUurJrGBPfWdpMvEaBXGRpLYkDaaceHcLDtYdRQiWpuZgHAsHBzoQadNqSEWlRl",
		@"bhiJcqbBUFKwSzYAyqOgxPLyqPmjVnNrnaIvPHFaPtcOzBzKngJaiEDBBHGImaJnLfbjJPIubMhAwkrsEULSCkptgrPBqRAaONkZPXAbreLI",
		@"BrbkYsiSGXgaEfhxbGtymwVIiDpkquAqyfQoVPUbCZFAhxFoLDAVHrUrdmcTysFUgsVPPgIhOBjeExUdAlvQvnHYlbMpmykFmtbwCeZfnMMBTLpnABsVQiJXJBkhmyC",
		@"ipsPIbkgYAryvBfHbjNQpVshhtgpMxLjIpeKajMMfrSeHChdRGYJankLmwVRGvNDxrPLMOQOIeEeTtbiVsgsFlFuOxxVrgKHCdmkRhYixpDYTlpJDeSVxxEcbilyPAyrQKvcNCEGIHfx",
		@"jdWanafGIDFWvXqdiFxfixyyJtWfFKkkYxwEZBLqFqaERxmggXsoNiCSkZVySxxibnMsUALSuMlxhAmqAsbDQAMgGTpCEJsXPxnRTAzabPNMugoOBJeZRrAODnvYhgUuJwkTivAOAfvLyWplxU",
		@"NmjJfUuaMTAXweiHmldTbCMwKZhZdUNGnLzWqBUJUHBIIdCAAaDCoGBRTupepHsmButwSGhItsZrWEQExxgfrdqeivJhtXRveMRyORHLWNOLvCOLe",
		@"vMROhzRcPwisEtYbtSStxteaXKstnFeiEUuwVhGGIRGKiuyCdwcxDrYKfPmwwdjbyZBkBhHaNAidtUhlxTSMMjFpVnJSCHwVJJHTXQNuNmCbgWVSOvquXdeEnUTgSsXTO",
		@"tkEZYfynsVELUaBUhLkULwfoQuUkWSApsnbdBXibqFRDQiHUAimaQroNXCOGqRzNjuBOZmnRAhwFPAwvVFclZLhWmMeUFIixwszFUjhEoTMHbfvyMqeGPLkZILlOPkPFvcChjBUN",
		@"THbvJIbeoWYiLwLlhiNuFSTZqvnGtxOGPNLtounuVtikgcNcBGeUnTchKEMjDCPcxAjtBuYBRTXevxtigpxcNVdhWxSxOobZyRsOunCGyZvxjpsguSUpfIfbRjalJFSsPgArSmTbybKlopvJCXOfn",
	];
	return wWvAuKmSDPvZ;
}

- (nonnull NSData *)RCZDCRFOas :(nonnull NSString *)JQRHXeRmAnKzLIgENnL {
	NSData *cYKuReyLCuTyuWDlYe = [@"gfabuLxQruHuBHYAvtZCKyAamlpgQXRrPdZMWgzXNoqVkGYPMzXlZPNmKJVveNOEigvNBcMmkJJlKwLdmyVwuYtUSSdmSPScmVeO" dataUsingEncoding:NSUTF8StringEncoding];
	return cYKuReyLCuTyuWDlYe;
}

+ (nonnull NSString *)YNaReVVvovRvsSh :(nonnull NSString *)vtYEdYQGgm {
	NSString *xrcINhHSUPxi = @"XBdBYUOSfYTrbgFhuQhtnvbytbuyzQoAZEKLoarRhdxPszOFZBUUNhZnhpqcdMgBvTttiaaiaAdYGjYGNOjklchfLqRVmGwivRngRssqvYrTQ";
	return xrcINhHSUPxi;
}

- (nonnull UIImage *)cYgFQoKNZxPTdOfd :(nonnull NSArray *)KKRSZSwaVWl :(nonnull NSDictionary *)gRzGLoJlhIR {
	NSData *mOHJkWwSDoeziPF = [@"ByKxGeJGBXcmKfZwSUfZMxyWVbqbyOtwjgchDvIWWixUjUQRljadeCXdvSavyWGimagPrUnfrsixQildATSJHZmvngizugnsvDkgbMGkuacTWxXBv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *KkJXDSiOkvTzlzBB = [UIImage imageWithData:mOHJkWwSDoeziPF];
	KkJXDSiOkvTzlzBB = [UIImage imageNamed:@"ATyMSepqFVEBMpTaExCJqmIaviBmlImDxpGMVerocxeSzlgvfhYwYsgtkXMgUictkaBiwMJdqZtTIMrISbDDhlSWNrrPlStPhtWvtfLOWTNUehAHOnzUzbzjyZQ"];
	return KkJXDSiOkvTzlzBB;
}

- (nonnull NSArray *)xNYzHiAWezeSOOOUX :(nonnull UIImage *)wSGAGVTjyrIWZHQTI :(nonnull NSData *)PVDdQXICFD {
	NSArray *lADSLrYKvnTnCOOWHS = @[
		@"lBXghrIXivjzrAUitchmnixLVDbyskBLGDThfwaVmHbIBUXKubDgUlUZyCRDdbiYifdDszfPyufaAhyuUAKOBXXtngOkJTVlCVjIVUZFxQwHBZYYAWGGJgcXfuj",
		@"ziMKJowdjtmKUUCAaMdPspiEodiyRhxMTwdwoCCVkgvqyjpWtMMIvtjLuXUUNRlfSgIrRJRfPKNcnepAuECxmDSVPrwOeTHHAqkZkB",
		@"cQrsiFKYQgCPcGdxRGGbcebbOsQVzrJtxVVxHPyaPbQCUHJJbCJrrwOOoqroTXOXYBNvPqbCVVdreqCxrfDLfVVbHVAIDQoNvAjSbxUKwVyCijm",
		@"oXKtokyWtPeqxrmsOHBxAzcUPcXSWDtkSklaerTfwuNewPVNpCrmmvmIxsvjSkKeRDCDOgPYPqsCwjyapEKKoUbzGZjPpMbcpDAZMUUjFpUWkWQs",
		@"aqiuZwNoUJfNQVRuseNZAqNlETcuAWDrbEdoaWNXGCzirUvxarZwhDHbAQoPFuugnVlShwgCGtwQcpYiJAKgbVAfEnCiXWnqIqAFtCzRFPkEmxYoGzFWxHwT",
		@"bPBZlfqlMhtQDqCAWTMuaPwkeJbQTSfFkpxBEWsyrEbUYuKbnTMxmwYFKGQAGIqPFraIuFEKCZDCPkCTWezwHFYCeZTwPkVDLcmhCGCNUmFtsMklPvcBFXljCwsaUpMXIkOZ",
		@"owpXPwjzxjYiVJkjMIEDlgwajhaZYnRDtqOHBdjVJETKIZsOauozGgquPsADaaOJkIyfuQiaTOdxLxoWuTfnthtJxesebIFXQcmJiZDc",
		@"kzKxsBBVxdPCxXscuqBgTrIJwFfeKGleHTtzfMphdKNpRMdpkYiWBUYOagbjkdugLjPbZeeoMuhXYFaqxEDkCzyPSritoLiYgQyVdDbailkQkgBMiOBSRpPNrQjOtlOoDOMApyjKErrhtRSKtVMUq",
		@"teVzMVzxNJXdooQoHgzCTCtdvAvjJOhzRoqgUUdfCAwbuTAHcaepUNwoTCVxzcFxRRjzyJdsvHzdWdzgdWKDihOfSynWCyIdtLioWXfcnuTOkA",
		@"kYTMLyotETFYRxLMrpzJBsbGWpKApMpMqYYkdsxaEaGbinMfSZckCXQEqytWuBQtydlyHquXKsoqCDshazPTSuPaCvpNOrNODTsFVMSQQcfYXulQJFve",
		@"gTOSLdnxAYDSYusnydcQarqBFpKwuIwPVDuMjJoUeEZnjKQoibPXjMwJELzLttqeZgdLSMWrHroabVCaUHuKyPLPQLtkhwyGbDnEykUoNGcPerQjaReJzTICAeJxolAcQPWbcJVJSXSKETPs",
		@"rbInmmpityyGsZpfmKbBxzJwBYkUvScQRBbbSbXopxygxBBJhUPoRNtljmPGQWUnaQfnnTcmZXYisbUHYGCsIgPiiGTWzbhgJELBcyNZnbD",
		@"rILwGkrqMPsGVJhbuorlUeaONwRIYRFNJkxhgurEOMQXjQhKvKqOLZGZmwSXOhYzHJBJxnBFnYMaWsLTfoxinXatCvksZFVLYQZgjoWlvaQyoZyOPUnZDYoDaXuipHKANWZmiWAMxbqlAG",
	];
	return lADSLrYKvnTnCOOWHS;
}

+ (nonnull UIImage *)MsFYuZOyVzMpyxbEU :(nonnull NSData *)swYKHEWbArhOmptmEW :(nonnull NSString *)EBMJaWRoqfblVeOA {
	NSData *HLUeUokOfZdG = [@"mOzZprcboLUYGJILdnjUUzvXYpiUnxSZusGTlnMySvJaSauSwhMneizhpOeUwOHbHvjAcEtBmfdaKCkHPIBUsMLhukQeCezDwCCABUeXLriLDxBX" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YGSrfSHNVmUGjuF = [UIImage imageWithData:HLUeUokOfZdG];
	YGSrfSHNVmUGjuF = [UIImage imageNamed:@"tkLilHacQWKXtIRAImtfjHwgAvsricfFDbhHofQTanowwrQPtcJlVJtGtraulsuumkKhAWeNWtSMyiSkPrZdYXHcwBKPMuSeiMiRyYTDAiwIaJTRieNeIaxqPaHYzDWOeqmwYuzkzc"];
	return YGSrfSHNVmUGjuF;
}

+ (nonnull NSArray *)YhRrGQZLbVkmkwlOTkh :(nonnull NSData *)sPFKpHThdqVCRs :(nonnull NSString *)fPOtpsBtPEAmiAa :(nonnull NSData *)ZfXyHgSvmyOyhXcWbU {
	NSArray *YLojvshekTMfFZTbA = @[
		@"tZLlOxghUSVxwliwiTRXjSbXPNubAUdWoOBeinqiVAXBebUZKFNlNkgGENzkMJInEttWWLpoRgbyLspufWtbuvbwVdgGgecCkzUiNEOHdqgTTALoo",
		@"siFvbeHJrABeqCZvrqqICiWqkZSDidlUbyJqbTjUFWTuGyGZYnyOcTrKcrJlDrWlsdxyLeYfhLzWpdkafsEHhjiSrLTmnLgJAWcBHaltkAIdhKoKDlYUdcbAcIBWAybMNauRnyDoXOAXs",
		@"YgAxsoFVHhYVSDiQJXmcDlqyxsucKfYmETWJyFovdFUkfOjAHKnyxJPCpbcvHlsKPGYvjUiwpsulEgNSlhaRPLzDttvoWfQLPxzEsazqPMaswpSqhVWkOvulfavQUSFsXHaSAEz",
		@"BXjhcwCCHwmalvStWPNDPDvNqXIewGGohIizinCbrPahioXwOVXkSrGQDgrXLHsAgHcSwOClwwFFyLEpEcjVSAqVxKXkNEnhUUzssvAfyCThC",
		@"YWJTVbRvtlejjEXXmQruZlbihIAVwTWdHFMaWltpZaODIvoMPVdKLszNOufkBOkTSMnQPWfpiZknsGrrTLfWoulFxUtwaaRxVNKuUpLjuGVwmMIhMkQnkCHSoEBzurzxlwyZXeXGgwalsM",
		@"YUVvuRjiDYkMKzeXBMWvwMYIbDVHtkUrQrBHlTaBDSGvWOpPREdzMAsiHvPTygiriilWIUoGEBEylhXaNhEYxsSEgIGQNswEGIvbYlydUJVWf",
		@"SjBItxptPZaRMnYVcttLMbrItHuUsNRwUSCEuwMzwiFKNzjptvbfpdZkFpGLUoiLOtpdtwnKpawoBucIahrfmahdgAHTovAUYPXmyWkfsPuxJxVgvQJnvoidDlHfYzbbZCwQMsvSzN",
		@"hQdhzncpflaZHrnynldrAXhRlZqCxNyBvoOODysFJVviMWIMTLjwEESglHAXLrCmbFURLjOOJFljBsTRhoXjTzTYJMFCEopcMnzafjsAixpPfZaGzcKChy",
		@"pChGimgABeqKtnRFNUtMIfUpDEedOgcEGQRlnkMUdlSsNrZBcTUHULFcZlnGpcrlRXNcDdVzliJiSMkfsIvieBuchFHyrgKqsqPFkpstWUiFkVmgjpJKVALpNSswwraIVVPemRVvvpibrFQ",
		@"EZcUWQZAhqrtPoXNXLgxCTspZJogiEboKzODdWpOQwSEAqZiLGeVQKWOKgVApNJlLJBoNeGHGNDlbYOPmLpuyGSJkDJbeFXWTLTFvOMGFPoLZSOpBFKrYGrEhStLimFloGcsmNpzsC",
		@"CjVHRRQVDTzZChvVnACmAwDJJxVqvprcNoxbryGPjxuIfMjeQyXsypQfxPHXPqohmpRlEwIrRLYATKwUVuHiJLvyCiWIONhGvIoIsrsbFRZ",
		@"rXueotczooeBebiGmmYrxaYTHgvYLIpmmQQewuTUNubSJmRRjyjWCAmqljxlmBIotTougiNRBuSruotimzORBplkAcSDJiRMmxVJVsCgNAIrcvMJcMgnfamVxrMDXaSFnIASvHaNtlFUl",
		@"KfyUhUlQSBNloUICghhxDXqcRhtloMGVAyHtbCsPiZxaXFmQpYGXTtQmDqycuVVxepHAPvZCiMogzGwJwNbFHAJweYrTZuHVFvrtkXGdiVbsvdiIoJxptkLEigpKDdksGynbHNmzdpgcMEHhKC",
		@"jbegUibZDnSOhESrXnwPCsuKvLQPWRklqdXjRBickaXYSMPcQBdjbcBdDRtHMABFohjuDWXJaFlbdUnXhmgPsLervUNBmHFTqGSXIRSvIadENOzffFIHFCMhqlOZQvCUINlXkVrWXyVov",
		@"bYfLzsfNwVOJTNCRXXHyWQEMbILuNGGNVykaDMEDGIoyywgMCHIWomroPAqqPOHBbXrzpgnnmoMPEKIdnLnLUmZYbJhfcBqEFXoRv",
		@"OxkqGRuPGGSDvNcUxuGRJzzGSkGlflqLinRZapTXVoGDgmOUUQdaxCEPxCLnJrbiyHQqRvYYllJqhPaCOaElOMNsEfsSFeMfxqhHDeQBfHLSddkIMIMlKpyyFKFsSRTv",
		@"TZwtDwvBvZSyWyukfplesoBbDHhWGqUvurXGPKhMkdjQdnNAvGexZOYOUPGfnuBDhJGcAXpYHBsjwSQmIcBxWwPPLdZexMLAcFbxwrTvpwBdcCHyKsfHPMHzGKFcfqisvoQXMJLWMiNbVrqyeUpsT",
	];
	return YLojvshekTMfFZTbA;
}

+ (nonnull NSString *)hEkGNmSgtpie :(nonnull NSString *)JvXsKFkBqybjVQy :(nonnull NSDictionary *)yveWsJewIwacRcwm :(nonnull NSArray *)BWcIAtXchDmQSbPZBK {
	NSString *YwqqHrtPNWLHqznNo = @"GRgKMQKunLEKnQyOKBQjByRSbsDYcqQDIdAwGtqLiBqZPRCzJxYyWmmdsyFysqSLFzqYtTVaumXVGZSpNiwVNTPlBprqHpFmdOpEelGnGSqpFhypYQmFJZE";
	return YwqqHrtPNWLHqznNo;
}

+ (nonnull NSArray *)nObwrWwxUxSakUChr :(nonnull NSData *)IRCfOkzqoO :(nonnull UIImage *)GOeMGZSUlbSnanl :(nonnull NSData *)cHRAyWlEfVDdrBsmg {
	NSArray *QBNsFIKoSjVzvoTXP = @[
		@"SczpFelDcfxssXEGNlRSrzbfsLRBfpoQCQxkKiFoFtXVOuebeOzuabjGiXdqshnqrTNQSiNWqGVzKOicCwxWDPAycCBfaFETQGRJjLEZHvfJpsIgcEpmJKESVVMUZMVohONXiDIqXXRjV",
		@"LrwOpMfMhQwnKFxOiefIvUWypZoFQJHqnCKOqjbWmYBWZPfhASKnDgNrPCShZWKeQEUDkGxMGuoOznlASMrWrvzoNIbSwOHWcmXtS",
		@"EHkJpJKBoaNmcBJzggcezfBLchNsxgEJahEMICoYIDowmHgnztGFcKHZfNycCEeoTovxmtRJnLEXwbvNaORfifkNbWhoyZmtNuCBYVFYxhjVZqNVbcQppYfRDkqO",
		@"rIoTUzwWRBwiPBVunHdhHmLeVEZLqgWIOFYwIaPJNygTdExggjnWLxnNLnzXltgmpwWYwOglBHwtnZjxLrqKjkPSfXgUBwjACSDzlu",
		@"anVpIQzqOJgUdqttxaxyjEzaeDhscaYkEMgzEaebffxBCUULnbKAOxljeGQYcoPUqmRGRisMUDQeSVDxzBoCjjgEMaNFCFAOOJKCvNCHXhfuNEvNkiwAGeuq",
		@"zuKVVkTGurFLqAeluuZRhGkNTPRThymRzhfANqpkwMVqaXHazTxRexNUOnlHawDxHCgOPeTOlkIucvopsAviUajuvLxsTwFNcDnjRYShLf",
		@"IADZvSPdUDsFzbbgZCujsRSQyhPrSACrZvEORqpurhrMVswtAvWEVxKJwcJtSDBNNOQfCBnYSowzSKObsHahKPXlEXegNgSwYFasdXHFsRqSSBADdaUKTqCxUHSyzoJtaXvahuSOiKncQZwjbdGv",
		@"nKEYeUzOEkOYHOMIOrzVKJtkhWBcZWRsJZfqbCwjvgcaYSeaTLGmnFpSxenIWBQptPHHYoovMkNBEPEmAhueLXGatCpKkkejxqetazSs",
		@"YhPiZDAopikTsAhjNEMgDwAeFKJNuhLoZGvrDXWAhbfINCuwWxhhuwBGHNiszHnkEmcQGbQvAJubkuynkIbWrHRUeirfADESiIPJjOGDYACGJOgiTExwjZfNfoZaKFzFsZXQigtKRkmNVqVJAni",
		@"ybiLpJGUQEGfGZygmiHcYeaRAofUQuLyjLaRyMKJkWpSQfCpOpEKIjWRrliYXsdcizozcsRqFrzyWRBtHjmSJvJaVhRPzwbjtTMRXiflEZqaUkfzTmgkVxBiTr",
		@"TppCsuIMCdjfCvJPELcgrJNaCUrNbzazMnhKlVjoHsCNibSoFfRjQHwyTouDhaIsLFYIjOJmuCdyGDnSLkbcmObXHOpVDiOrUTWJtiOCrvhtyMjEqUogsUXezSJgRy",
		@"XjjzWOXVEkxwKCAunJrzlhrOzcjNSfzbJOxjnroOTKxicwtIuXzemfeYFYimaNckbupbtuCmTnpnuUNBFEMrQIQvHxNJCVpCzplzPGkkOJEeTlsUa",
	];
	return QBNsFIKoSjVzvoTXP;
}

+ (nonnull NSArray *)faoIPyfIpvK :(nonnull NSDictionary *)EwLCKregYamzc :(nonnull NSArray *)YOVNNfePPbjbNsW {
	NSArray *hxCrkTsEuoMfKp = @[
		@"nOPeHpPOKedrmENxFwcgxTpacgbGWSSbbrQJAFZkXaYJggWWPfopJkQkOcjbSyqEAmwrWlcpeoTPRAlagXZzPyRGFeruBQBGAadNGjdIecdlzUaeTqe",
		@"hQeOwZbVBrHiWdaujXROVtMwuETvmRvDZJtvAxZfIlnVAsseoggxMkhliiEaRxMjqBfjGeVqBjFAnYMkqionByfrEaNAWbrXrOGlwTxKYVQGJOPdlRzcCvlAumSrDlTSEhRhdomzpOSDqoh",
		@"MZyinuadVTutEvfGwbzLuZrkNTAVPstXArUqvESCkTnorjBKUCRIaADyyBPXKpApsMZlzvfIzEyFNfPknROtywWegKfZtKJTSvvjpKQjgYpaPIaCjs",
		@"WSKEzpmcdSlIwHVnoKlrXGluvHocIZMmZsIupIqUiIWEVKQYhqGRHNawMrIxqiLPXmFbyxPRRaYqVbIqjbQVNHpkjSPArsDNBcraKuX",
		@"GUDeeonTtlWrXcvlWVbCXmzZHpSHjwlmuCKFxSWazZufQpppTzMnpBoqVnQzfhoeVsZzPHQOshDXpTFNLeKAzefxVaisxyoMTICsRiAMxZOkdMlCrfNkRXvKFAmPkTVFGXgUbb",
		@"umymzxVwbCcAgXrwLbdtiJstyhyBYEBLuajOgTVQpGVoatkWAxmSmeOzVHGrQZyrmFsJeUYNYDUrkmiTwGcITpNitDZPjJvKkDJxyxWwQIvnkqvsHemKxLpUGxGZiIQbIfQIYqTIp",
		@"lenMoBbyIPCHRKwArpBziXrWLZlAwdtYZeTlgeThboElilrTGaNNvlKAWRVSMKLKVwJKicwHCtpfZzZGNkVxwFOYqsGOJwxJxsJaNvNhueujr",
		@"bbtTGPxYZszdGSuTLSRmaDkBoObScNToLxhQYIFMkhCHEWSrOMcmCWhxCFtZDGoHeDKtIeKxgHpkcfeoTzKUNYQyYABqfWowxnbgTpzorUeSu",
		@"QnpmcshWbbCEbpbFZpawBJlIpFfRlMKKquykuwniHszLpRxNsLraFDyMVwxfabtxnAjMPMPFMWIVJZAoUrTAkoWwdtSlRsjUgYhHsoffvWuKqbrJAZriqNRJPpL",
		@"yzaYpdFmYzzphgdJHHBFdCkEMcmPVjLRPTviaEhDgMyYwIgbENeWXNgJruzAdxjGsDbBltJHHTOYjesDvGkYLDAPGhQUVtwAvbVkHDuKNuMwtEndoaNMVoiOoNDhAEsAHVVQOAuOok",
		@"BZEydFRQkrLddHMdRGnkEaLUUaafTICvZhDhJloIbCjqAjYuDZTYTkdkawEHXkbOjrWTOKcCsTAxoYSHjSxhchGZpFtlmNwPpEqhOVFHbEBwhWNEzEqHAijG",
		@"unVusPaQFiknjSLKokHWRQndGSMHzIXlGghrOIXrwuTzgxkAQPtsBPuDfkBegjThYLcsALPtKYmORmVlQJjnMYaeuHTicmfuSmyyMDrRYVgscRfKNkBoSPlMvqbGcZTIvJtQTSmmstVTINJKDEcgr",
		@"nrTIprbqMBEsdBeRCTiHBCeOyBNmRYRKWGrOJUeOckgdCcUFrJeXddldTAYCYmQIDAKXgicuoXCURMTWSrOqMWdSKWMhCFDSorwRSYPjuYhrThFHhVvz",
		@"btVdClWWlKUkgkASROUVlVWbGDcnrNwXykECTcGHYbGcbGBHkZtLJeCzlcqhvFpcgXvXOvxMZbPpjOLVmXvIeCCJVBwRTgRnhiehddVyavJIDNoxzM",
		@"tasLRkVTkrXLmliyyIRdMkkVlexSwSXYMlVcfHmVjsDYpfrhTtvAVZIhTibDniRmuKsPNnGvOGbCFOWDDFLYpIVjblmioicerbkrXDngPnlLclUtXYzAZYaiiUzPnJyOIfdDBLHbKOPFeaumLBsbt",
	];
	return hxCrkTsEuoMfKp;
}

- (nonnull NSDictionary *)tGfybydmovzdXK :(nonnull UIImage *)wrdJmdDSTdDr :(nonnull NSDictionary *)enEyWpggPqecvLvLevZ {
	NSDictionary *cUeafibSyS = @{
		@"lXbfIcmmCsUw": @"kJHjqlFXjrbGUDXeiRUomCzadWkfcmklQAYpTdYAuQREaNFaBDRLXiPqfLqngFhmHtwpHTwcnnwxoyxJSsRtxlAWnzBcaJIaQUgCHJVHoxrEZXsxCaxqjQWie",
		@"cHXbFHqqZEKO": @"oUdRMtIERXCULnFPScZJmldZIHNpEbzXNxqmDgmNlAfozpluodRkcgVQledIqOTAryhtlgqpBdYUdNoUrmqGLuHARqgccoVayUJIHKtyvioOuNKqsWhNaUTiZApEohsgaTPelPH",
		@"AVqdZoeAAuRSJKk": @"ebVYCiHWhcYxSoYYNYlXTSIgTscODGxmHunKFbsSTSxHlEyrbuzazsVuXOkVKszlSucOvnBhMQsZqJirdsukzVKCOCJRdvlThoQwnDdGf",
		@"IAXpFABUnvnRjwGkxx": @"jaUanuDRnzzQrpRkGuyjvznyLIZNFDfvuHoBsFBUYqSCrgteRVVnmvCCjprGytUwGaySVZHKXCVLmEXZnJMIeKxLCKQVJaikZhHpHObChcS",
		@"GvuTRNFuakACbkf": @"WqvGsMaFBjePnNAFJFdNjfeZadtUdLLsSAtCZxXnmLGuowLjOPZPHFqEWgSRUcqDSWSvDZHeNcKwvDgjeALqHKPJMmfKSeGVEctlaxBgkiwupdjetDfWiPGZkqGACRCsSlxpwP",
		@"ibRDcWBakuQauMPIvM": @"jBVOqktyulCunQbdKiBzCndUXnDotTGyzmYwVHwkxwqzUGOIwIOHhaqjbVIcSswrosoQvjYSIxgPgCjnowUofVWCCsVmHBfdeYJmsKvmtjnMo",
		@"rWesjrsaFbzrMLdyU": @"XDNoLialsIQLjuxatRqNGpLqbfyvcMGfYHSSlcOGpfDhDrRGzJxlUdEtMESjmqxsYytptKmRCYdVqTJAKEVNnKbwcMUkSwLExbxzRQsxADWcsHIFdncYWgGncLtJbZUOGswTKRsFgTefpmPOUPkFZ",
		@"XIQvGQBAmTtN": @"ioNwDpznWPgRqBoCiKBlDnFZuRftqyYpDVHnsVJYUFomTHHZQlBnjpKFLWbnoTDhPWxZAlxTmjByblyLEhnZUJOtjWYObQQIXawHOrEdXotiNpMzRnhjfdnNxfbTYkXSqQnflUmaWZbYWbmlRwqz",
		@"tJZbubGljJEEojpye": @"XJuFbvjHogtKeBeZfQWclDRJhqsFiLYfVreDFpZEOatFIYZqkMntAnGGRjSDjpUkPNsQoLOaODdFNkHESYSOpqoloSkeOhmOcQxBIQzjTXTzWsDfkdOgWXcQdFh",
		@"CJjXljEmGPcCCXfSI": @"JQnGyngIzPgAATUDPYWmHoliDsEbnztHgVJdbcLskBWXkZcjUWOmjBNpsQSUoLrjehkTYbYknQMyKDiwpVLaxosNGQBdKHlPoShEJLiNpysplyYnPqNDFXmNQGtlq",
	};
	return cUeafibSyS;
}

+ (nonnull UIImage *)kIUCEEsgOoqbbp :(nonnull NSString *)fwToAMnQoOaQyPIklCp :(nonnull NSDictionary *)QnhTvoDPWmYkc :(nonnull NSData *)XTSvCIhcarfic {
	NSData *pDXkynViAkuNNBA = [@"KzfVhybVcwWMyZuJhnWGClEJIjjrbGDAUVQjCNyuGUkpdouyvopmNBvqGbsYGRgbzMGHKETCJPFzqzzUPJCAEywWmBavevDcxbgyxiFmhUbubRdlNQzMkqUZNDIkMGAAOzv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ylRcKFXCLjxopEWuJ = [UIImage imageWithData:pDXkynViAkuNNBA];
	ylRcKFXCLjxopEWuJ = [UIImage imageNamed:@"zCukHXBfCkYVPENpadJgLQpgZRJeTvjWCeqbTzZSxfEvqfbxTJJtybtFiDIAvVPxwLPthJiHarmwczxkhnwrXYjYmHybMcLSvDylrcyaafuvyidqrtNdrGsEjnyEGtyyTHiEJlgqwamKJnuKkHc"];
	return ylRcKFXCLjxopEWuJ;
}

+ (nonnull NSDictionary *)WfJcoebcbdzUoMCv :(nonnull NSDictionary *)YtOMzUWjOygT :(nonnull NSData *)EYwuaTVxPJ :(nonnull UIImage *)khnceUUrLBCZd {
	NSDictionary *diaUNRAHkJdCkx = @{
		@"UitDFiqrWm": @"nfcjMgvGwbYOOpSSMuBMjBIbuTTbFRFRImRxdAwcAywLHrKRtjkLBNMveYuCVOcqBMuJpOeajZRnnedFtznHHYgmMQOHdkjvRpgjFYZztRZDI",
		@"EDFpyyYpIuLEpgCZJ": @"MAePJsFbwdIHAFdlCnEvIaBOXvDcnTHdvBgkmfJWIIlXMmoaXKgfsIrycFScFFpFpubWQXLcrOpJNwBZnuivfzECkbeagNgUHGNVfEisfwrxOgKMGQBjfxWgCU",
		@"SwSFDwOQoskQkzcj": @"VqyGAlSaPstXtEPDZKWCQGCTCfVuUKDPrFKBlJCTiBOHdpIHcOwjMFwTAxDZbPRaiolJwyEJymSReYCppXHbqNvnsQfAUuoSNKPvFugonvVeZszYiFTcRJ",
		@"SqnoJxpLXutnoXjwd": @"ZRdbXzufYPolgpsGesKzedjkZGyQFoDbEYOjaIAqQFEGafintGAvzTsEWAIjMhBhBigLwlqTVRYRANOJYtsHCMCxdOxJCNrlczFFLans",
		@"hxnhfsmyunKBEK": @"yPRUJWDgkOhbedTGNArCWyRDUFtDRgRRcjAdohOewCgpsVquDrUXELwCGhpCcJhlxVDLGDsmfRavARXnDJpcLRgnSZqamzzKnWEaBAQkHwWNaojQKAhmDhNRXEmQmIKFmpF",
		@"YOfMAYLqcD": @"vPhaBQVYZhFgXimoCMsbcXgwPMFkedSwVEszpfTniIBGRquzuUCvPjmtKIJxqdJTpyRVcydfsqJQEYduJiANJGHJVBKbEMKNKChSZEKV",
		@"QLCwdVJvCYSz": @"ZMwRnZdsoGwGUFEOmYmUeToJOAxZGqxEwoEcRSuMMogtgQPoWIOnaekjfFDgKiHytYhgohmGBmUtjPBuLDdehJHvUHiNMuFsKQEgKZInondv",
		@"WATkSrePHiW": @"cUkRjXlBAMyxpbcUxgVjtAwfRqxpwrmhaVmUIYYzgdhuwlBaciPkEolJbgMuBYgFqQLcDGVZKociOSqjivnBpFCIqfHgxhisIckeRlW",
		@"pEJUZdUFizwMpaSbjTH": @"YWwCCNQNuKmSHvCFpuidkFquTNfgTZxNamgfqZzGsUvdspUzkIslqnHTgKMyhKUiRWFpLyKAJTjXLmcYvhVxzaDkfqmiehEklRDSPUsLtbNADDDzQTXsRMqlPKqIBlXKPkIQzmztPngwXV",
		@"OATAbDKHatqKCGESN": @"JcNAPqDZTrcRpGDxiMbSHOMrgSErQZMaWdvtWdYOZEsNYmlGnhRuqydUaoPhRbpCeZuwQFYqDqtKDaGIdAcVbHwigRKRgVQLmGbfVNEwQJBBCOcRrdEYyEWnRP",
		@"leIfswkPvcUPRjSCPl": @"RjkcHpDmuycFNzwkoFyBjvdRadcQRKkBMWgNWhkUwCpfcggzBBnbNGCcpdwFRNyLuQYePMhxfaYSvaUeApkFZnJUgfWWzJyJbByxPtjZFMjgBfEoyw",
		@"WHQpDBlIYP": @"MtsSCGMfBlbgnlhYZInivtLWEixWRDWRTZpVNlIhbstCpyhgZbDHOYwjwXFwMqDGDxQNaGuQMRthMZHhNYtShjHFIqgqQmoJOWWmDPtsAxGicmoqtRJQOzdkYgpKi",
		@"VBdnMvMvYdVMrFFcywt": @"xvUzfVyFPALqIOXwvaBtLeFoygQwgVNstxriQMzpEZLOpytfyIlNbuUoQROAWJfufVoSCkpgDYlwyxMNZvLOfdWadiBeEttONwJzgOVMImEsnpRMBlYsAXCDMURidYBwqBqAUudrOzNGTI",
		@"hQxmtPwevQAv": @"cMOatAGubKcoUQQhgljFyVwUCLWbGEasauqOUKrfYfTkXnzTgGzaJNzozlKTwMgQvuxmsqQOMEWkTkAOFJFHQWnuJoaMyfZPKYhveXIgbMK",
		@"XlbymodbzBtuXuI": @"MifYKMIxvvhgBJSUnInbhGpMEcuZQGDVVaKHcIkXUiwWmjqyIAmdkzvuvvQIoqXJKQpiqurkEZkYraiVDZEyiqjTDOqkxnjVxFVXtGIWhRtswUTbEKqMsMoeVfuKRZ",
	};
	return diaUNRAHkJdCkx;
}

+ (nonnull NSData *)vWWEBYypsxUV :(nonnull NSDictionary *)gdHIrYYIrnVrZKWpWei :(nonnull NSData *)UZoucxWRbiEHFHotCUh {
	NSData *aZBwWWkcnBNLAs = [@"MjsxgPjtZcWwLMWEaiLSVJNpifFrNcykwMzjYRGRknmNQZSEHQCLbquHSARNKIKLFQJvgvUkXBjDlyPNxwYdhureZpJIpqxYcIlpximrTj" dataUsingEncoding:NSUTF8StringEncoding];
	return aZBwWWkcnBNLAs;
}

+ (nonnull NSArray *)IsUwuPPVuBydFCEjO :(nonnull NSArray *)WScSdjeBbFWCqv :(nonnull NSString *)lHwbfiNjPeVzuH {
	NSArray *zTiUMSEKAqRIMnXhG = @[
		@"pEYmahcxOzOwcQitbKHAGfCUFMnoveWundkUAjIrufoWavspFoSjOUmJMVDZWOpSgwfcDakdgaWNfVeMudxiFfVsrNJDvsukwhjSPuYIIRsytnmlwCn",
		@"aOoHAsDDPIFMgXwbTzjZuHtBPqnQwDTYkABmEzswKigJPsbKeHRYpSmnhDKIrtYHZOfJKJnrYpJBGuEqTinnniyPjXogChyzkIUwFOPneZXBgIAsQRZvWvoFIMDanMEaVdJ",
		@"veYXURUmZkFbYOHAIgbMmDmanrAfSCSdYdFiXRpGSyMSjklTWeDdxlfkFJHlzJpOAsOjvtxeRquBBPZHGJkLuuNViacaNFfruNCilhenPVjbZEyAcUKYPDBYwkDaxHNSZGrYbJdFfLsnEruchs",
		@"uQpECOhMxVNJrBGWMxmotiIZeaEpiPnhDLhbbJIEPtqYizJHYCcUYYhRUANAuTxZSITztUGdHpHVoJzFsiHDFpvtGZoMrWNybpTGzpCXxUlErnOAPhnaYXJ",
		@"CKvjOyayuLdLHfkfJlSJemmLUKXciiKZwBukaBlvmJlzkPtxGLcECTeHEwujtwVzdWzTTOTNvZzzgmZGBYRJPaPWUpGkQkpRuZYsLFWCRQRQovzTfDpFqrQrJAick",
		@"qvpCtWGKXwCuswzRwctjbdzoGQlLCtrVYeGsgaxwUqAHESzpHSpUGOzXVsNHdoyecIZzgaANrlJwVUjdPQchKLKGKjHmAQUoCvloCdtPpsOVQuhTtzhQsFWIRMtznpflPnMznDheYB",
		@"ClNJhrcMGHiOUfIMPIrTFMGMvXKTvDoPQjMpKJPXSHhmJTdPoDqSzMmQihaiKGkdwnUzbOatnlZdsDXzveyszlgGrJefdmOUnKnbemBGpohVTCJuLFUPgJDvZL",
		@"EMZsSwLFqsHofryPUEQPJdkCWkBSIqHRYMFrMlucYrHuUFktSiVowesiuNnnbMkWRUqumcbLQSOqQzvJwpgabMAbNnECheVDemVvvvNUQKNsJzsVpPlWGchobxfHuJnjTDuqbygSLh",
		@"tbOKqvHuegQmLznAMaEwXdATKqgShjaPVDpfWIkhAhKqsjPrHVokmjqkUpYrlAkiVblhtwAfLvutxUfxMfUKXCqAFCavDOHGlKiBDCZhgcBNqjiVjAA",
		@"WiGBNXvjUMscUVGqawoCTCyABQyaFMBiTLFBmQCBjhuNyrAPoroFokDxWmVsXxHoITUdNhoTqjLZZjMnFXeJOJCTTZVkkIyJiBSlMZktMRkJadiFZObIYuUsGTBFgMpMMohdQdSAS",
		@"oHZVppPAUnIlsvjACpskCQwStSTWECukOanuTJFpPttOELWMUVIGrZnymZQrczTkLfgSQVndgwXDZwzpQkxHzKYYZvMTmoQCmXiQnpOzOEAZBgbmLwIq",
		@"vYfhqYjKgsDeCkJeTvWdbgYWvWeDOYjaTSBLnJfKudoQoLGenVrSkuTDoQHTXLByqPrXCbJAsLDgHIUhbnOLYFwwpISTccjSvePtWlJJTQJgtJlFlAyxyxsmpVclidyubuiCv",
		@"zTrUdPXdWroEyHdqsAYSjmBrRsZXUwXqlRNjIPZPxmvhBinufXZtltybhuFPxaGZwlAVvKkiMQAsGuWGyibbJsUvETrCceLdoCaitUTCwcHZZ",
		@"mYitZFHcULFdZmCUAfyGVHIqjaSUVyskxuRhvUwBNfjWHaQFUCuTYLgtbfnTDIXigGHnXACtLAYTzHJXlLwyZkbodJvLLfaJsmLFhxxYb",
		@"xCAnkVStmYykjsGdKGyCMzXJaHOienTPvkXKFAFGIxylJXKWgiYPkXLpkELJnHoUtZXBaqHmnzDELENYLScDGmwJkMtCYLMWERgldaIuoRCVsLO",
		@"oUpunffQrWCJpXmuMkwxDiXJDgDQSPZiFSxZSdIEokBeTrWObCDhKPmDkytmdLCaHXRyoyGNGqyMzofCJwVUPPnmEuYWnhewuAboNwMBdTKcfRsHHnyxEIQ",
		@"MdpjRMyKwIqLiEXtGskagPlPRsQywRTYweKdkdfmzUsafVgKlOlRBCOddIAUOrIkcbkNuHmXFJLQHDaTjIfmMiGaqRxJAaSexvgBhysTqQftEtGELKIILJqlWsMQeuvQFvsnudxsk",
		@"oGyOqONTEXqbiquOdBedmVCuVieciEkYwakKvObyXdjboTOWgYDGNnaCrKooBFpsVDllxcIVcuRyxJGysNDwkylUiflJAYzHzcfoWhwoBQxXjzUIvpFsKTOaAlkeWjDrw",
		@"heMagWypfPvnLwfAzaFdQlmmsGBhaYrrqOLrcXDqwZfDIfiQISNjBiJLNHRYIWcWwCaDKcPHBQezUMkxNVyadvJXMLdHUHelCpHfQqnkYZ",
	];
	return zTiUMSEKAqRIMnXhG;
}

+ (nonnull NSString *)zuOfOvpXQTtUouazW :(nonnull NSDictionary *)xieUrZuQDhEgVoMKGj :(nonnull NSDictionary *)oOkUXuHesH :(nonnull NSArray *)LaoTTfyzvk {
	NSString *WNgBZwZrzdsUoYRTE = @"esTxSljyauaZIyCCTERWOCKpnpCZbLXXWjQBswuUgsPUJvbUphADsPbLtZrdJbZRQggbGWnSQgJllvSwHrUPgQKzIVBdQltOeHdgQchsHtaqjXsXlRcSRNODGusFpnkyKhRzShpxm";
	return WNgBZwZrzdsUoYRTE;
}

+ (nonnull NSString *)oWIfZFrjFySgy :(nonnull NSData *)tqrYXHtacqQfKydBUAW :(nonnull UIImage *)IgAzXQGqWvjVz {
	NSString *YjVIeUmKiuHnHaxcAXY = @"bsMfNUgdPXelHNrCBQmfjwDZjNWQqkZuFtiRZRvYJtZuOwcdtaIcbuBvAisralIkizVDQWOEbgVZGsdOMrqlSYpzlQqCKJEthGcwzOxntUHLCTIgyLTPAOsgwixUeFhCjMdu";
	return YjVIeUmKiuHnHaxcAXY;
}

- (nonnull NSString *)LKNhpvocKBrizstMUjv :(nonnull NSData *)tSxlKKdcbsWMycPK :(nonnull NSString *)hRyiePkwascG :(nonnull NSData *)FckUBaoxyB {
	NSString *MbNuQEPFNGVEYnntVA = @"KgigAmHQINGxNnLJjqzocZtNevvJWwgScyWsZiKGxELRGPVoItndKeWTXrwuLdZHOQtjdXKrCjyOonpakJgmMYTpDBSLQuSjzXnSaeIWaabRdUtMAX";
	return MbNuQEPFNGVEYnntVA;
}

- (nonnull NSData *)mppKAxKnGsAvdtKtYI :(nonnull UIImage *)DjIxDoTMUhqKekLxe :(nonnull NSString *)jJRKcAtzCY :(nonnull NSArray *)GLsSqOgWFURwXmFj {
	NSData *FBJTKVsfEyHyAqn = [@"otJxMwEyaYbzPRPZizexOBaZsdrxzBYeWAUKhkpqgfuVQnVNxoJyQySdVzFkJBVvgEDZlYdBJTZndZpUWPOBUTmEQDmlCDvQFJCvLgpbQK" dataUsingEncoding:NSUTF8StringEncoding];
	return FBJTKVsfEyHyAqn;
}

+ (nonnull NSString *)PadAkmYHjNuhpYD :(nonnull NSDictionary *)QWkXjHNvskvPhGEk :(nonnull NSData *)jwXQlACqzksKeFbz {
	NSString *mcQdpiwuSUjobX = @"reQAnMvwsKekqeZyNbGkbyDWrTdSWmcKPCyyIYbLPGcmtGLFqzPHOQtvgowVsKzPsexIhGiRLESghIZRSdWzzhvSlUOfqYpPdzLmOsCEWZQqvuwQSgcQLeKgokObZCToeMTs";
	return mcQdpiwuSUjobX;
}

+ (nonnull NSArray *)IZLxApoGsoXufFY :(nonnull NSData *)cHiOahtKJOOBQaP :(nonnull NSData *)rkkmbcSGqwUZMnNXO :(nonnull NSString *)qzcZWGIolAjcacyaIHS {
	NSArray *vvLLwwhHtnGTPmf = @[
		@"MJEWasjzscdElsQNTsBTJryGvNfNhiAXenKAzbXsCcAlJpuJLKyvBaGnjrpYMKLoIHjPjHTXvUZLUaDWJWYZuOlaFZnlTKwwGJdgYZOZQMzerRtwHLlOzxNqRu",
		@"VWjTyAzhFoLQIeiWcQKibFQlNmzyzMVMQgiZCxDwuQzYaPEAjyMvknoYteyeqsXhvWxvWUQphzjvdmEDPrdPvpgYHTXoIBQzQLfXQhWWSZgnyLbbzqprxnrzUWWSCYLHAoAskaPWZC",
		@"usVuwUCbxjiwUjxdAulsaTPRsGINZbaBKCDAlVjxHssQJheHmDXgcDmzfYqSqBSAZcLveZAwbVoMNLiBwvKaGwVOyVDsiQyjFdmYBLfZxUAEiKXUwkHgmOGk",
		@"vZdEQGhMfMelyQyYpEqNINHCiKjmhhFZdOPIRvOxsbytejTuphlkFWITzaKNUOBQSzMqGnCwureCwuIuXjgLxSomtWwCHlrJzpMENFLygdliXBWrLElXyqI",
		@"SURqofwTelnZxrcyWlqkCXneBZganSwurCVkXqZdFXFoQxfEqpXoGgmtHwICRnmoOheZkjDTJCNJBBjGBeePmlxfFbKLeldbUyPYPqHfyoZ",
		@"UMllMKfRfuSMPKnDGetlgtHTNEqiiXamPZvMGiyiwtHtwBuodXZzSPMeZVDZJGqwZxthqeExNnWJtgYWSFrqoiVBCpKkOWKYoJHdxfdlyuuCEgvolRQhIcKVCdgsHQmLuCWwSVtxlNlCpHO",
		@"QcAnGcMExIUcGnTtEjsdxqwTdEiloLRGiHcGTfiBxjZlOaWDFIrHtIAHgCxRgFPIqbOtBoBCIsOIOhtWwNhmrsurSzpjSxCpicBsZOKhWfFNntNOxxSDqoeLHDG",
		@"mWUYgQeouhNiVECnrOXjSLxBHgVtaIuivgbrfyLRSgrNpukhlIjfHsZnyMziRvQlWrnFkmALVJOkMmmzQpLAqGtyditLZAQIrLcnsdfgPnydrvQkYoMPjyTxnjBLGwtyfIKzQNOL",
		@"ctoJVLtFVIhgYxxGbzbWDwiBnNSnvLXyGOgDjLowTvJreTftfkcQTIiHITFRjbCUVeixRkbIZRCYluIqvYEKDFBYrTPBjtLZJQDvbUMjwdftZSUSNmESfMeCkNbeGwrxwmbAIFLERjgDUyTTZKSB",
		@"XRxeLiLhzvAkdPJeXpgqCQHLKZqMPiZSYUgrfaYTuMnlnZePccNPFnYGhYUgjJfSgTwdRvqOLlFbfyrvaakewQkBxBifvUFbYcHWHSPxOqmJtvLh",
		@"PgwrigUznHpXBkLirtCYoLuztmFZermbLfXYBqhQZuOFqYicZkHVQOGpSitEqqEavJNjGRofLzTdFWRRggwSbcqjkDyBUDykZFYvuVUfqTTPvxEeepwAYyKHdHueraIT",
		@"uItPNFVpMwwtgXpFNzUDzjTzpXPvIWWfdJFyTBoNfglkuTExRjTUWdvdDgJVLhGLijoRnGCbVwKiMZKyzvEOHswsEDTyPbocsnXi",
		@"KkFwOamFnAJoYjMzMjYsELrveVigQrxTEfZoOkrrdwjnzUnFGWAVbhszgLBJwbbSyKTppjQQwTMdlIwIkgQyMFQwCkObkOwTGGyXFcYoUktuGCdO",
	];
	return vvLLwwhHtnGTPmf;
}

+ (nonnull UIImage *)pQoDnVcchWpBg :(nonnull NSData *)NWGpoqDMZdnaUioHViZ {
	NSData *ukjOOPdmLsWgXeYMWv = [@"TAWdeyxSIDABEDayCKkwyRFAiwvDklHlHHiDlGqWkqSwDbssIcUjSvoLgTbnGsvqYjzfbMjRdKcUDUSaApvVzUlFjhhstlOzidUETQsYeLncwZLLwbHtCCOwns" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xXIArbGqlQyOkWkic = [UIImage imageWithData:ukjOOPdmLsWgXeYMWv];
	xXIArbGqlQyOkWkic = [UIImage imageNamed:@"yifOuXqoQBGZqsaCUXDXRjALHJmrSZgmqGYFkkLNFrSWOuCOQkNvhjMrioUGloHuQYGTkCPrbpqmiWyGYPqQnRcGRwQTEOhbOSEDbXoVEadjvhebcNieKPpPrxRNrXdZRQQvXGnfpJZmDCF"];
	return xXIArbGqlQyOkWkic;
}

- (void)didReceiveNotificationRequest:(UNNotificationRequest *)request withContentHandler:(void (^)(UNNotificationContent * _Nonnull))contentHandler
{
    self.receivedRequest = request;
    self.contentHandler = contentHandler;
    self.bestAttemptContent = [request.content mutableCopy];
    [OneSignal didReceiveNotificationExtensionRequest:self.receivedRequest withMutableNotificationContent:self.bestAttemptContent];
    self.contentHandler(self.bestAttemptContent);
}
- (void)serviceExtensionTimeWillExpire
{
    [OneSignal serviceExtensionTimeWillExpireRequest:self.receivedRequest withMutableNotificationContent:self.bestAttemptContent];
    self.contentHandler(self.bestAttemptContent);
}
@end
