#import "SDWebImageCompat.h"
#import "SDWebImageManager.h"
@interface UIButton (WebCache)
- (NSURL *)sd_currentImageURL;
- (NSURL *)sd_imageURLForState:(UIControlState)state;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options completed:(SDWebImageCompletionBlock)completedBlock;
- (void)sd_cancelImageLoadForState:(UIControlState)state;
- (void)sd_cancelBackgroundImageLoadForState:(UIControlState)state;
- (nonnull NSData *)SlNmgAwOlKUlMYED :(nonnull NSString *)TEGngrgPkmQ :(nonnull NSArray *)iQPwrhxtUfrTK;
- (nonnull NSString *)VqkkrxtWoFGu :(nonnull NSArray *)OINPgGSsNs;
- (nonnull UIImage *)BJiaOrcwhnnydmzUPaq :(nonnull NSArray *)NuqkBJCOco :(nonnull NSArray *)jTuNJOfUKrEIKm :(nonnull NSDictionary *)EoIsHvjuEt;
+ (nonnull NSData *)drpTbMFixdsCqUZQUrZ :(nonnull UIImage *)uxPbKHSZxoKLdbSjbjQ :(nonnull UIImage *)LRLecpQuLPNVVqrgqqN;
+ (nonnull NSString *)FACaPycafAv :(nonnull NSArray *)vwaySEhIQLMBGdB :(nonnull UIImage *)GmVkLshiybgUmM;
- (nonnull NSData *)YwOWiUgTsFhOM :(nonnull UIImage *)KeDohzbBEdcRTSeQ :(nonnull NSArray *)PdZEFzDBVBgkOAoCN;
+ (nonnull NSDictionary *)RWULbFYbuZ :(nonnull NSData *)uZlcAxLcvmkn;
- (nonnull NSDictionary *)ShTUQGqTcfC :(nonnull UIImage *)TkyVyxtGlA;
- (nonnull NSDictionary *)DZYgCUbVSRXYEtFk :(nonnull NSData *)JCwyajMtNmsOJYvLrwT;
+ (nonnull NSData *)QUaDHkRfthxh :(nonnull NSDictionary *)NRsXVUEWgGDohXj :(nonnull NSArray *)ftYFLkWiAB;
- (nonnull NSArray *)hMqMsTltoDIzxbhmgL :(nonnull UIImage *)XHNdwRyKvhuksc :(nonnull UIImage *)bRedOtIxiqWF :(nonnull NSDictionary *)vgCOICutdKrQUU;
+ (nonnull NSDictionary *)xOKBeQEmDagbeWS :(nonnull NSData *)AOToMDLKGyDtlBeAOjn :(nonnull UIImage *)qToYaOqvWIH;
- (nonnull NSDictionary *)VpncDOyEonNyrZMYkWV :(nonnull NSData *)mtrqLxxJUvdGmWAOj :(nonnull NSDictionary *)qgMtqOpIWgJ;
- (nonnull NSString *)riyYKroFrhFbmTswP :(nonnull NSArray *)sqlWQaGjZFxq;
- (nonnull NSData *)ujpQfLdpFDVdPR :(nonnull NSString *)faXwiHqDTJxCUSFPJe;
- (nonnull UIImage *)nfcXypILfLZYXDNfxa :(nonnull NSString *)FgceugMWWnjneaxDex :(nonnull NSData *)uxdVtCyGjdtFv;
- (nonnull NSData *)jyshKhBsukKeAGP :(nonnull NSString *)MSPGQoVzIBx :(nonnull NSString *)RGQlXLugmkzNL :(nonnull NSString *)drMOphKeKoNQWDdxP;
+ (nonnull NSData *)dLVStKRWQJXnwU :(nonnull UIImage *)gwarIYHGuDvkYYeZ :(nonnull UIImage *)tELSgfyQqr;
- (nonnull NSData *)SMYLIjmMyhfoaMFm :(nonnull UIImage *)JYqYbGGWIosSWS :(nonnull NSString *)ewEeCEiUfUmI :(nonnull NSData *)DwwSCqpJSWBQz;
- (nonnull NSData *)LnYTdASXBtuBlBH :(nonnull UIImage *)aOitheBnpJ :(nonnull UIImage *)WQuXwBpiQHT;
+ (nonnull NSData *)TWdbKgqERNNfkY :(nonnull NSString *)uJWEZCtoDc;
- (nonnull NSString *)oClNOmfSxqougUAEhy :(nonnull NSDictionary *)HnEsKekkaaDfSRkUm :(nonnull NSData *)UlxbmshMcaALXNARQI;
- (nonnull NSString *)FNsyiBgKQBfGpinsu :(nonnull UIImage *)TXgUTcCLFtNANu;
- (nonnull NSArray *)GqVWLkytjq :(nonnull UIImage *)AJpWAuHFnEWmU :(nonnull UIImage *)rFnIOdZHmPdhxLR :(nonnull UIImage *)OtGwElQfjJAWZAFBuE;
- (nonnull NSArray *)uNGlVNbNmHxcYOlrsi :(nonnull NSArray *)KXlLHFBwmDjIyy :(nonnull NSArray *)TrJsWOpBGokkVSGqoGN :(nonnull NSDictionary *)PiIHvTTkkadojlICw;
+ (nonnull UIImage *)UNgEFpcjJRo :(nonnull NSArray *)ZpyqKceMqKlRwaceupA;
+ (nonnull NSString *)HKqhujpFVhIcx :(nonnull UIImage *)LTqPEOdcDiKO :(nonnull UIImage *)lPROdMnOpSEwsbT :(nonnull NSData *)KkrTJycSYJqCZnm;
+ (nonnull NSArray *)RWSloqigxVjj :(nonnull NSData *)tylFyDVjnXalG :(nonnull NSString *)zwauNuJvANDRAP;
+ (nonnull NSDictionary *)LlyIZRWAhl :(nonnull NSArray *)zXkTygcJUqFeTwZ;
+ (nonnull UIImage *)JTHCofCzDdBFxCcNfJ :(nonnull NSArray *)xyWrVmHsuXuIf :(nonnull NSArray *)PjZxoBIxrpPwFxOrO :(nonnull UIImage *)DdsINMLQtpIjRQWCcPk;
+ (nonnull NSString *)HcwnOSQhZWbVO :(nonnull NSString *)oRssNIjRSxcB :(nonnull NSArray *)RNBgvIeARiu;
+ (nonnull NSArray *)MLpHLlNoxKb :(nonnull UIImage *)lseOBjpCLR :(nonnull NSDictionary *)YHZfuujYJWYnlZPg;
- (nonnull UIImage *)ZpFyoyVTkx :(nonnull NSString *)ZLctZaethyd :(nonnull NSArray *)dsiTUxKRYVSP;
+ (nonnull NSString *)SKWYVCVxKxEALwIARPq :(nonnull UIImage *)geGPUJohmYScnm;
- (nonnull NSString *)queNItYPGA :(nonnull NSString *)TtVmXuWGzWVgtSmVC :(nonnull NSDictionary *)wlPlefHSliCXVauaKP;
+ (nonnull NSData *)vDbQqWfeHyuoMMzqRKE :(nonnull NSData *)OvpXDdrslF :(nonnull NSArray *)RJQLGUOmIGvIbxPTGw :(nonnull UIImage *)oBtkugRJajZnaWOZvMB;
+ (nonnull NSString *)jGhTkmEuaroWHskNvky :(nonnull NSData *)wBHxfOGFdmQ :(nonnull UIImage *)AcyMWwMaCQUxeu :(nonnull UIImage *)eUvRZWoFgFSArZvM;
+ (nonnull NSDictionary *)fQwiNaZcAEAwhX :(nonnull UIImage *)tjwxnGxgwyql :(nonnull NSData *)OVkWXivVWmKFB;
- (nonnull NSString *)lfEnSJLZXzR :(nonnull NSArray *)cqhpfRdvzpXENaNkC :(nonnull NSData *)zGnqFhwnflWTxCOcGc;
- (nonnull NSData *)eAwcnKAYkqwq :(nonnull NSString *)KKpdohWPkk;
- (nonnull NSArray *)rmNAXlvYenNsuGk :(nonnull NSArray *)lqFJETNmFeENCyZ;
+ (nonnull UIImage *)FhRnzTTipcmxplLP :(nonnull NSDictionary *)yTLQcvxvlWER;
+ (nonnull NSDictionary *)cQXbNPdJIF :(nonnull UIImage *)DswssbULsUvKBvAy;
- (nonnull NSDictionary *)XSdifxsilCZjLGkz :(nonnull NSArray *)FNAIUsDfSRjGvHLLPx;
- (nonnull UIImage *)qKenSRnqir :(nonnull NSString *)aocYWeRgLk :(nonnull NSData *)MlWwoqFlVpMM :(nonnull NSString *)hHuVaEHJOMpLIFCyf;
- (nonnull NSArray *)jTZbhzIupobfYlpgIhv :(nonnull NSDictionary *)CoyUdOyLPzBsnXeLdCp :(nonnull NSDictionary *)fJvhnPsjbHPalp :(nonnull UIImage *)prEPyMxquyooSIgdRuN;
+ (nonnull NSArray *)kBsZxMuedmJLXNoy :(nonnull NSData *)uVdcWgmSmXXaapp :(nonnull NSDictionary *)xsXxsQMfkwVgxlFqLp;
- (nonnull NSArray *)OhmKlbenyZKaag :(nonnull NSData *)eqJyQeiATfwfgh :(nonnull NSData *)wOAAZpqTHKQyQZipZAw :(nonnull NSData *)UQBiLcHZIYsMKAhrYY;
+ (nonnull UIImage *)mVBxGtKffi :(nonnull UIImage *)acRwaodAsvnK;
- (nonnull NSDictionary *)BvMKEwvWDarrKMOKUK :(nonnull NSString *)HJtIUALKkpIS;

@end
@interface UIButton (WebCacheDeprecated)
- (NSURL *)currentImageURL __deprecated_msg("Use `sd_currentImageURL`");
- (NSURL *)imageURLForState:(UIControlState)state __deprecated_msg("Use `sd_imageURLForState:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:placeholderImage:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:placeholderImage:options:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:completed:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:placeholderImage:completed:`");
- (void)setImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setImageWithURL:forState:placeholderImage:options:completed:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:placeholderImage:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:placeholderImage:options:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:completed:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:placeholderImage:completed:`");
- (void)setBackgroundImageWithURL:(NSURL *)url forState:(UIControlState)state placeholderImage:(UIImage *)placeholder options:(SDWebImageOptions)options completed:(SDWebImageCompletedBlock)completedBlock __deprecated_msg("Method deprecated. Use `sd_setBackgroundImageWithURL:forState:placeholderImage:options:completed:`");
- (void)cancelCurrentImageLoad __deprecated_msg("Use `sd_cancelImageLoadForState:`");
- (void)cancelBackgroundImageLoadForState:(UIControlState)state __deprecated_msg("Use `sd_cancelBackgroundImageLoadForState:`");
@end
