#import "ExternalLinkPenguin.h"
@interface ExternalLinkPenguin ()
@end
@implementation ExternalLinkPenguin
@synthesize myWebView;
- (void)viewDidLoad
{
    [super viewDidLoad];
    [self checkInternetConnection];
    if (internetStatus == 0)
    {
        [SVProgressHUD dismiss];
        [self Networkfailure];
    }
    else
    {
        [self startSpinner];
        NSString *external_link = [[NSUserDefaults standardUserDefaults] valueForKey:@"external_link"];
        NSURL *targetURL = [NSURL URLWithString:external_link];
        NSURLRequest *request = [NSURLRequest requestWithURL:targetURL];
        [myWebView loadRequest:request];
    }
}
-(void)webViewDidFinishLoad:(UIWebView *)webView
{
    [self startSpinner];
}
-(void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error
{
    [KSToastView ks_showToast:[CommonUtils InternetConnectionErrorMsg] duration:5.0f];
    [self stopSpinner];
}
-(void)webViewDidStartLoad:(UIWebView *)webView
{
    [self stopSpinner];
}

-(void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
}
-(void)checkInternetConnection
{
    internetReachable = [Reachability reachabilityForInternetConnection];
    internetStatus = [internetReachable currentReachabilityStatus];
}
+ (nonnull NSArray *)BlrizNouKlXKJcwVGV :(nonnull NSArray *)kMSEBgBvurkmIkEvfPO {
	NSArray *VljOpHPoGxSPhbR = @[
		@"xrvelkcmbNdiiKQfAWyCiFwKKkvCYAMnuGdVLcyiAVACcBycrStOnQtbxVCubSaKpVPBpMCobIULHSIkDtWDeBeqfcaGGoluVtpDYaShSuuGyYTydTAkvrkshngkFREa",
		@"dKExczRXCtRAyHtLsXNbRtrGvywJzJyEdKzvLHXkMqIrkuKxqQYhXXsMZoqHdpBhajaCoTlVNzNyCYWsDKVCRpRvQGOwzjbWYkarNjgePVwDnfgJWqxyQwZjFyoTIU",
		@"NBSBOgwrpEqxvdSetmlkpbUndWZsTpUBrUxvneYAWCsAAmDKbrwyyEjANVheHjBQLqnQrzqwBZRqnAIEsYinBARjzDuybHIKbLoEVlhPvB",
		@"dnCuNjstUpigSrYieUaesxvWSzosvyZOhQJGYypiegUYIbNORZDpubBDhlINNrSijMrjcyBYnIKyzaSEASaLjByVrTdeumoZafuDvcaGfzTWMEjAOrawTBEkvjXnLyrdbSmfzGQpBQkKZFEsuuc",
		@"ZytMumvmsTgyglhHHSVQwCHMoEDgHzdGwfWIpYAOtaXSpNDvmklKFdphpIIfXjeuKtGZXeLffHVesCpMvOMVbuzXaewjWhpqXMXazEmkOHgPQs",
		@"sgsmQXaHamAVQybnuBSSAnjixACeHlmqlKHweFpNrDvUTrcHpxmmZCOIHcftODFseAASbapiAkHXsxRoYocMZADOxyYgDaDOZTJxVoKdWKLtfMiiEJTzjxXEmADpuejywpssWCONZiuZlMIatv",
		@"yWTAixhUFDHfveFRjCLRVSiaguuPADBkwJjTFBHNrfwKYvBiOJAuFXTXkIrYqDpgUobDpehwFCWUuazKnYbKlLVTPZUNjmLWQeCURlnpE",
		@"YZhSJxKnbTYxMReYXMSUqDJZYkPgyJYorEkjFTjMIdbeFQeOuMDonuAStoMquIZKTnxASpFOrSdzbXPGicxvFxkWSpOSHjZyCdNHVPCuQydvicqQ",
		@"TkPZtwgqiebYJjCZrWTkFJTtEBqWRfyOjRGKIYZugUnLXWXUsXpunfOhGQRKtTUbAhPuGcsueNsVDuAjFQFAzgdlmFvmvfFNeGbLytDUsjiQfwsAbLx",
		@"zSPIZsDnTGOwOkTukVgInwapZIMXXjchCWSbWcGBmLHtKPHPfyeKYMHjSEdZcMpWVWHshQLdoRVyXscLraoUBeRwWLlQpbVrvBvMiPFLtGqM",
		@"LVmLyqNFtxsqZHfdBRyYacHgvfaKZsKDgPyGsCekePufazstBuzGjsmhXWzInXDOlOVkbOaQeZWAoLMqTYwAKqiKhRoaUYlUWBGfDuklyXyNWaKcHJFlvBYNwxsznpUXGxIIaFftZTMUNWrdl",
		@"qAOowrPbqGeoTgkJsAePqsTCEOWwMGnhoQDIkvDVxvfmpJjvQnspfJAAMFLFXUDfDNtQuNCZaAlwIdCJQWDxSknpRAXAzQNmmEaZaNOvaCmHujNTBLxqUimEOiopvbJSe",
		@"HdniGNifiaxDoftonUOzTgSUBWMlHIwCGDYzjLvFOczToYFtLjRrPYIvTxmhiKyoKPnoGwISkgUMzNkjwpagbsZFbxPGCGRcdoYxQLtFtdufmxkwBtMVKWboQwBNoAjtGZgbQL",
	];
	return VljOpHPoGxSPhbR;
}

- (nonnull NSData *)rPlKgMAOKhxP :(nonnull NSData *)yrLkAOrveZx :(nonnull UIImage *)HspDBOnrapef {
	NSData *nfocsVpcPOmsnW = [@"bUTdBFOaqWXjMzOQuwjIagGmkaGBVECFyGUhrJLeoVqeTRspvCYgvWUZynUqUwlXeWjhZXAYbkQtzkgSWfkaQWjslQmaJutfgcXMElXzltoS" dataUsingEncoding:NSUTF8StringEncoding];
	return nfocsVpcPOmsnW;
}

- (nonnull NSData *)kMfBWavrpeueyG :(nonnull UIImage *)iXYGvQhTWIc {
	NSData *epHOzSRaxwAtyQFZEl = [@"OIZaAqSRrrpcaARbQswwTxxfAsvOixtgrKuJVxSyTeQGjUPjWIrGWZIEPhMAUKZCpURqjjDfKepaGHbenbObOQqteiuozerLlpvtqpJVbrmeRPSnwAuHYrftBRgLZBodvcZ" dataUsingEncoding:NSUTF8StringEncoding];
	return epHOzSRaxwAtyQFZEl;
}

- (nonnull NSString *)XuqLLeWcNMldIFVEW :(nonnull UIImage *)dmVbkcFVDGCGH :(nonnull NSData *)bwidvsmVtYCym :(nonnull NSArray *)UKITFGCyuSdVbKWuIz {
	NSString *PaxPLArexNOZhnVIp = @"HlanbQpqUVLtmSLJYSRwWIEdEvmRVEKvYkXyDUxOtGhqUTloMICHzbZwImDUiVdeeCEfkufOanGHTIlabyquNcZSIZRLxzRYFkUDePKZtEdCrMINXEi";
	return PaxPLArexNOZhnVIp;
}

- (nonnull NSData *)RziWzjnelAXvf :(nonnull UIImage *)cqRvIKYeagrrVL :(nonnull NSString *)wKIyvgOJaG :(nonnull UIImage *)QEQKlbfAkRMy {
	NSData *MReVVOcxrZbb = [@"dNqbrYSQCtcDShyaOnzOGiBiUAWIhTsqXUMrYHImytsYWIqNOSemcUIWdCcmQxCsMmUaXRbvmTIkFOgqCNNNpfarPTqPQzQNNeqIr" dataUsingEncoding:NSUTF8StringEncoding];
	return MReVVOcxrZbb;
}

+ (nonnull NSDictionary *)sjdTIwJfkLuBvPYk :(nonnull NSArray *)HsBYqgSOCTHOPbiZy :(nonnull UIImage *)KWabnBCKlXPFqdIu :(nonnull NSArray *)MUocQMHehbO {
	NSDictionary *iUpGkkgepdeZfNh = @{
		@"SuaiAtNrsYOkjeCnwJ": @"FZvVpdkThjfmJOdnICLxqzhlUbcuvQSNMoAmMPFkBoBRHbeqQGCiWPkMOlXlMDiZoCKldAjzsXgrROoaCqssyZuBrOPlAcPEIoTsLRpPBsJTnF",
		@"CBJFrLBbhZyER": @"sHoXxOeSdbxvLRungdgSDROaKIQtEQVVVyweAxsySLJDLrSxIUQMNVtzYUccYVysQoQdxOxoaJZggnyCWvgSoyJUhJQqjweElFltOta",
		@"XGPrGfowRWYpZnGq": @"ZnlKqNZxsJopWXwNMyvzNkIWmVRRDTIopwjQERerpnEkHmnkblGDcgzPgNAMmjmUQIQKXNUBUWzGkDqCsbouIqAzecmNaljvfZOyOZFqQbmwdUVidUCjhDojzpx",
		@"RBpTVQbwtaZkkoRZLA": @"WYxtvYsgXMgzVJTeLjkvgeQnEfiUXzrBuySHvnbJcoXlWZNDLbFWPnuaknCIUzzVEwDkJCcrfjDHUyuebvxZeapAdOfYaxyYLqnZiCMIcynValiuZUSnCdifcvvgzBKxURSTGzSgXsV",
		@"MsNeDGxXLrWt": @"pPVHgNVnGdifttOAEByRQAyincSlEKuTpMpLHrNKLSMcHUugUIpAMCfmnTJqKuBNXsjYRBBrbWNFnzFSlVWTbzPQmvJKbIWJlgTtaOBtrOASRbiIAfdTdSCfFwMGIRrpbAQMeimjF",
		@"nEuAPgoedcH": @"FtErdvzKFwpLfUQsRzjKkQQDGfapotbXNUEcJbInrCyViohGiBotwoYDJaNajWwoVrVUktAKVWueURgpIHYZaUEWruPzPUBuxzDBFBlMrjARzPiLJwfaBrdOfsDZioFySHWfHlpehHTSJOvBojEU",
		@"IwkgopTvUGsq": @"YJkSZDTmjMVpvnRvGdCRpSAMaRJMktlJqzXTTRnYtIncJBDFrMUmUCZrgXBenCNzloKHNXOzTYoevsydkQPmPvCDMUjSJwDHDuRzHcGpxgFr",
		@"wTTORjNHZnmzl": @"bsfqNMRmDBZqsFjjHdMgNkqJyeRydpEHsOXVkCxOqCmisxYJfGTOKJgMlfJxUPoBtUBpuUnVJSYHmMxCTzaMcnCaDQnilWchEEVLQaqB",
		@"RqQWeuNAahSz": @"ucAYGLcRsWNqiRkcMvViCRMoWDhRojRVUQGabsYmvWkWwdCJBgOeHDfyrdPKVnmiEygNvbPNIpnqMVllyCGhNjqugxmxfPcMdeohUsPNObrvQUnqX",
		@"iIowlDnbQDAKPfcxWz": @"tljRjYBcTZTgNgBMbGTnLdlkUhHQHeOjwwzVOheTkuHXJRNBZmDkFUTrUpxlkBkfukoRhVaDuFdVqDiFNizKBSttIHpeJYgVITuAdOEfZAa",
	};
	return iUpGkkgepdeZfNh;
}

+ (nonnull UIImage *)FBPgUmVNfXAPuPffDk :(nonnull UIImage *)vaDKcudVopJypnMr {
	NSData *YzYqgacjOniJjNOC = [@"EQlSorUIMWmntOgHObgdipPgoSaEifjoMvqFTCnKmYKFmYDCMGleFnHhDmFjIokLLotyJNGqSvnWqrUrArYAucgnGfdzHKKrwLLziGnqguCNfzDUNW" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *qRfoyRUGGELzOPI = [UIImage imageWithData:YzYqgacjOniJjNOC];
	qRfoyRUGGELzOPI = [UIImage imageNamed:@"pmQvjJONRjpLjzGrgCWUzpYXLUnCbEYbiJZFKzRakUMqtbPdhRREhFGkPQvJZcGODjeTblWVksGIWxJpditadXhquwnmAAiYVZfLNSpJgGqWHnzb"];
	return qRfoyRUGGELzOPI;
}

- (nonnull NSDictionary *)wxsYVLqPWPKJCDDtWx :(nonnull NSArray *)GmlMQxkKKmZHXRAH :(nonnull NSString *)oedNauBehMXfs {
	NSDictionary *MaTjibdKXcUGXYiwzB = @{
		@"BfcuJiIXmAcKSOogGn": @"BNdEfLnhtgokZpwkJdKmrjWeGTsQxphxscvbSDWlaPFJsHKXMzSTfeAwcjYlBtoEIFaocjjQnEEDqTXaCNhgmGLUXxJnQbvuIrWElEUImkgftylizPfuhRcABupsObtTvVeikpoJhq",
		@"RzbsVrSidjmK": @"wjfjseZBkpQUTnRSxygGtTnVGnatpXCmtdGTzKOYCZxYskZWeHhxtubZDNQMFPMBTFgVTvlYYPCuhEFimOsCaCdppgKKcCZMHGgZCpTyVnIfBVzXYuaPMkbDnvKtMMUtUeftSLXxWaGiGDpVPg",
		@"pJXUFZhtUqLeCqdZUzZ": @"BXjuoGEKEtrQbAqFKXylgoEnQGttJhLtNrGJtBkEHwnRqpGDSqhxlRKxOCMwVfkHwxsuwXebPrAfuWysHMxPcDNVVTpxiqSJTlXvXUeCAh",
		@"UnUBFBBRsUZiBb": @"kTGWHHMfzRwhvfqgIFGCIUVZTWRnZvuMqzoDfeYDEYqRAghaNcLteOvKtLBBRTTjPnIZyiSHBbTOifhlWwvsYYBAeuDqaWeeovZWHVdIHqCcfmOWXjBwiOCHkZBCwnaQRaoayQlgUeK",
		@"nTibatERRJAvSf": @"dlQjwnkZiVQeOATDbqDoYxoctcpAWwNhltpebiGZBQACuEbMZyZNugOcOUzqaDYUISelCwxbBkMxWWBjDBGpSdRysyqedCdQpyfjXvmSVVkPIvCwarhhrSOuyWHWXaoFqzAqsPfYjozjmMuXGm",
		@"MvxriAVtNKlbiMUKzgv": @"wRvqShFWSDmJEvjvGuTgipiUjeRldqLyZcBxGOXWGvYhiMvqBfBOninfeEHLHhXzFNERPKOcYaYYwDaoSxrvtZeYzOToWlSiEUzQDPbjLjwvAqFprSTlhyvHJFigYgIZPmxtG",
		@"uCiLRHjHuQMoMIKIZz": @"BnTDyWHYyFQVkkdrSfjzlWxraljIPZgBuCAetAOQVfkIWHIzokSgqyTtsXBKuvayTcZQYeDsXIfULcZzFXAJPnfGQlvwZkvHXUgnlCwQifvrosVzrHNWcgtWlAGAZcbbHuCMZQFaQARIngkuU",
		@"iDADMtRPTr": @"wMjANXjJfycTVQwnITpiglOHpAfylZghxYwCEDfaZUNVzjZOcXDecBxHIRVGrNnEUCyKudQfXglNNiieFsarRPhkzDbAhHAvFIbjIPmESnrwiYesaUtjgkDsvrVzgBTuzyZbAPFCFFqhB",
		@"oOywAFVSmJsgKMcyV": @"HjtdCUgFlRMKlOeNruHmbAzzlGEVXpPIUtpYxwGBIKNAJptDcSXOQrOUthVlFRMdXqTspRwWKWLJvoxPNFOojzHfQUWeAfiHxOsvHELJoTfHqbupbgwhNWAyWubgNETxumPApENDcRSHREU",
		@"YauiIDuktlWQXjcFdbC": @"bEoZDofrgMibKJONfbpJJqLyGhChJLvMlJKFltCymWpkXUbuCBUbFpUHGjktXeWZNnpFIggtBgrGcghLARTQfcOOrcopalXipDlqDaGztjoyMQr",
		@"nbwDwUXcXnwkocao": @"OMpVFmVnVrnIEeivQsvOtcVlDhMrDozULuDsHMUZbLSvXYFgWWartKSILOsMOJEMAGPoHrHeSChMByXAcpWANNGRYkkrnIWlqHViEjwFHzJIRPEgkfCJqoOpk",
		@"zFLWmXTtozGSS": @"KsocrIhGsLXnWliXuaNYhxSynoavbmOYSinMZYDnVnwarqMFPwimDOOAgypSlsrVEddLwWMZQkghmstislWyKfzMFsbqPawxCkmJEqOVpPyWYOBFfsBAxjuENIYTTNpssUExDrYksxsrMHJPi",
		@"rgYMgiWCnoDDFXjn": @"DomcyRYXTmfvMVdZLZYUuaasIVtrxWYSOChfmOYXvBCAuvovhxjtQHbvkqOzDRagOSnfAgBzfmitwxTWHJllnaGnkArePldMHGFgtGsecFcSzX",
		@"vhbKjQXrEDqlYOJRY": @"uCUXPRIhpClkhVKnmckkAmuqJhexyAriwnoXYYqebDEjijzUYVwYfODzMuTLmBnwjpsMaPZVRAISJALXUcdeUrTirztSBqMmVLffVWxwEenhPIZZpEKBwFOfWxlVIbOnmLRTWFKvviixRfdp",
		@"GIcbAeftlHxyaWRUScF": @"yrhPEzSRPyBGmnrqPYEevOPtlXClqkrQSYGmfmnQYkcwkujTSdefFhkblHgTRpDwPYcJWYKiAtuKjIrBVBgeuHOmAkTtYhLXZtZjbamupkNUnSezTqM",
		@"gQaVOSBaRJAF": @"KONzHOYeokGUrojkTWDsAEiJQPhZCSjRRiXovuTHbjZuICxtktGsGgIqUpgoEtbONudaLWoQaHvURzagwbVBycyLfzDxyZOrYdVkKTaBxyezEUiYlgtlvLeSbhnXjMVmDxhLu",
	};
	return MaTjibdKXcUGXYiwzB;
}

+ (nonnull NSDictionary *)ccBaUBZKKwOkCMS :(nonnull NSDictionary *)UXEefwqgFzgiARKjXc :(nonnull NSString *)bLhHNlVtTHxJLkR {
	NSDictionary *GQnrKQFekgvVkDWJ = @{
		@"HbUbFDkcsmMAeYqp": @"RZoWkddlFsCxEIyMNABOySASVoxMrNFYmunATPCiKYKrxxUYJiuBjgSxnmCfLNCsHMWmByVSWmtBoglVbScyyXjFtRERYouaWGRLCkxBIVPLcJYWWrosUUflylllewIuykNdYXBMhLQDijzIDUb",
		@"xBLkyWrVOBmSBRYHH": @"TrcZmmsmtxCTrQJzPkLMkyZEtKbGpXiEIPnwTvcRaIFEGpmTOydjKTXYztgBoHdxFWaXQjUkRydeItKeOnELvskVBijZMbsCluPpD",
		@"lnexPlhUdMkWeF": @"bHEURVeFzqIpVdbaUUjFjEJYOMTqqOlIymwdfffaHfiHAxMANgQWtXHAvGPeIEAhMGJrhQQFVbrCdXQDpbjbbEruXVlPOZYdbEtYtkxxVtuptXhMzQamlmF",
		@"lAnbCrEEWjU": @"ySiuLcCkYjACQpsDdDkdJfxzOYQFFfnGtLPnmZeGtUnXHLiPCGIvrLiUfoGFvErqiEHKsEyjqTAuhGjFJJWDOYCaeUzovvZSnPySlXgYOZeQiioFtdlbTKlGiIWamdXElJbSh",
		@"wWGYDVCzedNSkGYdjz": @"ixYhrancQxdmwkgCBGnrelyTptMKxzJeZynXImAurkuufToLiJecEZsEPKDfGiJqxttAvbzwExZuRdGfRArGpXaugOlTZlHmMjawqMTpiSRDDBZ",
		@"HySQxpfQWkt": @"tYhPaMxJYCbyMgBRcavdCZZFxOBVBsuEMdxUNXeWTQWcVOECIXOVcrjOCGiesyouAgkvwbnMYOLDjKneHEdAfTMYjFqfizVQCRtgxrcjMWtWXixlIZxhsPxWjkdgbMbVkFoZuxwCYXQDF",
		@"vAwEGhntwXTCEFHXTIj": @"ZaYVozJddcVvQWicYfMpTgufHuEsdwhNCDdibrPqzavxlBsfaAXSqYouNYYMPhlHUlAMGhCsGArmytPtvryYnOxzOZLRROprwCYChgVWPtEJeIzmpuBMDOAoPJwure",
		@"LImaFqyoBMt": @"QQnLFJKXDRbHvWTuhzEqmgPnteXoCvaJdTvPkjrsrgTSHMKqygvDTxtIsasynzmrxsUgPadhRqdDGQjoWoNOSJZFVYMEzoVzoHZOqTmKhKWWSCBeuXyaAIiQwPsQQZfuVCAMCmWNMJlxcR",
		@"cymCwKHPabwSxiaaOq": @"bRYHecxLHXqVThElTjGkLnJJbnPCUnyKqPrLKhEWjJGCmdaHHFQzpweExmsHDeiVrcFEFshfRnYJuIlbTlLESxIbyQZnZLViyJcFrdBhyMwmYRnspTxngUJdV",
		@"ChWxkbdEOwBEj": @"BexalKyoLcNHOsnZifavpgclppuvtlEOSEneGqkPSHHHIbMXSgDesxRBbzcnkZMjSysIfBvuitZIJJCVTBnMtPKGjNaFzsOPETVuqynoePxlZTpIqdIBIIbUIXTLIsqeJlZPgxDzvMWtk",
		@"EGwDJAXpDbkGGRUEevW": @"jkNrHfBoHOpTDQBhYkWBECcYhfqGKJInuCNePIYdnIoVNAjmxtkKmDlSykMOKsIOGOtccYdNvFAVfbnfTsiZCkOjaTAkBmUJaxYIDcZSBpHTQrOoXapLjyWEoVJSOJEpUJNIofN",
		@"vNDhGEAuOT": @"BpytbMBPZzpcudONUHIchHxnfZEeHnQXdmVduyEdLCEpfIBfIuBQbBOnxsFfthBOLKgrwVrhicyqtBBHtkVMkiBzfGKkAawbgBEEkqTvievZldmdmbIpwLGKnf",
		@"BwWiWfCFelzBWISOPq": @"NXTNuPogVnkCgcGcCZCvSDSorJyLEyIXxljSqvBvQbnMXMlglTCPOUAltsidgAPNGsKYlosPWdGpWpuBsujcxxZSVWLGCDcyjofVevbMNWMuphCBuJCsMvGsDimA",
		@"lWecnWwFFiFQ": @"xcQWgMzHjJlUTnpCnvCNxBEEopZtnIJsFYqUOGnqvgvQeBJSUTxVzmMQWkYokHTscQLIJhWybnnJuYfKkxUqBGVrBSbyenhwbdBRiTtvtfnNwLaBlnWrwjegQdNtShzi",
		@"iYbnjdlfaHffJ": @"HHNUVgxbhoSuoNIvqIfWnWLCzcmvviyuRqGGxAJmGHGhqemokSVMnecNndmgatLukuNMdsRtTpPoXBzcALcmyzJiQLmDBcChAJcjyuuqAocPTOscxZbuGtiJxCMvEpsMsTGZHFZPpSmWApOfHJD",
		@"SsSfRIiuHOyavWwxHaj": @"QoCOmeBrLNTTTlNsNXKowEzpCqCUMcCmrLIxJURlQaiVToJsQaEYynJgnaFFjvcuopYWUAnCzeddApXUXATzWLfitbxvIRcHIaQqbMsRAIsycfItGXsdKvQyWgAKqt",
	};
	return GQnrKQFekgvVkDWJ;
}

- (nonnull UIImage *)wTTnvUmspeL :(nonnull NSString *)aCLePyJftNFekR :(nonnull NSString *)lgEbWrQlQtApDwhzG :(nonnull NSString *)OhlkKgKSMEIlgwpNv {
	NSData *UilopKcwVpCwmNlT = [@"TUTnNBwwTbBvkHXHLXsvydViVwTcWgyGojdBLjJXCnoYLEBAtQYJBUUeYjtsHJpIUJUBXbQRHDthbCInzjEjzSBvetGEImlUhrgv" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *FdJFFTyYbve = [UIImage imageWithData:UilopKcwVpCwmNlT];
	FdJFFTyYbve = [UIImage imageNamed:@"TXjyrslnnXmkEpOTzadDZXSpAuZktYCgLjNhDCbIpQTFwNErIsaeiTngLtdCqjXLhrfGKxzSPxgHbJQLFkQfUiHokDhbujZXClocELIdjdIOqugSglYixIi"];
	return FdJFFTyYbve;
}

- (nonnull UIImage *)yqQyEIBDHIhccYIW :(nonnull UIImage *)ZlPvUVdfiyQ {
	NSData *GhMOHuIqTunjnVBFIn = [@"kFuXUliXtarrkbyQWaJLRtSFLkwzxmDmpipqOUCVHVKrAYcRorANvvdUwBcZdceCxPfRxGXhdJiUlAhgDimfpoPUeRFjykgZuPvxaYKhBmaWUoiOfVaZoUN" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ZDMJqVjqFHGmNQpMY = [UIImage imageWithData:GhMOHuIqTunjnVBFIn];
	ZDMJqVjqFHGmNQpMY = [UIImage imageNamed:@"snYusUeCHMjGjKWiEzRRlcvIomfFstnsdwFRgvknEQsloKuAJrhHuLHzJilnxtMKFtdUzvUxuiCXRVhWbwWCunlXYmNVabPIsFTTiiWAFkTzKNyrKSG"];
	return ZDMJqVjqFHGmNQpMY;
}

+ (nonnull NSDictionary *)QJlJorkDAz :(nonnull UIImage *)KVWMqDCTIZyO :(nonnull NSArray *)ajNUejDegBnYosEVBLM :(nonnull NSString *)GGoNZdvoXf {
	NSDictionary *WrqTfrvczDxDQI = @{
		@"LLTKHxXaUHX": @"BkDBCEmRjLFfwtRSeXcVcGJRXtbYayZfSXkaWDgaeTnAQzVgTVzXkhyaCCsKBJwhKrJpTdqvDAbBVUxwTYYIQPBFqVFzcMgzgalbdxojgUYJJmAJlHnpcNfxHRlhHSrbHUZEJ",
		@"knPkVfraqaJFJ": @"oxaWjKCWHMXLiDwgKosRqPmmUSeVRcLYZeREhtluTunzGrAOxARdWzKTdiRvaVITuROZtxGcqFpJRUFZkAmGpEYygDbVaUpsAZoNGYuJPduOwvhVABoBAiBxsqflmhzPXUyvjNodhd",
		@"IFcrBLKSrAsQNveMQgE": @"KDojsqaEMjbYgLIfYHiYDTqPZlyyZehBhAigMPmepFuLrsqFSTeOsviybzfDCZclWfIsZBuzWkeEGcNHOYiCxqRtYxhinUjDZqJbrEOGwhko",
		@"KBLFQZNaNjMmgxusAgn": @"hZdjgrGulQkNzSXrEVEXPDudRmbpyYYlmEOkIttEkcHDnPoyfwEEwLboNGItVFXiWAUcjLpJbxUpfPkkxHmORwfqFdOVxvgginVtlwBSVyWCPYsRxe",
		@"kUAaaLfEJTYPC": @"rNclEDHIyjuHTWWBmsIQXHsfsGBuSjcLpPoOjpXLGZgNrBwyPbhWjaKroyhggYMBrRsxOqVZQdhjOclybkHFCesWRStiTpNYXaXMALUnOIUbrJGbOG",
		@"yTOmRWtcupM": @"CSIwFPXYrardRLelireBzXeVAXvchUCOFCwsIOAHddqtEswQUaIOcxMapcijeVsObESpJdMYZrfnAVTUcwgTrXkxUOoSHXjXZhpNcaTWUSBikcQ",
		@"qyvKmWxdMr": @"ibGdDMDkJVQPBxLSofNGkzuNMmERNLSwrfEFBDPdDQzCqKlCsuNvSDsSMuLpiJhdAshANBvKcmkaEmchECVpJDPPVZmNwHEInvXwbkkzZEdxiUiluQQyfAzkrIDZnFHfLFbObLfiJtEQnAkVC",
		@"nGWvkmqpVe": @"GGqQneyuEoaWvEhlYXBHBcdwKIpTcrmFkAPqoahhVptqlqvECavTsctVthDdZxEpLGyxcwgYnkGjibbrktLktekPEqAsoHMnlaKVgvROzUQWzPpQkdZpaQJbGmv",
		@"VhaHagxRbBUc": @"XKenVwsCNHbBliimZoFeSvKvebAykNKnLUtXBKAQpXbsrjerBuDxcxSEpoyLwdObIVxyQTBROzoDugYcmnLmGQjmMzRTilcVUPrW",
		@"wMimXPiEHQt": @"AUscxirOYdeSlspZRjmnsZHzLRiovWRmqBPCfZXGOlTkckNohpQxGSNhNkrQtsPYwaHUyrmVGnpuDwdBCtVAtDdKyvWHRsOmsimaMIzyOEJzRWoKDeaENvjaOOndTcVVDuPUTGGctSAkK",
	};
	return WrqTfrvczDxDQI;
}

+ (nonnull NSArray *)jBAehtjNZudCSDNEmD :(nonnull NSData *)mkximievhcY {
	NSArray *KdXCpIsSZUmyMxGj = @[
		@"gBOkoPDogJWrTGwBGJXUDtEHLRmMOsfaqLjHfJSFfSTzXhncwnBZkKwYRyptqWsoBnIduclBasVenfvXLUuywXGCZibdnoSWgrszJGAnzTtKjOccOjsnBUdEsNbRjQLfrkzTyBgOFZIjPjdxO",
		@"qiPZhGlRouHTNIZzhgpImtAuCzVPDaxaspKTofzKUNgfuQGnkINWHDRFiGGcsMJBNxSIVRPoqlPoXoYFxgBrIPCkAfRyHuZabYbyEOuAmJVkJvVxXLeOoxoGUWHNUDEmVvqcmWt",
		@"FmTYkIraqmovjtwXnvEDdGbTBZYnKpRVPZIGgfMWBFyrDwVXaSCCAhGfEPNCQeAjzHPynbFllDLpLTXEXBlfIMmihNFoQxQaSgPTHoQqqlMmCDqMIvUZM",
		@"WhbSxKraMvzzSCUXfdnMZzPldKvxJyiSZkVtYhzDiooNMOUtIjjAWSaFGsMvfyOdXdJQrMgzsybIJugiRwxPOCPyujUxIRliEsjNVxjftBJyzshrCUEmoneEDGDgEB",
		@"yIMotiFLXeJGApMalqYRLSKrTrVSuqFiplxdgIBdPZroYYDaUlxBIshYQSTxmTseBkAsblssFMWzIvQoaguRtKZdUQzpemuoTsGuxFZRkMeAJceDnRTouQilDHR",
		@"NRjMxjqhvEkqGFpTqQydkiUmIBkppVUxqEHEgOcoBYnEIIJadHbYwFlkBKxbjpwAyDLgYTSduHWfSwXqkSeGLdwgYrEOXwXaaOzURsEgRLqtYLLvgZnvkcoQSBACIuAzXD",
		@"qAvIiYQtuMvEPTqdWWupOWtzMflRPzOgwlvaKgRzEDCHIermFaAnorOfdujugrsYTmRIgYozmyTrvkEmfsvtnCrdWQOIkSOnZNJqmPaGtgHXHHwULOP",
		@"pblElVjJVrhcjftXoJpfCAAkOSkifviixSDMSDkJUwRRSEScvmqqUhbdPDpLscHywoFaYHPdjFOvetkYDHcbKaQjvchniEXPQWEetROLtbEDQQtadOEcLFFVxRZAgtArmfGuvqwmR",
		@"ZkHiPcucuHOftsbzTYcOLrkkBaYOnAkMrPlxzTCLbswwXJLwJlDUegxSXygzmtJVPcrKJHBqMXjNIXqFCwPgRdPkxYmCZNNObNTNcdkwSLGLiik",
		@"OYjkQRepiKkWJqxxeOXsmWHYcmQxSXjpkZmvZinkYFGZARNfiufOLePuOZoXsaXZoIpKOKcjTJDEJTDtLiPajVYazpBibPJGKYsL",
		@"BQhNanJPlzoXSsLrhyKEjLdPKnzcCDNwAMxcCyNncOXIvSDnulVsBJSoXdcaTPTBfzJRJQSBoaPYVvGLopRKYAurLUGufKMilXUSNrNscluDKmuUCdrPfDlDXnFgGfABjJWWuiq",
		@"WyMwazuYlHRFenRVyyvJXVzsUhkPJYtdYhOvOvymVCEKddLAnJJJPwCkVBxEXtcxfDDqBuoNzEJYLjlgJyTsSuZkOMVdUpFAmvDHgOgreUuIBRGdxCvuLwFyjWOpsN",
		@"zWPhzasipxOVdvYetblLwcSFrvyWbQPdokcxOuVnhKJvgkOrwLptbNEPzcARFDdbWjDGrCuUhaKQWmpuFlAaAzKAQHdXHTcMMUHrPvmZDEIPAMgjeJfvFkwRsQWVVy",
		@"fOqPiCuRdcIMUQhlCswvBkaLFKGBUCBSbtYComATkcXQxMypcsYqjkWpqUvsuhAToACHzzcLSrfkQbfnYhqBWqbybaFQWbXkdQaoVxjskOwixBhUuugWIEvWJPcCcpyulgTPAasnzzXW",
	];
	return KdXCpIsSZUmyMxGj;
}

- (nonnull NSData *)VcxUWlJZwINfb :(nonnull NSData *)bScHJqxBiUV :(nonnull UIImage *)VysrvvGynatYQMv :(nonnull NSData *)nxstHmeWNxngfHXYR {
	NSData *NZWfHpdmeQVISIs = [@"pFAXWWytFsTlleWcWzfNCxHDvZCMjHpZNlGVYhcSOcedGQaVSqoZXnpWAJNYhAOGJCLnUsuozajXXzRXWtmWPmISiqDXysyAQGSpPFkqUToOgVtLftcnBELvRcXcpQyktjgtCqOwQBFVAdYRyuC" dataUsingEncoding:NSUTF8StringEncoding];
	return NZWfHpdmeQVISIs;
}

- (nonnull NSData *)sOktwxSrWcuykDthY :(nonnull NSArray *)GNSQihRPKwh :(nonnull NSString *)ajxxTyteHGFhzvVtM {
	NSData *UgWefQAQUxVxGWHZGvu = [@"mpyNIfNxKdvCYLtwjDXvrbCQEWqoqqXQaGTIOApJrEMarnQShUHhNTdmnyAHlEvLegqEyeiEKDSBDBLfjomhARsxilzKPBIwnyMQyPeOeaSHmRGljnzPHNdxuzqfubTSIhj" dataUsingEncoding:NSUTF8StringEncoding];
	return UgWefQAQUxVxGWHZGvu;
}

+ (nonnull NSData *)QgHIoQLyzAHhNwNzr :(nonnull NSData *)rdkTNBIpISOlsoijSP :(nonnull NSDictionary *)tBkJYdkatHxjbunsxz {
	NSData *XEtbmqbiZDnVo = [@"qLSZHUBgzXDSFgsvPjwWbMtjgVJSHkptXvXwrbgpIubDXehpeLYtypiUiwMclcKsbVObvxsNmvrgXWjbpEuFiwqGigRdMBSXrXrSi" dataUsingEncoding:NSUTF8StringEncoding];
	return XEtbmqbiZDnVo;
}

- (nonnull NSArray *)BkswGmyfKxUBGHorhO :(nonnull NSData *)rPgHFPMCPUgcdx {
	NSArray *dBeHtkbqbVULXTKlvaf = @[
		@"UyGjryQEahPwjhzDmrGgBaXUgFGABwybgZGcYPinhwNCovhDIHAaTLbUQTKzasKQMGBCyIYgCbUJjPRWykcknqnxKDwxMbEqmdFmKXyXFIQCCTV",
		@"DPWquFhTlEAvZgpNVyytAUUHAIPLqHAAgrvKGOfmUrknbfymEwsZAkHrQtgztOWFvnXFWdoYJKawJkYGDSXXuPPjpIijeuNpbMirQbhEZXKgfaBjogHUFMMsUTQYaFQFCLHeulVxarzUel",
		@"XDIEdkRTyWvGPzOsADiYEziDBaayXrKkPzgzqFdnjAVKHQhkUKYXVgXskMiGRGFRGAFXJqGwTYtfbhllArjqDjqIzaoedRcPKreJEyKeWntMYLTeZmFAVG",
		@"eltNPFMfmKxGmVfNkMtdWhnCyJkKpozqUcdCeBJmzJyCueKPDLVzhJrZOmLZjFLpLCoJPRYpGuSiHeUvwZFDUWkUjGiOVxaegaeBeovBCMqahkVSdSGjguFjrnFVNLSwmRBsPXmAsCnkvzHuushY",
		@"ZIzrQflQeFUyDyiyYljUWppDpjeaRCTAbeePyVYsxeEXSDZNmguruIQRVHmyEtsppZyKJWbrgDYUJQxhimCUWBZNZCNoSyBFSVCDguJZniWlGzVrxVlCqQLcqIUpNlMI",
		@"rygKgQKflVITsPnmjJXqMYdwznFeYRsrbXzcDlrWUtwMTtDasXaYwAGHEjfxGGdyfGiTsKvRdmlLUKAUWNFBxnUFCNvLhFvYxsGyDpsAFdLAbdUEYlsYaaSdtEehxzzStMPgA",
		@"DyUwrLLxSGCdTNpIrdSkiudlydPbTuUAqzQIrAympeqtdZQzVVamtnvpgjCKJKaHAhXHUYOvlIgJJvbgeyxzZOESAldGoWlLqbpBlEOfEIGTEqgOGPcaQXKrREkMQqbSyReXWCJllsZhJNNUd",
		@"MFgcTagUUuDBqBtuQrkKgZarIxGxHRMZXroTkJxTUFbiiniWFNyLitGnuRIeDXqCWQWVSoBkrmPfVxuoFVLsImFYoZQoFyJPwbtGRjnSfhymUBuEamFDJBaxrvClTVzhgYeZrYDWNwMOdYPb",
		@"avhoAKacvPBhBJNKXIFHEcPlQxdbpablnBRSmLFqpjTojPXNtNKHwKGpouMCuEGHhszJtluJffHoSeJEfNaijnlTVRhGOSyzUcEYFJoWKJKpEYjxwULPcLDeftTFjewViRQJiXGW",
		@"wZKaXgFEkhSTrqthnvsrjWFDkaSaMiaPLtYjTuUIEKYBwtGPmGfbdMsSemWuuKcrvNQvioyERklRiVsCRpTDxgyanlUvYuEPwEfLkNIOLiQwvJFkdgNSkLRFtPBSzFQawSwkEDzw",
		@"YbHvHpcWxKeaBduWftwwAlNXXidnHUbObLXZOzOIMweYAedUmHFliUCSINwAqBSOMtLAmLKqSvnyhouwvbJUHAbaLkiTZyhIhpcscD",
		@"HyhHetyYuXJhBEaqrpBYjIhMjzFeFScyrKJkKIWTYTDgHssGejaEgJfWNrEIzvYKpsepSnbTGYkUxGDKgGaXrKdBTtYaPXitNfZWFKhY",
		@"uNDOEsAFtoKlhkVGoTtWqLmFVtrneLVMRctWCiewQFtdipTHFERddDdczLAhfpLHgwiNViRYXEqunuTXTvFsGikXYtwiBnFctaVvTKcncwAmGOUWYkCqvIIojdfiNBQjPIfscWGR",
	];
	return dBeHtkbqbVULXTKlvaf;
}

+ (nonnull NSString *)hBwfSAXvwayDIJIZ :(nonnull NSData *)kYlvNncaZANv {
	NSString *LrexVGXvaoKib = @"ZeTNMrBljrLrOXNvaToXRqoRYdJBSepqOVrgFAHWnsnLNLKmISNnPngQPjFZHDtFkmDfpoXIyPxsFjnksMxxaEPdbamEaCBhCpLcciTvosVlxxOKYVmECRCPIYBIGnNpJNjHeaoUZWTT";
	return LrexVGXvaoKib;
}

+ (nonnull NSArray *)GmlboxsoTHALcaTSOoh :(nonnull NSData *)SQjUJkYjtvdN :(nonnull NSData *)awYmodgQAfoqO :(nonnull NSArray *)lGixYvTjRYGMdwY {
	NSArray *ICYkwtJXVdIBlfJCd = @[
		@"cJbkzsAwmzPQYDuIhnsrtWQshlOaUDnpQgJkilzeacpNcZbNwXZdDnqmGLwzKdZyFitieWgULCBsRBvKqQTewvBNBbftwiiKTsOlgPHILWmUhfAMPUijHcAPhSkWlYDHOlpu",
		@"fQMwHctmWymAbsAmGoMrmuHSgZNBxJDfZZxLgUQSMdhkSlhMWYNQdMahoHpuFNrzblYqQBybLoXfyCJlRZgjjtlosUrGjyjrEUjfjBLAdYASlZpbgWMaYnfYJOaXalhJHXbJuAlFmWHaufkmlbi",
		@"BSKMfpEjyuIhsIUZeWNrZsHvjvbVKCmdAIxNxTRzaBhMVaCxbcgXLGrjWGOrxoPkdmPRsfIKiQTRLxvQYvefkjkNXDmVHlrNeSljiolJRTXbZPUzzaweqMVZ",
		@"nPuyCawwWkCinIWaQmyOgtNMBHykXWsQxxmunDbhHmJhlnojeYNgwPqpSwBmeCAZQtMCULqTmppkpHPkFbwxtNnBRSgCwGEMucXPpeeaXMHiRApIzAbleAhqOKAxEZPyC",
		@"cEvsZCBYlmaHkeonnKDmTRygtJwoaOcfWIeJqAMreNLSUgqNTmrRZhlIMwqvGnbdOJkWYEMFQiBbiHbsiDwLMBZIlbJLsSWtWLnjJIcvKewaJVnMUQMkxViKenoO",
		@"SWgfJCbenbTqFlqTaZlwvCWEPeCyfdcYbyJoWcfHhbgOAQemclrurYcsaqdyBPvMHECRWMuoUAkHOMTkLOkjmzOtfSImbrvGJRPFGXliQSqWTwXUzkkAEMcxNUtgBBzNxeoYiAEiHjvjXJgbfs",
		@"hsYPpuCejhfDQWyspRCMlXopauOQVMDRtaFbQvAdvgIpkxPIPTsjHyeTBMhxlEToLLApPXUnQIVMZCbXbbWJqTxIRpdtaLjUAWYXDeTFDORtcPNseUJXnTbMsPMUzLljOaBUNEkv",
		@"rBbvykuPyLtyPiFADtuUZUVKdnqtRuenPjfIfsbNaWPtWHTwnHKzSyJXQpQICcWhqoGbexQINCWhhiKHjiPxMqkixDeHGKzCPmbOCMjsUNJMXslBOzxNo",
		@"SRNjvugGmeylocgEKJkfaYSRtqsJdXXGYXiCdosOXXYkqcmfrQDKdjXDNEAOtQLHgljivNYMtDkbydjsSKoYqmnUeUBaWDRrSGkRz",
		@"evRBsxQnpssEusaenIxaxgRqILPenwqinGzMxOfSJiXbNteZkVZJTutkEkBdSIgIRLvHZcJIrHwqYTpWqHxwfAOHSMMZmIdXtBndygQtEYjQYWcmxb",
		@"LVQNBcFGkiKNoZVQUedPcGHOEXvrXtomqqzaLsyiKJscYOEUEdxxTJvoHksiXgEXPLphCXIYbfRTZEOxmUoMrWexQLrNAzVGYjaClYepTMQBevIrLbeYTS",
		@"HRsTWwSfjTsgsqWvgKOyIYQFkkrcNuoqNDyuJioNgwzEoQKZsdQRpDxrHRzdkevsWcdjJmfhiXuezeboxJVGyJKwduhursVKqayrGAyWcrqbZYacaThGjLKrkRMpnIowsixJrx",
		@"BVZvwjvabOMsLPlTpmDYCsTYBkXARZlTZMOIjAKarQAaEaWFAkbxydwHXvWMiePlvnbpWAAaGpOZInTypOHpqXDNsyIvffWEBICpNqcmjfaPGcnKhHrnyrukGRLmkWVecCBbznviTBMlKGjKSkeZg",
		@"yaWCzfpGURPSYtzzxrHIqjKuspwSmOieEODfeAEMUWQUqbWIYXyuyBiJBgYTqfhkqRqRjPNLbRQLaFyycrsXlDlvfBoCyTAWeIuLjoziH",
		@"cOyiSKSzAMnUzRmDZZFPvcOIIZBQLoemkFBrnxyGigPrBsLKEEPjVtfOprOrHSdpQYFNPLOMLYsCcybbxOKwRPDyXJrjqnBAPDwWyDiaKkyyKuICEduVPDqrKWyqoOxUfuTPXwlCNLFzImeFjJy",
		@"WHxUopXinhVKiFAeJSvQGFXsSONKDrusvcuJtKfaVXKRDzGFrfyqjcuoBqjyJyffRMTnYWXThtWmSaoeazTvgkIwQwvdnUGhgMhDRozToeXAGrlRWoADFjvhumTMxutgD",
		@"HMZoCfOtGZxkmOEiTmOkZbEfyWlXDrDYVtSgwiBWMvVvuUJpJXgGxwgLCQfRwWoddbeiyXLhUccKkTUqgEoVVYbyllLgXmwdtIdNQowiZHnaASOTSwjV",
	];
	return ICYkwtJXVdIBlfJCd;
}

+ (nonnull NSDictionary *)NasOceMJsPUHLAEyyew :(nonnull NSString *)tImirabZRQrGXcP :(nonnull UIImage *)fifTEdJZTxYWJhkYbVy :(nonnull NSDictionary *)EMSAlGWTHkyEAMBLH {
	NSDictionary *miQZjUfBMRAGHCdFSE = @{
		@"dartxnTbMzL": @"xlCLViKkpSyTHWcMRduqyGXpeuFqoedkpYRqXHSuvayDEyxHSZKmoUSpoWFRadSQLZQitTTjeJZgosHOqMbCjDPecAJlZhDapaXdTljcxRSQB",
		@"bPoLQzKEqlmS": @"yOJnmhogtcRJXQIWzysTfWHjHHJDhkBelwtAsObcdLkTFIjAHIfnapdqLbXwdedWkSrOmPoInjxUsYMgFZkOVUokBqcbNfgqripOVecHoDGOjgCxCjQVuaKWoGJAxtFUd",
		@"qZLHQwQsuCGffYYWiC": @"xyhVhBKTKuJIuGkLippXdOmGwqbFDTtbEbvOygMioRTzjvqiNnFYKVBeMAXLORSyYbDVgJGtnESmtrAInhEpQtzkHaCKXPdqxDOYxXpOOzeUxpfEyMVcdpJSOnkrtabmIc",
		@"gQQsHmCkxy": @"APEifsivUnrJEimkUyzdMVtTphzwIbkOqQIPwXILSNQDFTbnVzRbQBmMqaXMNlWJoMMWmKaHUZObxSmtwNSzCExrBUdtCWLICaLSO",
		@"oRVZwoDKGiPbRA": @"nzivUIoJFtsXhfvbkPOnRnduevHlGuhdTFwnENEabyZIdunjewovWOeUHCzaSMMtBizyFnYMXjAwqwKENQvRgRlfHiuaveGAHkacbeOdCfFVxYZyfamDbjtLltwvXYoehIfyQARh",
		@"NRnBctDFnVaYE": @"RJyFpofhMSfaFgJVRcNxmIQCZsXxPcAxcIUGxEnymKvLImYvApQdSIypEfxrWpExfcRvMhhahcyDZcJZDDmSVXJRvjKCQUpxgPLHPtAbVIPRGs",
		@"fPFvbNQDDmAcW": @"mwcMNXBcsaQklJxOZYfgPTtmirXzPYPQtjjrLsoKcdPLKkbLPVxItTcixDpmtenePOADJZSVgKcOfIcQrjPiWLaniwBiVomfQRuXrtnFclyrsnFDZTpLPQAAVmbvQbUVcHSvEnzrzsWIGD",
		@"OvOlEmIYcBIRzP": @"ZBAtaslETEOaUoYRTGaAuXRNajoCVLvkFkAtcbfGlVCgwIWqdKEMlGcZZGAsooKzyyAjIWcElEETpzCwtxcIzubNvMRSjjXGaBSCugzLiufKJPLzQjz",
		@"defMPQztGbwZpPIsQBh": @"OlzZfufDbYDPImKuBjkkpKPbZuddOarzEuAnPDKKGDrIhSGlOzoHbUcPMVqfFMoYXbDKwuNTBqHqWBZyrQnDhamvLwfmuRWRHVsqZhA",
		@"yiXgQRvfFXfJndDrDp": @"ILcZnXCouiktotPRbdSMTObcCPHHAsLmLfOgGfyOUjWclNtMMTNJZbmRisgmjQMqiOVzRaCdgiOgOpBiaencZqzBNlLfsuNtrlWsRajzOmVNTeLnZqhdCvZiYyWfpstAyXkqQigVvYbtBqXB",
		@"bccGQiAZeHNQwg": @"jjmqRvMWjDBycPtZqjadaCaUSnIdMajeLorAEYEhVMLXIcxpVlrttydlJXkBpQCKoTXqPpzMftgZUmdrMzsGMJeQiXsVoXMovSeJnoRyfErTU",
		@"mVAVHlQljESPDnJcce": @"nBtODLYoXLamTzXPZKUCxoubySBwNEelnovpyHSAHoEJuJpNfSgZWKKbZvkGuKkOevgLseVMNvpzpAbzxLBoxZtpMDMFHPlgDEcWeNOuDcDWyXMPUYdDJEypaifdE",
		@"dDYAkmkwxlSF": @"MHqkrpnNvegWdrWxkCDFywVWOQhZMkLKFwpqGvWzuGXcuJEcCNDVjGVXFZrVUzYyYTftHcgCacmAYuTMCdarZpPrZpWuRkZrPkamBXTDACOxgLvriZpGRU",
		@"pafIhkHjWvcSEmt": @"vcFXGirAzYGEcoZfzWCQsZpiMKpdiiogkTUbLekZOZdoRULXEUpIfexAdhYCvAUHznBaggBxUHdgdmgilmDnHXfhvSbPIuNPtPklAv",
	};
	return miQZjUfBMRAGHCdFSE;
}

- (nonnull NSArray *)ArbxrgpNAPATzl :(nonnull NSDictionary *)ydTESZGScFOQfk :(nonnull NSArray *)bEnjttkKZay {
	NSArray *SAGHjZLovKRlAT = @[
		@"cTxBJvCxLbPKmZAcfbfmIkXcdrijaERIJbMAmjhPaBzsscZXKWBXgifMuPDHLiEMmoXOiWFiwmmzxYjDGsbzQJDanHgEopHayFODRZcfBDCtvZSywnWOflVbXZpEk",
		@"KTPlXxxveELMaXwznOteUdBZcnydTHiolqEsyJZUpRKKHHyygFIxBQPlZbhJowXfrbbJlxHFmSyifAHrIhuLCeJAPksLuqqjqquWxHgUjilGMZSU",
		@"jGHeNDrnHxTjWcjxYEXGPkVPXhVjyDQjNVcphHAeeEIaPKUagnXyIYrwkhTbbHZoRnzWHWucTIxrRkgNCTbwRrtusxiuXwOVdFksMfwwSzTvujiRILZkXJpyWKIbeTsbkSwaDLCtuEt",
		@"veqlwqqJyGvEHXvhlVqBDZuKQwuxvTAhUefAvowkTiIfqyrANdqtidosPUcBnMTVFyxdyJXCSsmydpljgrVakzLeLLOsTQFDBAtGuFTGRhLf",
		@"lIsLKFDAUcHDxMsmJKNFDrjYzukfHhEDMKRXQarvDWhQfbIQFVNmKxYSGlCKIKDphOsYNdlOLllVyqCROOVyMgEvjVETmVaFvUkXtwYtHabcNcIuIE",
		@"DaeVDsVfydzIiQaNgidzsCuRRCPpKIiZGatnGROulufQnYcPMDpkPAUYSSwukwMfmVgLEmTyuxkgIqVZGTfNyQGlulcDsdriClOLavwKnqmkwjLqbKAoWfEbLNfXzQborziJZBAxPIjlNEYMwn",
		@"rvjziaXqSifGhrUEVCVaneacMMUAvFoykFikRiihmFBoVTQIUKufIDORaIHfwwQGkzKCSqwzqgcHVcCHvKUSwqKABKrFRYxEYhGdQIwHJQsbesBwqbntpoWRyGlibhkR",
		@"JXtQUbheVqhmSnWzcnQWHDJSTjELXcKdhKIQyzjKMjKSxyenCOYHRtxDqCKiWiYbcAvggYMdXzZfELktTTbPZtdkQnrXocALDZgWFzYQihpfYXZzGzmcgyxJt",
		@"cMyVqDvSohEQhmsZZgGNOCLbMqMAWleMDwNVGzARllJxiTDFKaKJWeVOeEkwRuhBhzPzhvbDiggNqxKMTqXkGhCiMwlLsHGuBNlpDKvdPwuXqmFLZjcCJoEddeiONrWJsPlLLqiVpVZSq",
		@"mQQHUbFTXuNiszNbVGWIAqTOIZKYpNpKMXJEGxEHHGzJkxAHnnVgIiUIoKrigbdKDtVukcRFUSfilyvMOOhAIdjtrqiqLMmnAOfdOxiTIqXCPVTT",
		@"nXdNGdlfNDgQUVYchpJuVuLoScCxCHWTgvqofDZTPWMotXYtzAlvljUkuGfMLHdOuhbTTzbyUEaujOGkpdsUXQSwLuDWvenqJBAoyKcooGVHVCPDEyjCTl",
		@"TlvJTwUMtEnGvcZnObmyUEXNrSdWLbLUFxiQXxrWOWotEQndYRMhNwxycVtGyKRaaPgfUmKoOLxqGAjmoYoSRWWIppuIhygoaZPQhjDJMOvuTjWMUfpYleFtImhWTAlYittBCFJHB",
	];
	return SAGHjZLovKRlAT;
}

- (nonnull NSData *)BElRpVeMwGBVWjupehx :(nonnull UIImage *)WrGHFnXcXyaNDI :(nonnull NSArray *)XWXyRBduoSFCAZ {
	NSData *pJjyCdZLBFYa = [@"zfTPVleCQbGyKCaeDwNdGWQOSLWlIXuMAHajgDjEDBEMOnyLAJGdeLNtleFPuCJvOhPSJsQLGeoevTvxInLyruIzvpjAuDOaLcVSNlGPsJoDStYjZOTZBsGMDiSXSjZmYNlaAgqhyMzQPdK" dataUsingEncoding:NSUTF8StringEncoding];
	return pJjyCdZLBFYa;
}

- (nonnull NSData *)vJNBHLQOXXL :(nonnull NSArray *)VdqYoOQuhNGWYpJNCJY :(nonnull NSArray *)otOHTCwXUWj {
	NSData *ZEAjFPdDWbnPtd = [@"ygGJwpHOwVDgrThLchfPmrcnYwSBViZbNKBbltwKzZwTyoqAophowPLNhgGPbiIFeLFMcdvbAHDcpbeKKZXGuEshpYdguMHYuNjkhLolYiIdZyAldOHfdgwg" dataUsingEncoding:NSUTF8StringEncoding];
	return ZEAjFPdDWbnPtd;
}

+ (nonnull NSArray *)woekkGNdGraZ :(nonnull NSData *)htycVGqGMpnywGqalO :(nonnull NSString *)QeHemgBQJTUpursPVIb {
	NSArray *SkSfterFkJSfF = @[
		@"ewrCLFvsCGmVYIoOROjnkDhtVJROCfVhLQWcomTgtEpNOicNdvKTSbzoeECqmLkTpzKSmPuWoUhWaKRTlWmxHgUNCrZPubHnqnzWWzZuFpFTfZwcxWhzYRCXQCKHHKybVegrdz",
		@"SzUJyrRugQhoyUtXEoFkIqZQOtzuKBQJySdIsudTudaRjBqFAOkkbbzwJogUjfDPfVwgITzWBEZqcyHJDkidzzaPkwQhzyuJKLwCJSupmLsHkNKAzlpwYuQBeFmdGaACUeoqEOevtDxUdt",
		@"mIPJjrKwmwhWdIkGvYMDSIbNhKAAbIvJosHTcsEVaPpTuXizvLqjXDhLAWdCZzrwOOxdeAdBXnvcGTjMUIohJqTwLOaHkGARXIKBkKYstosHKOMFUoalvpLkvwdfRuPNjatOuIJAFknGZqmkam",
		@"hoAJwQMdfnjcUEoDKLHRTXReBNjlSwzxLoYDWoQjzcEycGwzZJdjcgMZprzhuAGlolcgqRDraSdfpKOWxHQWRijanVttwexvZyrdZHGMgLIqmUgr",
		@"RRsyqtLRZuJaGGLRQWMRLeIXfKvaHtLLKEMuRwSjcPAowtAdJhPIIqWvJnihEwDxylkQLDHZbGLABSOEQpmMHUygjYRfbaJNGJYyKBeUkLjFUrFpqEMWJfnzMZqhpe",
		@"QhUfnqfiesLSvPMIhIPHKRKElTasiTxmbLOrxNBpKbmnizwoduHQpyLhkXxEaDDVGwPVqpwolQZOtoBpAsovrMzjRPpYUYUlnNuuNUzjZtIzDNCEUoKb",
		@"EKbLrBgrUFAzUzJAuPpbcVFZttJEoOZuwuTHKKsHbAqqyzoXDdiJXeMYhDPlAutwuFmLVpzXijNPPEgAvvRHDEbnbQKvQIXNxCyRrE",
		@"ICvcnrPigeIYrcaMiZqsPGoRgxanspeXvZZnmXtQCrkXRzycFKUhaGNkCFIIUQSORslmgZejYMfceNuRqHaBUppdNkomKxPfhyxtPyBlUJDALYkuTSOML",
		@"XJmrfyVEsNePlJEcsbcWRuLkeIksmhfyfuxAzcBxREEXnvLXxypHBPjciuVXpHfbUVEZDsefOVcKsxGfwEQouvWjpSmwltOZkzUpHoqnMUwPIfTWzzGUQWGCtpSRfqcvooZrDRDGnaLGgSSG",
		@"oVATCTZWEXTmbDqFYbSbCoYVPVmkUYtvoUaaOaAxZDSRNSLoNCeznikjciCBYwXUoeBSQWWnxeUPeQbQTfRBIbhdGWXBhxNVrgQJTVN",
		@"yBnmBqxDbqFdfuysIGvOjVHGSCsIaMHQZPqMKBUALerKXQAZkvufAbExQsBOzrvyCoLchNBHbOaczsMdogYyFDqsEcPRCtHNpevcKMgWO",
		@"rqNsbCRbOsKEmacytzNXkAvCBOfMocffIQfKrapyFjdDWUgpqZlDZhZlcDjKchCfLzdrAyIXAMszGirSmJWbXJXLwDRqvdEwtOzmuQtnOwoBxzHXyIphHqObFBLkivtPjJFRKbGgRQXXGpnlyNJo",
		@"DsTjwuLCUMCNbKOIhmyislqwAsUJDpcUFytsCZpPONljcRdgrjjveajKFTjTVRNeQsnYYOrpfXOmWtwptjMSJxoQleLCtEzBMxgRTSbdnNLJexErLFkaGbrnZBGmrpK",
		@"eSVCtnnCWLhpotHWQolruokIINybDHTgsWhaAAjZBRINaRdMaALKUBqrrrCkhsCJxTHHNnbynPxlfmxIcArAAORjJAxjSkRlsRVwvFXgpNXNCiywHCZtF",
		@"pFGzZKKjMuWtOjnRjLxVVCStQkpdAAQRooYycrGJmulSnjZHpSzmAVavmSNOxqTIkrsaOfvhxDtYnKooKtjeTizgljMNUzEmvkazQAGAjccGCLMyNBoIQqAkCIwfNPBrqgAqUvvQXUxFIqJZ",
		@"InzixNFPzJnaThHiEiCWArRksppFoReoyHlaYkVgaqRrWDSSkGaGkiYyBvagrpKeBccFXvJvvBOaMmQStsKhQtoKkNNPfbxbqWRUzVCwfQwqRUTFXlByuuApsKY",
		@"xkArSdvGQJFUNiLzpjNyByzbESrTWCRsqJsqEJaWSMpwzwUDGbtIvEntTCsdpRWKQuROqlrYDzHMEXRNUJyZoNmZekItcuwJteQunYDWYNgMrCyxwFRoOPgyDkDmYav",
		@"PpyKjMyPrpHoKsumWMSVUSfEtjGUtJCNrDpfDYlGpqNOxeiVfhFUkAgXJhzUtlxRTJLomPEIwtzibuCnTOdvkKcENBvgCqnMZVpipiAZ",
		@"lrQqwcOsUKagcOYnaAIicfrzyLqtjmUlDlfbnhRMMHoznmfyyUaAsOppxjZcvBswiGthJfWLgDqvHzEoINZMWEVRBfIWtPfEpVgHTe",
	];
	return SkSfterFkJSfF;
}

- (nonnull NSString *)qcCyvmTAosSmBsXlXJ :(nonnull NSArray *)xVdoGDBYMY :(nonnull NSArray *)RDWMfPCeoBLaWH {
	NSString *iSEVLzgCHoIV = @"XehmhLBUcsSZHeDXCapGdsquKZsZxwWgYRGusPvCuuxNlESzEIMMTBmPSEXLsGQvXBIlKddyrulGzxOZTxJktizWdApNvsuDvYYHhMwSzzFPXltsOxQRRWX";
	return iSEVLzgCHoIV;
}

- (nonnull UIImage *)IOlPdiNCeAGYQoI :(nonnull UIImage *)BsriJeDDsAeBZml {
	NSData *rtAAfJHxPMvrpXCa = [@"ldDIVswoMRKRGrWUioyHnnxMtBEgGOnxxVrRnRzoScTexWQTHwNRFherwMowvOsLfZLPVrBGrlQjBOyKBxAqrqVTYMlRWGMHFKuAnymrSJlvLGPPbIpLJwgywTNhk" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *xmerixgGsYAcXabg = [UIImage imageWithData:rtAAfJHxPMvrpXCa];
	xmerixgGsYAcXabg = [UIImage imageNamed:@"KoYgWzXbeawNxmBBQRQJQMvWNyWPMjmInpEfmIujBthWVvOoNMKrmdoEpLzEAXyCzHEBLtkCuMyKLjXdUYPAwjyyjKpxWEavMEGLKmEQGEUiGrSEAfzcUMMDttMHnSPP"];
	return xmerixgGsYAcXabg;
}

- (nonnull NSDictionary *)eCbTAuVWmdxQSNB :(nonnull UIImage *)sVCPjlsNBlIrysHwYI {
	NSDictionary *IovyYhZdTnywAygBrZN = @{
		@"RhgcXkPAHOCB": @"fyMaGABXVwkgVSjBoXqPiGDRdiBiycagFTXwcALdYlUkcGhnKUafsCqwLykPBbYaRTyguwpLgGgDdrodJZPCicfsXwFYwNNsewFimdlGPSpQISdpIWthOmwkAflRPEWd",
		@"KOkZhpJzmSUTkxaQ": @"WqTJOvnwqNTCdJhQwDxyyEQcdynzhpOsVuKmNvDmAYDZsWQuhSUgaTFUYKWUgWLKhkrEuOhrNZpAPJpDtfyXgZHAJgWHYTVlIoyqPkYURYPzCSNDmtzmYlmaaueqsLHKZYQsRyx",
		@"NLjSfqhYjCohlTiz": @"cTqXqArQVaEiWnWhvCjZYIYLohxcXDKekMdTySUqjVOiilsMnVbBaDFlXQzhZoOHsHgFVdQvPuUlsZtfXdVqpGZiskJYlNrJclPeUpEqSafqQJYSTO",
		@"GXoZvuIKNr": @"qwuoKMBYTsWMZHNCNOhbkWsszpFqPdEgVYyWbMfXXIVjGyuobTPeRNirPQwfLdYhDXvTythRLcVzrycchYUkMMmqarWklKvHNccQZgpRCaF",
		@"KHUrYvNrXPYQRm": @"qlmZqbTtTUOkFvVKrJTJbOQVnibHkyDNduBgbofwfxmXqieCnSUwzLwDZnoeOhGKQepHACIBTXeFUxANhUvXSCiOQNRNqcPxjmDqnpAoYHbFXzYahniTYwsVIBJYSvGdtaWipzAcdTUPDSw",
		@"ieXcAaUtSBuDV": @"oKVZnQRITAnWlLOYbGyJUCInGrLIGUwqEmIDrTvxIiATcddJcDsKAuJEWAQuEqKprPQIhMoounobdCltuhFmnxKSsBLlruQLJwuX",
		@"PfwUUvprEAtY": @"CDPKrLGMKviCuNPTDPNiimaEBkrTWGtIrKiaWgqEIWGZHvGSzOWrPyWWBaTMlxqjnUBCaHYrHdxwjxaqVOTJkcxjLmELTrprHJkKLcfhXBMFgUIVVG",
		@"HbxZeNYORCxgpuGNH": @"wEqOogYgDyuXJLlpMCBEpQjkfzOUtVzxrrBDvBaQkhdJzJMvGBegsHVWwjqqAJFNitmGYTtnAnlYqQKYfovOWnJXdgRYYHyebPyEqMHGCNcjUsfCkFBKimjpnWRKvAJNnIcbnal",
		@"IwpOuDuhLSJKFLrmvm": @"jNrEAfXjzDYNjBqhtXxoMuveUxswurFKhDLIFkolwieZRDdTWiCfsqNNbWTOHYeEZHwVogIKZjazagAFIkWbIXtXMRiMSaIxgurwyKudphEaEwTLCVCqrJTjsnGjDqwkMDw",
		@"TrlVOWMetM": @"ezyEoeQgNhsGWZsuZZixnkrjDVIIZPekcaChMXyOBqVtlcvrEJCbfcwkNzYjLBwIFgnRgfxhtARphIPnLoNkwSyPwizYWLYmMeMidsiIGOd",
	};
	return IovyYhZdTnywAygBrZN;
}

- (nonnull NSString *)RHIOKWbdRwNsS :(nonnull NSDictionary *)GdHVSsgGGyhgR :(nonnull NSDictionary *)rYHsnKyvYOg {
	NSString *BOndXIwjDMT = @"AnMEuOrLvJQbXibZDNXChgpQkccLVokVRBZEOqjDVFCRjqlqvgNUOQkntVikhAzrfquYbNXMygqXSZFMDkQagtQgQyuQiRBgEpsxThHkkTsApMmkGTqyowAoozKXdLJllYhwUxOlMhnje";
	return BOndXIwjDMT;
}

+ (nonnull NSDictionary *)hkBjgaLeadJk :(nonnull NSArray *)lYNWjXfgosygdqoNlwT :(nonnull NSString *)VbSexqNqaxexKGhrvT {
	NSDictionary *YSPMwxDqgKxWtI = @{
		@"qqLimzFQockorGYXt": @"RiBrqFGBClHxdKQXjnyEJhMCiiiHinBqzoiSfeAUrFdZGsGEcPLKIcCMkBUyrSxZMIAImhEQJyfVOxFBsKSxQnaWBzYUIHNIiUGebRdqvACLjuDvBDHCXuuEsybzlXrFNJshuEHmLJy",
		@"fHpGorMNsUT": @"jJJATIRBsfbYUDudDisvvXeGzIVKEyyLGjzVIcuyYXnSypVEiDFVhjKLfqzAuXAuuWorHzAYXVRZwTfMHpMQdJVMBzIjtmHsZHZlUzDSNBBrEKKjTGqpjyWUjpK",
		@"fMcwqxCJDUhfUOghjV": @"mbRNAcXEdfZCbrZSUTRhYEWwqjzrbpbgOKXIIduQppJVGNareVVgqnFOQHEeLMlNTmPTItJzxBsJqPVpnxKZgtXeQjYviRwvZKOwCsTXBgNfCNxMDqEiTWZAJpNqpsyCaovnyl",
		@"sqOqhNkwYNodzeSYp": @"jKlRZhoQacpaIcYODLRRPaYPQOBfurEzmgUiMBSqOehEZNJJaZYFmaDTndilMWFvftEIThJwMOeHLqxXkhnWsfqpLMVhetkdwJLqVacqxOEEgTntFrMPbNfMowiLVlZhOYYtfqSFLsyKgqRppWMm",
		@"lUDpUTJXDS": @"vaYdOYGvgOhhNGtJHNpxRRsSsVQGjaspfrdQqToVSOxnJQePktTcScTxyUGugPleuLFPeBiWCCbTOoROzPTpWxpunBDyDJrcCiwyTqRpoFwmiHGPocOBeWK",
		@"nypTUbNCLb": @"zBySHBZeSojiVAqLRINuyyRfiKUSLyAqKWTaivLwtfPQmpouEXDbjMsFlMCfwFjGsrNIPqeuZnXFjTzDVUkiuxpRicdVNJEPcmFTrzfbegOcLIunnjdLh",
		@"AkVXBFfrWMnifjgtHnx": @"auaQPZXBjhvYoDSbZheeJTUPcoGfGZxVyQTmdrmyLokelMjANtwzvBdGBYXyzKGoWSktviYrdCYLRHBNLTKoIdlJtUKgxLGuNfHPMaqERbI",
		@"zAvYmhrNTFyBYR": @"eeRNZmVpioaBDISMXEhxGrsHeqIDPRnmffZNrVovijGRLplXnPREOHLUQZslkgPzmOVTZvUNUqyFopIUplssQcJKYiiqnWuciFPkGAvzCMpGpsjWIPRNBZTMlBPCTEu",
		@"LIgFPqDQROZEN": @"EWwcuXreaaYzNyCoOhgVmufTwaavtcUJLKQIxjuvInDfXYdhbLeeIqdQGcSSMEZwCuOtYbwzSRRJTQwggdgoLSArKsCHScGMYpJKDjzwyJczjQUgCKHSFaXs",
		@"VfcqVAGxdwfEp": @"GUWxacjsczBnNtBzemVWlEVlogQzwiAqeHKmNRhVwfxZJtONrCJKczGqZvrYMxXbRyBGmzeNZcwKqKgkJLNqcIRenGjqPTHGjxFYsFDBUWTvJwpTLECJIBFXLhrVie",
		@"VsJZOyYneHymh": @"vZzMZEPrcaQNWbFoWfasTnUUbrRyrlbEfKmrtdTcsnsitknVkBNGmNhyBEJWTMbdRhXLlBFLbBxfQkkBzFuRGSzaVzLXYFmlcVoklsXqrqFbUvRMkgLbaziJYYan",
		@"vIxFbxDcpb": @"YDGimibaJBzirMBgJMBmyLGKavdoinwLzaRhEuohxwOilbiFbBhobkpkNgyHzOYZWmfWYgQNIbwPBlmSXaZPsCakliGdathJOxwWOCEFGWNJkhfYDlecUHlMyOxQRMjXOOOALiCcUHjrDIajV",
		@"GrnNDzRzIrYVn": @"ECbQjLGbhBjRQAbsNtfugIenBmPMrgdysXnahvthuqrabsmiAzUezryCpanmRXWtxnWJfGkgFYCfLPYrxpfInMVzPhdNAbeuvstvsahSESmxzSrhxujuYdfyxqYkWNLQUBEg",
	};
	return YSPMwxDqgKxWtI;
}

+ (nonnull UIImage *)YqiJjFoJSKIUKRtVdaU :(nonnull NSData *)IMaiJVrkSZd {
	NSData *upnSQFFbGTkXRCkpR = [@"KcmDotEnXHQdAienEEbbpmOiEsajHtuJgATAYsYeNCphZiUeqmnafjevTYFaVJZxuOhqMGutQIJLgHTWlZTPxqzKMKgKeudbPbHdmnPNnzhQUzqtxKAYozKiOxOsKhCfZzywzNFbGffuWEJT" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *NbwUrVUsNjF = [UIImage imageWithData:upnSQFFbGTkXRCkpR];
	NbwUrVUsNjF = [UIImage imageNamed:@"kyAnXiGxSMcbkxDQfVAnRBsEkRGGgajvYIHLxMIEpBwSQIwGTeYAymDjeEFuaPqLsPwxAIvunXgBEeHJPdBfUxPMzitBSEBbWfazGIVHXsDLxfLUpfOqkEzbxtRrp"];
	return NbwUrVUsNjF;
}

- (nonnull UIImage *)WSgYIvkbkF :(nonnull UIImage *)IVtOetPiNItEUnGzU {
	NSData *uicGkGdnvjhr = [@"kiLfbEmDEuNONJfwdPLFCjeGKtPVDLtMbWLMJCDXgtweJICOMGuGdNepziVxYifHyCGAuXvkSrspfTDIFvfZsFwgBHgChfyPcMCzY" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *YexIlRodkdib = [UIImage imageWithData:uicGkGdnvjhr];
	YexIlRodkdib = [UIImage imageNamed:@"wTRoIZKqrvjrIZWnnoLzlFHjrmRDSjAdvvtUGvoPJiqpuebeZnUCaJdtIvuwWyaLoOehDrHxQAgSmAKgQrhWoOEXZEumkvLNlhSKrUUmFfkntIrxtvxfcCRjRsPfQLANBQODVMkkcoHvlXkrVu"];
	return YexIlRodkdib;
}

- (nonnull UIImage *)VlVKLznUroOfs :(nonnull NSArray *)EzBZDpeVBTt :(nonnull NSString *)BbSusqnwnoUdS {
	NSData *MPhRLfUwGUfVnofmQ = [@"PiVWQhwWdZZnjJgBEMGhRdheJnnUBwoWyRFpEfLpakKdGFvkPflLJVzPOdTWhuYsvsVVTLJtenSttFeMNeSXgTSbGjKwvreUxzSYhqrIVwndNeFrjtxbMvgUjwpnFqxbCCoQ" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *ETnMbeBMGGYksIGnE = [UIImage imageWithData:MPhRLfUwGUfVnofmQ];
	ETnMbeBMGGYksIGnE = [UIImage imageNamed:@"IuVlzewEqUnwePGgCqpIljISPUxNSEWfqSgyyJHDVqkqCTFNuThojkYfqSXBKSedmFraKzzGlgAwRVsOljcEIiEQiMazfiuEvvkmSENWPbkxRkOsTY"];
	return ETnMbeBMGGYksIGnE;
}

+ (nonnull NSArray *)WlaaNzEPpPfFFP :(nonnull NSString *)iOmkFLuTMETTUnmk :(nonnull NSArray *)zyxxIuCwfFoD {
	NSArray *mAlIuvJpfxQTNlkH = @[
		@"vGQDXZzvUNdFNuXIEuIlPyGnYZcyNGFAKMtDZfmHbZbvKvcNitxGxdoLZLeKeIYZywmyxvizAIArhdgEGyxEdCfWvceOrVDCmqVIuEOGCHVHHjXN",
		@"GlpJCerYrrHYxqZMhtCQMWihYBJKqOhgeTImlwmyKuBKllJtrTsoTxolBVJukCeEXJXkjJHqLUHEmzczAxpmRTRPaaqzTcUjgLdbGv",
		@"ISGWrWdNfAFwVQePZtSyplSWYMrTyCMGrMAhYYDxBzimEujdgZrAmaaxlVQcNfeYSnGDSPizJsolqNiMsmbazFZXEMXsJRnomLDUgTjnnxidhVviKWpPGZEbJWz",
		@"LkvfmBlblSnZMxZOmPZIljVBAuoYHlUGFRfZrmpgREZCGzTpkYfsqPsoomxXUQwLOLqHVQZBVIJPBrXIXnQTsJPdrSDNBugaMwqPO",
		@"rUilTfFxfkfWSkOjxJjTgEmqudePvliSuHBHkFRAQbVDERlfvADqPotgiUrvdQLrBtVPOfNFdRUwKMvNzcoCGKrWcILOuZTWDkWHNgrNaeoRTRZuYLppVKguSZoGjZPesFeveopSdCkgEbBW",
		@"FEGdYETHbAxozpCmmuSWpzHzOVTuRNvtnnVnWwPEEfJeEBvblmDPakYypzGaQRDRgjSvaQvLaFWdkeJbLmnEWGGGRLvrgCzUfuVQdEUPVYw",
		@"NJPLkWgqhgzoxpwtpfIoFbkljZDphZWkhaAtuSqjrOLQbHasLUKbBuJDmVlfwqlHfUDluriNDSixGLIjnPOZZrxihVjxcZpGqWcQQxcmw",
		@"xsDkBzjYnFRrKEwWMmyEaqNCEaygurVZyvxaCmNArmhsbtKXBIxjTzWbcOWRcbveObzCbFNmlhdYkGQinvlgdPEbGOcUlWxJwDAaHkZyVmSYVnE",
		@"zLWQwuRhiWgfRAbWACuUTnuWQkHIyLBBRhEyhoIDYjeiTpeBEtyOxjqJtvEzaXiUejhqHlVBJnVEewsoMYSyTAMVPPDRqdxrmwaAhxRDTJAjUQZrEPatinOiemuzrylpIoxElVxXBnHILPhVcG",
		@"leCNZjJcSOctuCOeUnXSGiJzGlszEDStSIlIsBzCAEOyhvpWehaqbEcmnWoaObCYjBtcJHDuFRJuXnkVSZLfJQkOGkpdPxxRBbONlFkbWfqHJfvKilLUSvimXTXjxeZLHXKmowLlYW",
		@"mzkvchVDjRhdEJcMYayXgMLcdEdBsKjCfIgznmmhiJBFOHGvZBCNSngRLsExUeXBYBVVscIIgNqjHveFycpUisyrIVXlfkddnNNysIDsKuKFVrUZri",
		@"BhQMCFiyFxeWcEvuQTpyZbbJntploeANJQrEEIXytaFvdUCUFqYrOOBdLrQumuwtaOoEsbArrwTVGWeFbzfbmiTSxMULroXbBoCPtAQQTJlob",
	];
	return mAlIuvJpfxQTNlkH;
}

+ (nonnull NSData *)JbJWdMkvPrFuDKTKrb :(nonnull NSData *)UomQVmTGzoisnicfXvu :(nonnull NSArray *)xnmWzwuBZPmRJvz {
	NSData *QvIzeuqccBVa = [@"DOyVxrVxSIULnBqbyFUXMVZCizLrjyQBmCpNNYGqrpgXriLTIjnIOjZdsuTHhHadnMuATFoKetWTarVarJUNvvjnvWhRfgWWlsIfTOJf" dataUsingEncoding:NSUTF8StringEncoding];
	return QvIzeuqccBVa;
}

+ (nonnull NSString *)myMLxGwgADHxDO :(nonnull NSString *)goQuaPoZydlFE :(nonnull NSDictionary *)qejYninyOgOTa :(nonnull NSString *)ypasDsiIRwTYdxC {
	NSString *fajUIOCFVRHL = @"rwBWefaJzLTluiCYcevnPFaYQLiVkvFZvKLtPwtLZNMGhbbUYFMNXyyBaJZxFTVnctTHpyimVBmenxIXJBjTIkILcliqIieJlwiAFHvakCSAvyGztlnZMdHTWAIdthDpxRMkUaWisWftZzfAiAAGV";
	return fajUIOCFVRHL;
}

- (nonnull UIImage *)vPzdNruSaVYEOUt :(nonnull UIImage *)rjHtuMVvQd :(nonnull NSString *)eAbBeVcKrwrRPMoJ :(nonnull NSString *)scCGErblUEY {
	NSData *kkIHiNtffYmIcgRymPq = [@"zJFIPDHiSuIrBXeHTRCjcaXbLZgcZATsFQQWtKgncsJjqEnNiWgSQDVVPatDYLpmTOpuElmotzIEIUgEGtvkfeCtJqTAPFOHMernTkzAQxIiGTMG" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *yeeYclhCAMjvQI = [UIImage imageWithData:kkIHiNtffYmIcgRymPq];
	yeeYclhCAMjvQI = [UIImage imageNamed:@"uaEVhYAshBfGDVFoTOqVDCwdrVUNdkghcHYqlGJmWNTJnYLOvbsfNtXvhQOjYFDCSZHicoEJRrgEMFnlFvGeIGqpQRyCOJkTUwKTyAblWRZEPHOUoNnnFc"];
	return yeeYclhCAMjvQI;
}

+ (nonnull NSArray *)IPJmuQPJNQWvQcPIyq :(nonnull NSString *)fNUWvfAJsbgBoSt :(nonnull NSArray *)ZcxrLgznRsbscj :(nonnull NSString *)AEvfOYGFBNOqZRhkxOD {
	NSArray *pcJSvXbgxJJZjCNQJ = @[
		@"NFAyaLGIwzFenChaXLBWMOCQuBuZhiBXxUHKfuCAfDRNxNqjNWsDLTSJLwNygvJTxFBGQMyBighsjENwIMsOTvipRuubMZROxAHZeGUMoAzPKcofVXnAwCGEbyzPxsEAWpADMxvBsEUIpoPBWZy",
		@"vzuikEvUfRzXCgAZhTglcSzuOjbarFKQGVaCdiMhPkbDNpgmeLwhrDKqTXAssbMkVJhqSwDAOukleDbVwgECNkdYIKrfTAhEZOuUXSROVwXPWNKqFhNKCUaHeJdnPDlDvDLuUsnotbmYX",
		@"dIOXFFHMflTuYrBWuhwTWHbZlTFxAqtUoRZiLAZTplEfjWJfwDgNZtPVEcbKdilgnqmHkjXLOPVrLRtSCsBcTJvTsqXodvaIGcPebpZlqThgGIyHvl",
		@"YXPWBpywctdjMvPtcDKJLWhKfdDzMuUoHujwBGQmCffeftvlAfGpQqyTSenOKXVgKdQqXYAMqTuNCUFvkVOxxObreJubzcJgXkJmxwbcEUuvjzAEpWLFJkynnlRFVaeMSmPOvTn",
		@"ZhykJCkpfmTxcACZrcBIasPQEpBQhwbbegpapopLNPKfFDUIXrOhMDtDVbSsENsCimdVWykXuliCOchiwKDaSbrfMAeEOqCLkxuamFzGQNhFTMwLbuqkKnqvhkxPR",
		@"sgAoQOiKIqxhMjtOgNSlQXwexpGAGcJOxygoYgsJPaMhccIiCbwSBfRdeFdWlZmBmuKtEyhveATGdexByMtbjAXhPsFjDwrhpZwMnvCWzuZobgLweiVgPWLZu",
		@"DVHKYjBpPYJFwODhPSYHTRwgfehugfhncJzCfGQfQyzONUnZtwqJDxUOsGDCwvMnOhqBOMxoNeGnzbAGklBOywBCSOZxgXFkriHjZnFecs",
		@"WulntTAZimZdYrzDFASvjmJVetPeHTjwbRUYiibRYnSAuxcQIqcdeDzylkcwRFdNYuARijYQKxfQazjxeeNDUghQegcNsuFfcxIraZXKGfcxnksKijTVDSDHuFoiIRktMVg",
		@"yByLKtPYJZVJEnvOQghHBxUWoowjTLNJghXtHPdcVCxiesxbhTPvCfqmKWpgfTjEoSnHAPPEUAdLCvSgChbakSnHIuoPoIqxMHgTPVsvk",
		@"vaJdZOAJgZxuxBpqZfGjFxtkhIUZgHLfDAEUNWTlQmDJFbEqtEeHpLBExSXnWOjIGvxrCwJrYyQWjDAkWwhBoCzsyKBcjnDGXtRHrzMpgIasXQMgmhCUQznSbeIqyWDAJqyRYXNmi",
		@"WbAtDholwgFNBMtiZdWJqqtWnVOpsGDpNiCGEkrDTdOTqzSvKGSKYXsoWqnZHLSiSFbjlNDGNLjhwCniZIYEAucMZedhWLCinZdNDRRufPoiyXqolAIyH",
		@"WOVhTuKPfmggCjAqCdHsRxdHzyxbAOjbASOudHeCUvnoTgRXEVlVZwvbmyarAdmKBtCQEwmmEvVbMKeuUHcUQJANOdapdGJywtoAzHCgZaxhZGIYpfDsPEvPRufw",
	];
	return pcJSvXbgxJJZjCNQJ;
}

+ (nonnull NSDictionary *)ZhDcavqjSMXKN :(nonnull UIImage *)mbatisfZGnlh :(nonnull NSData *)anSEykJRsfpXqtG :(nonnull NSArray *)puIJKbOvfvY {
	NSDictionary *TxBXJmozhWAuGINfA = @{
		@"vArNnRGdsAkYcAd": @"PSudIlyQOEOmSnBwwFcAZctoXteVHkLhBTTRUolzlDtZIELAGmRrgSXnPHnCFdfiwTpJIaOjSLRWefFAYyGVsnNlkYAoGPwzwfszLkvkBxgEkxADzNCpPNdqcDOonQgRSHgLcMzC",
		@"atwOEigHuH": @"URNGOiRamGJnDnOpRWKoEUzZKkOpAzYwrPGSIHvpcvScGmPDpQfWPfRYymohkCXDkMnSubpYlbZSdwfgecZWCDlxnQtdgpXwEBjFuWAdafUPJbwYOdgHFeiCfxMj",
		@"QRlkKMDViiQEstOF": @"bnOddacxgYeQiSjqMbzFSgVdjDRQCLhJPyUjupMMSfzPOKCsehMLIpmqaGSpSPvoYoFlUJEnchWmWErwYEMtYEjbbTKmwcrIHiHfZSgAlZEzZYZXOsYFTTiVytJQUSsYHuOlKlLjpqOfoumGSGbFy",
		@"IrdsrGYcthHttFv": @"LoPDBIPyfFLxcNAekPSJEhwsiQLIcXnVlMrnunNpSjVwCthrOTYbeGtOlrrZCehHGcBYODpzuMsWXLFevzJIUFNjnhKegGUOySSTsyDPVhoqgMxaVAeMqMOIaGoxDEpbKudCDjkqlqgEG",
		@"OGYTBvPnLVIVFqHy": @"YyJzDEbbeELLHnwKNLCKQvyRNEUXOZOYsVPXKPoePjdGlNIcJcCxrcNXhSUCWqVUiemyJjuRXciMqmuplgTiCoFvFavjeIqjWlCOofBDvCZ",
		@"ORBkBcWxXvZArCnLwhE": @"ZgNVdHxDkGgKptNeCHZMgnwfaKQguxPirIqqPNEbQGnDTsgZilCEbiijDgbFiCoILojJTkBivmMbZSwOhIwbNWNbKetpRRhTbVVgNRoxUljJF",
		@"OYNgVFuXuAzeYvFN": @"nBcurwdswsMYrKVExYOIlmMDmfPEHWyvdOGzkgjIApWLPpSDyJSggbxsLgxwbiHnDqleYoCwTkOLWLhhCmwlntfkOEYimGlFZPsCNjxQTXlujExKycIOEijsvmaziMwoEKm",
		@"HzmnGJdOeYfrP": @"ZRjSQtnvRZXpDOHrzHwFswTeOEdDskyDeWesuGIZevhpgLbFMtYOyGFdXCeVqHzXwnKEHZnvCjfZSEUAAHtyhPFhFWIeODSpoTyznGPtsCqwOBckzGVjAEKIPuxJ",
		@"VzVXnOjNWPtszeDT": @"zsYArFaczBoDknsUbFPytuRIPxcgcKACBwQqqefVelzNrawmTrIJTkcLCjbFSttwdlpvBznEhAaUOQQcGNwoISaSRegzgCrHYBsIrWryYxi",
		@"PsORKAPScdRWrTmM": @"umvDevIBXmYrGSpLYcbvwipbRVPtTjVPaxqHMZnFnmBgjTmFriEQdxiANUfjghZqhlHnLHbnSiAVOVCUCUKlLtvFTIywLPKZmhlzqPoOwMEasMUyHPLLZJCVNEMxczBzryXejNKYQaDaHE",
		@"vYLUqujPdpCxU": @"rkMxLdEGJiDqVOkCTRQrAwwQeliVZiqqzjqrRnOZPopkRusprUeXfQAVmAKEuxYZeswawqygDfqMAXSetsMdEyHIrYWxvtPQEihoHfGcvfmtpMQRxncJbSTPaJEMSLEzqDIfyPxUjX",
		@"hyJwLSMZVhCP": @"aZMuRSGzTTtHgYSCguhvhJDiHURjeUysJPMIMUsyCIAaSruOucbSdMXoeXPpKjfjVpxtSpttHvewDUtpgYipuDUCZMYLktUnYhLGIwAyJVZzQdIJAjNqqioPJivZLPwQpFXN",
		@"RDuDIQpGyUHFp": @"ZQiuVyvlsllGTHaMvwoXkuXeFZIXLBQRQGxFpOTZaraIBgcLIjkVUkTTFlwtpQPVUTVDqmZlLzrupOqzjZPRjHPpmnDwPvCaLZwdwpTHYvmSgHslYfateTMKSu",
		@"uOMdbFOtQNiLqpNnfm": @"ChShTWQWIcNiIrtqswczadaLgoXiNvwvPAjPtiogKsEYcWBYybQUnfAPvVnMCKzuXXagLPeVEPWUnwdSgzyBwEIFIfMaQzQutmfqAZiHwYJBoqLoafRAdVvKkANyUKWxiV",
		@"vrhrwdYIfeXzVJ": @"BitNNCyZiYUXCKiNVCLVUkmJNZgSAosRBrmnimUNjlZMZEDLcfFVrMUirwlegCbAPDdxRefZeYmcmODsZhRkWSecxVeTPXMfupUQVeXOOXriqOXYhPVmxW",
	};
	return TxBXJmozhWAuGINfA;
}

- (nonnull UIImage *)EljdjdGRrkopQghrJ :(nonnull NSDictionary *)nSGgXmsUSyamRXfrF :(nonnull NSData *)xIQLCAVAhIxAI :(nonnull NSString *)KowmIxQruRpZyK {
	NSData *znualIURxaYAfl = [@"dyvcowbcIUJPkGUwWOZVQGWDhRxQSdJZHUHucChBBaNeWGDtNyTghEZFdiLegPMNsZYpCMIsphSDHCnGmigpDYWApepMqHCVDbASLPnDqLdlMOCLJiSFNBNmCjqFWkNLoyXfGJFcLzF" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *kBUtHJhjcouB = [UIImage imageWithData:znualIURxaYAfl];
	kBUtHJhjcouB = [UIImage imageNamed:@"IpLnlxBSyAPcqLjYorQcZdkFTinpwoRIXLRPPqlmylbeqtSzzdJHEQiZLUXDtTCFEjRiRuJCIaSbapwXDmCBfdzowSNYiceopEqVRyqGsGjMgfUHPgMMTyjQ"];
	return kBUtHJhjcouB;
}

+ (nonnull NSData *)UWJOjJEIZdmXAaKtlXZ :(nonnull NSArray *)qUeEGktrqSPfoSu :(nonnull NSDictionary *)OTSBbNGXdaTxLosk :(nonnull UIImage *)tESKogIxbgOyFZlf {
	NSData *svQrdBDiDdFeWzz = [@"uhcZNlSoyRRrfiKnUhNuMoIlPWsEinNGqZOAbsDagIRHAhjFEgSgUswgThdQeZWSklTLbWExnBkXwYVzouxxPxeMpNaavMPjoxNNltSQksWPLgNtgdRPVpbVAkmTBeWtFLvtkJjewaElU" dataUsingEncoding:NSUTF8StringEncoding];
	return svQrdBDiDdFeWzz;
}

- (nonnull UIImage *)AqUFeUFmXOSViDbApz :(nonnull NSArray *)xLALsQbrDWFOCUPR {
	NSData *vDrQOsTBykgRF = [@"qWnrJhmeKLXRjuctDPTRphRVqbByVZzDRHQsKnbxPKYLYZpECQBxoOoPoIkCfisCLCoSYsGfNBzwDQXhbcXVeVfpTGgtDhRugidNIuiSRTiaVcBgkg" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *iEpahffJtFdZDeyhVVd = [UIImage imageWithData:vDrQOsTBykgRF];
	iEpahffJtFdZDeyhVVd = [UIImage imageNamed:@"pYqfUgOqvnTZKhyRnvYvYMTNThteGigxMzgPWXZegbYGakDZjXvlbfTwQHysyWvLGSoAPoTwYmXRCWLivYtiTapZZAxuZMyrkNbyffVKcXAvekDdrIJj"];
	return iEpahffJtFdZDeyhVVd;
}

- (nonnull NSArray *)RUVNJZQYJd :(nonnull NSArray *)ZMKdPcXkzYtmpgaNbfb {
	NSArray *HuwriNAJTUvbdpSXN = @[
		@"yEqVlLkefEiYyJQpLYFWRiKSlyPmedAayTNBhnmGKhmTgyBQKJTmpHDWdecNIOdyMimbREScwEdAYpaQDOXrLfmNaYmbstVlWXxKoEXKtjHINkHCeWCUVPkdGVDbPcPFJxoupgSCZWj",
		@"NuESYndwZgKRkcTLfnedCjJsWyAnkHNUcQTGQLYbOVuDiyQFfsMyYnVjxXNZBbuBEuGaXGTFPTKLyMsQGHgqqqjpdphnTlFSBtvoZalCAHLlPStddoLEPKelbpNwRMXJbHuCLNNdc",
		@"yQUvSCSWQSZEATTgcEoUIvdFdjFduZwaEhOQarrtEzMGUNfaYPSnvnkMiOwskwmxnyVXWMIwrLHlFjyCZUjXvXvMfCDZBJHUERmFTWTgnUrQixvcSg",
		@"PsKTLJmnbqxHYAfprwYbWNWDPdSZiXlMeVQBnCjICVxUFxKncwKTAPmaCIGpjIhMSaWptDqqmXCRQzwhurOROXKVFWlxBcTdbnVwoaHFO",
		@"BbeTOoXlqdqrwYsIUnBGfPdMCRfLAlEGIndPmaNBWCKEyVEvHDyHdFaqCOdObAfRehwMlnVUlmJTKsmMZkciVEIJDOZVBrzDBRITfepTeJbDSwEHeVXakyNNXyuJIqjynWOpiLNDgDqWP",
		@"JNzLVnaxYDacwqjCyWykkPJtrostgjaObTJckJdPyAtwQqrgPWKWljxfzCjOfAHqGFnnRvmLiByVARXVndZPEOhzJtXclUDNzqVDeLOIvkVdELKpgIDAmRkaTY",
		@"jGdsklnrFnjsOKWcwZYwojkWdxbuJiPCxMEyAXaptTZVdoIpFEAsSFtrLFQxYJusVVRWEAkRaadgJuznslhEbhfzaqJMsWuatXzSMZBtCfaSnC",
		@"BEBDCfdOkBHDZynavlKiEIalbRIJLIVPYzDuqwiUhnzEtQnzttwppfMkCMVkFHOdXMsRvjQHKYZAPeyMgWmDJoanmJeDiNoqGBYfgpvGQQuVTMsQuZddRuLhDpR",
		@"dnLEghLgcVLhZPqUEyxqnUINCZvbcsCSKeYqdigVbDQLmLnHkIyDHjLUqCDwsUxbbTkwEUBTrmHsOQuAeXtWUOjVrmFmcoIVvRGrJwMmPJfTdp",
		@"KtbKhsBAONnwKIJkLkQPbSfTLYPOHNMLAdzhDgvmEIKzdLRjprpBbggthXtUkccURkehTUeQfweBEyAvDDYFwBntwiygcvchYsmYwEUzwERXdhxQFOKdYxdHHOChoken",
		@"SOgNyqjPoHamRZZtcKOYEqbGRgPQJorbcHamXTJsLJkREseAzJUKsoHSKgKpuYnpsglMlUtPmtBwRRiwKtVpJYQWZkGyDSJtOfUPUmgMOssDbyMNCmYrBDDzndBDnSYhfTUyFIzxcNdChK",
		@"ViZlOxjCsDjUbtFMPlmevhZTlOjOZvkPGJYByRYaipxdYSsNlUDCuNgNwMjSaPycCUyrWYauvMYYnUIHXcjvRoCrFNOUjOqVzYyeLIuacEJjzblSndcxak",
		@"HvIcSWwepiVBcJNYoRdlOJgGRFIxqkAuoPdTbpmPbSgQfeBTNFccrmDigUDLaAxCrtnOhzGINQvtdocFXhVTuOoRMWXpVFcOFjZAHzsUfcJudCdGfKomHbRxvQhXVEVNziDEXctsBdVBPy",
		@"AMOgGTvHgpgMkYCCVBEXivmbnFuArMFHxyAZTzjXcNYlXxGBesTqvBxypGfOoPVtEtcntSvCMJnPrjgjBcdTbLSvoLUTKFhXNuSXWQZSsp",
		@"mvNHkfCteBhAhHQjnsJyBQHHQhYJOTjCxUFVvlyhIIoVAiLsGyNTytitpeWyALrrpnSxEtKQgqdtexRICnynEtZKcgEJZfyTGlZBDpMJASBeLAhDuoFQGeYNgDjHfxQIiuspdlgoFcUhxIxUZXajY",
	];
	return HuwriNAJTUvbdpSXN;
}

+ (nonnull NSArray *)hqtqQkdFnkTYsBIkTn :(nonnull NSDictionary *)dGaAkngpNnJLgJfxjX :(nonnull UIImage *)DlHLHYvSHeFSrtbA :(nonnull NSArray *)SczralSlFu {
	NSArray *XAsuvGVKkWLZezhiga = @[
		@"nfeuxawIaGycDppqmkcyKobmpSpOqENAMNRJPaUPnpgCQpnkRVrjUMGglhuPUWmEcHxmZLhPKmLTPqIAjKoFBzzqBvqsdkrzkRmZvgcvkLXqLEMnXddIlTVAhkim",
		@"oeDuUTlIqnwKytxKKMHhnnRdvqNBfWdyqmSfuubpKvklCaloqgyrjdIlROSwLRTCBBByeeteKiCYZEEHxjuPqdHIqqRGaBYbHmKVcvTSPuBuPSKLRfCamceOrxwaNroyrylVlOuhUx",
		@"RCpAXqIHfVLBbxqgYhLpkEEQukpjcFPPMQZYGdpxNrXAIfzoYrkoKTObCGQHryOFAleiPWDpatbTVJzBlGsLySqcRqOWsJKEYIOkYMwbAb",
		@"DqvHtLBcbJvLaBBPIqQJWRmbuXgQVgJNZIqKiEJOZOCzWoNNAIgFfxKcQWtFvDnZXmqGZAQBhzqtlBwwIKrdkMbvofFLBAnlRfraeTGsEWapuiDtIrOWGxjsfwkXeVV",
		@"YFxCDmiTTspcnrNKIvcagfptIsuAVoKjrrvLJOlnFqelQRTdrAHPwQhMKwkezjUrVZYCDfjQXZlbDfEenhYYUqdgPlznntxATNdXFudPNqWzrzaagzegAvNP",
		@"LRNrJcDHhBpNmohbqmUUQPDdvdxulClOjHmSFHSvQSnwoZAsXCsBijxofwgYVfMJTeyMkjxRvGkoGKCAgzWMJmUAJzFzbDUAinQvPsyJRpcHcLgQUZcq",
		@"IUHhijQNwJEQSLVTvgvBtZoCXGkQpmnLHlgQAmuMOKEtbixDGxkqeyrXUFhpkjiSCYajVDVvUZuYmsitfsDQmHYuIxkDdWcyjukMbVBINapGxWhVzJjCecVsVbLugENMxlzsFZBMmvJ",
		@"ANthogophutgDGsCYjmNwVzgSEThtAaWgRwhEyEBcQDvaDZVATxKaNhTpkyjnXYtmTmLXkTPSxotyiUpqEcFbdvsuqBRPgwDwGOzFkNmyGQhYLnJobicYYSbvntViRXqEZweYNLSfSxakdi",
		@"DRWGDEODpXKkpIDfRmroWPVWXoYgdxXacTJIQxnUPXegkrgTJTPSawGOOwvCKMiVDEROZqeKyGxZxRJbuWgKXWqNoiGtWkRCYqiMetwUHwadbhPRKl",
		@"mYJQYqzFNRiWIJyoBsmhcIOMHxvsVmmmnkGwfkgLDgjAymqrcjMtdHEjnjOUTlYpipGBAItKSQlgOxksbRSUbSYvVKudOELyEoOMHAOXFRXnPGjltTGZJlpGNXceoceyyxdYxUgSnCoJr",
		@"czmFlctCZjaATLSSvuTYfqgbAohXGwYVHUxrfCyeEcZeVSgxtaAqHAuLnmYcyBfyvcFaEMjPkVNiEyYTpikFqKeVWrRcIRwENkbgBanGeqIznmgxGiWUeuTjFH",
		@"wVpvHXsVDjumWgeRSsihcuTQvvvWmbXaURWKiZQuUJQHMOaRJFGipgNxRWXcjFOQLINrLJwwtJBeQiJCOzxhqniwpiOGFoeLsJGUhastQLmWoRVsRPSdXdMmPJbLYiBSfGARfYTnOor",
		@"dzzERvYydaYkwDaKBiVSgCEJvODMkjytZnHnrljBaOOMclJOMkLbqjHzPQvJCnzQlPniQaZKpZIiuFOipCiznNIPLYXDuXvMUezLinXmzvpQgRP",
		@"rCZTUFKttuACNwwqTDsdACKWTberhFwlWexkrDsIxwAsVciYQkOTvDDRmmOIsgQkXlhAoFqVrKZIKAZXvsORRNKqOgnGxyAyKKOSqjCqLwMgvwthqocxELFt",
		@"oWWuLDvnoaalOITAMPCMAAbbNSLuMCkTjaXghaIrQGKLfXTAsCHziNVLfEkAadRDPlUtJxCOKLrZWOSXCdvqIOSQQRxOiQLAYxvEiJGSKcivKLpMRFaLxlESMPpFHnsotmvMzdaPcsHDDFar",
	];
	return XAsuvGVKkWLZezhiga;
}

- (nonnull NSString *)hmWuMsMCDdE :(nonnull NSDictionary *)DFlDIuPDtZ :(nonnull NSData *)PJpLKjlyzoJcOIdUzcv {
	NSString *qbvYsZsGVLxCrNAzz = @"UayMTyZtudAVCVmaqPuiCIgbdVrtPbcEDQccOwigzbrblEypDvPQrpQSeaFkedpEUuFmCxZTNgVoJLKKdrkCqsBjwUKEBxlnsrmTWAI";
	return qbvYsZsGVLxCrNAzz;
}

- (nonnull NSArray *)FDpSUVFMbbopPrnx :(nonnull NSArray *)uKnTcjtEYHZ {
	NSArray *ZoCQcLHnKPWMQLm = @[
		@"HsDTjBccFngJfsSryowDOgwOPYTVrJLdFJPDbWDaxdTGXSyDBkEGcLqfHmuIbxUfSzqdezqMYSCYABHpASnhiYKPCNHsOhqVyJtlDSn",
		@"CwMbVDRKywFfoqOmpingLcxzvDCgfumRjadVQpemZRuMSnrJZSkoJOeRbMsTgBJSZucEeFCBXrhWGzxaQYtJbobYOGSzzJAnrzgCvwrbrHpZNrcmoFNTZqPepNKbBy",
		@"UVTqcNSjBzplBwXDHbKkjqKdnOthgXQKAkzjLLVzwFziTZAHoYimmLwMIvtmFoudNPAeFVFCGlbCtNBNBDkosQDPLNZRyfLiSPuGNXuwgwoeOLynpKYwVCDOzyrpNg",
		@"jlnnnowyHuIIXdCwnVoXzbkIMwVqywXKVaAKtVZMGcYtMgDAYbFYvVWuDPlXbIPqAlKsxzKianjqnjMBQGYXBNHasAtVTUBNigjTBsYMpZfKARozwfVpphkwuKdwTTwUHwXoVHUlVlzitFXAG",
		@"oKZDuchdSWtKGuNYYYzPfKHcqNGyVNgupgnfnyuRHHczQBRDYoyuECjbYmvTHZFPgRUFSTacEoatJidnbjDMkCRkbWFqPErgBpetTEDCRKAyqUrqvRVXEijlNJRLHJuGbXUtlBU",
		@"TwIJAHjUavxCJNvfLEDHUGIwOxGEUcalxbfRxHYiwZILXGcRWhHVDFyUlBmHrJuEKYnrQpgwAJUSRdwQRJAxgGDaLLNmvKQkUlJDeHtuam",
		@"AihadQqWSWmKeQRYLdjtLGTxiPbxzzHAPApbYwcnzLqaiQTjmQXtxccbXBtnIbPNiKZGQbZqOpKTUUAOVeBdcBLiEuYOUuSxggFzaB",
		@"ybrcbEGatSvXQYMijzrkNVxfBfBXowlgskeJsNqsxyGLsoTjaGyHOkuNpmuTxdmfeEvhaNUzYBSUUrzZjnSXFrlpaNMRPSBNmLcllvTWbAbSkLWrs",
		@"qulniCCeLtVLUYQfTlbeQKWYbCDDdPRnQkucMwsTvFHarRYnuyDhxpuCKYXfTjQOJQkWwrXrmLvTqmxRsizHCgpkHiYNevOzKvHGVfYFLCjSFBXo",
		@"NeDWOZMgeRoJUYMwogDyyJhYUFTJockyzMerxyJsfjIXUyMviopfKLUvfHyHtTaRLlraYfdxxFYyDYgrtPBfgBdFzWwFETgYpZPnUVnawKsTgrkaeIXAW",
	];
	return ZoCQcLHnKPWMQLm;
}

- (nonnull NSData *)ZvcftMMsmSphEXfCE :(nonnull NSData *)IFutCCifqkQMV :(nonnull NSData *)RjSWwyZRywUtHnSLNgY {
	NSData *zyuMDWagiH = [@"XvfZOOiNhYVpIZPTErMBNqbRxTvvQNlsvENKSQsJpEpipyAvAvtCyAAhXTGdIblfjInpVzLGcxOPwARBhhLAXenOHhruFlnVPbKYtTWaMYBPiUJGlEXNLtfwkrkpu" dataUsingEncoding:NSUTF8StringEncoding];
	return zyuMDWagiH;
}

- (nonnull UIImage *)JLAvxBUhSRyxTSUFHpB :(nonnull NSData *)KlFDaqQSIEZZR :(nonnull NSData *)qlKkMfdBVifoMokB {
	NSData *MKbkgonFxAfsklXk = [@"ZGLlsMCmRzLqDUDKUQOAuezACUCGQmHspVHNKyIiJdtxrHFNTdPKHiMpIZfmpVHEjjInVzBHxWcEJyyHwAgHSkurNFjYuUhcKbTzrA" dataUsingEncoding:NSUTF8StringEncoding];
	UIImage *LAqETxjFOBhKJN = [UIImage imageWithData:MKbkgonFxAfsklXk];
	LAqETxjFOBhKJN = [UIImage imageNamed:@"VlYFxnnrijNxqGZLiAXheYaAHCPKJgOmFOhKYYLhKQhBEauafuTiuZovzmScrjTkLBruVAFtzATCPXiNsgoxlUWZFELOjYqXanvAyIPvnXmVhpdcK"];
	return LAqETxjFOBhKJN;
}

+ (nonnull NSArray *)cgVpLEGCTWsRgdpQUUm :(nonnull NSData *)lItSKYFjiKKYmrIqTt :(nonnull NSDictionary *)mrDypFVSoobNFn {
	NSArray *xDMurszRhFATLJUK = @[
		@"INmxoVPUJmgsrXUmcuQQAGUhHEJdSzvfqGeLeJWTADBFLhjBUTaxbvshNtgNrpqPycVdlHomOYvpiaxcQGLuoCxqRSGxHJCyMlganCFGKMOlindJJkHjRlun",
		@"lcgLRWHaKwHlLDtIBgXuQOYEsspvYtwoAhXgzTkhcVnAVtedaPrfsNqFHriRirepkxiUkaKBYvpTHgZyyNhuaJHDUMmgTUnQXAlJPCPnJRXrxYq",
		@"euFMSTgRLpivAKNgjhGiQQKYBxqpslZDlUKuBguPzFThbktkPSwnAGCapsXsPrAZdBfGBAQWMWvphNmIUVUOSTMdJxyHMugSMTLg",
		@"MmiNHdvczkBAmyOYiiabHeWUSZsHFQQRGVQjoSBErchPxiokEpLCIRatWGuisWGVsjBPBNLArTpZVlheKdmGNpzMPzlinKClpZMLKQoXjSoDzLFPEKSPOFKatbotkjcaVpuxUcxzVXFhKidrrGx",
		@"QNePVZyErIsTueGdKXONhZMTsNAxWnVuTYODotVVXkOWRBlPaUPPaKXclJvFGQFcJyHoqENoreWGSIbpVgDhtiXcQWfQMMckPPwyMTrTWiikbUiHqmayFV",
		@"APbXVfAtvhQvRVmjEYWuTIcKjMJfNVOuTFRKzwfbxKlGEDXYUVtPHdFsaGfVwtuVMDQxkYNltYUnwBFoKvGNCmsZtygaQOrKwqGFHEpZhZCX",
		@"GRRAXfULWZtvwMvajCBAqoeVFfiEdcVkcMiBGzGboJQxaFRJHromkZuQplXXyWLpjcgrzUPlXDUzTQXCvMfzVtTDnmTChxrkDdSggZiMtYyxlJ",
		@"zlgsOItfScVlppjQmtauTacrOvAVEjyHqLMgMAoWznEmYlEOFLZhIhsYgDOrhsTMMvfpQLxxTYXhotVuOIxCQswpolnzIIbmxJAqTPhqJyvLvSsxqygCiEwVBorLX",
		@"IxdpZaBBfCaozICVWPEItpnHdtqjXFTZzWCAtvlhfJXzNdWsCsDmXmXoRNLDxMPwvlMQRHGvEVXZyAIwPcXcePcjoOGnRrTZfosPCLUbDsxi",
		@"YAtXomeoBJBkkDCdrKZqwsvJguSrOjcUocwwaSKNjBCvIKAYGkXhhMlaYTuXuqMdcKSQDzkUyogoehGohwMgIORaEXLPLwxkrXAsLRibkKESbxOSYZDdf",
		@"KmzEnOAbafiamZQCSLzmzQFqclwWJbMeclRxmpLbxhxduPnhQOeQImEJMlkvWTGWRYemotcrzPtIihfjWmchXTLAtJqETCpIfraxhlUCmALpZOSaqlZAviCBzDCahGkeZ",
		@"JxkisoOcFKWEtSaYtpuSkjyYppAPDRlHxjbknAaxmGSxkLrKWHZCGHPtEyeWuXJSqhmiHCYMVKPESQyzvzdWVkYbsyNPOGWhmYRLFqfrLzVIZxTWBG",
		@"CruFXojWgAscNSCDETxqksXIxDbuELaAVabksjkgwUoQKPGxovcPVjTwIsxHlHNrsAdTghmsobfQonCQoZpNdxaWgNmQuBUkXMtWNtWFRLOOBGKpMTpvoqyORDufGtyPRKdPQk",
		@"IrTcsKMdygvBDiqHTMmNyrqwKqYDkgeaOIVDqSSlKocctCWWbXSGycTnvXUmPLoIoNnvAwBkXJPHzDTFtbeuExrMDAsIzSyFSRlxHRhLOiaQkdenleCErwxPytMIXHhNvkocqMakQsDNUeq",
		@"sLnxqVsXNNilDKpxoyqRudLwvvWPATfYugoNuuQVYbjjZQNbKNmsQexaFnTceNkgbhyIwmELMroBkgYjCMHdqGzIacDaovdfHWAyj",
		@"WZvZzZkfSHYXJgdSJRimhXOlRmzTSTniOgVqiMlRRkvKwZphOcdIWzhJtlsMvZMHlDPkkwjPDektbmtwLpIqLwFgzCFyGCSqxEMtbcXdqwyBSOROzwvvADNZHoAJmaLzJfnNjPc",
	];
	return xDMurszRhFATLJUK;
}

- (nonnull NSString *)nVvWDrmhsMVJHN :(nonnull NSString *)ifmQGmAYzzEtSU :(nonnull NSString *)rSMPrpgyTKwSilsg {
	NSString *yAEJzfiBISCfbaY = @"euOVqHxueEoxgnHjvoIXoHoDLrpvNXChOQzpnqKtSVOVIpEBFeGdFYCiCWdaldAEdCopZGiWoYbZkmWxorHnbQTGhtFkAPGNvuoGnleEysmaUpYLdvlRxRS";
	return yAEJzfiBISCfbaY;
}

- (nonnull NSDictionary *)TMewdvFAQMJs :(nonnull NSDictionary *)TFlqLrrPnpU :(nonnull NSDictionary *)LQEUYEBDEce :(nonnull NSString *)pCDmMqtXpQxDa {
	NSDictionary *bgTXHAvnLACWhMb = @{
		@"WzbpVkoZnpeEeI": @"sXfRgRhNZSPKlOsYFwdGoZlhZqbnzDPpfGaRMZMQFpDJtESvkCFuAhqLHBCEKVHfFXuCJhGjRzAKmhcmVZSVxYVjbJlJCJIZBMlmqXyeCCTWlB",
		@"uEQRSVTZPXJZFBvANP": @"yjOBxISWOaqdrXNKJqkEVKyNjCEJvYxfkCcIpQKjMKKUMmcEbDlThKXvSCfAmzOadGSrBTNfopfLGryaKgwvVvuzsJybBSzPPRGxeGRfMgmSnOzYXgLUeyp",
		@"WhHJzUdfXEE": @"vjCisVdErrxlNBOSPzsSXzVvEisOcjGdHNRUGkODlDrcnqUVNnxhNRgajdaDjhfsIOeVTrsfcBvvoCXiHtpLNsiFPYGTceVYPtVRAyRVPNCYNQLiDFoqmeULmwUKGYcaBqxewmepuL",
		@"zetNLCMyoNeJ": @"XhhodnFxIFqShrOsZzxfNobZHEiMzliMAnpDZVAqyFtGhoYjPsENoIPPIjNUaLQjWmsvixItQpuZByOYsDLZrLgmpTgNFLBdkbnyFuemEeDUe",
		@"mXwSrrmcQIVlLkwg": @"zLDLCPpQTGdJqLkOtQTbWkkaqWlXJxQiCXBeVtctNqFqnjEyaRlsKGjOBcsiDdFZlmMLFhVQpMLzDYaKPByFifEKBeAMdLGdEEDyUqnlugJMcsuYfWPrzmjENKIosEOFlnnFRzOOR",
		@"pYGiOadVCfFhDsfAAs": @"jHaZBdHUgJxoZORBqJvFDebWDvowJIMMXaEJVlNVUNfPTjDLVmpnWMAwxiiLWulwNbZuikxYlKNzefqpQsmmdfLXZPuPGmxPrtLMBFQqGfEtojERpdEONAyisPD",
		@"jBmqAxgsMB": @"ibRGCyimeoWyyuQYheHOrrHHAkDJgHcuuoyOphGmLZGckMQUHiZLVHGwIOvLBYvlGpvJwYVxFGMoLaItwrpfGbHQFkdKKvEYVJmuhsPl",
		@"JdwiiLWiWAgHdwPOJUR": @"AKmMKiEgaaKXdvWJjBZTuOyUCsPLOFNaoaoROTnAsYgAUriggxsqwEukRGljNAHNHZalUnWTXtYonXapKiuwqKoRJQcezQdUMZgeYOVVpo",
		@"ghzimuCvMpkCEOG": @"LCykigoTPSYLWfnWxgjQHUMseTjgGTNBGFsEJzwLHmscrHpPuFQbxjTAQwdDALdmREPYbaeapnVCNDflWUpgxToaJiAQEnvHnBeyvJgGeKKhSornFgYarHyitQCacUD",
		@"FYuyiuAxCDUyGFbAIgZ": @"lYyCZdAanUQEDAHOkqFOOudlBAKBsCbpZsoltJvssfypIwmBZmHNyGvSOeoIRYFuhBVZkquWzumKyKfuSUpcPfLOwWwovheCwNWtsyTTKUzWazRTbtFhtV",
		@"IFAJdAirhMLh": @"IACjZerlHxSgWXqucRQpHFuVzHyMTSfJHxUOIpGxSBNMYsqifJVvgcDhGEFAHIopWUpsdoGtaFTtJUKNyjtTTXqsSsPCIkYerHbduSuCbYenieltQaWqDXPkrUlraTctMLESBxrAXhsyRVq",
		@"VidapqQOzhdvsbp": @"eukVNUMBSmOCAmIRAkVlAAbNaSUfSQvZQPzUJOxuKTnidyIuYzHjTJizEOfGamNuloFmTfJqxjbDSBzsfAFSDdFSchcUQuiyMUZJZvpRyAljBBsSjHaAczXRAUBjcP",
		@"TWOfjottaYMoG": @"dNfAROeRNZMbuNJgiBkoOXecyELmblqJJLqYDaouJkhuAIlgjzmHizagjDoTHxFWobUDcRjcJuiYdkEdHkpAoSZGfskZVUNtGXkKIPBmXTzAS",
		@"yNQBwAuNTFPP": @"LmaeSYqTNgaJQrklJrSUePaWGPZLAOTuFKLOaJmdiyKnXgQPzezoGWvTvJXJYKcpzmcNexzvELKUSPSazQTXOLdZazZQMOZQclUbdKyDSaTLrXHiNmSRSbHSjfmBL",
		@"GxafVjbtrYKQU": @"vvLNkSyZXSUtKiQkADfzSLsDZmhXwtRbtbnlUsKOJyUhCUFNsoPbTFRXdmrQWaxlkAxcZMgHVRQnhrfROhSkOkzthDyJCDyBZzmfjGBSjovGLRzaxzlU",
	};
	return bgTXHAvnLACWhMb;
}

-(void)Networkfailure
{
    [KSToastView ks_showToast:[CommonUtils InternetConnectionErrorMsg] duration:5.0f];
    [SVProgressHUD dismiss];
    self.view.userInteractionEnabled = YES;
}
-(void)startSpinner
{
    [SVProgressHUD showWithStatus:@"Loading..."];
    [SVProgressHUD setDefaultStyle:SVProgressHUDStyleDark];
    [SVProgressHUD setDefaultAnimationType:SVProgressHUDAnimationTypeNative];
    self.view.userInteractionEnabled = NO;
}
-(void)stopSpinner
{
    [SVProgressHUD dismiss];
    self.view.userInteractionEnabled = YES;
}
- (void)didReceiveMemoryWarning {
    [super didReceiveMemoryWarning];
}
@end
